### ISSUE TITLE
`Process` infrastracture block - execute on an environment without prefect

### ISSUE THREAD

**Issue by benjcabalona1029** [PrefectHQ/prefect#10043]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently, we can follow the steps from https://discourse.prefect.io/t/how-to-run-my-deployment-in-a-virtual-environment-such-as-conda/1423 to use a process block to execute a flow on another conda environment, However, this assumes that the other conda environment also has prefect installed.

### Describe the proposed behavior

Be able to execute a flow to run on another conda environment without prefect

### Example Use

When a script is executed on a conda environment uses an unsupported python version (i.e. 3.6)

**Comment by desertaxle** [comment]
Hey @benjcabalona1029, I need help understanding the request. Flows cannot be executed in virtual environments where `prefect` is not installed because `prefect` is required to orchestrate the flow. If you want to run a Python script that does not use `prefect`, then the `Process` block will work as it is currently implemented.

Can you share a more explicit example of a script you are trying to run and the result you're seeing?
