### ISSUE TITLE
Cannot return null for non-nullable field flow_run.id - INTERNAL_SERVER_ERROR

### ISSUE THREAD

**Issue by trinebrockhoff** [PrefectHQ/prefect#10072]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

We are running our flows using Prefect Cloud. We are seeing this error which I think is related to the Prefect Cloud Backend:

```[2023-06-26 14:21:28,404] ERROR - agent | Failed to query for flow run metadata
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/prefect/agent/agent.py", line 328, in _submit_deploy_flow_run_jobs
    flow_runs = self._get_flow_run_metadata(flow_run_ids)
  File "/usr/local/lib/python3.8/site-packages/prefect/agent/agent.py", line 688, in _get_flow_run_metadata
    result = self.client.graphql(query)
  File "/usr/local/lib/python3.8/site-packages/prefect/client/client.py", line 465, in graphql
    raise ClientError(result["errors"])
prefect.exceptions.ClientError: [{'path': ['flow_run', 0, 'id'], 'message': 'Cannot return null for non-nullable field flow_run.id.', 'extensions': {'code': 'INTERNAL_SERVER_ERROR'}}]``

### Reproduction

```python3
Not able to reproduce, as we didn't change any code or infrastructure.
```

### Error

```python3
No error, as we haven't changed code or infra.
```

### Versions

```Text
Azure Kuberenetes Service
prefect=1.4.1
```

**Comment by EmilRex** [comment]
The root cause of this error is a build up of soft-deleted flow runs. Whenever a scheduled flow is re-registered, the upcoming flow runs are deleted and replaced with new flow runs. The flow runs are initially marked for deletion (i.e. soft-deleted) and later actually deleted from the database by a backend service (i.e. hard-deleted). Flow runs that are soft-deleted and scheduled will still be attempted by the agent, resulting in the error above.

If enough flow runs are soft-deleted without being hard-deleted in a period of time, the queue of upcoming flow runs may get completely filled resulting in no work being picked up by the agent. This may also happen if the deletion service is not able to keep up with demand. Should this happen, please contact Prefect directly for assistance.
