### ISSUE TITLE
Fixed path vs relative path keeps Prefect from working as a proxy in JupyterHub

### ISSUE THREAD

**Issue by danielhstahl** [PrefectHQ/prefect#10389]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When using Prefect with [Jupyterhub's Server Proxy](https://jupyter-server-proxy.readthedocs.io/en/latest/index.html), the static /assets are being served directly from Jupyter's base url instead of the relative url:

<img width="1469" alt="image" src="https://github.com/PrefectHQ/prefect/assets/6961410/0b4c0f4a-8c60-4470-a3af-85c2d74b0f82">

Changing https://github.com/PrefectHQ/prefect/blob/16f46ca49838cbdb250d113bb149f13ca819302d/src/prefect/cli/dev.py#L163 to "./" fixes this, as seen here: 

<img width="1899" alt="image" src="https://github.com/PrefectHQ/prefect/assets/6961410/2b94be10-1d4e-4cb5-b716-040df7ab53d3">

I will PR a fix.

### Reproduction

- Install JupyterHub development as described here: https://jupyterhub.readthedocs.io/en/stable/contributing/setup.html#using-dummyauthenticator-simplelocalprocessspawner.  
- Install my prefect Jupyterhub proxy here: https://github.com/danielhstahl/jupyter-prefect-proxy.  
- Start Jupyterhub and click the "Prefect" icon.

### Error

```python3
Request URL:
http://localhost:8000/hub/assets/index-e12ca795.css
Request Method:
GET
Status Code:
404 Not Found
```

### Versions

```Text
2.11.3
```

**Comment by SomethingUseful** [comment]
Does this fix the issue where UI and CLI do not work when using a custom domain with a simple nginx proxy in between?

EXAMPLE:
I have an issue with UI.
I setup local server on remote box to run at 127.0.0.1:4200.
I setup a super simple nginx proxy to route mydomain:com:4201 to 127.0.0.1:4200.
This doesnt work because your profiles/api are set to an absolute URL and so when i go to the UI all the links are going to 127.0.0.1 and broken.
Ok. So I set the prefect url to [mydomain.com](http://mydomain.com/). UI now works fine.
Now when i go to create a new profile from default using cli, it times out because the url is no longer 127.0.0.1 and your cli tool is trying to connect to it.
How can I fix this issue?
$ prefect profile create wb --from default
$ prefect profile use 'wb'
⠦ Checking API connectivity...
TimeoutError

**Comment by danielhstahl** [comment]
I think the issue that you are describing can be resolved by using PREFECT_UI_API_URL, see https://docs.prefect.io/2.11.4/guides/settings/#prefect_api_url

**Comment by danielhstahl** [comment]
> Does this fix the issue where UI and CLI do not work when using a custom domain with a simple nginx proxy in between?
> 
> EXAMPLE: I have an issue with UI. I setup local server on remote box to run at 127.0.0.1:4200. I setup a super simple nginx proxy to route mydomain:com:4201 to 127.0.0.1:4200. This doesnt work because your profiles/api are set to an absolute URL and so when i go to the UI all the links are going to 127.0.0.1 and broken. Ok. So I set the prefect url to [mydomain.com](http://mydomain.com/). UI now works fine. Now when i go to create a new profile from default using cli, it times out because the url is no longer 127.0.0.1 and your cli tool is trying to connect to it. How can I fix this issue? $ prefect profile create wb --from default $ prefect profile use 'wb' ⠦ Checking API connectivity... TimeoutError
> 
> Not sure if this is helpful or not: "there needs to be a distinction between the UI api url and the cli api url? in the nginx proxy case they are not the same."

I think the issue that you are describing can be resolved by using PREFECT_UI_API_URL, see https://docs.prefect.io/2.11.4/guides/settings/#prefect_api_url
