### ISSUE TITLE
Azure Container Instance Work Pools not submitting identities

### ISSUE THREAD

**Issue by zhen0** [PrefectHQ/prefect#10476]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Using the Prefect Cloud UI to create a work-pool of type Azure Container Instance, the Identities input does not seem to be working.  If I enter a value and press save the input is not shown in the newly created work pool. 

This happens for both the push and standard version of the ACI work pool. 

### Reproduction

```python3
Try to create an ACI work pool!
```

### Versions

```Text
Prefect Cloud
```

### Additional context

I have tried adding the identities in different formats such as a list and string but neither seem to be registered.  No error is shown. 

From the network call it looks as though the value is not being passed from the UI to the api. 

<img width="711" alt="image" src="https://github.com/PrefectHQ/prefect/assets/40272060/6c627db7-07fd-4426-9a6d-95e02e2786c1">

**Comment by ne-warwick** [comment]
Experiencing the same issue I believe with #10465 with prefect server. Preventing the form from moving onto the next stage so I can't even get to the network call stage. Would you happen to have a JSON representation that could be used to call the API instead while this gets fixed by any chance?. Would love to start using the ACI worker as it works nicely for our dev team but we're still having to use agent + ib for this atm.
