### ISSUE TITLE
Flow submission with JSON parameters fails when using default values of parameter model

### ISSUE THREAD

**Issue by j-tr** [PrefectHQ/prefect#10781]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

When submitting flows with required parameters via the JSON parameter input field that match exactly the default values of the respective parameter model, the parameters are stripped from the input and validation consequently fails.

This is problematic for workflows where large JSON configurations dicts are used to configure flows. In this case, it is not trivial to spot that a provided parameter is equal to the default value.

### Reproduction

deploy

```
from prefect import flow
from pydantic import BaseModel


class FooModel(BaseModel):
    foo: str = "bar"


@flow
def main(
   foo: FooModel
) -> None:
    pass


if __name__ == "__main__":
    main()

```

run flow with JSON parameters that are equal to the model default parameters

![image](https://github.com/PrefectHQ/prefect/assets/11021147/b89bffdc-0d0e-46b8-bd16-0601cb465b56)

### Error

```
Agent started! Looking for work from queue(s): default...
18:10:56.724 | INFO    | prefect.agent - Submitting flow run '68c64541-8642-4738-a8b5-a218188e0afa'
18:10:56.834 | INFO    | prefect.infrastructure.process - Opening process 'zeta6-sothis-y'...
18:10:56.860 | INFO    | prefect.agent - Completed submission of flow run '68c64541-8642-4738-a8b5-a218188e0afa'
...
18:10:58.798 | ERROR   | Flow run 'zeta6-sothis-y' - Validation of flow parameters failed with error:
Traceback (most recent call last):
  File ".../prefect/engine.py", line 422, in retrieve_flow_then_begin_flow_run
    parameters = flow.validate_parameters(flow_run.parameters)
  File ".../prefect/flows.py", line 456, in validate_parameters
    raise ParameterTypeError.from_validation_error(exc) from None
prefect.exceptions.ParameterTypeError: Flow run received invalid parameters:
 - foo: field required
18:10:59.082 | INFO    | prefect.infrastructure.process - Process 'zeta6-sothis-y' exited cleanly.

```

![image](https://github.com/PrefectHQ/prefect/assets/11021147/fe5ae1cb-cbf8-4786-b078-30aea8e4d882)

### Browers

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```Text
Version:             2.13.1
API version:         0.8.4
Python version:      3.8.15
Git commit:          d147b180
Built:               Thu, Sep 14, 2023 2:54 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.37.2
```

**Comment by chrisguidry** [comment]
Thanks for reporting this issue, @j-tr and @figuernd, would you mind sharing your pydantic versions?  Like `pip freeze | grep pydantic`?

**Comment by j-tr** [comment]
i'm using pydantic==1.10.12

**Comment by figuernd** [comment]
`pydantic==1.10.13`

**Comment by figuernd** [comment]
In the bug description is mentions using JSON, but I'm finding that default inputs get stripped regardless of whether I'm using JSON or UI fields. I see the default values in the UI text boxes, I hit submit, and immediately get a validation error saying those same fields are required. Essentially using defaults at all cripples the workflow.

**Comment by figuernd** [comment]
Incidentally, I notice that the "JSON" tab will not show any parameters that are set to their defaults in the "Custom" tab. If I change the value slightly it will appear in the JSON tab, but will disappear again when switched back to default.

**Comment by NicholasFiorentini** [comment]
Same here, it started to occur when I upgraded Prefect Server from 2.12 to 2.14. The bug does not happen when we submit flows via REST API. Unfortunately, this is highly impacting since our users are submitting flows via UI.

**Comment by NicholasFiorentini** [comment]
## Minimal reproducibility

Prefect: `2.14.10` (both SDK and Server/UI)
Python: `3.9.7`
Pydantic: `1.10.13`

Given the following model:
```python
from pydantic import BaseModel, Extra, Field

class SubConfigBaseModel):
  # this model has 2 mandatory parameters with defaults
  param1: int = 1
  param2: int = 2
  
class RootConfig(BaseModel):
  # this model has only mandatory parameters without defaults
  subconfig: SubConfig
  another_param: str
```

The Prefect UI correctly show all fields with the expected defaults prefilled. Suppose the user inputs `another_param="something"` and leaves the defaults. Unfortunately, the JSON generated by the Prefect UI is:
```json
{
  "another_param": "something"
}
```

This JSON is submitted to the flow, but the flow validation fails since `subconfig=null`.

Please note that:
- This bug does not happen in our integration tests since we use the REST API (via the SDK). 
- This bug only happens in the UI and only when the model is rendered as a proper web form. This does not happen when the model is too complex and the user must input the JSON.

## Workaround

The solution to avoid this issue is to provide a default at the root level:
```python
class RootConfig(BaseModel):
  subconfig: SubConfig = Field(default_factory=SubConfig)
  another_param: str
```

This way, the JSON is still 
```json
{
  "another_param": "something"
}
```

But now, the flow correctly initializes the missing subconfig with the default model, thus passing the validation.
Prefect side

## Expected behaviour

The Prefect UI should generate the correct full JSON:
```json
{
  "subconfig": {
    "param1": 1,
    "param2": 2
  },
  "another_param": "something"
}
```

**Comment by znicholasbrown** [comment]
Thanks for the repro @NicholasFiorentini.

It looks like there's a mismatch between server-side validation and UI behavior here. I'm not sure the UI behavior is incorrect - if a value matches a default, it shouldn't need to be passed to the run at creation but I don't think validation should fail in that case.

**Comment by NicholasFiorentini** [comment]
> Thanks for the repro @NicholasFiorentini.
> 
> It looks like there's a mismatch between server-side validation and UI behavior here. I'm not sure the UI behavior is incorrect - if a value matches a default, it shouldn't need to be passed to the run at creation but I don't think validation should fail in that case.

The Pydantic model is behaving correctly: if there is no default factory, it is correct to report an error. The issue here, IMHO, is that the UI drops the default values from the JSON. If in the UI I see a value, I want to see the same value passed down to the server. This is paramount for debugging and auditing, otherwise the API call is not reproducible if the default changes with the code.

**Comment by NicholasFiorentini** [comment]
To clarify, when you define

```python
class RootConfig(BaseModel):
  # this model has only mandatory parameters without defaults
  subconfig: SubConfig
  another_param: str
```

and then you do
```python
obj = RootConfig(another_param="hello")
```

A Pydantic error is expected for the missing `subconfig`. While
```python
class RootConfig(BaseModel):
  subconfig: SubConfig = Field(default_factory=SubConfig)
  another_param: str

obj = RootConfig(another_param="hello")
```

The Pydantic model is correctly built without errors and with the default factory. This is the correct and expected behaviour.

The UI disregards the fact that the first model has no default factory and recursively inspects the model to provide the defaults on the UI. But, since it does that, it must also preserve the JSON for the defaults. Otherwise, you have a mismatch between the Python model and the JSON.
