### ISSUE TITLE
Misconfigured API URL warning is not silenceable

### ISSUE THREAD

**Issue by majikman111** [PrefectHQ/prefect#10840]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

A warning introduced by #8774 when used with a custom build to serve prefect with a base_url behind a reverse proxy causes a warning to be issued whenever the prefect CLI is invoked saying the variable `PREFECT_API_URL` is misconfigured, despite being configured correctly for the environment. 

My environment requires a custom build served behind a reverse proxy and previous requests for this functionality to be supported have resulted in a custom build being the only viable option.
#109
#861

Docker image to prefix Prefect API and UI with url prefix `/prefect`:
https://hub.docker.com/r/majikman111/prefect-ui-proxy

Preferably, it would be possible to silence this warning manually OR have it trigger when the URL does not end with `/api` or based on some other criteria.

### Reproduction

```python3
When using a custom image like this for serving Prefect behind a reverse proxy
https://hub.docker.com/r/majikman111/prefect-ui-proxy

Set `PREFECT_API_URL` to `http://localhost:4200/prefect/api`

Any `prefect` cli invocation will display an error message despite a correctly configured API url.
```

### Versions

```Text
$ prefect version
/home/prefect/prefect_venv/lib/python3.8/site-packages/prefect/settings.py:1392: UserWarning: `PREFECT_API_URL` should have `/api` after the base URL.
e.g. PREFECT_API_URL="https://api.prefect.cloud/api/accounts/[ACCOUNT-ID]/workspaces/[WORKSPACE-ID]"
  values = warn_on_misconfigured_api_url(values)
Version:             2.13.2
API version:         0.8.4
Python version:      3.8.12
Git commit:          dcd8a58f
Built:               Thu, Sep 21, 2023 2:33 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         server
```

**Comment by DEEKSHACodeaim** [comment]
Hi, can I work on this issue under hacktoberfest?

**Comment by eladm26** [comment]
I just added a new setting to enable silencing the warning, can you please have a look @desertaxle?

**Comment by EHJ-52n** [comment]
I am aware that this issue is closed, but I stumbled over it, because I have some issues with prefect behind a application proxy. Hence, I am adding my thoughts here.

Apart from silencing a warning message, some explanation, why you are checking, that the `PREFECT_API_URL` is always served under `scheme://hostname:port/api` might be helpful (see [settings.models.root.py](https://github.com/PrefectHQ/prefect/blob/main/src/prefect/settings/models/root.py#L385-L389)).

Or you might rephrase the error message to something like "prefect API MUST always be served under `/api` without any additional context path".

Maybe, you want to achieve something different and switch from `parsed_url.path.startswith("/api")` to `parsed_url.path.endswith("/api")` or I misunderstood the complete issue here.
