### ISSUE TITLE
Global concurrency for tasks that are async functions rather than tasks

### ISSUE THREAD

**Issue by Kirill-Ulich** [PrefectHQ/prefect#11081]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

You say it is parallelism for tasks https://docs.prefect.io/2.14.2/guides/global-concurrency-limits/#parallel-data-processing

But definition for the task is other https://docs.prefect.io/2.14.2/tutorial/tasks/#what-is-a-task

This is parallelism for async functions rather than tasks.

### Describe the proposed change

In the prefect context you need to change code example to make parallelism for prefect tasks.

**Comment by zzstoatzz** [comment]
hi @Kirill-Ulich - thanks for the issue.

I don't believe we're intending for `task` / `tasks` to refer to specifically Prefect tasks in this case, since we're trying to highlight that global concurrency as described here can be used outside of tasks or flows
> concurreny and rate_limit can be used outside of a flow to control concurrency and rate limits for any operation.

Instead, we're talking about tasks like you'd talk about [tasks in the context of an asyncio Event Loop](https://docs.python.org/3/library/asyncio-task.html#running-tasks-concurrently).

I think we could make this clearer by adding a `!!!tip` to this page to clarify what we mean by task here.

**Comment by zzstoatzz** [comment]
clarified in #11085
