### ISSUE TITLE
`image` argument is required with `.deploy` even if `build=False`

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#11096]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Users need to provide an `image` argument to `flow.deploy` - even if not building an image.

```
    async def deploy(
        self,
        name: str,
        work_pool_name: str,
        image: Union[str, DeploymentImage],
        build: bool = True,
```

### Describe the proposed behavior

Make `image` argument optional.

### Example Use

Saves unnecessary typing.

**Comment by viraj-s15** [comment]
Hello, I am pretty new to oss and I do not want to waste time of the people working on more important things by submitting a bad pr. This seems like a pretty small issue. Ive made the following changes to the code

```python
async def deploy(
    *deployments: RunnerDeployment,
    work_pool_name: str,
     # Added line below
    image: Union[str, DeploymentImage] = "__no_image_specified__",
    build: bool = True,
    push: bool = True,
    print_next_steps_message: bool = True,
) -> List[UUID]:

# Added if statement
if build and image == "__no_image_specified__":
        raise ValueError(
            "The build argument is set to true,please provide a valid image to continue"
        )
``` 
Havent changed anything else in the function.

I seem to be passing all the deployment test cases. The one being skipped is because I am not using a windows system. 

![image](https://github.com/PrefectHQ/prefect/assets/79002760/c427a170-b3fa-459b-bcf1-1aa850a40ff2)
