### ISSUE TITLE
make Cloud Run Jobs timeout longer

### ISSUE THREAD

**Issue by shunsock** [PrefectHQ/prefect#11325]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

We can not assign int value greater than 3600 to `CloudRunJob.timeout`
Prefect source code define the maximum time. Field is Pydantic feature. Please see code following.

```python
class CloudRunJob(Infrastructure):
    ...

    timeout: Optional[int] = Field(
        default=600,
        gt=0,
        le=3600,
        title="Job Timeout",
        description=(
            "The length of time that Prefect will wait for a Cloud Run Job to complete "
            "before raising an exception."
        ),
    )
    
    ...
```

The Infrastructure is defined here
- https://github.com/PrefectHQ/prefect/blob/main/src/prefect/infrastructure/base.py#L46
```python
class Infrastructure(Block, abc.ABC):
```

The Block is defined here, and inherit Pydantic. Therefore, Field is Pydantic feature and Validation is run when initializing.
- https://github.com/PrefectHQ/prefect/blob/main/src/prefect/blocks/core.py#L196
```python
class Block(BaseModel, ABC):
```

### Describe the proposed behavior

Change timeout le to 86400. It looks we can make maximum time greater than 3600 because Cloud Run upper time is 24 hour.

> By default, each task runs for a maximum of 10 minutes: you can change this to a shorter time or a longer time up to up to 24 hours.

Reference
[Google Cloud: Set task timeout (jobs)](https://cloud.google.com/run/docs/configuring/task-timeout)

### Example Use

it enable user to run task which takes over 1 hour on Cloud Run

### Additional context

If this issue is accepted, I want to commit to this project as engineer.

**Comment by desertaxle** [comment]
Thanks for the issue @shunsock! The reason the timeout for the `CloudRun` infrastructure block is capped at 1 hour is because that block uses the Cloud Run V1 API which has a max timeout of 1 hour. 


Fortunately, we recently released a Cloud Run V2 worker which uses the Cloud Run V1 API and can support runs of up to 24 hours! You can get started using the Cloud Run V2 worker by creating a Cloud Run V2 work pool in the Prefect UI.

I'm going to close this issue since it sounds like the Cloud Run V2 worker will satisfy your needs, and we don't plan on adding enhancements to the `CloudRun` infrastructure block since we recommend using workers over infrastructure blocks and agents. Feel free to comment or open another issue if there are any enhancements you'd like to see on the Cloud Run V2 worker!
