### ISSUE TITLE
Add documentation on conditional flow run pauses

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [PrefectHQ/prefect#11434]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

I don't think it is clear how to specify that the flow should only go into pause if only the upstream succededs. The only way I see how this can be achieved today is if i call results first so I get the exception but I don't think that is very clear.

```python
@flow
def my_flow():
    ran = task_one.submit()
    ran.result()
    pause_flow_run(timeout=600)
```

### Describe the proposed behavior

from prefect import task, flow, pause_flow_run

```python
@flow
def my_flow():
    ran = task_one.submit()
    pause_flow_run(timeout=600, wait_for=[ran])
```

**Comment by serinamarie** [comment]
Hi @thomasfrederikhoeck, thanks for the issue! I totally understand wanting a conditional pause. We already have multiple ways to [use results from submitted tasks](https://docs.prefect.io/latest/concepts/task-runners/#using-results-from-submitted-tasks) and I don't know that implementing those parameters into many methods we have would make sense rather than interacting with the [PrefectFuture](https://docs.prefect.io/api-ref/prefect/futures/#prefect.futures.PrefectFuture).

```python
from prefect import flow, pause_flow_run, task
from prefect.states import StateType
from time import sleep

@task
def task_one():
    for i in range(3):
        sleep(1)
        print(i)

@flow
def my_flow():
    terminal_state = task_one.submit(return_state=True)
    if terminal_state.type == StateType.COMPLETED:
        print("Task one succeeded! Pausing flow run..")
        pause_flow_run(timeout=2) 
    else:
        print("Task one failed. Skipping pause flow run..")

if __name__ == "__main__":
    my_flow()
```

If you more feedback or details to add, I'm happy to hear it from you or others :)

**Comment by thomasfrederikhoeck** [comment]
Ah, okay I will use that pattern. Thank you @serinamarie !. I think coming from 1.0 where the trigger `manual` it would be good with above as an example in the documentation for `pause_flow_run`.

Old style:
```pytton
from prefect.triggers import manual_only

@task(trigger=manual_only)
```

**Comment by thomasfrederikhoeck** [comment]
You can leave this open as a request for the documentaion or close it - up to you @serinamarie  :-)

**Comment by serinamarie** [comment]
Thanks for the context @thomasfrederikhoeck! A PR to update the documentation is here: https://github.com/PrefectHQ/prefect/pull/11536
