### ISSUE TITLE
What's the difference between raise signals.SUCCESS() and return state.Success()?

### ISSUE THREAD

**Issue by occoder** [PrefectHQ/prefect#1161]
It confused me for a while that my task run function could either raise signals.SUCCESS() or return state. Success() explicitly. Then what's the difference between them?

**Comment by cicdw** [comment]
Hi @occoder - I'd recommend asking questions like this in our [gitter channel](https://gitter.im/prefectio/prefect) since they don't really constitute a code issue.

To answer your question though: returning a `state.Success()` object is almost certainly not what you want to do.  For example,
```python
@task
def return_state():
    return prefect.engine.state.Failed("FAILED")
```
When that task runs, it will be marked _successful_ and its _result_ will be  `prefect.engine.state.Failed("FAILED")`.  That is, the task state associated with this task will look like:
```python
task_state # Success
task_state.result # Failed("FAILED")
```

Generally speaking, signals are useful for "asserting" the state a task should be in, at any point during its execution pipeline.
