### ISSUE TITLE
CVE in `starlette==0.32.0`, which is pinned due to vendored FastAPI

### ISSUE THREAD

**Issue by barapa** [PrefectHQ/prefect#11719]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When trying to install the latest FastAPI, which depends on starlette, prefect cannot be installed due to version compatibility.

### Reproduction
```python3
Start a new python project and try to add fastapi and prefect as dependencies:

> poetry init
> poetry add fastapi
> poetry add prefect
```

### Error
```python3
Because no versions of prefect match >2.14.16,<3.0.0
 and prefect (2.14.16) depends on starlette (>=0.27.0,<0.33.0), prefect (>=2.14.16,<3.0.0) requires starlette (>=0.27.0,<0.33.0).
And because fastapi (0.109.0) depends on starlette (>=0.35.0,<0.36.0)
 and no versions of fastapi match >0.109.0,<0.110.0, prefect (>=2.14.16,<3.0.0) is incompatible with fastapi (>=0.109.0,<0.110.0).
So, because prefect-bug depends on both fastapi (^0.109.0) and prefect (^2.14.16), version solving failed.
```

### Versions
```Text
Not successfully installed, but attempting to install ^2.14.16
```

**Comment by desertaxle** [comment]
Thanks for the issue @barapa! We vendor our own version of `fastapi` so that we can support `pydantic` versions 1 and 2, but that means that we are pinned to `starlette< 0.33.0`. We will be able to remove our vendored version of `fastapi` and remove our `starlette` pin when we drop support for `pydantic` v1.

**Comment by OliverKleinBST** [comment]
FYI, since lately starlette<0.36.2 also reports a vulnarabilty:
starlette 0.32.0  GHSA-93gm-qmq6-w238 0.36.2
https://github.com/advisories/GHSA-93gm-qmq6-w238

**Comment by chrisguidry** [comment]
Discussed this with @zzstoatzz today:

Our options are:

a) drop support for `pydantic` v1 now (before the deprecation period is technically over), unvendor `fastapi`, and then upgrade both

b) vendor `starlette` and try to apply this same patch to the vendored versions

c) wait for our deprecation period to expire

We both agree that we should pursue option (b) due to the vulnerability in `starlette` and the fact that we still have users on pydantic<2.  Options (a) and (c) both negatively affect Prefect users, and (b) is only a messy situation for Prefect maintainers (that will be resolved later this year when our deprecation period hits).

**Comment by chrisguidry** [comment]
For folks who are blocked until our next release, you can bump `python-multipart` to `python-multipart>=0.0.7` and you'll have the fix.
