### ISSUE TITLE
Duplicate logs when extra loggers including root logger

### ISSUE THREAD

**Issue by guanzhong11** [PrefectHQ/prefect#11727]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I added the `root` logger to the extra loggers to show the root log. 
```
"PREFECT_LOGGING_ROOT_LEVEL": "INFO",
"PREFECT_LOGGING_EXTRA_LOGGERS": "root"
```

When i run deployment, many duplicate logs appear in the flow run.

### Reproduction
Block Environment
```python3
{
  "PREFECT_LOGGING_LOG_PRINTS": "true",
  "PREFECT_LOGGING_ROOT_LEVEL": "INFO",
  "PREFECT_LOGGING_EXTRA_LOGGERS": "root"
}
```

Flow code
```
import logging
from prefect import flow


@flow()
def my_flow():
    logging.getLogger('httpx').disabled = True
    logging.info("flow log")
```

### Versions

```text
Python:   3.9
Prefect:  2.14.12
```

### Additional context

<img width="1611" alt="image" src="https://github.com/PrefectHQ/prefect/assets/125853836/3eabbb02-b55e-4a37-b07b-4da48b5fe635">

**Comment by urimandujano** [comment]
Hi @guanzhong11, the issue here is that the other loggers are are propagating their log records to the root logger, causing duplicate logs to be emitted. 

The way to prevent this is going to be to configure all of the `loggers` propagate setting to be False. This would probably require a custom logging.yml configuration. Alternatively, you could increase the `LOG_LEVEL` for the root logger so that it only picks up more severe logs. Check out this [docs page](https://docs.prefect.io/latest/guides/logs/?h=logging#logging-settings) for more information. 

Feel free to re-open the issue if the configuration options above don't fix the problem.
