### ISSUE TITLE
Escape work pool names when translating from CLI/UI to API URLs

### ISSUE THREAD

**Issue by chrisguidry** [PrefectHQ/prefect#11768]
We had an instance of a customer with a work pool named `' some-word\'` which couldn't be removed via the UI or the API due to the leading space and the trailing `\`.  Work pools are a little different from many of our domain objects, as they are referenced in URLs by their names, and that's the only way to `DELETE` them at the moment.

When the CLI or UI translate work pool names into API URLs, they should each be using HTTP URL encoding, so that example above would become `'%20some-word%5C'` when used in URLs.

**Comment by pleek91** [comment]
I just tried creating a work pool with a space and another with a `/` and both times I got a 422 from the api saying there was an invalid character. How did this work pool even get created? 

Generally that's what I'd expect since I believe things like blocks also use a "slug" which must follow special naming rules (lowercase with dashes)

**Comment by hamzamogni** [comment]
When I was trying to replicate this issue.. using the CLI I could create a work pool named ` something\` (with a backslash)

Afterwards:
- Deleting this work pool thorugh the CLI worked (I couldn't replicate the issue).
- Deleting from the UI couldn't work, replicating the issue.
