### ISSUE TITLE
IntervalSchedule with start_date in the past

### ISSUE THREAD

**Issue by yosemitebandit** [PrefectHQ/prefect#1179]
Is there a way to trigger backfilling?  

I'd like to be able to run a flow against past intervals.  I setup this demo flow, but it's only scheduling runs for the future.

```
"""Demo flow."""

import datetime
import random
import time

from prefect import Flow, task
from prefect.engine.executors import DaskExecutor
from prefect.schedules import IntervalSchedule


@task
def generate_data():
    data = []
    for _ in range(10):
        time.sleep(random.random())
        data.append(random.random())
    return data


@task
def combine(datasets):
    return zip(datasets)


every_minute = IntervalSchedule(
    # Backfill (start dates in the past) not working as expected.
    start_date=datetime.datetime.utcnow() - datetime.timedelta(weeks=1),
    interval=datetime.timedelta(minutes=1),
)

with Flow("demo", schedule=every_minute) as flow:
    d1 = generate_data()
    d2 = generate_data()
    d3 = generate_data()
    d4 = generate_data()
    result = combine([d1, d2, d3, d4])
    print(result)

executor = DaskExecutor(address="tcp://dask-scheduler:8786")
flow.run(executor=executor)

```

**Comment by cicdw** [comment]
Hi @yosemitebandit - great question.  I'm wondering what you would expect to happen with backfilling?  Backfilling will only have a non-trivial effect across its runs if some state of the world is changing with each run.  I'm wondering in your case what you would expect to be different with each run?

**Comment by yosemitebandit** [comment]
Yes, good point, my demo doesn't describe that actual use case very well!

My actual use case: we have thousands of scientific experiments that we've conducted over the past year or so, and we're continuing to conduct new ones.  I was thinking of creating a flow that analyzed all past and future experiments by (1) slicing up the past year into 1hr blocks, (2) finding any experiments that started in each block and (3) running the analysis on those selected experiments.  This would then continue on into the future as the interval schedule ticks away.

I'm pretty new to ETLs / airflow / prefect so I'm guessing there's a better way!  Maybe I could have one flow just analyze all the past experiments before a certain date, and another flow could run on an interval schedule and handle newer data..

**Comment by cicdw** [comment]
Awesome, thanks for the added context - that makes sense!  

In that case, in order to run your flow on historical data I'd recommend:

1. inferring the "historical time" from [Prefect Context](https://docs.prefect.io/api/unreleased/utilities/context.html#context-2) - if you rely on one of those date references for the analysis, then it will be updated with each new run
2. in order to "backfill" in this scenario, you can loop over the various dates / times you want to analyze and override the relevant context values with the `context` keyword argument to `flow.run` (user provided values will override the defaults)

Alternatively, depending on whether you truly need this to run on a proper schedule, you could introduce a `Parameter` that represents the experiment (or batch of experiments) you wish to analyze, and kick the flow off manually with various values of this `Parameter`.

**Comment by yosemitebandit** [comment]
great, thanks for the pointers!

**Comment by snenkov** [comment]
Hi,
I have a similar issue, but my use-case is such that each ETL I add to Prefect is one which fetches data from a source.
So I want it to run (once) for all past dates (e.g. if the schedule is on a daily interval) in order to fetch all historical data and then to run on schedule.

I tried finding a way to do this based on your conversation in this thread, but could not.
Can you please shed more light if this is possible and if so, how?: )

**Comment by cicdw** [comment]
Hi @snenkov for example:

Using context:
```python
import pendulum
import prefect

@prefect.task
def do_something_time_specific():
    current_time = prefect.context.get("scheduled_start_time")
    if isinstance(current_time, str):
        current_time = pendulum.parse(current_time)
    # does something dealing with time

flow = Flow("backfill", tasks=[do_something_time_specific])

flow.run() # will use current timestamp
flow.run(context={"scheduled_start_time": "1986-01-02"}) # will use old timestamp
```

Using a Parameter:
```python
import pendulum
import prefect

current_time = Parameter("timestamp", default=None)

@prefect.task
def do_something_time_specific(current_time):
    if current_time is None:
        current_time = prefect.context.get("scheduled_start_time")
    if isinstance(current_time, str):
        current_time = pendulum.parse(current_time)
    # does something dealing with time

with Flow("backfill") as flow:
    do_something_time_specific(current_time)

flow.run() # will use current timestamp
flow.run(current_time="1986-01-02") # will use old timestamp
```

There are analogous things you can do if running against a Prefect backend (as both context and Parameters can be provided to each run), and also for runs that have schedules.

Also note that [this PR](https://github.com/PrefectHQ/prefect/pull/3327) will make Parameter typing more natural for datetime objects.

**Comment by snenkov** [comment]
Thank you very much. I will try this shortly. It looks like exactly what I am looking for.

I see you define a new flow, called “backfill”.
Does this suggest that it’s a “best practice” to actually have two separate flows:
- one for backfills like the one I asked for
- one for the exact same tasks, but for ongoing?

**Comment by cicdw** [comment]
Great - let me know how it goes!

Sorry the name was misleading - I recommend you use the same flow for both use cases.  You can run a Flow both on a well defined schedule and introduce ad-hoc runs as you see fit. This is particularly easy if you use a Prefect backend!

**Comment by snenkov** [comment]
Got it. Two final questions:
- (rookie question) what is a Prefect backend?
- what you suggest, i can register (such that it goes to the UI) and will run the historical component only once - the run as schedules for future dates and times. Is my understanding correct?

**Comment by cicdw** [comment]
- by "Prefect backend" I meant either [Prefect Server or Prefect Cloud](https://docs.prefect.io/orchestration/)
- that is correct; you can create as many (or as few) ad-hoc historical runs as you'd like, at anytime.  If you want to create your historic runs _first_ (before running the standard schedule), then when you register the Flow you can pass `set_schedule_active=False` so the schedule is not activated until you choose to activate it

**Comment by snenkov** [comment]
Hi @cicdw,

I ran my code now with your first suggestion and unfortunately I still struggle to pass a different start time from now.

Here is my full reproducible code:

```
import prefect
from prefect import task, Flow


@task
def extract_data():
    current_time = prefect.context.get("scheduled_start_time")
    print('current_time', current_time)
    print(type(current_time))
    if isinstance(current_time, str):
        current_time = pendulum.parse(current_time)
    else:
        print("current_time is not a string")


with Flow("My-First-Flow") as flow:
    extracted_data = extract_data()
    

# will use old timestamp
flow.run(context={"scheduled_start_time": "2019-01-01"})
```

And here is the output I get:

```
[2020-09-23 21:22:25] INFO - prefect.FlowRunner | Beginning Flow run for 'My-First-Flow'
[2020-09-23 21:22:25] INFO - prefect.TaskRunner | Task 'extract_data': Starting task run...
current_time 2020-09-23T21:22:25.599161+00:00
<class 'pendulum.datetime.DateTime'>
current_time is not a string
[2020-09-23 21:22:25] INFO - prefect.TaskRunner | Task 'extract_data': finished task run for task with final state: 'Success'
[2020-09-23 21:22:25] INFO - prefect.FlowRunner | Flow run SUCCESS: all reference tasks succeeded
```

In short, the `prefect.context.get("scheduled_start_time")` is of type DateTime (not str), which is obviously not a problem.
The problem is that it's not value which I pass in `low.run(context={"scheduled_start_time": "2019-01-01"})`.


I also tried added a schedule (thinking this may fix it), like so: 

```
from datetime import timedelta

from prefect.schedules import Schedule
from prefect.schedules.clocks import IntervalClock

schedule = Schedule(clocks=[IntervalClock(interval=timedelta(days=1))])
```

and then only changed `with Flow("My-First-Flow", schedule=schedule) as flow:`

but it simply waits for the next scheduled run: `[2020-09-23 21:26:50] INFO - prefect.My-First-Flow | Waiting for next scheduled run at 2020-09-24T00:00:00+00:00`


Do you know what might be the issue here?

**Comment by joshmeek** [comment]
Apologies as I haven't been following the full conversation but it looks like the `scheduled_start_time` is being overridden here
https://github.com/PrefectHQ/prefect/blob/4d65753882b0646433fcadb1030f90b3f829300a/src/prefect/core/flow.py#L1022-L1027
and instead it should be using the value found in `flow_run_context` if provided.

**Comment by snenkov** [comment]
Hi @joshmeek, can you please place this in the context of my code? I could not follow what change I must make to get the historical dates backfilling working, from a specific date.

**Comment by joshmeek** [comment]
@snenkov Ah sorry, not a problem with your code at all! This piece right here was changed recently to allow for some backend specific functionality to work in local runs and I think this got overlooked. I'm actually going to make the PR to update this right now 🙂

**Comment by snenkov** [comment]
Sure, @joshmeek  : ) In regards to my code, can you help me solve this issue? I guess for a more experience users of Prefect, it should be more trivial. I just don't know how to start a Flow from a past date and run it based on some schedule (e.g. each day since 2010-01-01 up to now and to continue the schedule in the future ofc).

**Comment by joshmeek** [comment]
Okay okay I have caught up now. We don't want to be using `scheduled_start_time` in context because that's somewhat of a reserved word for flow runs. Besides that it doesn't actually matter what we call the context key. We could just do something like `intended_backfill_start_time` and it would work like this:

```python
import pendulum
import prefect

@prefect.task
def do_something_time_specific():
    current_time = prefect.context.get("intended_backfill_start_time")
    if isinstance(current_time, str):
        current_time = pendulum.parse(current_time)
    # does something dealing with time

flow = Flow("backfill", tasks=[do_something_time_specific])

flow.run() # will use current timestamp
flow.run(context={"intended_backfill_start_time": "1986-01-02"}) # will use old timestamp
```

I believe as it currently stands to create a backfill like that you are going to want to loop over the desired time values and create a flow run for each date in the past. I don't think schedules natively support times in the past. Something like this would be defined as:

```python
import pendulum

current_date = pendulum.datetime(2010, 1, 1)
end_date = pendulum.now()

while current_date < end_date:
  flow.run(context={"intended_backfill_start_time": current_date})
  current_date.add(days=1)
```
