### ISSUE TITLE
Allow from_source to get source from a string (i.e. InMemoryStorage)

### ISSUE THREAD

**Issue by nileshtrivedi** [PrefectHQ/prefect#11798]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

According the [docs for managed execution](https://docs.prefect.io/latest/guides/managed-execution/#code-storage), `from_source` currently supports only git-based storage and remote block-based object like S3. I cannot load the source of a flow from an in memory string.

### Describe the proposed behavior

It would be amazing to have the ability to pass the flow source code directly as a string. This would allow flows to be maintained in SQL databases which are both easier to query and manipulate/update.

As we can see from [the source code](https://github.com/PrefectHQ/prefect/blob/1bb9c73ceb355bbf7ba17927c2f740f533752209/src/prefect/flows.py#L792) of `flow_source`, source needs to be either a URL to a git repository or a storage object. This feature request is about a new type `InMemoryStorage` to be used with `flow_source`. This could be initialized with any dict which would map filenames to the file contents.

**Comment by desertaxle** [comment]
Thanks for the issue, @nileshtrivedi! While loading flows from in-memory strings is possible, using `InMemoryStorage` with `flow.deploy` will be difficult. We need to serialize each storage type into a pull step, which is stored serverside. The only way to get a flow loaded from an in-memory string to the remote execution environment is to write the entire flow string in a pull step. We opt for referencing remote files for flows so users don't need to store their flow code serverside.

Your idea for storing flow code in an SQL database is very interesting! We generally use directories for storing and retrieving flow code to make sure things like relative imports work, but if that isn't necessary in your use case, pulling flow code from a database could work. You can implement a class that adheres to the [`RunnerStorage`](https://github.com/PrefectHQ/prefect/blob/f5b6285775f9584cb8096a121f5465c14ce74852/src/prefect/runner/storage.py#L27) protocol to enable this functionality.

All in all, I don't think that we'd accept an `InMemory` storage type into the core library because it wouldn't support some key use cases, but you can extend Prefect to suit your use case by creating your own implementation of our interfaces. Let me know if you have any questions and I'll be happy to clarify!

**Comment by nileshtrivedi** [comment]
I understand. The idea was for flows to be modifiable at run time. It does seem like I can achieve that via remote block storage.
