### ISSUE TITLE
Enhanced deployment parameters UI does not work with optional parameters (None)

### ISSUE THREAD

**Issue by fredrikhgrelland** [PrefectHQ/prefect#12067]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

![image](https://github.com/PrefectHQ/prefect/assets/40291976/b9b0a6b4-9877-415e-8afc-98fd7ffda0c7)

### Reproduction

create optional parameters in a flow:
`@flow(
    flow_run_name=flow_run_name,
    log_prints=True,
    retries=1,
    version=settings.version,
)
async def sync(
    table,
    target,
    limit=None,
    source={},
    full_refresh=False,
):`

### Error

see screenshot

### Browsers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```Text
Version:             2.14.21
API version:         0.8.4
Python version:      3.11.1
Git commit:          9a059bfe
Built:               Thu, Feb 8, 2024 5:35 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         cloud
```

**Comment by marcinpurtak** [comment]
I have experiencing the same issue after the last release. Quick run's are currently not possible to start becouse of that issue. Same thing happened at the begining of January 2024! Last time when you left any parameter window empty and hit quick run it was passing empty string instead of None. Probably it is same issue right now. :(
![image (8)](https://github.com/PrefectHQ/prefect/assets/44641138/28494578-2cc5-45e9-bc44-2a24ea3bad7a)

**Comment by jakekaplan** [comment]
The fix for this should be out. Please let me know if you're still having an issue!

**Comment by fredrikhgrelland** [comment]
It works now.
