### ISSUE TITLE
docs - how does prefect manage the dependencies?

### ISSUE THREAD

**Issue by flypenguin** [PrefectHQ/prefect#12076]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

when reading the quickstart, you use the "httpx" pypi dependency.

yet there is _no_ mention at all to any dependency management on the whole page. since this is even part of the quickstart, that would be _very_ much worth mentioning. (a link might suffice)

### Describe the proposed change

add information (one line / one link might be enough) about python dependency management (note: _not_ prefect task dependency management) on deployments into prefect cloud on this page https://docs.prefect.io/latest/getting-started/quickstart/

**Comment by discdiver** [comment]
Thanks for opening and noting that the presence of httpx could use some clarification. PR is up.
Dependency management in Prefect is nice in that you just need any packages to be installed in the execution environment.

httpx is a dependency of Prefect, so that one is nice.

Depending upon the type of work pool, we have a few ways to get Python packages installed into the execution environment (e.g. specify it in an `extra_pip_packages` environment variable and it will be installed into a Docker container at runtime, put it in a `requirements.txt file` and Prefect will build it into a Docker image for you. 

We show those ways at various places in the docs (e.g. in the discussion of [deploying with work pools](https://docs.prefect.io/latest/guides/prefect-deploy/#additional-configuration-with-deploy) , but it's a bit more in the weeds than we want to get in the Quickstart.
