### ISSUE TITLE
Imperative Patterns Documentation

### ISSUE THREAD

**Issue by kforti** [PrefectHQ/prefect#1207]
I am finding it difficult to piece together the docs to find the imperative patterns for building Tasks and Flows. In my application, I am passing around an instance of a Flow between python objects which are adding tasks to that Flow. There is this snippet that explains an imperative way of creating a [flow](https://docs.prefect.io/guide/core_concepts/flows.html#imperative-api), but I see many more api's for tasks and flows in the api guide that could also make it easier to build flows in the way I described. 

I am thinking to add examples to the Task and Flow methods in the api docs, as I experiment with the code to get my pattern right. Is this something that you think would be useful?

Also, is it possible to set dependencies using just the slug of the upstream task?

Kevin

**Comment by cicdw** [comment]
Hi @kforti - excellent question.

- here is another example of the imperative API: https://docs.prefect.io/guide/examples/imperative_docker.html
- we would love more examples of how people are using the imperative API, so please don't be shy about contributing one! 
- currently, we don't expose a way of setting the dependencies via slug unfortunately, but it is an interesting idea...

**Comment by joshmeek** [comment]
@wagoodman We should revisit the idea of making all "advanced" tutorials in both functional as well as imperative formats

**Comment by DataDaoDe** [comment]
I just wanted to say I am having a similar experience as that of @kforti . 

As someone who is trying to learn prefect, the functional API seems to me to hide a lot of what is actually happening under the hood. This makes it really difficult to undestand how prefect works at the detailed level you need so that you can manipulate the classes and functions to your own custom requirements. 

The imperative API on the otherhand is quite explicit and shows you exactly how things can be stitched together. As a beginner and for me at least, I would prefer / am only interested in the imperative API tbh, for the reasons outlined above. For me, the functional API is a nice shortcut if you can use it for your use case, but actually hinders understanding how prefect works.

These are just my opinions, overall I am really liking prefect though :)
