### ISSUE TITLE
Flow run - custom run - Literal with string values and None, None is not allowed in dropdown - new UI

### ISSUE THREAD

**Issue by NodeJSmith** [PrefectHQ/prefect#12199]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

A parameter that has a type hint such as `Literal["prod", "stage", "uat", "dev", None]` does not show `None` as an option in the select dropdown when creating a custom flow run in the new UI, requiring that you deselect the Validate Parameters button to submit the run. It does work in the old UI. 

### Reproduction

The below flow will replicate this. I believe this is specific to Pydantic v1, I was not able to replicate in V2:

```python
import asyncio
from typing import Literal

from prefect import flow, serve
from prefect.deployments.runner import RunnerDeployment
from pydantic import BaseModel, Field


class ServerEnvMixin(BaseModel):
    server_env: Literal["prod", "stage", "uat", "dev", None] = Field(
        None, description="The server environment, defaults to None to be inherited from environment"
    )


# conductor
@flow(name="test")
async def test_flow(server_env: ServerEnvMixin):
    print(server_env)


async def test_deployment() -> RunnerDeployment:
    deployment: RunnerDeployment = await test_flow.to_deployment("test-deployment")

    await serve(deployment)


if __name__ == "__main__":
    asyncio.run(test_deployment())
```

### Error

As shown below, there is no option for a None or empty value. If the default is set to None the value will default to not being selected, but this will cause `'server_env' is a required property`  error if `Validate parameters before submitting` is checked.

![image](https://github.com/PrefectHQ/prefect/assets/8505845/96a1abdb-6f39-41c5-8985-729d7edc615b)

![image](https://github.com/PrefectHQ/prefect/assets/8505845/ad8359b8-536d-455c-85be-d832c25d2478)

### Browsers

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

**Comment by pleek91** [comment]
@NodeJSmith we use pydantics[ json schema ](https://docs.pydantic.dev/2.6/concepts/json_schema/)feature to generate a schema for deployment parameters that we then use to generate the ui. I believe what you are seeing is an [issue](https://github.com/pydantic/pydantic/issues/1270) with pydantic v1 where `None` is incorrectly omitted from that schema. 

This was fixed in pydantic v2. 

We're still investigating how we can work around issues like this with pydantic v1. But right now you can work around this by selecting "Use JSON Input" for the parameter in question and set the value to `null`. 

<img width="183" alt="image" src="https://github.com/PrefectHQ/prefect/assets/6200442/363d246f-efa2-4fd8-a361-29b97fffed3b">

You shouldn't get a validation error but if you do you can uncheck the "validate parameters before submitting" checkbox to skip validation. 

Also, if you are able to upgrade to pydantic v2 and then re apply your deployment you would see `None` as an available option in the dropdown.

**Comment by pleek91** [comment]
I'm going to close this issue for housekeeping. We were able to make some tweaks to validation so if you use JSON to enter a `null` (`None`) value it should pass validation. But we're not able to fix the underlying schema issue from pydantic 1. Please let us know if this work around isn't working for you. Sorry we weren't able to do more here.
