### ISSUE TITLE
Using Parameter() as part of command line arguments

### ISSUE THREAD

**Issue by tokestermw** [PrefectHQ/prefect#1253]
Hi, I have this simple script that takes command line arguments (through CLI package `plac`). Let's say I have an argument called `model_name`, and I would like to pass this argument into Prefect Flow using `Parameters`. So I define `model_name` as a possible command line argument *and* I define `model_name` as a `Parameters` (which I rename to `model_name_param` to avoid namespace collision):

```python
@plac.annotations(
    model_name=("This is model name", ),
)
def main(model_name):

    with Flow('Train spaCy NER') as flow:
        model_name_param = Parameter("model_name")

        train_data = load_train_data()
        nlp = load_model(model_name_param, train_data)

    flow.run(model_name=model_name)


if __name__ == '__main__':
    plac.call(main)
```

Are there best practices to use Prefect with a CLI package? It feels a little redundant to define `model_name` twice, but maybe I'm not doing this right. Thanks!

**Comment by joshmeek** [comment]
Hey @tokestermw! So for my understanding you have a CLI command which takes in `model_name` and passes it to a flow through the `model_name_param`. As far as I know this seems to me like a good practice because you need to thread the `model_name` from the CLI into the flow. Alternatively you could just pass the `model_name` to the task itself here because you are recreating the flow every time and `model_name` would be treated as a constant.

I'm not entirely sure how the `plac` package works but another approach could be to instantiate the flow elsewhere and have the CLI command only call `flow.run(model_name=model_name)` instead of recreating the flow every time. 

There really is no one true way of doing this but it looks like you're on the right path!

**Comment by cicdw** [comment]
Closing this as I believe @joshmeek 's answer is solid.
