### ISSUE TITLE
Memory leak impacting long running flows

### ISSUE THREAD

**Issue by bellmatthewf** [PrefectHQ/prefect#12668]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Prefect `@task` has a memory leak, impacting long running scripts. Memory consumption continues to increase with the number of task runs. Memory usage during tasks is not fully garbage collected.

The example below should prove that this leak is coming from Prefect.

### Reproduction

Here's a minimum viable example using the [memory-profiler](https://pypi.org/project/memory-profiler) package to demonstrate the leak.

In this script we have two functions that create identical lists. One is wrapped in `prefect.task` and one is not.

```python3
from memory_profiler import profile
from prefect import flow, task


@task(cache_result_in_memory=False)
def with_task():
    return [{"abc": "123"} for _ in range(10_000)]


def without_task():
    return [{"abc": "123"} for _ in range(10_000)]


@flow(cache_result_in_memory=False)
@profile
def main():
    for i in range(1000):
        with_task()
        # without_task()
    print("DONE")
```

The `@profile` decorator from `memory_profiler` outputs memory usage. When calling the function wrapped in `prefect.task` we can see usage from the task is `199.1 MiB` shown below.

```
Line    Mem usage    Increment  Occurrences   Line Contents
==========================================================
    82    177.2 MiB    177.2 MiB           1   @flow(cache_result_in_memory=False)
    83                                         @profile
    84                                         def main():
    85    199.1 MiB  -3872.8 MiB        1001       for i in range(1000):
    86    199.1 MiB  -3850.9 MiB        1000           with_task()
    87                                                 # without_task()
    88    189.2 MiB     -9.9 MiB           1       print("DONE")
```

The important thing to call out here is that this number scales with the number of iterations our task. If we reduce iterations from `range(1000)` to `range(100)` memory consumption drops significantly. Similarly, if we increase the iterations of our task, memory consumption will continues to grow infinitely, even though we aren't storing anything in memory between task runs.

Conversely, if we run the `without_task` function instead, no matter how many iterations we do of our function, memory usage stays constant at `176.9 MiB`. Increasing or decreasing the number of function calls has no bearing on memory usage, as we would expect.

```
Line    Mem usage    Increment  Occurrences   Line Contents
==========================================================
    82    174.7 MiB    174.7 MiB           1   @flow(cache_result_in_memory=False)
    83                                         @profile
    84                                         def main():
    85    176.9 MiB     -5.0 MiB        1001       for i in range(1000):
    86                                                 # with_task()
    87    176.9 MiB     -2.9 MiB        1000           without_task()
    88    176.9 MiB      0.0 MiB           1       print("DONE")
```

This to me confirms that it's a bug in `prefect.task` that is causing the leak.

Additionally, the size of the memory leak scales with the amount of memory used during tasks. If we increase `range(10_000)` in both our functions to make them use more memory. We can re-run both functions and see that memory consumption from the function with the `@task` decorator grows disproportionately compared to the non-task function.

### Error
No error, but memory consumption grows infinitely with task runs

### Versions

```Text
Version:             2.16.8
API version:         0.8.4
Python version:      3.12.1
Git commit:          11cb641c
Built:               Fri, Mar 29, 2024 11:01 AM
OS/Arch:             darwin/arm64
Profile:             development
Server type:         server
```

**Comment by cafebaba001** [comment]
prefect has so many bugs,It's not yet suitable to be launched as a commercial product now.

**Comment by adamkpi** [comment]
Bump!

**Comment by Omarble** [comment]
bump

**Comment by zhen0** [comment]
Thanks for the issue @bellmatthewf and for the bumps @adamkpi and @Omarble!  This is something that is on our radar and that we hope to look into further in the next few weeks.

**Comment by zhen0** [comment]
@cafebaba001 - I'm removing your comment as it wasn't additive to the issue and it feels out of keeping with our code of conduct.  Feel free to reach out to me if you have feedback you would like us to listen to!

**Comment by abrookins** [comment]
Hey @bellmatthewf! Thanks for keeping the flame alive. I've cleared my desk for next week and will focus on learning more.

I made some initial explorations this week. Flows keep track of all tasks that run within them, which, in the case of long-running flows that run many tasks, can generate small amounts of runtime data that add up over time, especially futures and weakrefs to futures. Large numbers of weakrefs can end up in various places and stay in memory until Python decides to release them. One type of object that grows the most in your example code is `ReferenceType`, which suggests weakrefs aren't getting released. As always, that could be a red herring, but I'll start there next week.

**Comment by bellmatthewf** [comment]
Much appreciated @abrookins, sounds like a great starting point 🍻

**Comment by abrookins** [comment]
Hello again, @bellmatthewf! I explored the example code you shared in a few different ways, with tracemalloc, objgraph, memray, and mprof. I'll list my conclusions, intentionally written in a way that explains more than you may need to know, in case the audience is wider:

0. Defining a few terms that may be obvious but help keep me on track: I'm going to talk about "flows" and "tasks," and I mean "your Python function decorated with `@flow`" or "your Python function decorated with `@task`." We also sometimes refer to "flow runs" and "task runs," which are the API records we create when one of these functions actually runs.

1. Using the given example code, I didn't find evidence of a memory leak, only memory growth as a result of the way flows track their calls of tasks and other flows. With Prefect, memory grows (slowly, but consistently) over time as a single flow executes tasks or other flows. The reason is that [flows keep track of all task calls, states, and results](https://github.com/PrefectHQ/prefect/blob/0d89908ea7023894893b9a13b3d23e942777c264/src/prefect/context.py#L394-L398). Until the flow exits, this data stays in memory. We call the object that does this bookkeeping the "engine context."

2. When the flow exits, we delete the engine context. After that happens, Python's GC will eventually delete the task futures, states, result references, etc. So to the extent that a worker might see memory grow over time, as #12989 reports, the issue would only be related to this bookkeeping if the worker was executing long-running flows that ran other tasks or flows. (This doesn't rule out a memory leak specific to the kubernetes worker -- I just haven't found one in that worker yet.)

3. Flows also keep records when they call other flows directly (as a function call, as opposed to running a "deployment" of a flow asynchronously). So memory will also grow the same way when a long-running flow continuously runs other flows, instead of tasks. This would account for #12458.

I'm sure that still leaves you wondering how to run a long-running flow that executes many tasks in a way that won't OOM. There may be better options, but generally, some ideas are:

1. Using a different flow/task design. If you are iterating through batches of work in a long-running flow and sending batches to a task, consider a design that uses one flow to iterate over the batches and then [triggers another flow using a deployment](https://docs.prefect.io/latest/concepts/deployments/#running-a-deployed-flow-from-within-python-flow-code). Maybe the input to the batch flow is a set of IDs or filenames, etc.

2. Consider an event-driven design using [automations](https://docs.prefect.io/latest/concepts/automations/). For example, you could create an automation that uses a Prefect-hosted webhook to receive batches of IDs, filenames, URLs, etc. and automatically runs a flow using a deployment to process that batch.

3. You might start evaluating [Prefect 3](https://www.prefect.io/blog/introducing-prefect-3-0). In case it sounds like I'm just shrugging at memory growth, I'm not! We removed this bookkeeping when we built Prefect 3, in part to better support long-running flows that execute many tasks. This means that some features of Prefect 2 that relied on the bookkeeping work differently in Prefect 3 (or don't exist). For example, in Prefect 2, flows automatically wait for all task futures to resolve, but in Prefect 3, which doesn't track task calls, you have to explicitly wait for the futures to resolve. But the benefit is, of course, that memory does not grow as you execute tasks within the same flow.

**Comment by bellmatthewf** [comment]
@abrookins, thank you for the work you've put in and the thoughtful response. What you've explained makes sense. In particular if upgrading to Prefect 3 is all it takes to solve this, then we have an easy fix, which would be amazing!

To make sure I am covering all bases that this is not in fact a leak, let me give you a scenario using my initial example.

If we do 10 task iterations of 10,000 objects in the returned list, memory consumption is 178.8 MiB
If we do 100 task iterations of 10,000 objects in the returned list, memory consumption is 183.2 MiB

**A gain of ~5 MiB going from 10 -> 100 task iterations of 10k items in the return array**

If we do 10 task iterations of 100,000 objects in the returned list, memory consumption is 225.2 MiB
If we do 100 task iterations of 100,000 objects in the returned list, memory consumption is 234.8 MiB

**A gain of ~10 MiB going from 10 -> 100 task iterations of 100k items in the return array**

This shows that memory growth increases faster based on the size of memory used/returned in our task.

I realize that this lines up with you saying
> The reason is that [flows keep track of all task calls, states, and **results**](https://github.com/PrefectHQ/prefect/blob/0d89908ea7023894893b9a13b3d23e942777c264/src/prefect/context.py#L394-L398)

Storing results in particular would understandably account for this faster growth.

However, in the example above I've already set `cache_result_in_memory=False` so why are results even being stored? I would have expected us not to be storing any results with that setting. I have a hunch that if results weren't stored, the other engine context items wouldn't cause any issues.

**Comment by abrookins** [comment]
@bellmatthewf I agree that the behavior you described sounds like an example of this design causing memory growth in proportion to the number of task calls made within the same flow. Reviewing the behavior, I don't see (yet) how memory growth would scale with the size of the data the tasks return. I'll come back to this, but first I want to correct my comment about Prefect 3.

Rereading the Prefect 3 engine code today, I realized I was wrong: while the new engine dropped some of Prefect 2's tracking, it retained task call tracking. **So Prefect 3 is not currently a solution to this problem**. I will review the design with our team ASAP to see if we can make this behavior configurable.

I agree that it's reasonable to think the `cache_result_in_memory=False` would disable this behavior. However, that option controls whether or not individual states -- the objects that track the state of a single task call -- cache their result objects. (A state contains the result of a task call.)

Separately from caching results on state objects, we save the state object for each task call made within a flow so that we can [resolve task dependencies](https://docs.prefect.io/latest/guides/specifying-upstream-dependencies/). So in theory, a new option could exist that disables dependency tracking. Other features may depend on these states, so we'd need to evaluate that.

Returning to the question of whether memory growth scales with the _size_ of returned objects, not just the number of calls: if in-memory caching is disabled, we continue to store the state object in memory, but it does not contain the true result object, only a reference to it.

This is why I don't see how the size of the return object would increase memory growth, only the number of task calls (and thus the number of state objects we're accumulating).

Using your example code, the state objects that accumulate in `task_run_results` look like this:
```python
Completed(message=None, type=COMPLETED, result=PersistedResult(type='reference', artifact_type='result', artifact_description='Result of type `list` persisted to: `/Users/andrew/.prefect/storage/b7854bda821d436598a2fdfb19030827`', serializer_type='pickle', storage_block_id=UUID('9ae9a4b1-b10f-4bf7-ab5c-288ba3059610'), storage_key='b7854bda821d436598a2fdfb19030827'))
```

The size of this object is 56 bytes:
```python
ipdb> sys.getsizeof(flow_run_ctx.task_run_results[4768702960])
56
```

But the actual task result is larger -- calling `result()` fetches it from storage:
```python
ipdb> sys.getsizeof(flow_run_ctx.task_run_results[4768702960].result())
90104
```

However, even without the actual result in memory, the problem remains -- memory will continue to grow with each task call.

I will post an update after I do some thinking on this one!

**Comment by bellmatthewf** [comment]
> This is why I don't see how the size of the return object would increase memory growth, only the number of task calls (and thus the number of state objects we're accumulating).

Exactly what I'm wondering too.

You can imagine if iterating through tasks of 500mb returned results, if Prefect memory is growing based on task memory usage, then this quickly becomes a problem.

Based on the `task_run_results` object that you've described above, I think there must be another piece of this puzzle. This object is too small to be causing the issues that we've seen.

**Comment by abrookins** [comment]
I agree. It's hard to believe the states data structure is responsible. I've also tested an early return from the link function, and memory use doesn't change much.

However, disabling result persistence does affect memory use. Using this version of your example code, the difference between runs with result persistence turned off vs. on is around 100 MB. 🤔 🤔 I'll look closer into this.

```python
@task(cache_result_in_memory=False, persist_result=False)
def with_task():
    return [{"abc": "123"} for _ in range(200_000)]


def without_task():
    return [{"abc": "123"} for _ in range(200_000)]


@flow(cache_result_in_memory=False)
@profile
def my_flow():
    print("START")
    for i in range(1000):
        with_task(return_state=True)
        # without_task()
    print("DONE")
```

**Comment by abrookins** [comment]
I found what is probably the source of most of this memory use -- serialization when we persist results: https://github.com/PrefectHQ/prefect/blob/2.19.7/src/prefect/results.py#L681-L690

Following along the memory allocations with an example of the result of one task run (a list containing 100,000 strings), we make:
1. An allocation for the object the task returns, a list of strings: 0.06 kb.
2. An allocation for the pickled form of the object: 683 kb.
3. An allocation for the base64-encoded, pickled form of the object: 923 kb.
4. An allocation for the JSON-serialized `PersistedResultBlob` obj, which contains another copy of the base64-encoded, pickled object: ~923 kb.
5. Allocations when Python writes the object to a file: ~2 mb.

Given a starting object of 0.06 kb, multiple serialization steps introduce write amplification (into memory) totaling around 4.5 mb for each task call. Even if the memory doesn't "leak," it will stay allocated until Python garbage collects it, and then I think [there can also be a delay](https://bloomberg.github.io/memray/memory.html#memory-is-not-freed-immediately) before memory is _actually_ freed at the OS level.

Prefect 3 has better optimized serialization and results persistence. Here is memory usage from the same code (the example we've been using in this issue) in Prefect 2 and then Prefect 3:

Prefect 2:
```
    64    265.6 MiB  -1048.5 MiB          51       for i in range(50):
    65    265.6 MiB   -985.0 MiB          50           with_task()
```

Prefect 3:
```
    64    159.0 MiB   -154.0 MiB          51       for i in range(50):
    65    159.0 MiB   -133.8 MiB          50           with_task()
```

**Comment by abrookins** [comment]
So I believe the summary here is:
- Serialization during result persistence requires copying task return values
- This process uses significantly more memory in Prefect 2 than Prefect 3
- We may or may not improve serialization performance in Prefect 2 depending on other priorities., but we are definitely investing heavily in Prefect 3's performance, here and elsewhere in the engine

**Comment by bellmatthewf** [comment]
Thanks again for the hard work on this Andrew. I think this answers the root cause of the issue. We will try out Prefect 3 and can open a separate issue if it memory usage continues to cause problems.

**Comment by yaronlevi** [comment]
@bellmatthewf You wrote:

"You can imagine if iterating through tasks of 500mb returned results, if Prefect memory is growing based on task memory usage, then this quickly becomes a problem."

I think that if you are returning 500mb from a Task result, this might a "red flag" for flow design and maybe you should consider a different desing. Ideally the orchestrator (could be Prefect, Airflow etc...) just activates computes that lives somewhere else, and just monitors the result and "orchestrate" things. If suddenly a 500mb object made it's way into the orchestrator land, it could lead to those memory/cpu/state-serialisation issues.

Couldn't you architect your flow in a way that those big MB/GB objects are never passed through the orchestrator, but instead passed via something like an S3 or any other DB?

**Comment by abrookins** [comment]
Thank you for your advocacy for better memory use, your MREs, assistance debugging, and responsiveness @bellmatthewf! I'm closing this now that we've found the largest source of runtime memory use. We will continue to optimize Prefect 3's use of memory. If we find any improvements that apply to Prefect 2's architecture, we'll backport those as time allows!

**Comment by yushao2** [comment]
Hello, can the memory use optimizations be backported to prefect 2?:
