### ISSUE TITLE
Work pool is returned as null when flow runs are in a running & scheduled state - Cloud only

### ISSUE THREAD

**Issue by zhen0** [PrefectHQ/prefect#12775]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I'm consistently seeing the api return  "`work_pool_id": null`, & "`work_pool_name": null` for flow runs in a scheduled and running state. It seems to return them in a pending state.

This only seems to happen on the get flow_runs/id route (i.e. for individual flows and not on the `post flow_runs/filter` route) and is showing up in the UI on the flow run page.  The flow run list item (which uses the `post flow_runs/filter `route) meanwhile is showing the correct information.

Potentially connected to [this user issue](https://github.com/PrefectHQ/prefect-ui-library/issues/2260)e where they are seeing a difference in run duration in the flow run page vs the list item.  (I was not able to replicate but found the above while trying to do so.) 

### Reproduction

```python3
Create a flow run and watch it from the UI flow run page - the work pool is not shown when in a scheduled or running state.  You can also see the api returns from the network tab.
```

### Versions

```Text
Cloud
```

### Additional context

Examples from the same run:

<img width="1253" alt="image" src="https://github.com/PrefectHQ/prefect/assets/40272060/08dc3986-63fc-408d-837f-248672a515f8">

<img width="1159" alt="image" src="https://github.com/PrefectHQ/prefect/assets/40272060/34a027be-7153-4e8a-9276-17d22aeb0d13">

<img width="1259" alt="image" src="https://github.com/PrefectHQ/prefect/assets/40272060/c9c29717-0e79-4a6a-893d-569d21748e12">

**Comment by bunchesofdonald** [comment]
I wasn't able to replicate this issue, but I believe it was inadvertently fixed by our switch from the legacy caching we were doing to the new single object caching we built out.

The legacy caching was only updating/invalidating the flow run cache, which also contained the work-queue / work-pool data, when a flow run was cleaned up (post-deletion), or when the flow run was updated. The single object cache has a direct link to the work-queue (which has a direct link to work-pool) so it's doesn't have this stale cache issue.
