### ISSUE TITLE
Breaking change in 0.6.0

### ISSUE THREAD

**Issue by orcaman** [PrefectHQ/prefect#1288]
Hi team,

We were using release 0.5.5 and when trying to upgrade to 0.6.0 we are faced with a breaking change: prefect forces us to use all lowercase letters for keys in the config.toml file. 

This creates a problem for us because we have several keys who are different only in their letter-casing by design, so that if we try to lowercase both, we are faced with a duplicate key. 

Is there a good reason for this change or is it something that may be fixed?

Thanks!

**Comment by jlowin** [comment]
Hi @orcaman - the reason for this change was that the primary way of setting configuration values is by environment variable, and depending on the OS, env vars may not respect case. Therefore it becomes impossible to update a mixed-case configuration key by environment variable. (We found this one out the hard way from some Windows users.) Moreover, we don't want to only update configuration keys that exactly match the environment variable because most env vars are uppercase by convention, but prefect keys are generally not.

However, we could consider relaxing the error message and documenting that environment variables can only be used to override lower-case config keys. @cicdw what do you think?

**Comment by orcaman** [comment]
@orcaman that would be great!

**Comment by jlowin** [comment]
@orcaman please see #1290
