### ISSUE TITLE
Consider integrating Apprise for notification support

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/prefect#1295]
Apprise is a lightweight notification service for Python with [many integrations](https://github.com/caronc/apprise#popular-notification-services).

A notification task could look as simple as this, while still enabling users to send messages to almost 50 different network (including Slack, email, Twitter, SMS, and arbitrary JSON payloads).

```python
@task
def notify(url, title, body):
    # NOT TESTED
	a = Apprise()
    a.add(url)
    a.notify(title, body)
```

Because (I believe) Apprise embeds auth in the URL, this would be as easy as returning the URL from an appropriately-configured task OR allowing users to set it via secret. 

Bonus points for embedding this in a state handler...

**Comment by jlowin** [comment]
Slack support appears to be based on deprecated webhooks, not apps, though...

**Comment by caronc** [comment]
@jlowin Hi, i stumbled across this ticket just searching GitHub to see who was using Apprise.  The good news is Apprise also supports Slack apps; _but the documentation didn't reflect this_.

Upon seeing your post, [I've since updated it](https://github.com/caronc/apprise/wiki/Notify_slack).

Hopefully that helps; let me know if you have any questions!

**Comment by jlowin** [comment]
@caronc awesome! Thanks for the update, I'm excited to work out a first-class Apprise integration for Prefect
