### ISSUE TITLE
Add an "Automate" option to the Webhooks three-dot menu in the UI

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#13197]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

No automate option is present from an individual Webhook page or the Webhooks page.

### Describe the proposed behavior

An Automate option is available.

### Example Use

A user could then more easily use a webhook event as an automation trigger.

### Additional context

Suggested by a user at PACC. We both expected that this option would be present.

**Comment by pleek91** [comment]
There's two different "webhook" concepts in prefect. 
1. Incoming webhooks - in prefect cloud, which emit an event
2. webhook blocks - in cloud and oss, call a webhook with a specific payload

I think this issue is about creating an automation trigger based on an incoming webhooks template (which is emitted as an event). Is that correct? Initially when I picked this up I thought it was about pre populating a webhook action on an automation. But that would require a webhook block and not a webhook event. Which doesn't fit with the PR description. 

@WillRaphaelson

**Comment by discdiver** [comment]
I was referring to #1. See the screenshot below. If there was an option in this dropdown to automate with the webhook event as the pre-populated Automation trigger, that would be nice.

![Screenshot 2024-07-11 at 5 19 54 PM](https://github.com/user-attachments/assets/ede0b54b-8000-409a-a687-9b1d818ec5fb)

**Comment by WillRaphaelson** [comment]
The primary question here is one of the appropriate trigger definition to bootstrap. The real user story here is bootstrapping a trigger to respond to the events that the webhook emits right, no one cares about events we emit when a webhook is created or updated, but because the webhooks can contain jinja, what do we even put in the event field of the trigger, for example, if my webhook spec says {{this}}.{{thing}}.{{happened}}. 

So I think one path forward is:
- if the template is static, the event is just whatever event is written in the template.
- if the template is dynamic or cloudevent, that button just takes you to the custom trigger form with the keys set up and no values.
