### ISSUE TITLE
Add a Clock for various trading day schedules

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/prefect#1327]
The Quantopian package provides many trading calendars that could form great starting points for Prefect schedules. We'd probably implement a new `Clock` that emits candidate events from the trading calendar. A sample trading day schedule might be:

```python
schedule = Schedule(clocks=[TradingDayClock('NYSE')])
schedule.next(3) # the next three NYSE trading days
```

and the calendar key corresponds to those found in https://github.com/quantopian/trading_calendars

cc @ssanderson if I'm overlooking anything

**Comment by ssanderson** [comment]
hey @jlowin! Sorry I missed this ping. I've been on vacation.

A couple thoughts off the top of my head that might be relevant to you:

- The data model for `trading_calendars` minutely frequency information is a little bit wonky due to its origin as a library internal to zipline. The main gotcha to be aware of is that market minutes are labeled as of the end of the minute, which means that `open_time` is 9:31 on NYSE, rather than 9:30 as you might expect. Your example above looks like it's only interested in daily-frequency information, so you might not care, but if you wanted to build something like "Run a task 15 minutes after NYSE open", you'd want to be aware of this.
- We at Q only use minute-level information on the NYSE calendar at the moment. For other markets, we only have daily data on Q, so there are a few features missing that you might expect. The most notable one is that we don't currently model lunch breaks in markets like Tokyo. It's also pretty likely that there are some unsurfaced bugs in the non-NYSE calendars that we're not noticing at the moment because we only depend on them for daily information (e.g. we had the timezone wrong for Toronto until recently: https://github.com/quantopian/trading_calendars/pull/64).
- Some markets have calendars that are hard to predict in a rule-driven way (e.g., calendars based on religious holidays or lunisolar phenomena). For some of these calendars (e.g., Singapore), we've just hard-coded lists of future holidays out a year or two into the future, which means those calendars will eventually be wrong and will require source code updates to incorporate new holidays. I'm not sure what prefect's deployment model looks like right now, but that might become an issue if you expect users to have very long-lived deployments.
- Similarly, to :arrow_up:, markets sometimes have unplanned "holidays" due to natural disasters, deaths, or other unforeseen circumstances. These events are also currently modeled with hard-coded lists, which means consumers need to update when this happens. As Quantopian gets more serious about our support for international markets, one of the debates we're having internally is how we can reduce amount of scrambling we have to do in these scenarios. One model we've considered, for instance, is putting trading calendar definitions behind a web service, and providing a mechanism for pulling calendar definitions dynamically from that service. There are some tricky design questions around this though (e.g., how would the dynamic fetching interact with global calendar registry that tcals currently exposes?). cc @gmanoim-quantopian, @Eronarn, and @ehebert , who are currently thinking about this more than I am.

**Comment by jlowin** [comment]
@ssanderson thanks for the complete report -- this is extremely helpful. While the caveats you highlighted are noted, I suspect that the benefits of being able to harness the trading calendars in a transparent way will more than offset these details, at least for getting started.

**Comment by cicdw** [comment]
Closing as stale
