### ISSUE TITLE
Model fields that use `gt` generate invalid JSON schema

### ISSUE THREAD

**Issue by rsundqvist** [PrefectHQ/prefect#13560]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When using pydantic `Field` members with the `gt` option, the `parameter_openapi_schema` sent to the server seems to be invalid.

### Reproduction

```python3
from prefect import flow
from pydantic import BaseModel, Field

class Config(BaseModel):
    sample_rate: int = Field(
        default=100,
        gt=0,
        lte=100,
    )

@flow
def dummy_flow(config: Config):
    pass

dummy_flow.to_deployment("mre", enforce_parameter_schema=True).apply()
```

### Error

```python3
prefect.deployments.runner.DeploymentApplyError: Error while applying deployment: Client error '422 Unprocessable Entity' for url 'http://127.0.0.1:4200/api/deployments/'
Response: {'exception_message': 'Invalid request received.', 'exception_detail': [{'loc': ['body', 'parameter_openapi_schema'], 'msg': "The provided schema is not a valid json schema. Schema error: 0 is not of type 'boolean'", 'type': 'value_error'}], 'request_body': {'infra_overrides': {}, 'name': 'mre', 'flow_id': 'b2ba56f4-ae0e-49c8-8d36-f8cd97f94d7a', 'paused': False, 'schedules': [], 'enforce_parameter_schema': True, 'parameter_openapi_schema': {'title': 'Parameters', 'type': 'object', 'properties': {'config': {'allOf': [{'$ref': '#/definitions/Config'}], 'position': 0, 'title': 'config'}}, 'required': ['config'], 'definitions': {'Config': {'properties': {'sample_rate': {'default': 100, 'exclusiveMinimum': 0, 'lte': 100, 'title': 'Sample Rate', 'type': 'integer'}}, 'title': 'Config', 'type': 'object'}}}, 'parameters': {}, 'tags': [], 'manifest_path': None, 'work_queue_name': None, 'storage_document_id': None, 'infrastructure_document_id': None, 'schedule': None, 'description': None, 'path': '.', 'version': 'e80c4a8bae48edd81bf5ae6d0b78b124', 'entrypoint': 'mre.py:dummy_flow'}}
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422
```

### Versions

```Text
Version:             2.19.2
API version:         0.8.4
Python version:      3.11.9
Git commit:          e42a3971
Built:               Thu, May 23, 2024 2:45 PM
OS/Arch:             linux/x86_64
Profile:             dev
Server type:         server
```

### Additional context

* The issue seems to be with the `exclusiveMinimum` field of the schema. You test this by setting `gt=50` and looking at the error message changing.
* The error disappears if you replace `gt=0` with `gte=-1`.
* This also happens when using `sample_rate: PositiveInt`, without a `Field` assignment.
* Neither online validators nor `check-jsonschema` seem to mind. That might be on me though, I tried to extract the schema from the error message.

**Comment by rsundqvist** [comment]
Reproducible on:

* pydantic-2.7.2 pydantic-core-2.18.3
* pydantic-2.7.1 pydantic-core-2.18.2 (we run this one)
* pydantic-2.6.4 pydantic-core-2.16.3
* pydantic-2.5.3 pydantic-core-2.14.6

Any lower and the errors start coming from the prefect namespace instead. So we can't use a different pydantic version.

**Comment by GfxKai** [comment]
Re-opening as I'm facing the same issue on the latest versions of Prefect + Pydantic:
```
Version:             3.0.3
API version:         0.8.4
Python version:      3.10.12
Git commit:          d9c51bc3
Built:               Fri, Sep 20, 2024 8:52 AM
OS/Arch:             darwin/arm64
Profile:             local
Server type:         server
Pydantic version:    2.9.1
```

Tracked it down to the usage of `PositiveFloat` in one of my configuration models. Flows deploy without issue if I switch to `float`.

Seems related to this [Pydantic issue](https://github.com/pydantic/pydantic/issues/4108), but it's pretty old 🤔

**Comment by GfxKai** [comment]
After a bit of digging, I think I've found the issue:

1. On the client side, [`prefect.deployments.runner.RunnerDeployment`](https://github.com/PrefectHQ/prefect/blob/main/src/prefect/deployments/runner.py#L427) calls `prefect.utilities.callables.generate_parameter_schema` to generate a JSON schema for the flow parameters

2. Internally, this calls [`prefect._internal.pydantic.v2_schema.create_v2_schema`](https://github.com/PrefectHQ/prefect/blob/main/src/prefect/utilities/callables.py#L401), which uses a subclass of [`pydantic.json_schema.GenerateJsonSchema`](https://github.com/PrefectHQ/prefect/blob/main/src/prefect/_internal/pydantic/v2_schema.py#L117) for the actual schema generation

Crucially, this class uses **Draft 2020-12** as the default JSON Schema dialect [since v2.0](https://docs.pydantic.dev/2.0/concepts/json_schema/)

3. When Prefect server receives the [`POST /api/deployments/`](https://github.com/PrefectHQ/prefect/blob/main/src/prefect/server/api/deployments.py#L58) request, FastAPI tries to construct and validate a [`prefect.server.schemas.actions.DeploymentCreate`](https://github.com/PrefectHQ/prefect/blob/main/src/prefect/server/schemas/actions.py#L246) model from the request body

4. The validation method for `DeploymentCreate` validates the parameter OpenAPI schema using [`prefect._internal.schemas.validators.validate_parameter_openapi_schema`](https://github.com/PrefectHQ/prefect/blob/main/src/prefect/_internal/schemas/validators.py#L196)

7. Internally, this calls [`jsonschema.Draft4Validator.check_schema`](https://github.com/PrefectHQ/prefect/blob/main/src/prefect/_internal/schemas/validators.py#L73) to do the actual validation

Obviously, this schema validation class uses **Draft 4** JSON Schema dialect

As you can see in the [JSON Schema docs](https://json-schema.org/understanding-json-schema/reference/numeric#range), `exclusiveMinimum` and `exclusiveMaximum` were boolean as of Draft 4 but have subsequently changed to numeric type.

As such, I'd imagine the simplest solution would be to update the server-side validation to use `jsonschema.Draft202012Validator`
