### ISSUE TITLE
Agents should have heartbeats

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect#1373]
Today we ran into a situation where an agent (which had been successfully running for 26 days straight) just ... froze.  The python process was still alive but nothing was actually happening.  To alert users to this sort of behavior in the future, we should have an Agent heartbeat and a way of "warning" users in the UI that they don't have any active agents running.

**Comment by joshmeek** [comment]
I had a sight convo w/ @zdhughes earlier about this. I am all for this

**Comment by cicdw** [comment]
In conjunction with this, we might also consider a liveness probe / healthcheck on the k8s agent.

**Comment by lauralorenz** [comment]
UI on Cloud side now stores agent information (based on the labels they request during a poll) which is kind of like a heartbeat. Downside is that this is only based on labels and not on something specific to agents. Closing this ticket for now since that will be handled more in Cloud re https://github.com/PrefectHQ/cloud/issues/2105
