### ISSUE TITLE
K8s Agent & Job Container Priority

### ISSUE THREAD

**Issue by TylerWanner** [PrefectHQ/prefect#1394]
## Use Case
** Please provide a use case to help us understand your request in context **
When the cluster overloads and starts to evict pods, it should never kill the agent

## Solution
** Please describe your ideal solution **
Give the agent higher priority than the jobs

## Alternatives
** Please describe any alternatives you've considered, even if you've dismissed them **

**Comment by joshmeek** [comment]
This would require the agent deployment to also specify a `PriorityClass` which I'm not sure we want on it. Another option is we could allow for an optional `priorityClassName` and users can specify the name of a priority class they have on their cluster (w/ docs on how to do so).

**Comment by lauralorenz** [comment]
Just another update from Core team reviewing this again: One workaround today may be that people specify their own yaml for their kubernetes agent (either instead of the autogenerated one by prefect or modified from it) that handles the priority, but if someone decides to go with configuring that from the prefect agent for this ticket, the extra information on the agent deployment mentioned by @joshmeek would be the way to go.

**Comment by joshmeek** [comment]
We're slowly moving away from providing an install manifest that would account for all of these behaviors. This would fall more into a specific implementation than something we want to implement at this time. Closing for now but can reopen if it becomes requested more 👍
