### ISSUE TITLE
Add `as_completed` utility for `PrefectFuture`s

### ISSUE THREAD

**Issue by desertaxle** [PrefectHQ/prefect#14241]
Add a wait utility that mirrors concurrent.futures.as_completed. Should accept an iterable of futures to wait for completion and a timeout. It should act as a generator and yield futures as they are completed.

**Comment by marxide** [comment]
Thanks for adding this feature -- it's exactly what I needed.

Took me a while to find though because it is not documented, unless I missed it! The main docs mention it once in passing in a warning callout (https://docs.prefect.io/v3/develop/task-runners#submit-tasks-to-a-task-runner) but doesn't offer any detail. I couldn't find any reference in the SDK docs, nor a docstring in the source.
