### ISSUE TITLE
Flow returning None with failed task ends with state Completed instead of Failed

### ISSUE THREAD

**Issue by GalLadislav** [PrefectHQ/prefect#14470]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Flow returning None with failed task ends with state Completed instead of Failed. This issue happens for documented example code for [Return None](https://docs-3.prefect.io/3.0rc/develop/write-flows#return-none).

This behavior occurs for tasks too.

### Reproduction

```python3
import prefect


@prefect.task()
def task1():
    raise ValueError("Task 1 failed")


@prefect.task()
def task2():
    task1.submit().result(raise_on_failure=False)


@prefect.flow()
def flow_failed_submit():
    task1.submit().result(raise_on_failure=False)
    task2.submit().result(raise_on_failure=False)


@prefect.flow()
def flow_failed_state():
    task1(return_state=True)
    task2(return_state=True)


if __name__ == "__main__":
    flow_failed_submit(return_state=True)
    flow_failed_state(return_state=True)

```

### Versions (`prefect version` output)

```Text
Version:             3.0.0rc9
API version:         0.8.4
Python version:      3.12.4
Git commit:          b75631a7
Built:               Mon, Jun 24, 2024 5:50 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Pydantic version:    2.8.0
Server:
  Database:          sqlite
  SQLite version:    3.37.2
```

### Additional context

prefect.flow_engine.FlowRunEngine.handle_success() should probably in case of returned None value pass to prefect.states.return_value_to_state() list of task run results from RunContext?

**Comment by zhen0** [comment]
Thanks for the issue @GalLadislav - we'll look into this one.

**Comment by zzstoatzz** [comment]
hi @GalLadislav - thank you for the issue!

I believe this is expected behavior in Prefect 3.0:
- Flow runs final state is now determined by what the flow function returns or raises, not by task states.
- Using `raise_on_failure=False` suppresses the exception, and returning `None` (like the examples) will result in a `Completed` state just like any other literal return value 

To make the flow fail when tasks fail, you could:
- Remove `raise_on_failure=False` to allow the exception to raise
- Explicitly checking task states (i.e. `is_failed()` etc) and raising an exception or returning a failed state
- Using a try/except block to handle task failures

I will open a 3.0 docs PR to clarify this - feel free to raise questions here if something isnt making sense.

**Comment by GalLadislav** [comment]
Thank you, it all makes sense now. It is better this way that i can pass only states that counts to overall result of a flow/task.

**Comment by desertaxle** [comment]
The docs have been updated to reflect this change in https://github.com/PrefectHQ/prefect/pull/14714, so I will close this as completed. If anyone has any further questions about this behavior, leave a comment!
