### ISSUE TITLE
Dict parameter changes order of keys

### ISSUE THREAD

**Issue by angelika233** [PrefectHQ/prefect#14779]
### Bug summary

When specifying a parameter in a dictionary, prefect automatically changes the order of keys - from shortest to longest string.  This happens even when OrderedDict is used.

To reproduce it just use OrderedDict or dict as a parameter of the flow and the deploy it. In prefect UI order of keys is changed.

*Changing value from UI doesn't help

### Version info (`prefect version` output)

```Text
Version:             2.19.7
API version:         0.8.4
Python version:      3.10.14
Git commit:          60f05122
Built:               Fri, Jun 28, 2024 11:27 AM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         cloud
```

**Comment by zzstoatzz** [comment]
hi @angelika233 - thanks for the issue!

would you be able to provide:
- an MRE for this issue
- and a description of why the ordering of keys presents a problem?

In general, as far as I know the openapi schema spec (the way the SDK represents parameters schemas for the UI) doesn't guarantee any ordering for property object keys.

I would guess that an MRE may look something like this
```python
from collections import OrderedDict

from prefect import flow


@flow
def foo(
    normal_dict: dict = dict(aaa=1, bb=2),
    ordered_dict: OrderedDict = OrderedDict(aaa=1, bb=2),
):
    print(normal_dict)
    print(ordered_dict)


if __name__ == "__main__":
    foo.serve()
```

but I would note here that [using default mutable arguments in function definitions is generally not recommended](https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments) in python.

**Comment by angelika233** [comment]
Hi! You're right - this MRE is what I meant. I have a flow that creates a SQL table and dictionary that specifies columns and data types. Changed orderer of keys in dictionary messes up the table. 
I would like to point out that this problem occured in prefect 2 - in prefect 1 I had simillar flow and it was ok.

**Comment by cicdw** [comment]
As a side note: we typically recommend hard-coding any business logic into your flow instead of relying on implicit behavior such as this. We can still investigate this but wanted to call that out in the meantime 👍

**Comment by zzstoatzz** [comment]
hi @angelika233 - the core of this issue is that the UI needs to have any information about ordering in the openapi schema for the parameters, where a `dict` or `OrderedDict` are normally represented as an `object` (whose keys don't necessarily have an order) in an openapi schema.

In your case, you can enforce the order by introducing a model definition that explicitly defines the order of `aaa` and `bb` like this example

<details>
<summary>Example</summary>

```python
from pydantic import BaseModel, Field

from prefect import flow


class SomeModel(BaseModel):
    aaa: int = Field(json_schema_extra={"position": 0})
    bb: int = Field(json_schema_extra={"position": 1})


@flow
def foo(
    normal_dict: dict = dict(aaa=1, bb=2),
    ordered_obj: SomeModel = SomeModel(aaa=1, bb=2),
):
    print(normal_dict)
    print(ordered_obj)


if __name__ == "__main__":
    foo.serve()
```

![image](https://github.com/user-attachments/assets/e2e93bce-9a22-4984-8d91-4fe3be387b1d)

</details>

and just to close the loop

> I would like to point out that this problem occured in prefect 2 - in prefect 1 I had simillar flow and it was ok

This was also likely circumstantial / implicit behavior that I would not recommend depending on.

Let me know if you have any questions here, otherwise I will close this issue.

**Comment by cicdw** [comment]
@angelika233 FYI we found a solution here: https://github.com/PrefectHQ/prefect/issues/8596#issuecomment-2634888092
