### ISSUE TITLE
Some documentation is gone from the website.

### ISSUE THREAD

**Issue by michalz92** [PrefectHQ/prefect#1488]
Some core documentation has disappeared (or has been moved?) from the website. Maybe it's just the guide that was deleted, but I have too few examples to know. Here are two:

https://docs.prefect.io/guide/core_concepts/notifications.html
https://docs.prefect.io/guide/examples/state_handler_logging.html

**Comment by joshmeek** [comment]
The docs previously under `/guide/` were moved to `/core/` (also w/ `core_concepts` being renamed `concepts`. Were there any places in the docs that these `/guide/` absolute links were used?

**Comment by jlowin** [comment]
I think we can add redirects for the old links: https://github.com/vuejs/vuepress/issues/239#issuecomment-384269121

**Comment by michalz92** [comment]
I didn't find any such examples, but you use the old links in your Medium posts and some top google search results.

**Comment by jlowin** [comment]
@znicholasbrown if you have a moment, would appreciate your expertise here. In the local development server, these redirects worked, but in the built/deployed site they aren't working. 

### Dev
`http://localhost:8081/guide/core_concepts/parameters.html`
redirects properly to
`http://localhost:8081/core/concepts/parameters.html`

### Deployed
`https://docs.prefect.io/guide/core_concepts/parameters.html`
redirects to the correct URL in the browser (`https://docs.prefect.io/core/concepts/parameters.html`), but renders the page at `https://docs.prefect.io`

**Comment by znicholasbrown** [comment]
@jlowin so the problem here is that we're generating static docs as opposed to a SPA - no router is actually matching these dynamic routes, since there shouldn't BE dynamic routes; all of the pages have to be rendered ahead of time. There's a community plugin (https://vuepress.github.io/en/plugins/redirect/#usage) that's supposed to bridge that gap by generating the dynamic routes but I haven't had much luck with it.

This is a known issue, tracked here: https://github.com/vuejs/vuepress/issues/160
which is supposedly resolved here:
https://github.com/vuepress/vuepress-plugin-redirect/issues/1

For now, I think setting up the redirects through netlify is the most expedient solution for now.

**Comment by jlowin** [comment]
Thanks @znicholasbrown, will do asap.

**Comment by cicdw** [comment]
Confirmed: the redirects are working and the above links are back in business - thanks @jlowin and @znicholasbrown !
