### ISSUE TITLE
DbtCoreOperation `working_directory` argument does not work

### ISSUE THREAD

**Issue by mgsnuno** [PrefectHQ/prefect#15235]
### Bug summary

`DbtCoreOperation(working_directory=....)` does not raise an error and does not work, the signature is `ShellOperation( working_dir=...)`

Summary: passing `working_directory` should raise an error and the only option should be `working_dir`.

### Version info (`prefect version` output)

```Text
Version:             2.20.4
API version:         0.8.4
Python version:      3.10.14
Git commit:          3b951c35
Built:               Wed, Aug 28, 2024 9:09 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         server
```

**Comment by desertaxle** [comment]
Thanks for the bug report @mgsnuno!

The reason passing in `working_directory` didn't raise is because the Pydantic config for the `Block` class specifies `extra="allow"` which means that all `Block` subclasses will accept all initialization kwargs, whether they know what to do with them or not. I have a vague recollection that we tried to change that setting to `extra="forbid"` and it broke some key `Block` operations.

Regardless, we should update the docstring of `DbtCoreOperation` to list the correct kwargs. If you are willing to submit a PR, that would be awesome!
