### ISSUE TITLE
Deployment-backed global concurrency limits should not be mixed in with user-created GCL's

### ISSUE THREAD

**Issue by collincchoy** [PrefectHQ/prefect#15316]
### Describe the current behavior

Deployment-based concurrency limits implicitly create and use global concurrency limits behind-the-scenes for enforcement. When a worker pulls down a scheduled flow run that's part of a deployment with a set `deployment.concurrency_limit`, a special global concurrency limit object will be created on behalf of the user for use in limiting the deployment's runs. These limits have a special pattern name `deployment:{deployment.id}` but are otherwise the same as if a user were to have created one via the `concurrency` helpers. 

This has the potential to create issues as these "system-owned" resources are exposed to users in the UI and via the prefect CLI which:
1. can create confusion and clutter for a user wanting to view GCL's that they create/manage
2. can create unexpected data issues as users can freely modify the underlying GCL's creating unexpected side effects for enforcing the deployment's desired concurrency limit

### Describe the proposed behavior

Because prefect creates these objects on behalf of users, we shouldn't expose it to users in the same way that user-defined global concurrency limits are. 

deployment-related global concurrency limits should be hidden:
- in the UI on the concurrency page in the global concurrency limits table
- from the CLI via prefect gcl ls
- from CLI actions like: prefect gcl enable/disable/delete/update/inspect
- bonus: guard users from creating a gcl with a name like deployment:<uuid>

Implementation note:
Rather than filter by name prefixes, we should add a new field to concurrency limits for better tagging and filtering of these deployment-related concurrency limit objects as system-owned.

In particular, consider adding an extendable `meta: JSONB` column or an enumerated column `used_for` to be used to filter out non-user-created GCL's from the GCL web apis.

**Comment by cicdw** [comment]
Could we consider something more basic such as prefixing such "private" limits with an underscore, and then adding a validator to any user-created limits that they _cannot_ contain an underscore?

**Comment by cicdw** [comment]
Alternatively, could we create a standard "public" limit using some rule, and let users manage it as such?

**Comment by collincchoy** [comment]
> Could we consider something more basic such as prefixing such "private" limits with an underscore, and then adding a validator to any user-created limits that they cannot contain an underscore?

Yeah! Suggesting just filtering on `name NOT LIKE '_%'`? 

I was assuming that we'd rather have a better-defined field to filter and index on, but this is certainly simpler. Might want to consider another/different indexing strategy though as a lot of queries will be including this filter now.


> Alternatively, could we create a standard "public" limit using some rule, and let users manage it as such?
Hm like a `public: bool = True`/`hidden: bool = False` that would more directly allow someone to create and use a concurrency limit without needing to explicitly manage it in UI views?

**Comment by abrookins** [comment]
@cicdw Just to add some context. We discussed using a naming strategy and schema validation approach vs. adding a new field and thought the field was cleaner. A new field would avoid interfering with existing limits, while a naming strategy risks conflicting with existing limit names.

There are some benefits to using a JSON column for the field, versus, say, an enum (`used_for`) or a boolean (`is_public`, `is_private`, etc.). As we discussed recently, global limits don't track limit holders the way task run limits do, but ideally, they would. Having a JSON column would allow us (me?) to add a fast-follower to this project that uses the `meta` column to store limit holders. This is kind of beside the point since that's not a direct requirement of this feature, but it's on my mind.

**Comment by cicdw** [comment]
So my fear of a pubic/private distinction is basically what happened with anonymous blocks - it creates a shadow system that ultimately behaves completely differently and is easy to get into a bad state because all clients have to reason about anonymity.

@collincchoy on:
> Hm like a public: bool = True/hidden: bool = False that would more directly allow someone to create and use a concurrency limit without needing to explicitly manage it in UI views?

No, I actually meant a naming convention, so when a user creates a deployment with a concurrency limit of 1, for example, we'd create a completely standard concurrency limit with the name `"deployment/{deployment_id}"` (as an example of a naming convention).  They could then edit the limit / monitor it / etc. just as they could any other limit, and _maybe_ the API would prevent editing such limit names to avoid footguns.

I guess what I'm getting at is that if we have a goal of reusing the concurrency system, then I think we should do so directly and transparently, instead of creating a "special" type that gets filtered out of views.  If we instead think that these limits are truly special, then I think we should consider colocating them with the objects that make them special, so in this case maybe store them directly on the deployment object.

**Comment by collincchoy** [comment]
> No, I actually meant a naming convention, so when a user creates a deployment with a concurrency limit of 1, for example, we'd create a completely standard concurrency limit with the name "deployment/{deployment_id}" (as an example of a naming convention). They could then edit the limit / monitor it / etc. just as they could any other limit, and maybe the API would prevent editing such limit names to avoid footguns.

This sounds like the current state where we're using a naming convention that's `deployment:{deployment_id}` (`:`-delimited instead of `/`). 

So do we not actually see these as issues?

> This has the potential to create issues as these "system-owned" resources are exposed to users in the UI and via the prefect CLI which:
> 
> 1. can create confusion and clutter for a user wanting to view GCL's that they create/manage
> 2. can create unexpected data issues as users can freely modify the underlying GCL's creating unexpected side effects for enforcing the deployment's desired concurrency limit

Your suggestion would be to leave the naming convention in-place as the identifier and link for concurrency limits backing deployment concurrency limits. Allow users to freely manage them as normal concurrency limits, but with the sole exception of concurrency limits using this naming convention have immutable names. 

Does that check out and sound like the best path forward? If so, I can go ahead and close my prior PR and then only add a check into PATCH /v2/concurrency_limits/{id_or_name} route to make limit names that follow the pattern `deployment:{uuid}` immutable.

**Comment by collincchoy** [comment]
> This has the potential to create issues as these "system-owned" resources are exposed to users in the UI and via the prefect CLI which:
> 
> 1. can create confusion and clutter for a user wanting to view GCL's that they create/manage
> 2. can create unexpected data issues as users can freely modify the underlying GCL's creating unexpected side effects for enforcing the deployment's desired concurrency limit

Closing this in favor of https://github.com/PrefectHQ/prefect/issues/15375 which addresses both above points:
1. the underlying GCL's are user-facing as a feature
2. converge towards a single source of truth to remove the need to bidirectionally sync updates
