### ISSUE TITLE
getting logs when using DaskExecutor

### ISSUE THREAD

**Issue by govindKAG** [PrefectHQ/prefect#1545]
when using DaskExecutor (dask.distributed with 4 workers on my local machine), is there a way to get all the logs in one place instead of four shells ?

**Comment by cicdw** [comment]
Hi @govindKAG my sincere apologies for not responding earlier - assuming you are referring to the Prefect logs, this can be a bit tricky.  In the same way that dask doesn't natively collect all the worker logs in one centralized location, Prefect Core doesn't either.  

In order to achieve this, there needs to be some sort of "service" that the logs are sent to (or a common shared filesystem / database).  Prefect Cloud _does_ collect all logs out-of-the-box, but I'm honestly not sure of the best way to do this using Core alone.  This can get extra tricky because if you attach a logger handler to your root logger in one process, it won't survive after being sent to the workers (this is because the Python logging module just re-initializes itself after pickling).

**Comment by govindKAG** [comment]
@cicdw you're right. I did try  adding a filehandler and streamhandler to the logger instance and it didn't do the trick. Seems like setting up a service is the only recourse.
Closing the issue.
