### ISSUE TITLE
I keep getting TypeError when using blocks despite already being saved

### ISSUE THREAD

**Issue by NicholasPini** [PrefectHQ/prefect#16229]
### Bug summary

I keep getting
```
TypeError: Result storage configuration must be persisted server-side. Please call `.save()` on your block before passing it in.
```

with this code:
```python
from prefect import flow
from prefect_aws.s3 import S3Bucket

test_block = S3Bucket(bucket_name='my-bucket')
test_block.save('test-s3-block', overwrite=True)

@flow(flow_run_name="flow2_main", persist_result=True, result_storage=test_block)
def flow2_main() -> str:
    return "Hello"
```

when I try to deploy my flow. This is exactly what the documentation does, why doesn't it work? I can see the block being present in the prefect UI.

### Version info

```Text
Version:             3.1.4
API version:         0.8.4
Python version:      3.10.15
Git commit:          78ee41cb
Built:               Wed, Nov 20, 2024 7:37 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         cloud
Pydantic version:    2.10.2
Integrations:
  prefect-docker:    0.6.2
  prefect-aws:       0.5.2
```

**Comment by zzstoatzz** [comment]
got it! thanks for the extra info - I reproduce now, will take a look

**Comment by zzstoatzz** [comment]
hi again @NicholasPini - your workaround of using the string representation of the block should work, but just to give some color

```python
sys:1: RuntimeWarning: coroutine 'sync_compatible.<locals>.coroutine_wrapper.<locals>.ctx_call' was never awaited
```

the problem here is a bit tricky, and related to #15008. As mentioned [here](https://docs.prefect.io/v3/resources/upgrade-to-prefect-3#resolving-common-gotchas), you can resolve this by updating your `.save()` call like this

```python
test_block.save("test-s3-block", overwrite=True, _sync=True)
```

though the fact that this is necessary is clearly a problem, which is what #15008 is about.

If that is making sense, can I close this under the umbrella of this larger async/sync compat issue i've been linking?

**Comment by NicholasPini** [comment]
Changing the code to
```python
block = S3Bucket.load("test-s3-block")
block.save("test-s3-block", overwrite=True, _sync=True)

@flow(flow_run_name="flow2_main", persist_result=True, result_storage=block)
def flow2_main() -> str:
    return "Hello"
```

did not solve the issue. I get the same error. What solved the issue was to add `_sync=True` to the `load` method:
```python
block = S3Bucket.load("test-s3-block", _sync=True)
block.save("test-s3-block", overwrite=True, _sync=True)

@flow(flow_run_name="flow2_main", persist_result=True, result_storage=block)
def flow2_main() -> str:
    return "Hello"
```

This also works without calling `save` because the block already exists.
