### ISSUE TITLE
Pylint error message on @task with params

### ISSUE THREAD

**Issue by zbarry** [PrefectHQ/prefect#1693]
## Description

I'm using pylint as one of my code linters (in VSCode, for the record, though that most likely isn't an influence). I get an error message from it when I use the:

```python
@task(kwarg_1=blah, kwarg_2=blah)
def the_task(params):
    return
```

formulation, because `fn` is not defined in such a use case:

> No value for argument 'fn' in function call pylint(no-value-for-parameter)

Not a huge deal, but would be great to not receive such a linter error :). I guess turning `fn` into a kwarg with a default value of `None` might fix this? I believe this is a viable solution, because `@task` without params will always receive a function, and `@task(...)` expects to not receive a function.

## Expected Behavior

No pylint error.

## Environment

pylint `2.4.3` from conda-forge
prefect `0.7.0` from conda-forge
python `3.7.4` from conda-forge

**Comment by cicdw** [comment]
Hi @zbarry - apologies for never commenting here; unfortunately we can't put a default on the `fn` argument to the `task` decorator.  We use the incredibly convenient `curry` decorator from the [`toolz`](https://github.com/pytoolz/toolz) package to allow for diverse decorator patterns such as:
```python
@task
@task()
@task(name="hi")
``` 

Whenever we place a default of e.g., `None` on the `fn` argument, we get:
```python
from prefect import task

@task(name="hi")
def my_task():
    pass

# TypeError: fn must be callable.
```
This is because without a positional argument, `curry` begins binding the provided arguments _before_ it binds the `fn` keyword.  The position argument essentially enforces an ordering on when `curry` does the final keyword binding.

**Comment by zbarry** [comment]
Ahh, got it! Thanks for the explanation. I’ve just been putting pylint ignore pragmas on the `@task` definitions, which is totally fine. I’ve really been enjoying learning Prefect so far, by the way.

Gonna close this. Thanks again.
