### ISSUE TITLE
K8s Agent references old prefect docker image name

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect#1697]
## Description
Whenever the kubernetes agent creates a job, it references our old docker image naming conventions in at least on place [here](https://github.com/PrefectHQ/prefect/blob/d204261c6f9856dbfd7442a194de91c4be768e7f/src/prefect/agent/kubernetes/agent.py#L198).  We should audit all such references and update them for our new naming scheme, which can be inferred from our `circleci/config.yml` file [here](https://github.com/PrefectHQ/prefect/blob/master/.circleci/config.yml#L296-L324)

**cc:** @joshmeek

**Comment by joshmeek** [comment]
Due to the naming changes we have a couple options around `"prefecthq/prefect:{}".format(image_version)`
1. Add a check here to use the new naming conventions for >= 0.7.0 and old simple version convention for < 0.7.0
2. Add a new tag to the old images to follow the new convention in order to avoid a check

**Comment by cicdw** [comment]
option 2.) seems like the easiest to me - no maintenance burden, just a one time tag / push of a lot of images

**Comment by joshmeek** [comment]
@cicdw Okay great, I'll make the PR and before it's merged we can tag those old images

**Comment by cicdw** [comment]
Images for 0.6.7 and 0.6.6 have been built and pushed with the new naming schema.
