### ISSUE TITLE
Support *args for task run() methods

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/prefect#17]
Currently, `*args` is explicitly not supported because edges that pass data are identified by string keys that become the `**kwargs` for the task's `run()` method. One way to support `*args` would be to automatically create edges with integer keys. When executing a flow, we would put edges with string keys into `**kwargs` and edges with integer keys into `*args`.

**Comment by lauralorenz** [comment]
Closing this issue since:
1. no one has requested it externally/we don't have a use case for it
2. we are worried about this having unintended side effects of users getting confused about what is passed to their tasks, or enable them to create flows that have a weird structure they may have not expected

**Comment by snenkov** [comment]
Can you please show an example of the workaround? Since I do want to use `*args`, but I get the following error:
```
ValueError: Tasks with variable positional arguments (*args) are not supported, because all Prefect arguments are stored as keywords. As a workaround, consider modifying the run() method to accept **kwargs and feeding the values to *args.
```
