### ISSUE TITLE
Add button on Docs for opening issues about documentation

### ISSUE THREAD

**Issue by joshmeek** [PrefectHQ/prefect#1796]
## Current behavior
Currently if a user finds an error in the documentation it requires them to navigate to the repo and open an issue.

## Proposed behavior
Add an easy access button to the docs on the lower left where the left side navigation bar is. So it could also warrant a new issue template for documentation tweaks/fixes.

Please see my beautiful illustration below with a very helpful large arrow

![image](https://user-images.githubusercontent.com/40716964/70189094-58f1e080-16c0-11ea-956d-a3955a3a70e5.png)

## Example
"Mistake? Open an issue!"
Open to other button name suggestions

**Comment by znicholasbrown** [comment]
Instead of a button in the bottom left, we should do a selected-text popup like this: 
<img width="307" alt="Screen Shot 2019-12-04 at 8 10 15 PM" src="https://user-images.githubusercontent.com/27291717/70194912-16d19a80-16d2-11ea-9514-e5c3ded98dbc.png">

that will auto-populate the GitHub issue with the selected text!

**Comment by cicdw** [comment]
I don't think these ideas are mutually exclusive and I love both of them for the record.

**Comment by znicholasbrown** [comment]
PR here: #1797

**Comment by joshmeek** [comment]
Closed by #1797
