### ISSUE TITLE
Equivalent of `itertools.product` for tasks?

### ISSUE THREAD

**Issue by mohamed--abdel-maksoud** [PrefectHQ/prefect#1986]
## Current behavior
The following:
`task3.map(param1=task1_out, param2=task2_out)`
results in calling `task3` on inputs akin to `zip(task1_out, task2_out)`

## Proposed behavior
Calling `task3` on inputs akin to `itertools.product(task1_out, task2_out)`

**Comment by jlowin** [comment]
Hi @mohamed--abdel-maksoud - thanks for the comment! We use the `zip()` pattern because it is the standard among the data tools we are comfortable with (like Dask). However, I think you could achieve the behavior you want like this:

```python
@prefect.task
def product(x, y):
	return list(itertools.product(x, y))

task3.map(product(task1_out, task2_out))

```

In order to keep the API simple, at this time I think we will continue to mirror other tools and have `map` use the `zip()` behavior, but I hope this code assists you in your objective.
