### ISSUE TITLE
Expose ability to set location and / or  permissions on Flow files within Docker storage

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect#2025]
Currently, we place Flow objects in the `/root` directory of their Docker containers.  This can be a problem when root access is somehow restricted.  We should introduce two new APIs:

- introduce a way to configure the directory / location of the flow within the image
- optionally set the correct permissions on the flow file so that non-root users can read / write it

**Comment by szelenka** [comment]
OpenShift Container Platform, which runs containers using an `arbitrarily assigned user ID` (i.e. non-root). This provides additional security against processes escaping the container due to a container engine vulnerability and thereby achieving escalated permissions on the host node.

To clarify on the problem, when the `COPY` command is used within the DockerFile, it will copy the file into the Docker Image with the exact user permission mask as it was created on the host system generating the Docker Image.

In the case of Prefect, when registering a Flow and opting to have Prefect build the Docker Image, the code will attempt to cloudpickle the Flow into a temporary directory on the system performing the build, then `COPY` that file into the Docker Image.
https://github.com/PrefectHQ/prefect/blob/master/src/prefect/environments/storage/docker.py#L420

Setting the `umask` to override the `COPY` command within the Docker Daemon is not feasible, so the only workaround we have today is to set the `umask 002` on the host system performing the Prefect `register` command. This allows you to specify the default file permission on the host system, before it's `COPY` into the Docker Image. Then once it's in the Docker Image, it'll have the appropriate permissions set on the host system. 

When registering Flows on a local PC, it's pretty easy to modify the `umask 002` (at least on Mac). However, when working with shared CI/CD tools, we don't always have control over specifying the `umask` on the machine which will perform the `register`.

It'd be great if the code could be modified, such that after the `COPY` command, it would update the file permissions to allow the `root` group to have rwX permissions (`chgrp -R 0  {dest} && chmod -R g+rwX {dest}`). This would have zero impact on normal flows, and it would then enable non-root execution of Prefect Flows.

**Comment by szelenka** [comment]
Actually, the `umask` trick doesn't work in this context. Since Prefect is using the Python open to dump the file, it avoids using the `umask` and explicitly sets 644 as the permissions on the *.flow files cloudpickle is creating.

After it creates the flow file on disk, you could chmod there to allow the `root` group `write` access. Which would avoid having to run the chgrp and chmod commands within another Docker file layer:
```python
os.chmod(flow_path, 0o664)
```

**Comment by lauralorenz** [comment]
From discussion with the core team, it sounds like there is also an option here (which introduces less configuration bloat which we liked) for us to instead store at something like `/opt/prefect/flows`. Since Cloud knows the absolute path this shouldn't affect any users to change this way. Fundamentally the important part about having used `/root` in the first place was just that we could guarantee that directory would be available but if we can guarantee `/opt/prefect/flows` from the Dockerfile command we feel this is good.
