### ISSUE TITLE
Add new AWS Secrets Manager Task

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect#2069]
To add to our non-Prefect Cloud [Secret Task library](https://docs.prefect.io/api/latest/tasks/secrets.html), we should add a new AWS Secrets Manager Task.  This should only involve exposing the following three kwargs at initialization:
- `secret_id`
- `version_id`
- `version_stage`

as described here: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/secretsmanager.html#SecretsManager.Client.get_secret_value

**Comment by alexisprince1994** [comment]
👋 Hi there! Just for some clarification questions on this:

* After reading through the code, it looks like we're going to need AWS Secrets to make the request to Secrets Manager. Are the AWS Lambda tasks good examples for doing this?
* There are multiple places where a secret value can be stored (and due to my lack of familiarity with it, maybe both?). Is there a preference towards creating a parameter indicating which one to grab vs returning a dictionary with both?
* Looking at the EnvVarSecret as a starting point, it looks like there's a flag of whether an error should be thrown or not depending on whether the secret can be retrieved. Since retrieving the secret from AWS includes 2 steps, one based on the authentication via access keys and one actually getting the secret, should an error occurring at either step be raised if a `raise_if_missing` flag is set to True? Or should it only be specifically if authentication was successful and there is not secret?

**Comment by joshmeek** [comment]
@alexisprince1994 In a recent release there was a new AWS utility added to handle authentication for places where credentials are used for the boto3 client https://github.com/PrefectHQ/prefect/blob/master/src/prefect/utilities/aws.py and I think it might address some of your questions as the tasks now make use of this utility as well as prefect Secret tasks.
