### ISSUE TITLE
Create a beginner-friendly walkthrough of setting up a Dask Cluster for Prefect

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect#2094]
Items we should cover:

- how to choose number of workers
- what dependencies should workers have
- how to choose node types / sizes
- how to choose nprocs / nthreads
- how to choose resource requests / limits for workers (if on k8s)
- how to spin them up 
- what can happen to disrupt your flow (e.g., worker evictions)
- possibly mention networking from workers to schedulers (security / exposing scheduler as a service / etc.)

**cc:** @joeschmid / @jsignell

**Comment by jsignell** [comment]
What form would this documentation take? If it were a blog post rather than straight docs it might be more generally useful. This is also the kind of thing that we'd be happy to collaborate on.

**Comment by cicdw** [comment]
Hey @jsignell - sorry for the delayed response!  I think either blog or documentation could work well, and I don't think they're mutually exclusive

**Comment by jsignell** [comment]
Agree! Let me know if you want to team up :)

**Comment by lauralorenz** [comment]
Hey @jsignell I'm interested in this too and have some bandwidth to team up! It also so happens that I am a beginner Dask gal in the first place so on the one hand, sorry I will be a n00b but on the other hand, I think I will be a great person to write with since I am the type of person to be writing *to*. I think this might be easier to brainstorm in a google doc or similar in the initial phase, so if you agree, if you don't mind requesting access to [this google doc](https://docs.google.com/document/d/1sd0JasEWl1lwPXnVhzhZ6uK9-v-5OiacLXCr1UXI-Go/edit?usp=sharing) with whatever email you want to hang out on, we can start to work asynchronously there or organize to sync up to chat about it. Let me know if you wanted to team up a different way. Thanks :)

**Comment by jsignell** [comment]
Sweet! I just requested access :)

**Comment by jcrist** [comment]
I'd be interested in helping out on this as well, if y'all need a hand.

**Comment by jsignell** [comment]
@jcrist I'll add you to the invite for our next sync :)

**Comment by lauralorenz** [comment]
Ok just a couple updates as a list here:
- [ ] there is a PR to the dask blog Julia and I worked on (https://github.com/dask/dask-blog/pull/63)
- [ ] I will give a tl;dr of configuration concerns in a tooltip and link to the dask blog on the Dask Deployment tutorial in the prefect docs once the above is merged
- [ ] there is a google doc for a separate blog that is more prefect-focused about connecting to your dask deployment that is still on me
