### ISSUE TITLE
Add Token Auth to Prefect Server

### ISSUE THREAD

**Issue by szelenka** [PrefectHQ/prefect#2238]
## Use Case
Leveraging all the services that make up Prefect Server on a single machine allows for quick jumpstart for the UI, but if someone were to expose those ports on the network, the GraphQL endpoint to the Postgres database is open to non-authenticated users.

I believe Prefect Cloud enforces this with auth0 to get idTokens to then `login` or Personal Access Tokens for humans, and the RUNNER / TENANT tokens for Prefect Agents.

It would be nice to have something similar for Prefect Server to provide a basic level of security for the GraphQL endpoints Apollo services.

## Solution
I believe Airflow had a very basic concept of user authentication, where it defaults to installing an `admin` user, who can then provision other people to have access to the Airflow UI. If I'm remembering correctly, they also had a method to extend the authentication to allow users to write their custom authentication mechanisms (i.e. LDAP).

For Prefect Server, a solution could be extending the schema to allow for basic user authentication when the UI loads to provide a generated token. Since it's basically a demo for Prefect Cloud, it doesn't need to be fancy, but it should provide some level of protection.

Then in the UI, there could also be a location to generate similar Access Tokens for Users/Agents to authenticate to the GraphQL Apollo service to protect it from unauthenticated malicious attacks on the network.

## Alternatives
Could also write an intercepter to perform this authentication before the requests get to the Apollo service.

**Comment by jlowin** [comment]
Hey Scott, appreciate the thought --

As you know from using Cloud, we’ve thought a lot about the complexities of auth and spent a significant amount of time ensuring we can implement it in the right way throughout Cloud at the API, GraphQL, and database layers. In fact, Cloud’s auth layer is a substantial application on its own. For this release of Prefect server, we’re focusing on delivering the key features that users need to run flows end-to-end, and we consider auth (and all of its complexities) out of scope.

An important thing to keep in mind about Airflow’s auth layer is that it’s only applied at the UI, and does not automatically block database access or any network access. Because it’s not a true defense, it doesn’t meet the standards that we consider necessary in production environments like Cloud, and we don’t want to trap ourselves in maintaining a half-baked approach when we already spend our time maintaining a fully-featured approach for Cloud. Therefore, just as any Airflow DAG has admin access to the Airflow database, we anticipate Prefect flows having similarly open access to the open-source Prefect database. And like Airflow, we strongly recommend that users deploy the server only in environments they control by locking them down at the network level. 

Once Prefect’s server is feature-stable, this is something we can revisit as an engineering initiative and as bandwidth allows, but it’s something we want to be absolutely sure is done properly since bad auth can be a greater evil than no auth.

**Comment by newturok** [comment]
Don`t try it, but workaround maybe can be for now to make flow with some variable "key" in the config that is required to run it.

**Comment by djpirra** [comment]
Is Prefect Server still not having stable features? I also believe having strong authentication mechanisms for the on-premise version of prefect is a very strong need.
Many customers cannot adopt cloud and should have an alternative way even if that is delivered by a licensed module.

**Comment by lucardcoder** [comment]
any updates on this?

**Comment by syakesaba** [comment]
+1 @lucardcoder

**Comment by ebusho** [comment]
> Is Prefect Server still not having stable features? I also believe having strong authentication mechanisms for the on-premise version of prefect is a very strong need. Many customers cannot adopt cloud and should have an alternative way even if that is delivered by a licensed module.

🤑

**Comment by WisniewskiGabriel** [comment]
If they want Prefect to take over the industry they gotta implement authentication.

**Comment by tibbon** [comment]
I was going to consider implementing Prefect at my day-job (which _could_ eventually result in us using the Cloud service if we don't have time to maintain it), but this intentional avoidance of allowing such a feature in the version on Github makes this an entirely non-viable path for us. That is rather unfortunate lockdown, as otherwise this was looking to be a fantastic tool.

**Comment by syakesaba** [comment]
They use wss:// to connect server API.
It will be big challenge to implement auth to that.

The easy way will be to restrict source ip addresses of workers and users.

**Comment by cicdw** [comment]
Hey everyone - I want to follow up here with a soft update: it's been 4 years since our original decision to avoid authentication for OSS. We have much greater capacity for supporting enhancements like this now, and **we are planning to incorporate a security layer for the open source package**. I don't want to over-promise on what it will look like, but most likely it will be a token-based authentication mechanism along with a password for UI access. As far as timeline goes, sooner rather than later, most likely no later than Feb 2025. Once we have the intended design we'll open an issue and pin it to the repo - I'll also return to this issue and provide an update once that's out.

I appreciate all of you continuing to chime in here and on other related issues!

**Comment by cicdw** [comment]
For anyone who didn't see otherwise, a working version of basic auth is now available in 3.1.9; technically this was included in 3.1.8 but 3.1.9 also includes a fix for the UI for users also using CSRF so I recommend starting there.

To start a protected server:
```
PREFECT_SERVER_API_AUTH_STRING="admin:admin" prefect server start
```

Authenticate client operations:
```
PREFECT_API_AUTH_STRING="admin:admin" python -c 'from prefect import flow; flow(lambda: None)()'
```

**Comment by shah1dk** [comment]
Thank you so much for implementing this deal breaker kinda situation for us using Prefect in our product.

My docker-compose for Prefect server looks like this:

```
prefect:
    image: prefecthq/prefect:3-latest
    command: prefect server start --host 0.0.0.0
    environment:
      - PREFECT_LOGGING_LEVEL=DEBUG
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:yourTopSecretPassword@db:5432/prefect
      - PREFECT_SERVER_API_AUTH_STRING="admin:admin"
    ports:
      - "4200:4200"
    depends_on:
      - db
```

This results in Prefect UI credential page, but as soon as page loads, I get a toast message in red saying `Authentication failed". Then, when I enter anything in password, it lets me in.

Please let me know if I'm doing anything wrong. Or if you've any documentation for above implementation.

Attaching screenshot here:
<img width="1106" alt="image" src="https://github.com/user-attachments/assets/bc09718d-a466-43bd-b69a-e0775bd16e6c" />

**Comment by mohanrao** [comment]
@cicdw  i am also getting same errors after i authenticate like @shah1dk
