### ISSUE TITLE
Local agent health check

### ISSUE THREAD

**Issue by lmeyerov** [PrefectHQ/prefect#2313]
## Use Case

The local agent parent process should support external healthchecks

We are trying to use prefect as our task manager, where each compute resource has a docker-compose-based service with a prefect local agent in it, and do standard  docker / docker-compose administration over it. While we can monitor the health of the docker process itself, there is no clear way for docker to ask the prefect local agent if it is ok, which prevents 2000-era monitoring, auto-restart, etc.

## Solution

* the prefect local agent exposes an HTTP status check route
* the status check route does whatever consistency checks make sense, even if just a quick "hello!", and returns a 200 status if OK. (Unclear what those are, we're ok with "i'm up" for starters.)
* fancy: config vars to control this further

That is enough that `supervisord`, `docker`, etc. healthcheck frameworks can hook in

## Alternatives

* Prefect handles all observability & reliability operations internally, including executor monitoring & restart stack, in some unexposed + non-standard way
* Prefect does not support health checks

**Comment by joshmeek** [comment]
@cicdw curious to hear your thoughts on this

At first look we could add the optional healthcheck feature to run in a subprocess since the agent isn't already webserver by default. Only possible downside is it would take up one of the spots for the thread pool that are used to send off flow runs simultaneously.

**Comment by jcrist** [comment]
I'm looking at handling this generically within the base agent class. The plan is to add a `/ping` endpoint that always returns `200 OK` as long as the agent is running. We could add a more complicated health check, but the `/ping` api is fairly standard and is the easiest first pass.

One open question is what library to use for the http server. We could use the stdlib http server, since a health check is simple and low resources. However, since dask is already a dependency of prefect, we could also use `tornado` (which is a requirement of dask). I personally prefer async code for these types of services, but could go either way. One perk of using tornado is we'd only need to claim one thread for the health check server, rather than a thread-per-response model.

**Comment by cicdw** [comment]
Given that we already implicitly rely on `tornado` and you have reasons to prefer it, I'm 👍 on using it.  I don't really see a downside
