### ISSUE TITLE
FlowRunner manages context cache wrongly

### ISSUE THREAD

**Issue by ahirner** [PrefectHQ/prefect#2403]
## Description
AttributeError and different behavior of output caching between Flow.run and FlowRunner.run.

## Expected Behavior
No AttributeError, same behavior and cached result reuse of FlowRunner.run after Flow.run.

## Reproduction
```python
from datetime import timedelta
import random

from prefect import task, Flow
from prefect.engine import FlowRunner
from prefect.engine.cache_validators import duration_only

@task(cache_for=timedelta(seconds=10), 
      cache_validator=duration_only)
def rand_inc(r, x):
    rand = random.randint(0, r)
    print("RAND", rand)
    return rand + x

with Flow("Cache") as f:
    a1 = rand_inc(10, 0)

# this fails:
runner = FlowRunner(f)
state1 = runner.run()

# this would pass:
#f.run()
```
Traceback:
```
Traceback (most recent call last):
  File "/Users/dafcok/miniconda3/lib/python3.6/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "~/miniconda3/lib/python3.6/site-packages/prefect/engine/task_runner.py", line 631, in check_task_is_cached
    candidate_states = prefect.context.caches.get(
AttributeError: 'Context' object has no attribute 'caches'
```

Moreover, if you `f.run()` once before `runner.run()`, cache validation always logs `Task 'rand_inc': can't use cache because it is now invalid`.

## Environment
```
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Darwin-19.0.0-x86_64-i386-64bit",
    "prefect_version": "0.10.4",
    "python_version": "3.6.8"
  }
}
```

**Comment by joshmeek** [comment]
Looking for some thoughts on this. What's happening here is the `flow.run` function sets a global `caches` block in context (among other things)

https://github.com/PrefectHQ/prefect/blob/6d141372cf89064d24bbafad582a9db26be0cbd5/src/prefect/core/flow.py#L1024-L1025

And then is uses flow runners to run that flow where each flow runner would have access to that `context.caches`. Now running the flow directly from the flow runner takes it a level deeper, below that context block. This means that if the flow runner is updated to make this `context.caches` in a similar way to the `flow.run` then the cache will not persist across runs since the flow runner is responsible for only a single run. We could add this in there with the knowledge that it will proceed without error but in calling something like 

```
runner = FlowRunner(f)
state1 = runner.run()
state2 = runner.run()
```

the second run will not use the cache from the first run.

**Comment by ahirner** [comment]
I think one design goal could be that FlowRunner.run() is guaranteed to not modify global state, caches or otherwise. Is that already the case? If yes, passing `context=my_dict` could explicitly modify `my_dict` which can be used for other runs.
In the long run, I'm not sure if in-memory caching should become obsolete after #2394
