### ISSUE TITLE
Consider using Sphinx for documentation

### ISSUE THREAD

**Issue by jcrist** [PrefectHQ/prefect#2480]
Prefect is currently using a home-rolled documentation system. Most projects in the Python ecosystem make use of [Sphinx](https://www.sphinx-doc.org/en/master/). Similar to #2479, standard tooling makes it easier for external contributors to contribute, since they don't need to learn something new specific to only your project.

Sphinx provides a number of nice features that the Prefect docs may want to use:

- Automatic formatting of docstrings for api docs, complete with links between types and related methods
- Crossreferencing capabilities - making it easy to reference api docs from inside examples and tutorial code.
- A rich ecosystem of plugins (for example, one for auto-documenting `click` CLIs, see #1971)
- Customizable themes

The prefect docs are quite nice as they are, so maybe we don't want to use Sphinx. Since Sphinx is the norm in the Python ecosystem, it would be good to at least document (in this issue) the reasons for that decision if so.

**Comment by cicdw** [comment]
Historically we chose not to go with Sphinx for a few reasons:
- we didn’t like rst
- we don’t like the way Sphinx documentation looks
- we wanted the docs to have a Prefect look and feel

That being said, we could still do this as it does solve two concrete problems: crossrefs + auto-documenting our CLI.  (And maybe [Sphinx supports markdown](https://www.sphinx-doc.org/en/master/usage/markdown.html) now?).

I do view this as a somewhat high risk undertaking only because we get a lot of positive feedback on our docs as they currently are, so it would be important for us to maintain that look and feel.

**Comment by jcrist** [comment]
Can you expand on the `rst` stance? `rst` is generally more expressive (and extensible), and helps avoid inlining html. A lot of the rich crosslinking support comes from rst sytnax supporting cleaner annotations, something that I don't think would be as easy/clean in markdown. (A distaste for markdown for docs isn't mine alone, see e.g. https://www.ericholscher.com/blog/2016/mar/15/dont-use-markdown-for-technical-docs/).

> I do view this as a somewhat high risk undertaking only because we get a lot of positive feedback on our docs as they currently are, so it would be important for us to maintain that look and feel.

FWIW, I think we could get the site to look fairly similar using sphinx, it's more a question of if the change would bring enough of a draw.

---

*Note that I'm not 100% arguing that we need a change, but I am at least interested in documenting why we've chosen to not use the standard python documentation system in favor of something homegrown.*

**Comment by cicdw** [comment]
> Note that I'm not 100% arguing that we need a change

totally understood, I'm all for revisiting past decisions. If the migration solves a concrete problem then it's worth considering.

For `rst`, I find that I have to "think in rst" to write docs which interrupts how I write, and I think more people are familiar with markdown than `rst`.  At least a portion of the issues raised in that article are addressed by the fact that we use `vuepress` for rendering our docs (so we have access to formatting primitives like `::: warning This is a Warning box`) and don't need our docs to be portable since they are compiled from markdown -> JavaScript.  (Meta comment: I generally find myself more unhappy than happy with most hosted documentation, so I don't give much weight to doc standards right now).

All of that being said, I don't think my thoughts are super surprising here so I'd be more curious for others to weigh in (**cc:** @joshmeek / @lauralorenz / @jlowin / @znicholasbrown / anyone else reading who has an opinion!)

**Comment by znicholasbrown** [comment]
My thoughts

Cons of switching:
- Vuepress is also extendable and pluggable, with a growing number of community plugins as well; we'd have to either find reasonable equivalents in existing plugins or write them ourselves
- Having a Vue-based documentation app provides continuity between the Core UI and docs
- Out of the box, Sphinx isn't great visually, so the design switching costs would be high
- Having docs as an SPA is nice since navigation doesn't require a full re-render of the page; this isn't true of Sphinx docs as far as I can tell
- Markdown and rST are both fine but I'd agree with @cicdw that markdown is a more familiar format because of its ubiquity

Pros of switching:
- Markdown does not have great in-line extensibility (or any afaik), rST has both
- This could provide us with a meaningful inflection point to think about the structure, navigability, and user design of the docs
- We could probably migrate away from the home-grown parser; while the parser is a really tremendous tool, it may not be one that we want continue to maintain. It's not documented nor is it easy to invite other collaborators


Switching won't be easy or quick; it will require a large amount of design and QA, as well as a near-complete rewrite of the existing docs. I think there are some good arguments to be made for switching but I worry about both the end writing experience (documentation is already difficult to draw contributions on) and the high switching costs that'll be involved. Completely open to changing my mind on this though.

**Comment by jcrist** [comment]
Just a few quick comments, great hearing the opinions of y'all.

> Meta comment: I generally find myself more unhappy than happy with most hosted documentation, so I don't give much weight to doc standards right now

To be clear, I'm only arguing for RST/sphinx docs, not for a hosted service like readthedocs.

> Having docs as an SPA is nice since navigation doesn't require a full re-render of the page; this isn't true of Sphinx docs as far as I can tell

Sphinx is generally a static html site, and most themes use minimal JS. Rendering is pretty zippy in these cases, and hosting and development doesn't require a local server since you can just open the html files in your browser and everything works.

> We could probably migrate away from the home-grown parser; while the parser is a really tremendous tool, it may not be one that we want continue to maintain. It's not documented nor is it easy to invite other collaborators

100% agree on this. For me the real draw is less the prose docs and more the api docs. I think sphinx (with years of dev time and many contributors) can do a better job of extracting and generating structured output from api docs than we can with a custom parser. There might be an intermediate option where we use sphinx (or parts of the sphinx ecosystem) to generate the api docs, and pull them in to the larger vuepress site? idk.

**Comment by jlowin** [comment]
> There might be an intermediate option where we use sphinx (or parts of the sphinx ecosystem) to generate the api docs, and pull them in to the larger vuepress site? idk.

I think this is an interesting thread to pull. As API docs are autogenerated anyway (granted, by a homegrown parser), there's less cruft involved in swapping to a different system.

For the prose docs, I have more explicit resistance to be honest. Though I recognize that RST is more expressive than Markdown, while I was maintaining Airflow there were numerous occasions where otherwise-motivated contributors actively avoided writing docs simply because they found RST too burdensome to wrangle with. I think if you're comfortable with RST (as I was once, writing other people's docs :) ), it's easy to overlook the cognitive burden it puts on unfamiliar users. It's far easier to invite someone to submit even a paragraph in Markdown than in RST, because almost no special instruction is required.

However, circling back to my opening comment, perhaps the place to introduce this is the API docs where non-developer users are unlikely to contribute anyway.

**Comment by lauralorenz** [comment]
I'm a fan of the idea to try to integrate Sphinx only for the API docs to split the difference between the benefit of the Sphinx autodoc plugin and keeping the markdowny-in-the-back, beautiful-in-the-front synergy of our existing vuepress ecosystem for the prose. 

If we go that route, we don't get all the auto cross-referencing benefit *in the prose* docs, but AFAIK we don't have that first-class anyways now (I hand-linked pre-rendered in the past a la `[prefect.engine.results_handler](../../api/latest/engine/result_handlers.html)`, as opposed to the Sphinx way of `:py:mod: prefect.engine.results_handler`) and a naive grep indicates we don't link out to the API docs that much in our prose docs now (though that might be because it was too annoying so take that with a grain of salt 🤷 )

FWIW I have had a lot of trouble convincing developers to move to `rst` in the past on internal projects so I would echo that sentiment in this thread. Those were internal only projects, so maybe this pales in comparison to the argument that Sphinx/`rst` is a known standard being stronger here given Prefect is open source so some subset of external contributors probably already use it. But I don't want to underestimate that outside of that I still have observed a vocal discourse against `rst` by beginners and vets alike which is why things like Sphinx's markdown plugin that Chris linked or [mkdocs](https://www.mkdocs.org/) now exist. If we can get a trial going to see if a combo of `sphinx-autodoc` + this `recommonmark` thing (the markdown docstring plugin Chris linked) still gives us all the goodness of `sphinx-autodoc` on the API docs side, maybe we can get the best of both worlds there.

**Comment by madkinsz** [comment]
My 2c is that this is worth revisiting as we consider overhauls to the organization of the documentation. I agree that rst increases the burden to contribute though. I also feel hesitant that we'll have the bandwidth for this anytime soon.

**Comment by damienrj** [comment]
Sphinx works pretty well with the markdown extension. There has some been some progress on autodoc style docs for Markdown though https://github.com/mkdocstrings/mkdocstrings/.

**Comment by madkinsz** [comment]
Thanks for weighing in! We took a long look at that as we tested documentation tooling for Orion. Our current plan is to continue with the same tooling here and use mkdocs for Orion (and we are indeed using autodoc generation there). Eventually, we'll only have the vuepress setup for legacy documentation.
