### ISSUE TITLE
Change default scheduler on `LocalDaskExecutor`

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect#2485]
Right now, our `LocalDaskExecutor` defaults to using the `"synchronous"` dask scheduler which doesn't allow for any parallelism.  The original reason for this was to provide a smooth transition `LocalExecutor` -> `LocalDaskExecutor` -> `LocalDaskExecutor` w/ parallelism but I think more often than not users are confused when `LocalDaskExecutor` doesn't provide parallelism.

We should update the default scheduler to `"threads"` (or `"processes"`, @jcrist you might have an opinion about which is best in this case).

@kingsleyb I'll assign this to you as a good first issue but feel free to unassign yourself if you decide not to pick it up.

**Comment by jcrist** [comment]
> We should update the default scheduler to "threads" (or "processes", @jcrist you might have an opinion about which is best in this case).

Threads is good default for most things. The multiprocessing scheduler in dask (`"processes"` here) is generally not recommended - it has some inefficiencies that are fixed in `distributed` and would be too tricky to fix for the local implementation. We generally recommend users only use `threads`, `synchronous`, or `distributed` (which works fine locally!).
