### ISSUE TITLE
Generic dask cluster environment

### ISSUE THREAD

**Issue by jcrist** [PrefectHQ/prefect#2503]
Currently Prefect has created `Environment` classes mirroring a few of Dask's `*Cluster` classes:

- `DaskKubernetesEnvironment` for `dask_kubernetes.KubeCluster`
- `DaskCloudProviderEnvironment` for `dask_cloudprovider.ECSCluster`/`dask_cloudprovider.FargateCluster`

This approach works, but seems a bit untenable, as it requires a new class in prefect for each cluster-manager class in dask.

Since dask `Cluster` classes all share a uniform interface, a different approach would be to create a generic `DaskClusterEnvironment` (actual class name TBD) that takes in a dask cluster class and kwargs as configuration:

```python
environment = DaskClusterEnvironment(
    cluster_class="dask_cloudprovider.FargateCluster",
    cluster_kwargs={
      "image": "my-excellent-prefect-image", ...
    }
)
```

This has a few nice benefits:

- It doesn't require Prefect to maintain large variety of Dask environments. The dask Cluster classes all have a standard interface, so any of them should work with the single `DaskClusterEnvironment` class in prefect.
- It helps ease the burden on Prefect duplicating deployment documentation for every platform Dask supports. We'll probably still want to provide a few examples, but since the syntax is the same as Dask's it's easier to punt the documentation burden off to the corresponding Dask docs.

**Comment by joeschmid** [comment]
@jcrist I really like this idea. I'm not sure if the following concept would be in scope for this, but one aspect that comes up is around lifecycle management of the Dask cluster. The simplest approach is clearly to dynamically create a cluster for each Flow run, but obviously that comes with significant overview.

I wonder if an option for lifecycle management with "create if necessary / re-use if exists" semantics could make sense to be part of this? There's a bunch of complexity that comes with running multiple Flows simultaneously on the same Dask cluster (software version distribution to workers, e.g. are the Flows using the same image for Docker storage, # of workers to support N Flows, etc.) so maybe that would be a phase 2 or just out of scope. Wanted to mention it more for brainstorming rather than a hard requirement that we have.

**Comment by jcrist** [comment]
> I wonder if an option for lifecycle management with "create if necessary / re-use if exists" semantics could make sense to be part of this?

Yeah, I think that's an interesting idea, but out-of-scope for this current issue. Will need more thought.

**Comment by jcrist** [comment]
After thinking about this issue a bit more over the day, I've put out an alternative idea in #2508 that I think makes more sense than the one presented here (see that issue for more info). My current thought is that this issue should be closed in favor of #2508, but I'll leave both open now for discussion.

**Comment by joeschmid** [comment]
Thanks @jcrist. I'm in agreement that we should just continue discussion/work on https://github.com/PrefectHQ/prefect/issues/2508 and close this one in favor of that. Happy to let others chime in if they feel like leaving this open has value though.

**Comment by jcrist** [comment]
Sounds good. Closing in favor of #2508.
