### ISSUE TITLE
Add warning to agent install upon setting server backend without overriding API endpoint

### ISSUE THREAD

**Issue by gfalcone** [PrefectHQ/prefect#2514]
Hi, 

I would like to run the Prefect platform on my private infrastructure. I managed to setup my local Prefect Platform with Docker Compose and setup the Kubernetes Agent to run my tasks like this : 

`````
prefect backend server
prefect server start
prefect agent install kubernetes --rbac | kubectl apply -f -
`````

When running the dummy task defined here : https://docs.prefect.io/orchestration/tutorial/k8s.html#running-a-kubernetes-agent , my prefect agent goes nuts as you can see below :

![Screenshot 2020-05-07 at 16 29 59](https://user-images.githubusercontent.com/3447482/81306649-01490e00-9080-11ea-8042-7cb54cff549c.png)

It seems that it is directly querying the Prefect Cloud API's instead of my local setup's API (this happens also when I set up the Kubernetes agent with the backend server specified like this : 

````
prefect agent install kubernetes --rbac --backend server | kubectl apply -f -
````

Is it working as it should be ?

**Comment by joshmeek** [comment]
Hey @gfalcone could you also try setting the `--api` to the endpoint that your server is running on? Keeping in mind that the agent running _on_ k8s needs access to that endpoint. I can see why the `--backend server` is confusing because it doesn't actually change the endpoint the agent is looking at and we should adjust that behavior!

**Comment by joshmeek** [comment]
Updating this issue to better reflect the change necessary
