### ISSUE TITLE
Use literal_eval for parsing configuration values

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/prefect#2536]
## Current behavior
*Please describe how the feature works today*
Currently, Prefect takes a [hardcoded stab](https://github.com/PrefectHQ/prefect/blob/master/src/prefect/configuration.py#L37) at converting strings to Python objects. We could replace this function with `ast.literal_eval()` and instantly gain a more flexible cast, including the ability to natively handle lists and dicts. 

## Proposed behavior
*Please describe your proposed change to the current behavior*

Currently, setting `PREFECT__X__Y="['a', 'b', 3]"` results in `prefect.config.x.y == "['a', 'b', 3]"`. This means some Prefect objects (thinking of environments, but also including the config itself) must re-parse config options. This is after we already make an attempt to coerce some values to known types. Replacing this with `ast.literal_eval()` would result in `prefect.config.x.y == ['a', 'b', 3]`.

## Example
*Please give an example of how the enhancement would be useful*

**Comment by cicdw** [comment]
I definitely get the idea here @jlowin but I think using `json` might introduce more user-facing complexity; to give you a concrete example, the code you wrote above would _not_ work using `json.loads` because `json` expects double quotes.  

That being said, using `ast.literal_eval` avoids those sorts of formatting issues and still allows for the safety + flexibility that I think you're looking for here.

**Comment by jlowin** [comment]
Ah shoot you're right, that's not even valid json. I like your suggestion better!
