### ISSUE TITLE
Configuration Reference

### ISSUE THREAD

**Issue by dylanbhughes** [PrefectHQ/prefect#2562]
## Use Case
*Please provide a use case to help us understand your request in context*
We've reached the point where there are a _lot_ of configuration options. These can get overwhelming and a bit confusing, especially for users running Prefect Server. Some need to be set on machines that build flows, some need to be set on machines running Prefect Server before the server starts.

## Solution
*Please describe your ideal solution*
We should create a configuration reference that describes every possible configuration option and how and where to properly set them.

## Alternatives
*Please describe any alternatives you've considered, even if you've dismissed them*
N/A

**Comment by jlowin** [comment]
I might want to revisit #2102 to relatedly split up configs - for example, Core, Contrib/Plugins, etc.

**Comment by dylanbhughes** [comment]
A great example by @jcrist https://gateway.dask.org/api-server.html

**Comment by joshmeek** [comment]
Yeah great idea, we could use a doc for this! I also want to add more comments / structure to the current base `config.toml` to make it cleaner

**Comment by jcrist** [comment]
We just added one for dask/distributed by adding a schema file that lives alongside the config `yaml` file. This was needed, since there was no easy way to parse structured comments from the default yaml file, and we wanted to also test that the schema (for documentation) and the config file don't fall out of sync. See https://github.com/dask/dask/pull/6069. Zero-to-JupyterHub follows the same pattern for documenting their helm-chart.

**Comment by dylanbhughes** [comment]
Maybe we should revisit now that server II is out?
