### ISSUE TITLE
Add start and end timestamps to flow state so duration of flow can be handled

### ISSUE THREAD

**Issue by petermorrow** [PrefectHQ/prefect#2622]
## Current behavior
It doesn't look like the start and end times of a finished flow are currently available.

## Proposed behavior
Save the start and end time of a flow to the finished state so the duration of the task can be determined.

## Example
When I change the implementation details of a flow I'd like to be able to check how long a flow took in a state handler.

It would also be nice if I could do this with tasks.

**Comment by jlowin** [comment]
Prefect Server and Prefect Cloud both track run start times, end times, and duration by comparing the timestamps of run states (for flows and tasks). The first time a run enters a running state marks its "start time" and the last time it exits a running state marks its "end time." Any state handler can query the API for the run's start time to compute its duration to that point.

This is deceptively difficult to do without an orchestrating backend/API, because, depending on failures, retries, and other conditions, it may take multiple disjoint attempts -- possibly on completely different machines -- to run a flow to completion. Even an individual task may be spun up multiple times in multiple places before finishing. Therefore, properly tracking duration requires state management across environments to pass those times around. Since Prefect is already built around the concept of timestamped States and an API for orchestrating them, we reuse them effectively for purposes like these.
