### ISSUE TITLE
Flow not starting or throw an error after a while [multiprocessing, cloud]

### ISSUE THREAD

**Issue by gbreeze** [PrefectHQ/prefect#2634]
## Code

``` python
import prefect
import time
from prefect import task, Flow
from datetime import timedelta
from prefect.schedules import IntervalSchedule

from multiprocessing import Pool


def long_task(x):
    print("long_task")
    time.sleep(10)
    print("long_task done")


@task
def hello_task():
    logger = prefect.context.get("logger")
    logger.info("Starting Pools...")
    thread_pools = Pool()

    thread_pools.map(long_task, range(4))

    thread_pools.close()
    thread_pools.join()
    logger.info("all tasks done")


if __name__ == "__main__":
    if True:
        schedule = IntervalSchedule(interval=timedelta(minutes=2))
        flow = Flow("hello-flow", schedule, tasks=[hello_task])

        flow.register(project_name="test")
        flow.run_agent(
            token="..."
        )
    else:
        flow = Flow("hello-flow", tasks=[hello_task])
        flow.run()

```

## Exception (in cloud logs)

``` error
Unexpected error: PicklingError("Can't pickle <function long_task at 0x0000019E18510A68>: attribute lookup long_task on __main__ failed")
Traceback (most recent call last):
  File "c:\users\mail\appdata\local\programs\python\python37\lib\site-packages\prefect\engine\runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "c:\users\mail\appdata\local\programs\python\python37\lib\site-packages\prefect\engine\task_runner.py", line 943, in get_task_run_state
    self.task.run, timeout=self.task.timeout, **raw_inputs
  File "c:\users\mail\appdata\local\programs\python\python37\lib\site-packages\prefect\utilities\executors.py", line 182, in timeout_handler
    return fn(*args, **kwargs)
  File "e:/Temp/prefect/test1/task1.py", line 22, in hello_task
    thread_pools.map(long_task, range(4))
  File "c:\users\mail\appdata\local\programs\python\python37\lib\multiprocessing\pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "c:\users\mail\appdata\local\programs\python\python37\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
  File "c:\users\mail\appdata\local\programs\python\python37\lib\multiprocessing\pool.py", line 431, in _handle_tasks
    put(task)
  File "c:\users\mail\appdata\local\programs\python\python37\lib\multiprocessing\connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "c:\users\mail\appdata\local\programs\python\python37\lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function long_task at 0x0000019E18510A68>: attribute lookup long_task on __main__ failed
```

I'm probably doing something wrong here. Is there some documentation about multiprocessing?

**Comment by cicdw** [comment]
Hi @gbreeze - this is a tricky one.  Here's what's happening: `flow.register` uses `cloudpickle` to store your Flow as bytes on disk.  Your agent then deserializes your Flow and runs it.  

Whenever `cloudpickle` serializes your `hello_task`, the `long_task` reference is serialized as a member of the `__main__` module.  When `multiprocessing` runs it then attempts to pickle something called `__main__.long_task` which no longer exists (because the flow isn't being run from `__main__` anymore).

I played around with a few alternatives but couldn't get anything to work - @jcrist are you aware of any patterns we could use here?

**Comment by jcrist** [comment]
Apologies for the late reply here. The issue here is that when we run a registered flow, we unpickle the flow, we don't re-run your script. As such `long_task` exists as an object in the running interpreter, but doesn't have the name `__main__.long_task`, so `pickle` can't serialize it. If `multiprocessing` used `cloudpickle` instead (which can serialize functions without a consistent name) things would work fine. A few options:

- Store your code in a separate library/file that's available in your deployment location. You might have a library of helper tasks like `long_task`, and your script for building the flow would import those and register them. In this way `long_task` would have an importable name from a file, not `__main__.long_task`.
- You might use a different `Pool` implementation that uses `cloudpickle` instead. It's unfortunate that `multiprocessing.Pool` in the standard library doesn't let you configure the serializer, otherwise using `multiprocessing.Pool` with `cloudpickle` would be a good solution. You have a few options here - `joblib`, `multiprocess`, `dask`, etc... Here's one way that works with `dask`'s multiprocessing scheduler:

```python
import prefect
import time
from prefect import task, Flow
import dask


def long_task(x):
    print("long_task")
    time.sleep(2)
    print("long_task done")


@task
def hello_task():
    logger = prefect.context.get("logger")
    logger.info("Starting Pools...")
    dask.compute(
        [dask.delayed(long_task)(i) for i in range(4)],
        scheduler="processes",
    )
    logger.info("all tasks done")


if __name__ == "__main__":
    with Flow("hello-flow") as flow:
        hello_task()

    flow.register(project_name="testing")
```

- Alternatively you might ditch using using multiple processes directly, and instead add `long_task` to your Prefect flow itself. If you run with a `DaskExecutor` (and have dask configured to use processes/threads as you'd like them), dask will schedule your tasks in parallel across the processes/threads in a way that should be efficient.

 Any of the solutions I provided above would be fine, I'd have to know more about what `long_task` really is to provide better advice on which to pick.
