### ISSUE TITLE
Expose serialization/deserialization of Results

### ISSUE THREAD

**Issue by AndrewRook** [PrefectHQ/prefect#2639]
## Current behavior
Currently when you use a `Result` with a `target` the user does not have any control over how the data is (de)serialized before being (read from)written to the `target`. The default (cloudpickle) allows for I/O of a wide variety of objects, but there are many cases where you might want to use something more specialized, e.g. Pandas's `to_csv`.  

## Proposed behavior
First I propose coming up with a standard interface for a serializer/deserializer, something like an object with `serialize` and `deserialize` methods. Then I propose that serialization/deserialization be exposed as a kwarg accepting an instance of that object, probably in the instantiation of the `Result`. 

## Example
You can see discussion of this in #2115.

**Comment by bachsh** [comment]
I think it makes a bit sense to implement that with inspection, and registering custom (de)serializers for user-defined types. Since task can know what types it expects and what it produces, it can use that information to handle (de)serialization.

For example we can register a (de)serializer like this:
```
@serializes(CustomType, CustomType2)
class Serializer:
    def serialize(obj):
        # .. serialize...
		return serialized_object
	def deserialize(serialized_obj)
		# .. deserialize...
		return obj
```

WDYT?

**Comment by bachsh** [comment]
@AndrewRook, typically in an ETL flow, intermediate data is persisted using the same serialization across the flow. Another example I've had the chance of working with is with training ML/DL model. Sometimes there's a need for multiple stages in training and you'd like to persist them. It makes sense to define the way to serialize a model (e.g., a pytorch model) once in the application instead of supplying the serializer every time.

However, you are right in saying that you might want to control the output of specific tasks. That corresponds perfectly with the Prefect way of modifying tasks, where each task can be configured both at the flow (global) level, and then have this configuration tweaked on the task level.

**Comment by bobcolner** [comment]
What about a simple option to turn-off the default cloud-pickle sterilization? It would be up to the user to ensure the task returns bytes. 

This would work for many use-cases I run into.
