### ISSUE TITLE
Allow tasks to be defined within flow context

### ISSUE THREAD

**Issue by eric-czech** [PrefectHQ/prefect#2677]
## Current behavior

Warning on task creation within flow context:

```python
from prefect import Flow, task
with Flow('f') as flow:
    r = task(lambda x: x)(1)
flow.run()

UserWarning: Tasks were created but not added to the flow: {<Task: <lambda>>, <Task: 1>}. This can occur when `Task` classes, including `Parameters`, are instantiated inside a `with flow:` block but not added to the flow either explicitly or as the input to another task. For more information, see https://docs.prefect.io/core/advanced_tutorials/task-guide.html#adding-tasks-to-flows.
```

## Proposed behavior

I understand that this is preferable:

```python
fn = task(lambda x: x)
with Flow('f') as flow:
    r = fn(1)
flow.run()
# No warning
```

but, I can't understand what that warning is really telling me in the case above.  A new `FunctionTask` is certainly instantiated in the first case but why is that a problem?  I'm finding it difficult to stick with this latter, warning-free idiom in more complicated pipelines where the tasks themselves are defined lazily as class inheritance models for our data sources are used within the flow context to connect various tasks together.  On the other hand, ignoring the warning has yet to cause any real problems in my tests.  

Is it a bad warning or am I missing something?  I'm also a little confused as to why defining a task object wrapping stateless, static functions in a stateful context is a bad practice.

I can see some ways to workaround the warning by merging flows or using the imperative API, but I'd really like to avoid that. 

## Example

```python

def task_type_1(path, options): ...

def task_type_2(path, options): ...

class DataSource1(GenericDataSource):

    def __init__(self, config):
        # This is a configuration that contains dozens or hundreds of properties,
        # many of which I only want to use to control how the Prefect pipeline 
        # **is defined**, not how it behaves when executed
        self.config = config

    def get_task(self):
        options = self.find_options() # super class does some more generalizable work
        if config.flag:
            # Note that `options` enter the flow as constants in a closure
            return task(lambda path: task_type_1(path, options))
        else:
            return task(lambda path: task_type_2(path, options))

def run(config, path):
    ds = DataSource1(config)
    with Flow('flow') as flow:
        result = ds.get_task()(path)
```

Some things I've thought about and would like to avoid are:

- Make my `config` a dict and program all the conditional logic using Prefect conditional operators.  I basically want to be able to build a variety of different Prefect flows based on a configuration, not make one big one.
- Call to my `*DataSource` classes before entering the flow context and cache task definitions

Is there another way to be thinking about this?  I'm kind of stumped on what the best way to proceed is if this is really an anti-pattern.

**Comment by jlowin** [comment]
Hey @eric-czech, first of all what you're doing is 100% fine, and you should continue doing it! That warning is [relatively new](https://github.com/PrefectHQ/prefect/pull/2584) (I think it was released just last week) and there is room for improving it.

In particular, the warning is aimed at new users who don't know that you have to call a task after defining it, and it is triggered by instantiating a task inside the flow and not adding it to the flow. If you're curious, I think you're seeing it because even though you DO use the task after instantiating, the functional API makes a copy of the task when you call it and it's the ORIGINAL version of the task (which is, in fact, unused in your flow) triggering the unnecessary warning.

Since it's unusual to define tasks within the flow context, we frankly didn't adequately check the warning behavior under that circumstance. I'm going to look into a clean way to detect this behavior and suppress the warning; in the meantime, you can disregard it!

**Comment by jlowin** [comment]
p.s. thank you very much for such a clear example!

**Comment by eric-czech** [comment]
> the functional API makes a copy of the task when you call it and it's the ORIGINAL version of the task (which is, in fact, unused in your flow)

Ohhh I see, that makes sense.

> Since it's unusual to define tasks within the flow context, we frankly didn't adequately check the warning behavior under that circumstance. I'm going to look into a clean way to detect this behavior and suppress the warning; in the meantime, you can disregard it!

Phew, good to know this is a valid approach.

Thanks for the quick response @jlowin!
