### ISSUE TITLE
Docs Issue: incorrect (old?) import path for LocalResult

### ISSUE THREAD

**Issue by claforte** [PrefectHQ/prefect#2682]
In the tutorials / Next Steps, it looks like this line:

`from prefect.engine.result import LocalResult`

... should be replaced by:

`from prefect.engine.results.local_result import LocalResult`

**Comment by alexisprince1994** [comment]
The `Result` subclasses (such as `LocalResult`) are located in the `prefect.engine.results` package and can be imported from there. It looks like the base `Result` class was placed in `prefect.engine.result` instead of `prefect.engine.results` (oops... that was my PR!). 

Thanks for pointing that out! Will submit a PR to fix the docs! Will write a separate issue for moving the actual base `Result` class from `prefect.engine.result` -> `prefect.engine.results` to be consistent with the rest of the repo.
