### ISSUE TITLE
Cycle error with 'ifelse'

### ISSUE THREAD

**Issue by eric-czech** [PrefectHQ/prefect#2688]
## Description

Cyclic graphs are constructed by sequential conditional statements without cyclic task references.

## Reproduction

```python
@task
def a(x):
    return x + 1

@task
def b(x):
    return x * 1

def run(show_cycle_error=False):
    x = 1
    
    # First ifelse
    t1 = a(x)
    t2 = b(x)
    ifelse(x > 1, t1, t2)
    y = merge(t1, t2)
    
    # Second ifelse that uses nothing but outputs from first ifelse
    t3 = a(y)
    if show_cycle_error:
        t4 = y
    else:
        t4 = task(lambda x: x)(y)
    ifelse(y > 1, t3, t4)
    z = merge(t3, t4)
    return z
```

As long as the true/false branches in the second `ifelse` are derived from the results of the first, everything is ok:

```python
with Flow('f') as flow:
    r = run(show_cycle_error=False)
flow.visualize()
```

<img width="536" alt="Screen Shot 2020-06-01 at 7 45 38 AM" src="https://user-images.githubusercontent.com/6130352/83406558-e8145280-a3dc-11ea-8f70-a6a5e9389999.png">

Without that `t4` identity task though (the "lambda" step in the image), I get a cycle error:

```python
with Flow('f') as flow:
    r = run(show_cycle_error=True)
# ValueError: Cycle found; flows must be acyclic!
```

Perhaps this is related to https://github.com/PrefectHQ/prefect/issues/2679, or maybe I'm misunderstanding the way Prefect is trying to represent conditionals in a DAG, but there is no reason this shouldn't work in either case right?

**Comment by jcrist** [comment]
So the trick here is that `ifelse` is used to gate a task from running, but in your case `y` has to run to determine if `y` should run (`y` is used in its own conditional). This should be doable with some logical additions to `ifelse` to check for upstream dependencies, but it's an added complication.

Note that if you use `case` instead of `ifelse` to build your conditionals, then everything works fine. The `case` contextmanager is easier to reason about (IMO) when defining conditional tasks, but `ifelse` should have also worked here.

```python
from prefect import task, Flow, case
from prefect.tasks.control_flow import merge


@task
def a(x):
    return x + 1

@task
def b(x):
    return x * 1

with Flow("test") as flow:
    x = 1

    with case(x > 1, True):
        t1 = a(x)
    with case(x > 1, False):
        t2 = b(x)
    y = merge(t1, t2)

    with case(y > 1, True):
        t3 = a(y)
    t4 = y
    z = merge(t3, t4)
```

![test](https://user-images.githubusercontent.com/2783717/83527991-29c0fe00-a4ae-11ea-84d3-eaac33ac696f.png)

**Comment by eric-czech** [comment]
Nice, I'll stick with `case` then.  Thanks @jcrist.
