### ISSUE TITLE
Cached task seems to neither hit nor miss

### ISSUE THREAD

**Issue by dipasquo** [PrefectHQ/prefect#2754]
## Description
Attempting to upgrade a flow from prefect 0.10.7 to 0.11.5. Flow tasks use custom ResultHandler and caching of several long running Tasks.

I run flow repeatedly with same (one) input.  First Flow run has no cache hits, all Tasks are run and their results cached (expected behavior).  Second Flow makes a cache hit and fulfills Task from cache, Flow runs to successful completion (expected behavior).  Third Flow run identifies candidate cache states, but seems to neither retrieve cached results nor does it invalidate all the candidates/run task, as a result downstream tasks do not have required input and fail.

Log messaging from SECOND run (i.e. first one where cached result available):
```
Task 'run_...': 1 candidate cached states were found
11:19:32 PDT
INFO
GCSTmpFileHashResultHandler
Starting to download result .....
INFO
GCSTmpFileHashResultHandler
Finished downloading result ....
DEBUG
CloudTaskRunner
Task 'run_...': Handling state change from Pending to Cached
```

Log messaging from THIRD run (i.e. expected another cache hit, but cached result was not retrieved nor the cache invalidated:
```
Task 'run_...': Starting task run...
11:23:43 PDT
DEBUG
CloudTaskRunner
Task 'run_...': 2 candidate cached states were found
11:23:43 PDT
DEBUG
CloudTaskRunner
Task 'run_...': Handling state change from Pending to Cached
11:23:43 PDT
DEBUG
CloudTaskRunner
Task 'run_...': can't set state to Running because it isn't Pending; ending run.
11:23:43 PDT
INFO
CloudTaskRunner
Task 'run_...': finished task run for task with final state: 'Cached'
``` 

## Expected Behavior
Expected that in subsequent Flow runs with same input, cache hit would result in a cache retrieval.  Or, some logging that indicated that candiate cached states were invalidated for some reason and the Task was run.

## Environment
KubernetesJobEnvironment deployed via GKE

**Comment by dipasquo** [comment]
We realize that ResultHandlers are deprecated but expected this to be non-breaking upgrade.  Eventually we'll adopt Result interface but wish to do this incrementally.

**Comment by lauralorenz** [comment]
Hi @dipasquo, is this still an issue for you? (Just noticed the issue was closed and reopened really fast a while ago, which maybe was an accident.)

We do expect custom result handlers to be a non-breaking upgrade, as they are converted into `ResultHandlerResult` objects that expose the underlying custom result handler's `read` and `write` methods from the "old" ResultHandler interface into the "new" Result interface (reference here: https://github.com/PrefectHQ/prefect/blob/master/src/prefect/engine/results/result_handler_result.py#L53-L82). In other words, the code from your custom result handler's `read` and `write` methods should still be called by the pipeline directly. 

Can you share any more about your custom result handler, or let us know if there's something that stands out to you in the reference link there with respect to how your custom result handler works?

**Comment by dipasquo** [comment]
Hi @lauralorenz, yes, I guess I closed it accidentally, then reopened it. Likely still an issue but no longer a priority as we've moved ahead to re-implement our custom ResultHandler as a custom Result and upgrade to 0.12.  Leave it to your discretion to close this again

**Comment by dipasquo** [comment]
I'm going to close this, as it is no longer blocking us and the more time goes on the less relevant it is.  Feel free to re-open at your discretion.
