### ISSUE TITLE
Create data binding in task initialization 

### ISSUE THREAD

**Issue by beghtesadi** [PrefectHQ/prefect#2778]
## Current behavior
Currently, you can create data dependencies by binding a task `run` method to an upstream's result.

## Proposed behavior
Is it possible to also create bindings at the task instantiation? This is helpful when you need to initialize a task with a dynamic input. 

## Example
```python

with Flow("My flow") as flow:
    task_one = TaskClass(...)
    task1_out = task_one(...)

    downstream_task = TaskClass2(arg1 = task1_out)
    task2_out = downstream_task()
flow.run()
```

We couldn't find a way to do this, but let me know if there is already a way of accomplishing this.

**Comment by cicdw** [comment]
Hi @beghtesadi - any logic / data that is only known at runtime should be encapsulated within a task's `run` logic.  To achieve what you're after, you can move whatever you were doing at initialization into your run method.  Prefect Flows are composed of Tasks, and it wouldn't really make sense to run a Flow with things that are not-yet-tasks.  Since your Flow structure is known, I don't see a use case for deferred initialization that can't be solved by a refactor.

**Comment by cicdw** [comment]
Closing per my reasoning above
