### ISSUE TITLE
Document Prefect server deployment on AWS/EC2

### ISSUE THREAD

**Issue by sahayadigo** [PrefectHQ/prefect#2787]
Is there any document available for running prefect in AWS ECS instance using EC2

**Comment by joshmeek** [comment]
Hi @sahayadigo at the moment I am not aware of any documentation surrounding this but I know many people have done it. Since the current iteration of the server can be spun up with Docker compose it should be able to be deployed directly on an EC2 instance and then have the ports exposed for outside access. I am going to update this ticket to be about `docs` because we need to improve clarity on how to do this.

Tagging @znicholasbrown if he has any specifics to add because IIRC he was just talking to someone about this.

**Comment by znicholasbrown** [comment]
@sahayadigo: @joshmeek is correct, you're able to deploy Prefect Server on an EC2 in the same way you would locally, with 2 notable differences in spinup:
1) You'll need to set the `server.ui.graphql_url` variable in the EC2's `~/.prefect/config.toml` to the public server endpoint of your machine, it'll look something like this: `http://EC2_PUBLIC_UP:4200/graphql`
2) Ports 8080 and 4200 need to be exposed to web traffic; 4200 exposes the API and 8080 exposes the UI. 

Once those are done and server has started up, you should be able to access the UI at:
`http://EC2_PUBLIC_UP:8080`. You'll know this everything was configured correctly if you see a green API health status tile in the bottom right of the dashboard.

**Comment by lauralorenz** [comment]
Closing this for now as we are rolling this type of docs update into a larger deployment communication initiative instead of a one-off issue. Hopefully the tips so far help you out @sahayadigo!

**Comment by juloi** [comment]
> @sahayadigo: @joshmeek is correct, you're able to deploy Prefect Server on an EC2 in the same way you would locally, with 2 notable differences in spinup:
> 
> 1. You'll need to set the `server.ui.graphql_url` variable in the EC2's `~/.prefect/config.toml` to the public server endpoint of your machine, it'll look something like this: `**http://EC2_PUBLIC_UP**:4200/graphql`
> 2. Ports 8080 and 4200 need to be exposed to web traffic; 4200 exposes the API and 8080 exposes the UI.
> 
> Once those are done and server has started up, you should be able to access the UI at:
> `http://EC2_PUBLIC_UP:8080`. You'll know this everything was configured correctly if you see a green API health status tile in the bottom right of the dashboard.

Having to set `server.ui.graphql_url` in the `config.toml` file to `**http://EC2_PUBLIC_UP**:4200/graphql` is still a key step in automating the deployment prefect server in an EC2 instance, otherwise none of Overview, Flows or Agents tabs of the UI work. I looked on the official docs, and this step is not found there, would be very useful to add it soon!
