### ISSUE TITLE
Remove slugs entirely from tasks

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/prefect#2806]
## Current behavior
*Please describe how the feature works today*
Today, users can supply slugs as task identifiers. Prefect enforces a rule that two tasks in a flow can not have the same slug (so functionally, slugs are IDs) . This causes unexpected behaviors, especially with the functional API, because tasks are copied-on-call and new (random) slugs have to be generated. Consequently, no matter what user-supplied slug is present, most functional flows have random slugs.

In #2531, @cicdw introduced stable slugs that enable all kinds of useful downstream features. Critical to this implementation is that the **flow** assigns slugs to tasks. For simplicity, his implementation continues to allow users to assign slugs to tasks, but it is superfluous. We could remove slugs from tasks (and related serialization) and dramatically simplify task identification.

## Proposed behavior
*Please describe your proposed change to the current behavior*

Remove task slugs as an attribute

## Example
*Please give an example of how the enhancement would be useful*

**Comment by Marlin-Na** [comment]
As a user, I would like to rely on the slug behavior (unique within a workflow). For example, use slug as directory name for saving results, or as database key, etc.

I would propose that we can keep slug, but allow it to be `None` at the time of task initialization. **flow** will only assign `slug` to task if the task slug is `None` (i.e. user doesn't care about slug). When copying a task, instead of generating a random new slug, we simply inherit the slug from old task. This means if user cares about slug and gives a slug to task, he/she will also be responsible for giving a new slug when copying the task.

Additionally, removing slug entirely would be a breaking change. The proposal above might be easier to implement.
