### ISSUE TITLE
LocalDaskExecutor with "processes" scheduler runs some tasks twice

### ISSUE THREAD

**Issue by zviri** [PrefectHQ/prefect#3124]
## Description
I noticed that when running a Flow containing mapped tasks via the `LocalDaskExecutor(scheduler="processes")` some of the tasks in the flow run twice, and in worst case scenario the whole pipeline runs twice.

With all the other executor setups (e.g. `DaskExecutor` or just using `threads` scheduler in the `LocalDaskExecutor`( the pipeline runs correctly.

## Expected Behavior
The execution of the same pipeline should be the same across different executors.

## Reproduction
I was only able to create this simple example which shows that one of the tasks ran twice. However, the original pipeline that has a similar structure runs all its tasks twice, every time.

```[Python]
@task
def check_files():
    print("CHECKING FILES")
    return True

@task
def load_files(checked):
    return [1,2]

@task
def process_files(f):
    return f

@task
def agg(f):
    return sum(f)

with Flow("EvalPipeline") as flow:
    checked = check_files()
    files = load_files(checked)
    processed = process_files.map(files)
    summary = agg(processed)
state = flow.run(
    executor=LocalDaskExecutor(scheduler="processes", num_workers=1)
)
```

Output:
![example_output](https://user-images.githubusercontent.com/1793977/89765052-dbeff400-daf5-11ea-8757-618489d7d1d1.png)

## Environment
* prefect==0.12.6
* dask==2.15.0

**Comment by jcrist** [comment]
Thanks for the excellent bug report. We did some work a few releases ago to prevent tasks from running multiple times when using the `LocalDaskExecutor`, but there was an edge case with the multiprocessing scheduler that allowed tasks to still run multiple times in certain cases (dask's multiprocessing scheduler runs some optimization passes that didn't play well with how we handled this). This has since been fixed in #3127, and will be released in the next few days.
