### ISSUE TITLE
Flow added from remote machine does not started by agent

### ISSUE THREAD

**Issue by bralbral** [PrefectHQ/prefect#3138]
## Description

Good evening!

The prefect server 0.13.1 and the prefect local agent are running on the remote server.

I want add flow to server from my local machine.

I tried:

```
from prefect import Client
client = Client(api_server="http://remote_server_ip:4200/graphql")
client.register(flow=flow, project_name='bral')

```
 And flow successfully registred on server, and  i can see it from my local machine using this connection (http://remote_server_ip:4200/graphql) on ui.

But agent does not scheduled this flow, and on ui you can see error : "Late run"

![image](https://user-images.githubusercontent.com/54455457/89943297-a4cd3000-dc26-11ea-8802-f79346725ccf.png)

Local agent does not see  too:

![image](https://user-images.githubusercontent.com/54455457/89943390-cd552a00-dc26-11ea-9c8b-314561278bb8.png)

But if i copy this script.py to remote machine, and 👍 
`flow.register("bral")`

Flow will registred, and trigered by local agent.
## Expected Behavior

I don’t know for sure, but perhaps it was originally intended to use client.register () constructs for the cloud? And initially went wrong while trying to add to my remote server.

Thanks!

**Comment by joshmeek** [comment]
Hi @bralbral this is most likely due to the [labels](https://docs.prefect.io/orchestration/agents/overview.html#flow-affinity-labels) on your flow. Flows registered with Local storage are by default tagged with a label matching the hostname of that machine. This is to prevent agents that are running elsewhere from attempting to pull local files. If you want to use your flow on a different machine I recommend looking into one of the other [cloud-based storage options.](https://docs.prefect.io/orchestration/execution/storage_options.html#local)

**Comment by bralbral** [comment]
Thanks for useful link! So, i need add storage , for example local storage, use `storage.buld()` and this storage must exists on remote machine?

**Comment by joshmeek** [comment]
If you store your flow on your local machine then there is no way to access that flow on the remote machine unless it has access to the same file system. If you are able to access the same file system then you _could_ start that agent with the label of the host machine's name. For the other storage options you don't need to use Docker at all. The flow can be stored directly via upload to S3, GCS, Webhook, etc.
