### ISSUE TITLE
Setting graphql_url doesn't work while connecting outside of localhost server

### ISSUE THREAD

**Issue by NoName115** [PrefectHQ/prefect#3254]
## Description
I'm running a prefect-core instance on one machine which is behind VPN (lets say IP of this server is 10.128.55.10), I'm working from other computer connected via VPN into internal network. When I set-up prefect server and configurate my `config.toml` file:
```
[server]
    [server.ui]
    graphql_url = "http://10.128.55.10:4200/graphql"
```
I'm able to connect to `http://10.128.55.10:8080` UI but it says that it cannot connect to graphql API, when I set the url for graphql manualy via UI to `http://10.128.55.10:4200/graphql` everything is connected and works, but it's not set automaticaly via config-file as I would expect.

## Expected Behavior
Opening website at url `http://10.128.55.10:8080` will automatically connect to the graphql endpoint at `http://10.128.55.10:4200/graphql`.

## Reproduction
1. running Ubuntu server verion 20.04 LTS
2. $ python3.7 -m venv venv
3. $ source venv/bin/activate
4. $ pip install -U pip && pip install docker-compose prefect
5. configurate `config.toml` in `~/.prefect` folder, as mentioned above
6. $ prefect server start

7. Connect from other machine into VPN and open url for prefect-ui `http://10.128.55.10:8080`
8. graphql API is not connected automatically

## Environment
```
{
  "config_overrides": {
    "backend": true,
    "server": {
      "endpoint": true,
      "graphql": {
        "host": true
      },
      "hasura": {
        "host_port": true
      },
      "host": true,
      "host_port": true,
      "port": true,
      "ui": {
        "endpoint": true,
        "graphql_url": true,
        "host": true,
        "host_port": true,
        "port": true
      }
    }
  },
  "env_vars": [],
  "system_information": {
    "platform": "Linux-5.4.0-42-generic-x86_64-with-Ubuntu-20.04-focal",
    "prefect_version": "0.13.5",
    "python_version": "3.7.8"
  }
}
```

**Comment by NoName115** [comment]
Only solution which worked for me was to run `prefect server start --no-ui` and then clone `prefect/ui` repository, change `VUE_APP_SERVER_URL` variable in `.env` file for `http://10.128.55.10:4200/graphql` and start prefect UI via `npm run serve`.

**Comment by joshmeek** [comment]
Hi @NoName115 I don't think that configuration operates in the same way as it used to (I'm wondering if actually we can remove that from config entirely). As of the `0.13.0` release the Apollo endpoint is configured for the UI either on the `/home` page or through the manual setting that you did when you served the UI repo directly.

https://docs.prefect.io/orchestration/server/deploy-local.html#ui-configuration

**Comment by NoName115** [comment]
Hi @joshmeek, thank you a lot for your answer. It's really confusing then for users to set-up server correctly, I for example today spent several hours trying to figure this out, as even in your UI is written to configure this in the `config.toml` file, see https://github.com/PrefectHQ/ui/blob/d873d4408e11b3b660107f38c66f8541038cf68f/src/pages/Home/StartPrefectServer-Section.vue#L97

Or maybe second option, is it so complicating to implement this feature same way as it worked before, so configuration file can be use for that?

**Comment by znicholasbrown** [comment]
Hi @NoName115! We've got a [ticket open in the UI repo](https://github.com/PrefectHQ/ui/issues/99) for what you've described, and it includes the reason we're not using that method in the built application any longer. My apologies for the confusion, the screen that you linked isn't intended to modify the UI settings at container runtime but is referring to otherwise configurable options for the rest of the stack.

In the meantime, since it sounds like you're looking for a somewhat more complicated deployment, you can run the UI as its own development web server, similar to how the Apollo application is run, and you can modify the environment defaults in the`.env` file included in the repo (for your case you'll modify `VUE_APP_SERVER_URL`). The full instructions for running the UI in development mode are in the UI [README](https://github.com/PrefectHQ/ui).

**Comment by joshmeek** [comment]
Closed by https://github.com/PrefectHQ/ui/pull/219
