### ISSUE TITLE
hashed_inputs slowing task execution

### ISSUE THREAD

**Issue by RanganThaya** [PrefectHQ/prefect#3276]
## Description
When the task runner executes from the cache, the code hashes the input as seen from Line 689 (https://github.com/PrefectHQ/prefect/blob/master/src/prefect/engine/task_runner.py). This `tokenize` slows the flow run when the input is large. 

Consider the following snippet
```
from dask.base import tokenize

large_dict = {}
for i in range(0,10**6):
    large_dict[i] = {'key_1': 'This is a sentence', 'key_2':str(i)}
%timeit tokenize(large_dict)
```

Output

```
26.8 s ± 368 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

Is there an option to disable hashing of inputs?

**Comment by jcrist** [comment]
This is unfortunately not possible - the way caching works currently the input needs to be hashed to find a cache match (how else would you check if the cache matches for arbitrary input args?) Note that the speed of `tokenize` has less to do with the size of the input data and more to do with the number/depth of objects (there is a larger per-object overhead than size of objects, a large numpy array will tokenize faster than a large deeply nested json-like-thing).

I get a slightly faster time, but it's still in the 10s of seconds:

```python
In [10]: %time tokenize(large_dict)
CPU times: user 19 s, sys: 715 ms, total: 19.8 s
Wall time: 19.9 s
```

There might be a way we can be more selective with when/how many time we call `tokenize` (cc @cicdw, who knows more about this mechanism than myself), but the use of `tokenize` itself is pretty core to the implementation.

Note that if you have some large data, but know something about it that can make computing a stable hash faster, you can make a wrapper object that computes a hash much quicker. We might want to add a mechanism to prefect to make doing this easier, but for now something like this should work:

```python
In [17]: class MyHashWrapper:
    ...:     def __init__(self, obj):
    ...:        self.obj = obj
    ...:     def __dask_tokenize__(self):
    ...:         """Return something representative of the object"""
    ...:         # perhaps we know the `key_1` key is representative of each dict, regardless of other keys
    ...:         return [o["key_1"] for o in self.obj.values()]
    ...:

In [18]: obj = MyHashWrapper(large_dict)

In [19]: %time tokenize(obj)
CPU times: user 207 ms, sys: 53.2 ms, total: 260 ms
Wall time: 262 ms
Out[19]: '6da48e9d0e1afa64f863b9f0fafad79e'
```

See https://docs.dask.org/en/latest/custom-collections.html#implementing-deterministic-hashing for more info on customizing tokenize behavior.

**Comment by RanganThaya** [comment]
Thank you for the pointers. This works. 

Just an idea for large input values: If the incoming values are cached results, rather than hashing the entire input we can also hash the file name or the checksum of the file.

**Comment by cicdw** [comment]
Checksum'ing the filename is an interesting idea; another minor optimization we could make is to avoid hashing inputs whenever the cache validator is `duration_only`, although it _is_ possible for many different tasks with different validators to use the same `cache_key` so that has the potential for some edge cases we'd want to consider.

**Comment by jcrist** [comment]
If we're ok with updating the algorithm behind `tokenize`, there are some ways I can think of to speed up `tokenize` for these types of arguments. A quick hack:

```python
In [112]: import cloudpickle, hashlib, io

In [113]: class HashFil(io.IOBase):
     ...:     def __init__(self):
     ...:         self.hash = hashlib.sha1()
     ...:     def write(self, buf):
     ...:         self.hash.update(buf)
     ...:         return len(buf)
     ...:     def writable(self):
     ...:         return True
     ...:     def buffer_callback(self, buf):
     ...:         self.write(buf.raw())
     ...:

In [114]: def tokenize(x):
     ...:     fil = HashFil()
     ...:     buf_fil = io.BufferedWriter(fil)
     ...:     pickler = cloudpickle.CloudPickler(buf_fil, protocol=5, buffer_callback=fil.buffer_callback)
     ...:     pickler.dump(x)
     ...:     buf_fil.flush()
     ...:     return fil.hash.hexdigest()
     ...:

In [115]: %time tokenize(large_dict)
CPU times: user 484 ms, sys: 10.6 ms, total: 494 ms
Wall time: 498 ms
Out[115]: '56d3daa5fe1a91b83dba0ae021b5bad0e463296c'
```

Dask's tokenize is a few years old and predates pickle 5 - it wasn't written this way originally due to the overhead the extra copies would have made. It's also optimized for normal-sized arguments and to minimize per-call overhead for small arguments (it's called everywhere in dask).

Prefect has different design restrictions. We don't call `tokenize` that often, so minimizing the per-call overhead in the small case is less important than minimizing worst-case performance (e.g. large nested objects). Something like the above should be performant enough and could replace our use of dask's tokenize (I don't think we'll want that in dask, as the per-call overhead is about double, for small args things would be 2x as slow (note that this is microseconds, which matter less for prefect, but do for dask)).

If we're cool with this, I'm happy to push up a patch.
