### ISSUE TITLE
DBTShellTask dbt_kwargs

### ISSUE THREAD

**Issue by zhen0** [PrefectHQ/prefect#3280]
## Description

From community slack: https://prefect-community.slack.com/archives/CL09KU1K7/p1599551263372600

From that slack comment: 

__I am trying to run a DbtShellTask with a dynamic set of dbt_kwargs that are defined at run time. The task works when I define the dbt_kwargs in the task initialization, but not when they are provided at runtime._

Looks like the dbt_kwargs needs an empty dictionary at initialization to be modified at runtime. 

_The documentation or the task default arguments should be changed.
Either change the documentation to say that it requires an empty dict at initialization but that this dict can be modified at runtime, or change the default arguments to not be None so that the dictionary modification I mentioned above works as expected.
Thanks so much!__

## Expected Behavior

Ideally, you don't need to provide an empty dict at initialization.  If not that, the docs define what is need at initialization correctly.

**Comment by nathaniel-md** [comment]
Which do people think sounds better from a design perspective? Either changing the docs, or the default arguments, or the line [here](https://github.com/PrefectHQ/prefect/blob/24cb38fe661baa5b91f1506a74709eff60a334cc/src/prefect/tasks/dbt/dbt.py#L136)... I tend to think that it would be okay to initialize the `dbt_kwargs` argument to be an empty dict instead of `None`...

**Comment by zmac12** [comment]
With the PR merged to resolve this issue, is there anything I need to do to get it closed out?

**Comment by joshmeek** [comment]
Nope @zmac12 it should be good to close!
