### ISSUE TITLE
Improve flow runner to enable more task parallelism

### ISSUE THREAD

**Issue by xuevin** [PrefectHQ/prefect#3380]
## Description
Flatten has edge cases which sometimes causes tasks to run sequentially. I have identified 2 cases below which demonstrate the unusual behavior. In the test case, I `flatten` the output of a mapped seed task and execute 3 dependent sleep tasks which are intended to run in parallel. The implementation of the DAG has an influence on whether the job executes in parallel or not

## Expected Behavior

`fast_flow` demonstrates the expected behavior. Upon launch, all three print statements show up immediately.
`slow_flow` adds one additional step by storing flatten into an array, and retrieving it by index. This has the same DAG as `fast_flow` but this ends up executing sequentially.
`slow_flow_2` is identical to `fast_flow` but removes the map task. It is odd that downstream tasks are required for parallel execution. 

![image](https://user-images.githubusercontent.com/296101/94098011-aa0cc580-fdf5-11ea-94f0-036b6ac173c2.png)

## Reproduction

```python
import time
from prefect import task, Flow, flatten, unmapped
from prefect.engine.executors import LocalDaskExecutor


@task
def seed(i):
    return [i]


@task
def sleep(i, sleep_time):
    print(f'Sleep {sleep_time}')
    time.sleep(sleep_time)

    print(f'Finished {sleep_time}')

    return [i]


@task
def task2(i):
    print(f'Task2 {i}')
    print(f'Finished {i}')
    return [i]


with Flow("slow_flow") as slow_flow:
    start = ['A']
    inputs = flatten(seed.map(start))
    all_paths = []
    for i in (10, 11, 12):
        foo = [flatten(sleep.map(inputs, unmapped(i)))]
        all_paths.append(foo[0])
    sleep_out = flatten(all_paths)
    task2.map(sleep_out)

with Flow("fast_flow") as fast_flow:
    start = ['A']
    inputs = flatten(seed.map(start))

    all_paths = []
    for i in (10, 11, 12):
        all_paths.append(sleep.map(inputs, unmapped(i)))
    sleep_out = flatten(all_paths)
    task2.map(sleep_out)

with Flow("slow_flow_2") as slow_flow_2:
    start = ['A']
    inputs = flatten(seed.map(start))

    all_paths = []
    for i in (10,11,12):
        all_paths.append(sleep.map(inputs, unmapped(i)))


fast_flow.run(executor=LocalDaskExecutor(scheduler='threads'))
#slow_flow.run(executor=LocalDaskExecutor(scheduler='threads'))
#slow_flow_2.run(executor=LocalDaskExecutor(scheduler='threads'))
```

## Environment
Prefect - 0.13.7
python 3.8.2

**Comment by jcrist** [comment]
Hi @xuevin, thanks for the reproducible example. I've marked this as an enhancement rather than a bug, as I don't think it breaks any of our existing guarantees.

The way prefect is currently written, we guarantee that tasks in a *single `map` task can run in parallel, but multiple unrelated tasks (or `map` tasks as above) may or may not depending on the internals to the `FlowRunner` implementation. That said, there's no reason why we couldn't enable parallelism across the three different `map` tasks above.

For now, if you want to ensure that tasks will run in parallel, you (unfortunately) either need to write them explicitly as a single `map` task pipeline, or check that the quirks of the existing flow runner let these tasks run in parallel.

**Comment by xuevin** [comment]
One approach that I have used to achieve parallelism is to this implementation of flatten. This works well locally, but I think it will occur a lot of overhead when moving toward distributed systems. 

```python
@task
def flatten(list_to_reduce):
    return [item for sublist in list_to_reduce for item in sublist]
```

However, I still see that it requires the additional dependent tasks that follow it to properly execute in parallel. ie. `slow_flow_2` is still slow.

**Comment by jcrist** [comment]
Yeah, that will gather all results locally before mapping, which will add a bunch of overhead if the results are large-ish (if they're not it's probably fine).

The proper fix would requires some changes to the `FlowRunner` to be better expose parallelism opportunities between tasks rather than within a single mapped task.

**Comment by tkram01** [comment]
I think I am seeing the same issue. This code runs sequentially

```
from time import sleep
from prefect import Flow, task
from prefect.executors import LocalDaskExecutor

@task()
def add_ten(x):
    print(f'starting {x}')
    sleep(10)
    print(f'ending {x}')
    return x * 2

with Flow('simple map', executor=LocalDaskExecutor(num_workers=25)) as flow:
    t = add_ten.map([1, 2, 3])
    s = add_ten.map([10, 20, 30])

if __name__ == '__main__':
    from prefect.run_configs import LocalRun
    flow.run_config = LocalRun()
    flow.run()
```

but this runs in parallel

```
from time import sleep

from prefect import Flow, task
from prefect.executors import LocalDaskExecutor


@task()
def add_ten(x):
    print(f'starting {x}')
    sleep(10)
    print(f'ending {x}')
    return x * 2


with Flow('simple map', executor=LocalDaskExecutor(num_workers=25)) as flow:
    t = add_ten(1)
    t1 = add_ten(2)
    t2 = add_ten(3)
    t3 = add_ten(10)
    t4 = add_ten(20)
    t5 = add_ten(30)

if __name__ == '__main__':
    from prefect.run_configs import LocalRun

    flow.run_config = LocalRun()
    flow.run()
```

They should be equivalent. This is a big issue for us. Are there any workarounds?
