### ISSUE TITLE
Update .map() to do permutations when provided with more than one parameters.

### ISSUE THREAD

**Issue by snenkov** [PrefectHQ/prefect#3416]
## Current behavior
When `.map()` is used on a function (with two or more parameters), currently it (silently) assumes that all parameters which want to be mapped are iterables of the same length.

As such, it takes the lowest `len` parameters and maps to the rest. Anything above this length is discarded of (silently).

For example:

```
from prefect import task

@task
def my_func(a, b):
    print((a, b))


with Flow("mapping example") as flow:
    a = Parameter("a")
    b = Parameter("b")

    my_func.map(a, b)

flow.run(parameters={
    'a': ['foo', 'bar'],
    'b': [1, 2, 3, 4, 5]
})
```

The above will print only:

```
 ('foo', 1)
 ('foo', 2)
```

This is identical to doing this in python:

```
import itertools
a = ['foo', 'bar']
b = [1, 2, 3, 4, 5]

list(itertools.product(a, b))
```

## Proposed behavior
Ideally I think it should do one of three things.

### First proposal - most desired behaviour. 

The same code above, should do a permutation and print all possibilities such as:
```
 ('foo', 1)
 ('foo', 2)
 ('foo', 3)
 ('foo', 4)
 ('foo', 5)
 ('bar', 1)
 ('bar', 2)
 ('bar', 3)
 ('bar', 4)
 ('bar', 5)
```

### Second proposal - less desired.

Raise a warning.
This is because otherwise some part of the information just disappears. I bet that most (if not all) time when a user passes a different length parameters, it's not intentional.

It's a less desired proposal, because having the ability of doing what is described in the first proposal is just so powerful and elegant.

### Third proposal

Have a new function such as `.product_map()` which will do what I describe above.

## Example
This will be useful since it will remove further any loops.
Often I have jobs which take multiple parameters (date and some string (url)) is one example. In such a task I need to loop over each URL on each date. This is now achieved with a loop + .map. What I suggest will be only achieved in a single line of code. I consider this to be a common scenario.

**Comment by cicdw** [comment]
Our reasoning for using the `zip` pattern instead of a `product` pattern can be found here: https://github.com/PrefectHQ/prefect/issues/1986#issuecomment-583188939. TLDR; it's the standard within data tooling.

Because this is currently possible with a single extra task that performs the product, I'm hesitant to implement another first-class API for mapping right now as that can be a slippery slope with maintenance.  

We can leave this open to see how popular of a request this ends up being.

**Comment by snenkov** [comment]
Extra task was indeed my solution - > then passing the tuple (or whatever is it), so I agree it's not too bad this way.

**Comment by jcrist** [comment]
Since `task.map` follows the existing `map` conventions found in the Python standard library (and other implementations like `dask`, `toolz`, etc...) I'm going to close this. At some point we might want to add a utility for expressing a product (matching `itertools.product`), but for now having users do it manually should be sufficient.

Closing.
