### ISSUE TITLE
Feature for deletion of task metadata once the flow is completed.

### ISSUE THREAD

**Issue by ChiragSokuwar** [PrefectHQ/prefect#3450]
## Current behavior

As of now, there's no option to delete the task metadata stored locally or in S3. This data consumes a huge chunk of space on the system. 

## Proposed behavior

There should be a way to delete the data for both locally and the data stored in s3.

**Comment by jcrist** [comment]
Hi @ChiragSokuwar. To clarify, are you asking for a way to delete older flow versions that were registered using `S3` as `flow.storage`?

**Comment by ChiragSokuwar** [comment]
Hi @jcrist, I am asking about the metadata(Results) that gets created when there is an information exchange between the tasks.

**Comment by sm-Fifteen** [comment]
I'm having the same issue. Checkpointing is turned on by default, there doesn't seem to be any sort of automatic clean up and the documentation doesn't mention when/how these intermediate result files should be safely removed once the flow run is complete and no longer needs to be restarted.

Some of the result files I get are over a gigabyte in size (which would be fine if the file got deleted afterwards), so this is proving to be an inconvenience because not all local agents or cloud storage backends have infinite amounts of storage space to spare.
