### ISSUE TITLE
Set flow labels through the CLI register command

### ISSUE THREAD

**Issue by mattop4d** [PrefectHQ/prefect#3455]
## Current behavior
Right now there is no way to add a label to a **flow** when registering it using the CLI. You only can set the label from inside the flow's code.

## Proposed behavior
It would be really nice to have a `--label` parameter (just like the one we have for agents) that would allow us to add labels on the fly when registering a flow from the CLI.

## Example
Adding the parameter would look something like this:
`prefect register flow --file my_flow.py --name My-Flow --label my-label`
or this:
`prefect register flow --file my_flow.py --name My-Flow -l my-label`

This could be very useful for registering flows with continuous integration depending on the environment you want to build the flow for (for example, `dev` or `prod`).

Thanks a lot and keep it up!

**Comment by jcrist** [comment]
Thanks for the feature request, this would be a welcome feature.

One question:

If a flow already configures labels (`['a']`) on it, what's the expected behavior with labels set via the CLI (`['b', 'c']`)?

- Override the labels set on the flow (`['b', 'c']`)
- Extend the labels set on the flow with those from the CLI (`['a', 'b', 'c']`)
- Error, can either set labels on the flow directly, or via the CLI, but not both

Right now I'm leaning towards extending the list of labels as the expected behavior.

**Comment by mattop4d** [comment]
That's a good point!

I guess I'm with you. Extending the list is the most intuitive, at least for me.
