### ISSUE TITLE
Allow exporter arguments in Jupyter ExecuteNotebook task

### ISSUE THREAD

**Issue by swierh** [PrefectHQ/prefect#3687]
## Current behavior

When running the `jupyter.jupyter.ExecuteNotebook` task with `output_format='html'` the default settings for the HTMLExporter are used. There is no way to pass arguments to this exporter.

## Proposed behavior

Allow passing arguments to the HTMLExporter.

## Implementation suggestion

Something like `html_exporter = nbconvert.HTMLExporter(**exporter_kwargs)` on the following line:
https://github.com/PrefectHQ/prefect/blob/master/src/prefect/tasks/jupyter/jupyter.py#L65

## Example usecase

This allows you to exclude code cells, only showing their output, in the exported html document by passing the `exclude_input=True` argument to the exporter.

**Comment by madkinsz** [comment]
Since this would only apply to the html exporter and not the json output perhaps it'd make sense to allow make `output_format` a `Union[str, Exporter]` so an initialized exporter can be passed in directly instead with whatever arguments you want (base `Exporter` type at https://github.com/jupyter/nbconvert/blob/master/nbconvert/exporters/exporter.py#L49)
