### ISSUE TITLE
Prefect client API to update an existing project

### ISSUE THREAD

**Issue by AlessandroLollo** [PrefectHQ/prefect#3718]
## Current behavior
The only way to update an existing project (i.e: project description) is by using the low-level GraphQL client.

## Proposed behavior

Introduce a new API `update_project` which can be used to update information (i.e: project description) of an existing project.

## Example

The new API would look similar to `update_project(project_name="foo", project_description="bar")`
It may also take other arguments in addition to `project_description`, I'm not sure if there are any other attributes which may be useful to update.

**Comment by joshmeek** [comment]
This may need to be broken up into two functions because currently there are two mutations instead of one single update mutation—`set_project_name` and `set_project_description`. Both take the ID of the project so the function signatures would look something like

```
set_project_name(id: str, name: str)

# and

set_project_description(id: str, description: str)
```

We _could_ do a single update function which will update the name and/or description based on whether they are provided or not however I'm not sure if that would be too ambiguous 🤔

**Comment by madkinsz** [comment]
I'm not sure what best practice with GraphQL is, but it seems like it'd make sense to add a generalized update mutation for a project?
