### ISSUE TITLE
Use custom container names when useing docker storage with docker agent

### ISSUE THREAD

**Issue by konczbenedek** [PrefectHQ/prefect#3819]
Hi,

I trying to figure out how to set the name for the container that docker agent spans when the flow is deployed from the cloud.

We are using the docker agent running on the local network together with the Prefect Could as an orchestrator. There are multiple jobs that run scheduled to be run by one of the containerized docker agents in a separated container. Our problem with the approach is that every time a new container with the same flow is started it gets an autogenerated name by docker which makes monitoring hard. It would be great if we could use the image name or something similar for the containers.

**Comment by konczbenedek** [comment]
It seems to me that when the `create_container` method of the APIClient class the name parameter is not provided [here?](https://github.com/PrefectHQ/prefect/blob/4b6b5253e671291498f62e3ef8af9705fc2c7a88/src/prefect/agent/docker/agent.py#L407)

**Comment by joshmeek** [comment]
This is probably something that could be added to the [`DockerRun`](https://docs.prefect.io/api/latest/run_configs.html#dockerrun) as `name` and then the name can be passed to the create_container call. @jcrist thoughts on adding this?

**Comment by jcrist** [comment]
Since names have to be unique, we wouldn't want to use `name`, as any pre-named thing could collide if there are multiple concurrent runs. Docker does support labels for containers - we could auto-label all containers with their flow name/slug/something which would group them together. Would also avoid adding another config parameter (too many options can be confusing for users).

Would labeling containers with information on their corresponding flow be sufficient @konczbenedek?

**Comment by konczbenedek** [comment]
@jcrist labeling sounds sufficient. We would need a parameter that is the save over all containers spun for the given flow name / slug so metrics (like average lifetime) would recognize them as one-kinde of entity.
