### ISSUE TITLE
Dask Client.profile artifact

### ISSUE THREAD

**Issue by bnaul** [PrefectHQ/prefect#3836]
Just a general proposal for now: what would folks think of an artifact that calls Client.profile and uploads the output? Might have to just persist the HTML version to some storage location and link to that, probably the full flame graph info would not really translate to Markdown very easily.

Still getting a handle on what artifacts are good for so if this makes no sense let me know and it won’t hurt my feelings 😄. But if it does make sense I’d be happy to implement it.

**Comment by jcrist** [comment]
Hmmm, I can see this being useful, but I'm not sure how to fit it into the current system. A few notes:

- Currently artifacts are only at the task level, while you'd want this to be at the flow level (unless you wanted to add a task to do it at the end of a flow run). This would require some backend changes, but nothing terribly complicated.
- Dask profiles contain potentially proprietary info about your code, we wouldn't want to store this in prefect's system. As such, the most we could do is store a link to the profile stored elsewhere (but then this is further complicated, since user's would want to configure the storage location/backend). They can also be quite large, so we wouldn't want to store them in our DB anyway.

You could do this fully in userspace though, with a custom task added to the end of a flow run. This could be done with a `resource_manager` to ensure it always runs. Something like (untested pseuducode):

```python
import prefect
from distributed import worker_client

@prefect.resource_manager
class dask_profile:
    def __init__(self, file_path):
        # could also have the upload step create the file name, so no explicit path needed
        self.file_path = file_path

    def setup(self):
        pass

    def cleanup(self, _):
        with worker_client() as client:
            profile = client.profile()
        upload_to_path(profile, self.file_path)
        prefect.artifacts.create_link(self.file_path)

with Flow("your-flow"):
    with dask_profile("s3://bucket/path/to/profile.json"):
        # put all your tasks in here
        # the profile will run after all contained tasks, regardless of success/failure
        pass
```

Something like that might suit your needs, and wouldn't need to be contained in prefect core at all. It also gives you full flexibility with what you want to upload and where, something we'd likely have to make configurable if we put it in the main library.

**Comment by bnaul** [comment]
Thanks @jcrist! Something like the above was what I had in mind for now; we had talked in https://prefect-community.slack.com/archives/CL09KU1K7/p1602269846235100 about how I'm currently persisting these w/o any artifact integration. I thought it might make sense to move upstream to Core since it feels pretty broadly applicable, but I agree it seems hard to support as just a drop-in since there's a few user configuration steps and it doesn't quite fit the standard pattern.
