### ISSUE TITLE
`prefect server start` should allow an external postgres instance

### ISSUE THREAD

**Issue by madkinsz** [PrefectHQ/prefect#3891]
## Current behavior

Because https://github.com/PrefectHQ/prefect/blob/master/src/prefect/cli/server.py#L19 replaces `localhost` with `postgres` (forcing docker dns usage), a typical setup will not be able to connect to a local database. I've suggested replacing `localhost` with `127.0.0.1` as a temporary workaround for users but have not tested it myself. Regardless, the postgres container cannot be easily dropped from the docker-compose file as currently implemented and consequently when using an external postgres we're still spinning one up in docker which is pretty confusing and makes it hard to tell if things are working as expected.

## Proposed behavior

- Allow the postgres section to be dropped from the docker-compose file with a CLI flag
- When using an external postgres, do not replace `localhost` with `postgres`

`prefect server start --external-postgres` would just drop the `postgres` section of the docker-compose file as we drop things for "no ports" flags and add a conditional to the string replacement in environment creation.

## Example

User wants to use managed postgres
https://github.com/PrefectHQ/server/issues/156

**Comment by joshmeek** [comment]
Yeah this can follow a similar pattern to what we do for the `--no-ui` flag 👍   while we're here maybe we should also add an option to specify the host/port/conneciton_url of the postgres instance. Would replace this:

https://github.com/PrefectHQ/prefect/blob/3f34f173351a66a6c4a47bcf396ceecb18f68e7f/src/prefect/cli/server.py#L19-L21

Definitely relying on the localhost by default but I can see situations where a non-local instance would be wanted!

**Comment by sm-Fifteen** [comment]
This is currently preventing me from testing [database persistence locally](https://docs.prefect.io/orchestration/Server/deploy-local.html#database-persistence-and-migrations) on a windows-docker setup, since `--use-volume` runs into [volume ownership issues](https://stackoverflow.com/questions/49148754/docker-container-shuts-down-giving-data-directory-has-wrong-ownership-error-wh) with the official Postgres docker image on Windows, and while I do have a local instance of Postgres on this machine, I can't seem to get prefect server to see it (same errors as what's being discussed in PrefectHQ/server#156).

**Comment by mahiki** [comment]
Yes i want to make the connection to local or RDS postgres easier.

**Comment by chaitan94** [comment]
I've :+1:'d this quite a long back :smile:. Just wanted to gently bump this up.

**Comment by madkinsz** [comment]
Hey @chaitan94 -- we've assigned an engineer and this feature is coming :)

**Comment by jcrist** [comment]
Fixed by #4424. Closing.
