### ISSUE TITLE
Prefect agent continues to run but doesn't register itself in server

### ISSUE THREAD

**Issue by alexkoay** [PrefectHQ/prefect#3972]
This portion of the code is encountered when trying to register a new agent to the server, both running in a GKE cluster.
https://github.com/PrefectHQ/prefect/blob/4971eca9fbacf0db2e8e1e65691f26ce026160ae/src/prefect/agent/agent.py#L229

What seems to happen is that GKE restarted all the pods, and the server came up at the same time the agent did, but because it failed the registration, the server doesn't show the agent as running and healthy in the UI.

This doesn't seem to be the case for the cloud, so I'd like to understand if there is a reason why the agent should not error and allow the pod to restart vs. continuing on silently. Perhaps it's a case of a missing `raise`?

**Comment by joshmeek** [comment]
@alexkoay I believe this line where the exception is not raised was added intentionally because there was a time where server did not yet have agent registration but then it was added in newer versions. We didn't want the agents erroring out and forcing users to upgrade their server instances. That older version of server should be long behind us now and we should now handle the exception accordingly 👍
