### ISSUE TITLE
Task starts to run while upstream LOOP task is in Retry state (not actually finished)

### ISSUE THREAD

**Issue by jm4rt1ns** [PrefectHQ/prefect#3985]
## Description
I am submitting this as a bug as recommended by @jcrist on slack chat.
 
```
@task(max_retries=5, retry_delay=timedelta(seconds=60))
def execute_a():
    ...
    if condition:
        return value
    raise LOOP(...)

with Flow("myflow") as flow:
  result_a = execute_a()
  result_b = execute_b(result_a)

```
The task **execute_a** is calling an API, looping until all pages are retrieved. It will return a value on the last iteration of the loop.
While the flow is running and **execute_a** is looping, I will shutdown the network to simulate an issue when calling the API:
```
...
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='myhost.com', port=443): Read timed out. (read timeout=10)
[2021-01-20 17:50:02+0100] INFO - prefect.TaskRunner | Task 'execute_a': Finished task run for task with final state: 'Retrying'
[2021-01-20 17:50:02+0100] INFO - prefect.TaskRunner | Task 'execute_b': Starting task run...
[2021-01-20 17:50:02+0100] INFO - prefect.TaskRunner | Task 'execute_b': Finished task run for task with final state: 'Pending'
[2021-01-20 17:50:02+0100] INFO - prefect.FlowRunner | Flow run RUNNING: terminal tasks are incomplete.
[2021-01-20 17:50:02+0100] INFO - prefect.Myflow | Waiting for next available Task run at 2021-01-20T16:51:02.371101+00:00
```
As we can see in the logs, task **execute_b** shows as it has been started and set to Pending state.

## Expected Behavior

I would expect to not see this:
[2021-01-20 17:50:02+0100] INFO - prefect.TaskRunner | Task 'execute_b': Starting task run...
[2021-01-20 17:50:02+0100] INFO - prefect.TaskRunner | Task 'execute_b': Finished task run for task with final state: 'Pending'

I would expect **execute_b** to only start after **execute_a** finishes and returns a value. 
Should I be expecting something different?

## Reproduction
You can reproduce the behaviour following what I have described

## Environment
I tested this locally using Prefect 0.14.3

**Comment by cicdw** [comment]
Hi @jm4rt1ns - I can understand your confusion here, but in fact Prefect _is_ doing what you expect.  Each time a run is triggered, Prefect will walk the entire dependency graph.  Each task will then decide whether it actually needs to run (or not), and produce a log + state corresponding to that decision, which is what you are seeing here.

So in your example, the execution proceeds as follows:
- `A` fails, detects retry settings, and decides to retry in 1 minute.  This is represented by a sequence of state changes Pending -> Running -> Failed -> Retrying for this task run
- `B` is visited next, and realizes that its upstream dependencies are not all complete.  Therefore it ends _prior to ever running_ in a Pending state.  
- whenever the retry time is reached, `A` will go back into a `Running` state and execution will proceed
- once `A` has completed (whether successfully or not), `B` will run its trigger and decide whether it can proceed - if `A` is Successful, `B` will enter a `Running` state and run, and if `A` has failed, `B` will enter a `TriggerFailed` state and never run.

You can also see this if you, for example, introduce a new task upstream of `A` -- whenever `A` goes to retry, the first task will still be checked to confirm its state, and you'll see a log corresponding to this check.

I think we could make the logs clearer, so instead of saying "Starting task run" and "Finished task run", we might instead say something less definitive.

**Comment by jm4rt1ns** [comment]
Yes you are absolutely correct on the fact that in the end Prefect is actually doing what I expect in terms of final result from the flow, that has never been a concern for me. 
Maybe it is just a question making the logs clearer so that a downstream task does not show up as "Starting..." when the upstream LOOP task has not completed.
Thanks for your input, I will close the issue now.
