### ISSUE TITLE
Append to existing markdown artifact

### ISSUE THREAD

**Issue by mattop4d** [PrefectHQ/prefect#4007]
## Current behavior
Right now you can create new markdown artifacts and update them. The problem is that updating them will replace its content completely. Also, there is no way to get the current contents of an artifact. This means that if I want to add information to an existing artifact, I have to keep track of the artifact ID and also of its contents.

## Proposed behavior
It would be great to have a way to append information to an existing artifact without deleting its previous content.

I can think of 2 ways it could be done:
1. Create a new function just for appending information
2. Add a boolean parameter to the already existing `update_markdown` function

## Example
Option 1:
``` python
# Publish a markdown artifact
my_id = create_markdown("# Hello world!")
# Append more information with a dedicated function
append_markdown(my_id, "I am a description text")
```

Option 2:
``` python
# Publish a markdown artifact
my_id = create_markdown("# Hello world!")
# Append more information with the 'replace' flag set to False
update_markdown(my_id, "I am a description text", replace=False)
```

I'm not sure if this is useful to anyone else or I am using artifacts the wrong way 😄
As always, thank you for your awesome work!

**Comment by joshmeek** [comment]
Thanks for opening @mattop4d! I'm not sure I have a strong preference either way for the implementation. I do like the second option where update defaults to `replace=False` and under the case where it's true the function gets the contents of the artifact and appends the new text. However, this could get confusing because it would only be useful for the markdown artifact and probably wouldn't be used with the link artifact or some other future ideas (i.e. image artifacts).

> Also, there is no way to get the current contents of an artifact. This means that if I want to add information to an existing artifact, I have to keep track of the artifact ID and also of its contents.

I think the implementation here boils down more to adding a function to retrieve artifact contents. Appending/updating will always require passing in the ID. Also, if instead of a change to the current functionality, adding a function to get artifact content combined with the current update functions would allow users to define explicitly _how_ they want to append to the artifact contents. Thoughts?

**Comment by mattop4d** [comment]
That would also work!
Having a way to retrieve the current contents would serve the ultimate purpose which is to be able to set an artifact contents by doing something like `contents += new_data`, so this could be a third option.

I'd be happy with any of them :)

**Comment by madkinsz** [comment]
I have a preference for adding

- `get_artifact(artifact_id: str) -> dict` -- new route, returns a dict of the artifact model
- `update_markdown(..., append: bool = False)` -- new kwarg for appending to markdown, `replace` doesn't make the behavior clear to me
