### ISSUE TITLE
Flow registration on custom server gives wrong URL

### ISSUE THREAD

**Issue by steph-ben** [PrefectHQ/prefect#4082]
## Description

I have setup a custom, remote prefect server. 

However, when registering a flow, only `localhost` is displayed in the Flow URL :

```
$ prefect register flow --file ./myflow.py -p sandbox
Result check: OK
Flow URL: http://localhost:8080/default/flow/9235a237-f6bc-41c7-89bc-132db233b49e
 └── ID: a09a47b0-1292-412f-bd70-89c8bf4dcf1e
 └── Project: sandbox
 └── Labels: []
```

## Expected Behavior

I expect the server name in the url, eg. 

```
$ prefect register flow --file ./myflow.py -p sandbox
...
Flow URL: http://bench.ovh:8080/default/flow/9235a237-f6bc-41c7-89bc-132db233b49e
...
```

I suspect the following code might help : https://github.com/PrefectHQ/prefect/blob/master/src/prefect/client/client.py#L903

## Environment

My settings is the following:
* I'm running a remote server
* From my dev machine, the following is configured :
```shell
$ cat ~/.prefect/config.toml
[server]
host = "http://bench.ovh"
```

```
prefect diagnostics
{
  "config_overrides": {
    "context": {
      "secrets": false
    },
    "server": {
      "host": true
    }
  },
  "env_vars": [],
  "system_information": {
    "platform": "Linux-3.10.0-862.el7.x86_64-x86_64-with-glibc2.17",
    "prefect_backend": "server",
    "prefect_version": "0.14.6",
    "python_version": "3.9.1"
  }
}
```

**Comment by joshmeek** [comment]
Hi @steph-ben the reason why the server URL isn't being picked up is due to handling the case where users host the apollo endpoint at a different place compared to the UI. It is a common practice to expose the server's graphql API behind one host and then make the UI accessible via another. To explicitly tell prefect where your server UI is hosted you can either set 

```
[server]
  [server.ui]
  endpoint = "..."
```

in your `~/.prefect/config.toml` or via the env var `PREFECT__SERVER__UI__ENDPOINT=...`.
