### ISSUE TITLE
Opt-out of task Result

### ISSUE THREAD

**Issue by novotl** [PrefectHQ/prefect#4215]
## Description
We're using Result on flow level, so all tasks output get persisted. However, we have a task that is easy to compute, but the Result mechanism adds significant overhead. For such a task, we would like to opt-out and don't store the Result. This works until something fails and flow needs to be restarted.

Based on docs
> Checkpointing will automatically be turned on; you can disable it by passing checkpoint=False to each task you want to turn it off for ([source](https://docs.prefect.io/core/advanced_tutorials/using-results.html#setting-up-to-handle-results))

## Expected Behavior
In the example below, I have flow-level result and a chain of tasks: `a -> b(checkpoint=False) -> c`. If the task `c` fails and I restart the flow, I expect:
- load Result of `a` and run  `b -> c`, because I didn't want to persist the result of `b`

Instead I get:
- re-run only `c` with `None` as the input

## Reproduction
```
import os
import random
from typing import List

import prefect
from prefect import task, Flow, Parameter
from prefect.engine.results import LocalResult

result_directory = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "results")
)

result = LocalResult(
    dir=result_directory,
    location="{flow_name}/"
    "{scheduled_start_time:%d-%m_%H-%M-%S}/"
    "{task_full_name}-{task_run_id}.prefect_result",
)


@task
def init() -> List[int]:
    return [1, 2, 3]


@task(checkpoint=False)
def cheap_compute_costly_upload(nums: List[int]) -> List[int]:
    return [num + 1 for num in nums]


@task
def fragile_task(nums: List[int], error_probability: float) -> None:
    if random.random() < error_probability:
        raise ValueError('I\'m fragile, just retry me')
    prefect.context.logger.info('Input is %s', nums)


with Flow('test', result=result) as flow:
    error_prob = Parameter('error_probability', default=0.7)

    a = init()
    b = cheap_compute_costly_upload(a)
    fragile_task(b, error_probability=error_prob)

if __name__ == '__main__':
    flow.register(project_name='default')
```

With this issue https://github.com/PrefectHQ/prefect/issues/3926 in mind, I was able to achieve what I want using SecretBase, but it's hackish.
```
# mark the problematic output as secret, so it will get re-run
class CheapComputeCostlyUpload(SecretBase):
    def run(self, nums: List[int]) -> List[int]:
        return [num + 1 for num in nums]

...

# slightly different call with class instead of @task
b = CheapComputeCostlyUpload()(a)
```

**Comment by cicdw** [comment]
Hi @novotl - this makes sense to me; I see two paths forward:

- we are currently working on a small feature that will allow you to attach such "helper functions" (e.g., `cheap_compute_costly_upload`) to the edges between tasks so that they aren't treated as tasks and don't get in the way of orchestration; this seems like a great use case for the new API
- alternatively, you might consider reworking the [Secret Result](https://github.com/PrefectHQ/prefect/blob/master/src/prefect/engine/results/secret_result.py) class to your needs.  I think the only thing you'll need to consider is how to get the right kwargs to the run method - currently they are hardcoded [here](https://github.com/PrefectHQ/prefect/blob/master/src/prefect/engine/results/secret_result.py#L38)

**Comment by cicdw** [comment]
Result persistence is now configurable in 2.0 (see https://docs.prefect.io/concepts/results)
