### ISSUE TITLE
Wrong port is reported for flow URL after changing it w/ --ui-port

### ISSUE THREAD

**Issue by brizzbane** [PrefectHQ/prefect#4249]
## Description

(FYI complete newb).

When running the prefect server  with a different UI port:prefect server start:

 `--use-volume --ui-port 8888` 

unning a Python task script will tell you the original 8080 port, i.e.:

```
Result check: OK
Flow URL: http://localhost:8080/default/flow/b4a451fb-2905-4d80-bba9-cfc9f797b5db
 └── ID: 3ff5c165-beca-4307-a965-b03382916785
 └── Project: tutorial
 └── Labels: ['mydomain.com']
```

## Expected Behavior

That the "Flow URL" would have the same url defined by --ui-port

## Reproduction

 Start the server with a different port using --ui-port.  Run any flow to register it.  The link reported will have original :8080 port.

**Comment by madkinsz** [comment]
Hi @brizzbane, that url is generated by your local code not the server so it doesn't actually know where the UI is hosted, it's just inferring it from your config. Since you passed `--ui-port` via the CLI instead of the config, you'll need to tell your local code about the UI port change as well.

The relevant config chunk is
```
    [server.ui]
    host = "http://localhost"
    port = "8080"
    host_port = "8080"
    endpoint = "${server.ui.host}:${server.ui.port}"
```

You'll want to set `server.ui.port` to `8888` so your `prefect` core library can generate a correct link :)
