### ISSUE TITLE
Docker Storage: Copy relative files 

### ISSUE THREAD

**Issue by kstadler** [PrefectHQ/prefect#4306]
## Current behavior
https://github.com/PrefectHQ/prefect/issues/453 allows for copying files using absolute paths

## Proposed behavior
Also allow copying using paths relative to script that is instanciating Docker storage

## Example
```
    files={
        # path source -> absolute destination in image
        "/Users/me/code/mod1.py": "/modules/mod1.py",  # current behaviour
        "../mod2.py": "/modules/mod2.py",  # also possible with new behaviour
    },
```

**Comment by madkinsz** [comment]
@kstadler -- is there a reason you don't want to just use `os.path.join` and `os.getcwd()` here?

**Comment by kstadler** [comment]
Just to keep the code DRY.. though in the meantime it seems we'll probably not use Docker Storage

**Comment by madkinsz** [comment]
I think this is tricky because a lot of users define their storage outside of the Flow definition or register their flows via the CLI and it could easily become unclear where the root directory is. I'm not sure it's worth the possible confusion. If you want to limit repetition you can definitely write a function that parses a dict and generates absolute paths in just a couple lines. I'm going to close this for now unless we get more requests.
