### ISSUE TITLE
Add support to Storages to pull whole repo

### ISSUE THREAD

**Issue by xyxz-web** [PrefectHQ/prefect#4328]
## Current behavior
If I'm not mistaken, currently only the flow file specified in the path attribute of GitHubStorage, GitLabStorage and similar is pulled.

## Proposed behavior
It would be great if there was an option to either pull the whole repo or at least certain directories, as an option for storing dependencies that are shared among different flows.

## Example
```
 GitHub(
        repo="my/repo",
        access_token_secret="GITHUB_ACCESS_TOKEN",
        path=source_path,
        pull_whole_repo=True,
    )
```

**Comment by willianchan** [comment]
Same problem here, it would help a lot to be able to pull the entire repository

**Comment by kst83** [comment]
Just wondering... since this ticket has been assigned, does it mean it is already being worked on?

**Comment by madkinsz** [comment]
@kst83 we're looking at the feasibility of implementing this across our git storage options, the issue will be updated once we have more news.

**Comment by sm-Fifteen** [comment]
One can currently use `Module` storage for that [to have the shared dependencies be recognized](https://github.com/PrefectHQ/prefect/issues/4233), though with the additional caveat that repo syncing has to be done by hand. If multiple flows are contained within the same module, and they're all running in the same working directory, this could get a bit race-y.

Syncing full repos instead of individual files could probably be done with a generic `GitModule` storage backend using something like libgit2 (`dulwich`, `pygit2`, etc.) instead of APIs specific to Bitbucket, Github, Gitlab, and so on. If individual flows and flow versions are tied to specific git commits ( instead of assuming that the latest registered flow version always matches the HEAD of the tracked branch), this might require a bit of extra magic to ensure flows can run on separate copies of the checked out files.

**Comment by madkinsz** [comment]
> Syncing full repos instead of individual files could probably be done with a generic `GitModule` storage backend using something like libgit2 (`dulwich`, `pygit2`, etc.) instead of APIs specific to Bitbucket, Github, Gitlab, and so on. If individual flows and flow versions are tied to specific git commits ( instead of assuming that the latest registered flow version always matches the HEAD of the tracked branch), this might require a bit of extra magic to ensure flows can run on separate copies of the checked out files.

This is an interesting idea. Perhaps we could have a common base class but I'd be a bit concerned about supporting the various authentication patterns with a single implementation.

**Comment by sm-Fifteen** [comment]
> This is an interesting idea. Perhaps we could have a common base class but I'd be a bit concerned about supporting the various authentication patterns with a single implementation.

Wouldn't [the standard fetching methods like `git+https` and `git+ssh`](https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols) be enough? Flow storage is read-only and, from my understanding, the main reason why `BitBucket` storage and the like use specific APIs is to allow fetching individual files rather than pulling the full repo for a single flow.

**Comment by madkinsz** [comment]
That makes sense! I think `GitRepo` would make more sense than `GitModule` since we're not going to do any python module inference, otherwise that's a great suggestion. We'd be happy to take a look at a proof-of-concept PR for this, otherwise we'll get to it when we can!

**Comment by zangell44** [comment]
I'll try to get a proof of concept PR out later this week unless someone else is particularly keen to take it. on

**Comment by sm-Fifteen** [comment]
> 
> 
> That makes sense! I think `GitRepo` would make more sense than `GitModule` since we're not going to do any python module inference, otherwise that's a great suggestion. We'd be happy to take a look at a proof-of-concept PR for this, otherwise we'll get to it when we can!

Well, being able to treat the Git repo as a module or as a collection of modules is kind of important for the issue at hand, since it's about storing flows with a number of shared dependencies, something that won't work if there's no way to identify a subset of that repo as an importable python module (so that dependencies stored within that module can [either be imported as `import example_project.tasks.math` or as `import ..tasks.math`](https://github.com/madkinsz/prefect-flow-register)).

**Comment by madkinsz** [comment]
I don't think we should complicate this with Python modules to start. The most common use-case we've seen is a desire to have a config file or something pulled alongside your flow. Implementing some sort of module loading comes with a lot of questions
- Do we pip install your module?
- Do we just add it to the Python path?
- How are you telling us where your flows are?
- How are you telling us where your modules are?

The example you've linked to is out of date and my recommendation now would actually be to use a file-based flow storage (ie `GitHub`) with a `DockerRun` where you've built an image containing your shared dependencies.

Once we implement a basic version of this that makes your entire repository available, we can consider the more complex case of installing Python modules.

**Comment by kst83** [comment]
Personally my use case would actually be using python module dependencies.

Some thoughts about this:
Docker Images are great for pre-installing pip dependencies (which could be how to handele them here too), but for local code dependencies I'd prefer to always use the same version as in the git repo.
Telling the position of the flow could be done the same way as with the current GitHub/GitLab Storages using a parameter. 
For modules a parameter telling the root path of the modules could be used, defaulting to the root directory.
I'm sure I overlooked some things, just my 2 cents.

**Comment by xyzy-web** [comment]
I see there is work in progress at #4418 now.
However the scope there does not include module support, which was the original intention of this issue.
Should I open a separate issue for a Git Storage with module support?

**Comment by madkinsz** [comment]
I'll either leave this issue open or open a new one with a clearer scope. Installing your code from Python modules in a git repo and ensuring it is available in a distributed environment is far more complicated to address than making the entire repo available at flow load, we'll continue to look for a good way to do that.

**Comment by jcrist** [comment]
I'm going to close this now and reopen a smaller scoped issue on the remaining bit about installing a module in the repo.

**Comment by jcrist** [comment]
See #4574.
