### ISSUE TITLE
S3Upload Task not detecting AWS credentials loaded with dotenv

### ISSUE THREAD

**Issue by kst83** [PrefectHQ/prefect#4331]
## Description
On my local computer when you run a flow's .py file directly for debugging purposes with flow.run(), then S3Upload Task doesn't seem to use the PREFECT__CONTEXT__SECRETS__AWS_CREDENTIALS variable normally used for providing credentials.
S3Download is probably the same, though I didn't test it.
The error I get is: botocore.exceptions.NoCredentialsError: Unable to locate credentials

## Expected Behavior
The secret loaded with dotenv should be detected

Optionally run `prefect diagnostics` from the command line and paste the information here. -->

**Comment by kst83** [comment]
The same flow runs perfectly fine if I register it and run it through the GUI with local agent.

**Comment by kst83** [comment]
I've narrowed this down:
If you run load_dotenv() before the import of prefect, everything works just fine.
Maybe the solution would be an env_vars parameter for flow.run to explicitly pass the env_vars like with the agents?

**Comment by madkinsz** [comment]
Hey @kst83 -- The Prefect Context is loaded at module load time so it makes sense that modifying the environment after that's happened would not include the new items in the context. @zach-angell @cicdw perhaps we should be reloading context environment variables at flow runtime?

**Comment by cicdw** [comment]
Can you clarify what you mean @madkinsz ?  The current behavior is standard -- when a flow run is kicked off by any agent, it will load context based on the current OS env vars.  I don't think we should allow for post-load env-vars, as it has too much potential to create anti-patterns with more complicated bugs.

**Comment by madkinsz** [comment]
@kst83 -- I think Chris is right that this is a typical behavior and we should probably keep the config loading limited to a single time. I think a better pattern for a local run like this would be to call `load_dotenv()` wherever you like and then update the context using the context manager e.g.

```python
with prefect.context(foo=os.environ["FOO"], bar=os.environ.get("bar", "default")):
    flow.run()
```

**Comment by kst83** [comment]
@madkinsz:
This would mean it would be necessary to repeat the variable names in every flow where S3Upload is used - IMHO a bad not DRY coding style.

How about supporting the following?:

```flow.run(env_vars=load_dotenv())```

This would be similar to the way that environment vars can be passed to Agents.

**Comment by madkinsz** [comment]
It doesn't really make sense to pass environment variables here, that's what the context is for. You can still do that without repeating variable names

```python
import prefect
from prefect import Flow, task


def fake_load_env():
    return dict(X=1, Y=2)


@task
def foo():
    print(prefect.context.get("X"), prefect.context.get("Y"))


with Flow("context-local-flow-run") as flow:
    foo()


flow.run(context=fake_load_env())
```

**Comment by kst83** [comment]
That's close to what I want, but it doesn't seem to interpret environment variables the same way as running load_dotenv() before importing prefect or passing env_vars to an agent.
E.g. for defining AWS Credentials for S3 Upload you normally set the variable `PREFECT__CONTEXT__SECRETS__AWS_CREDENTIALS`.
However, this doesn't work with above code.
Is there a way to achieve this behavior?

**Comment by madkinsz** [comment]
Here's another blurb 

```python
import prefect
from prefect import Flow, task



def fake_load_env():
    return dict(secrets={"AWS_CREDENTIAL": "foo"}, Y=2)


@task
def foo():
    print(prefect.context.secrets)


with Flow("context-local-flow-run") as flow:
    foo()


flow.run(context=fake_load_env())


# or something like


def fake_load_env():
    return {"PREFECT__CONTEXT__SECRETS__AWS_CREDENTIAL": "foo", "PREFECT__CONTEXT__FOO": "bar"}

def parse_env(env_dict):
    parsed = {"secrets": {}}
    for key, val in env_dict.items():
        if key.startswith("PREFECT__CONTEXT__SECRETS__"):
            new_key = key[len("PREFECT__CONTEXT__SECRETS__"):]
            parsed["secrets"][new_key] = val
        if key.startswith("PREFECT__CONTEXT__"):
            new_key = key[len("PREFECT__CONTEXT__"):]
            parsed[new_key] = val
    return parsed


flow.run(context=parse_env(fake_load_env()))
```

At this point though, you really just ought to be loading your dotenv before importing `prefect`. It's reasonable for us to parse environment variables into the config once at module load.

**Comment by kst83** [comment]
Ok, so there is no clean solution...
For now I've opened an issue at python-dotenv suggesting the introduction of an auto_load_env module.
Let's see what the maintainers think about that...

**Comment by dpmccabe** [comment]
I think this issue is more general (and problematic) than initially described. For instance, here's a bug with agents that has nothing to do with flows. If you have `PREFECT__CLOUD__AGENT__AUTH_TOKEN` set in `.env`, this works:

```py
from dotenv import load_dotenv

load_dotenv()

from prefect.agent.docker import DockerAgent

agent = DockerAgent()
agent.start()
```

A more standard approach with all the imports at the top does not:

```py
from dotenv import load_dotenv
from prefect.agent.docker import DockerAgent

load_dotenv()

print(os.getenv("PREFECT__CLOUD__AGENT__AUTH_TOKEN"))  # token is printed as expected
agent = DockerAgent()
agent.start()  # prefect.utilities.exceptions.AuthorizationError: No agent API token provided
```

I'm not aware of another library that works this way. For instance, you can import `boto3` before running `load_dotenv()` and AWS clients discover the newly-loaded credentials at runtime.

In general, I don't think that importing a module should mutate anything. If there's configuration required for something exported from that module, those config values should either be accessible via class/method arguments or there should be a dedicated method to load the config from the current environment.

Maybe this issue could be reopened?

**Comment by cicdw** [comment]
Hi @dpmccabe, on 
> In general, I don't think that importing a module should mutate anything

I agree, which is actually why the module currently works the way it does today.  Prefect configuration is loaded from the OS environment whenever the Prefect package is first imported (note: nothing is mutated) and not changed afterwards.  This configuration is determined via a naming convention on OS environment variables.  The suggestion here is that Prefect configuration _should be mutated_ by a call to a third party library, which itself is presumably is mutating values in `os.environ` (note: setting values here does not affect the currently running process).  

`boto3` and other packages pick up these changes because they load specific variables directly from the `os.environ` Python object, whereas a package like Prefect loads the OS environment into a custom configuration object for easier access (also, in many cases we don't a-priori know what keys we're looking for).  For another example and related discussion, check out [this SO discussion](https://stackoverflow.com/a/1186194).

Even if we were to add a `refresh` method that reloads configuration from the OS, certain changes would not take affect (logging configuration, values in context, etc.) so I wouldn't rush to this.

**Comment by dpmccabe** [comment]
Thanks for the explanation. I'm not sure the comparison to what dotenv does is entirely accurate, though. As far as I know, merely _importing_ from `dotenv` doesn't do anything; it's _calling_ `load_dotenv()` that injects variables into `os.environ`. I still can't think of another Python library where importing code from it does anything but make that code available to your script.

Generally speaking, ENV variables aren't the only way or necessarily the best way to set configuration. For instance, I generally prefer using a dedicated secrets storage mechanism like the AWS SSM Parameter Store. In those projects, the only secrets in the environment are AWS credentials and everything else gets pulled from SSM. There are a lot of benefits to this kind of setup, but I won't get into those right now.

I think it's fine that Prefect allows you to use specially-named ENV variables for things like the API token. boto3 does the same thing with AWS credentials of course, but you can also pass your own secrets to boto3 methods if you want. So rather than providing a `refresh` method, I'd actually prefer that nothing be configured at all until you run some `init_prefect` method. Ideally, that method would expose options to set up your environment with explicit values in addition to allowing them to be discovered automatically through your environment. It makes the code clearer, less "magical", and more in line with the goals of reproducible science.
