### ISSUE TITLE
ECS Agent: Bring back enable_task_revisions 

### ISSUE THREAD

**Issue by potter420** [PrefectHQ/prefect#4357]
## Current behavior
In the old day, FargateAgent have `enable_task_revisions` to make each version of a flow a task definitions. Right now this behavior was not implemented in the ECS agent.

## Proposed behavior
ECSAgent should also have enable_task_revisions as the deprecated FargateAgent has.

## Example
This would be very useful for audit guys to not be bombarded with thousand of task definitions.

**Comment by madkinsz** [comment]
Ah sorry @potter420 -- Github got weird and I didn't see you'd linked a PR. I'll review that instead.

**Comment by madkinsz** [comment]
Hey @potter420 -- I've checked in with the team and I do not think this is something we can support. Now that we've made it so run configs can be modified per flow run, the previous technique used in the `FargateAgent` actually won't work since any run can invalidate the cache. To avoid registering so many task definitions, I'd recommend pre-registering task definitions as needed, and specify a `task_definition_arn` on the flow instead. In this configuration, the agent will never register a new task definition.

**Comment by potter420** [comment]
Agree with you, I have just looked at the new ECS run since we are migrating from 0.13, we can now specify custom task definition per run, that will certainly cause various problems, like hash checking the task and everything. I think we will write a function that produce sensible default task definition for flow run instead and have prefect agent register for us first run then fixed that version for the next until we deploy a new version of the flow. Me unable to create anything since it a managed account.

Thank you. Will also amend my pull request to undo the changes related to this.

**Comment by madkinsz** [comment]
Glad that it makes sense to you! Thanks for taking the time to work through it :)
