### ISSUE TITLE
Ensure Task Library Tasks can be completely configured from the `run` method

### ISSUE THREAD

**Issue by dylanbhughes** [PrefectHQ/prefect#4377]
## Current behavior

Some tasks in the Task Library require a user to provide certain pieces of configuration as part of the initialization method. Whenever we can, we should try to avoid this because it means that those variables are locked it at the time the Flow is built, instead of at runtime, which prevents the use of Parameters or Secrets to configure the task.

## Proposed behavior

Let's audit our Task library and ensure that these types of arguments can be provided at either initialization or at runtime whenever possible.

## Example

Our [MySQL Task](https://github.com/PrefectHQ/prefect/blob/master/src/prefect/tasks/mysql/mysql.py#L9) is one example. Even though the Task initializes the MySQL connector as part of the `run` method, the `hostname` must be provided at initialization.

**Comment by RajdeepRao** [comment]
Hey @dylanbhughes I'm new around here, but would love to contribute to prefect! I don't quite know the best way to claim this, but leaving a comment here for now?

**Comment by dylanbhughes** [comment]
Welcome, @RajdeepRao! Go ahead and assign this to yourself 💯 

If you have any questions, [join us in Slack ](https://www.prefect.io/slack) in the #prefect-contributors channel 😄

**Comment by StefanBRas** [comment]
In the general case, should eveything that can go in `run` always go in `run` or does it make sense to have some variables be configured in either `init` or `run`?

I have some cases where a task has variables that are almost always static, but they could also be assigned at run time if needed.

You might want to run this task several times in a flow, so it can save you from giving the same inputs several times. Kind of like using `partial` from `functool` to fix some variables.

Example:
```python
from prefect import Task, Flow

class DoSomething(Task): 
    def __init__(self, some_variable = None, **kwargs): 
        self.some_variable = some_variable 
        super().__init__(**kwargs) 
    def run(self, some_variable=None): 
        run_time_variable = some_variable or self.some_variable 
        return run_time_variable
        
with Flow('test') as flow: 
    init_task = DoSomething(some_variable='init') 
    run_task = DoSomething() 
    init_task() 
    run_task(some_variable='run')
```

**Comment by dylanbhughes** [comment]
@StefanBRas the advantage of having them in `run` is that they're configurable at runtime by `Parameters` or `Secrets`, which aren't available at initialization time. In general, I try to put all args in both `init` and `run` whenever possible to give users the option

**Comment by Tostino** [comment]
Just wanted to mention that this is a blocker for me for me actually using Prefect to do work at this point.  My flows all need to configure runtime parameters for...pretty much all of this due to the nature of the stack I am integrating into.

So at this point i'm pausing my work I was doing to migrate much into prefect tasks, and just using Prefect as a calling wrapper for my existing ETL processes until there is some general solution here.

**Comment by madkinsz** [comment]
@Tostino -- The solution will just be an effort by the community (and internally) to duplicate all of those options for the built-in tasks. For your own tasks, you can just use the `@task` decorator (which does not define class level options) or just skip defining an `__init__` for class based tasks and define everything you care about in the `run` method since you don't need any shared static configuration.

**Comment by Tostino** [comment]
@madkinsz Totally understand for my tasks it's not an issue. It's the built in ones that I want to use that are giving me grief. And @kvnkho helped me out in Slack explaining this issue was a thing (thought I was just doing something wrong at first), and with a "fixed" version of the PostgresExecute so I can at least use that for now. I just wanted to mention that for my workload, runtime is the only time i'm going to know some of this stuff. Having these tasks be inconsistent as to what is supported at init vs runtime will just mean I need to pay attention to what tasks are actually available to me (now that I know about this issue) without having to modify them in the meantime. 

Thanks for everything!

**Comment by tchoedak** [comment]
@madkinsz is this task a good example to follow? https://github.com/PrefectHQ/prefect/blob/master/src/prefect/tasks/azure/cosmosdb.py#L10. And does this require us making sure that __init__ doesn't use positional arguments, only keyword arguments?
