### ISSUE TITLE
Add Helm support for Kubernetes Agent 

### ISSUE THREAD

**Issue by zhodowanec** [PrefectHQ/prefect#4406]
## Current behavior
Kubernetes agent requires CLI deployment

## Proposed behavior
Ability to deploy Kubernetes Agent via Helm chart

## Example
Add ability for `helm upgrade -i agent -n prefect-local prefecthq/prefect-agent` to deploy Prefect Kubernetes Agent

**Comment by mashun4ek** [comment]
Hello @zhodowanec! Are you using Prefect Cloud or Prefect Server? If you're using Prefect Server [helm chart](https://github.com/PrefectHQ/server/tree/master/helm/prefect-server). On [this line](https://github.com/PrefectHQ/server/blob/1f1386c0cbe9f5d94389bcd9977775c35373b1a8/helm/prefect-server/values.yaml#L322) you can enable the agent, which will create an agent `deployment`.

**Comment by zhodowanec** [comment]
@mashun4ek I am currently using Prefect Cloud. Is there a standalone version of just the agent, and dependent resources, that gets packaged up into a helm chart?

**Comment by madkinsz** [comment]
Hey @zhodowanec -- we don't publish a separate chart for the agent right now. You may be able to disable all of the Prefect Server components and use that chart but I think the best solution may be to just pull the agent template out of the Server helm chart yourself (it's a good bit of work to set up chart publishing on our end) and install from the local directory.

**Comment by SailingYYC** [comment]
Actually Helm Repos (v1) are one of the simplest forms of feeds, any static file serving service can serve it.

Here's a great [GitHub Action](https://github.com/helm/chart-releaser-action) that will do it all for you, hosting the Helm Repo right inside of the GitHub Pages on the Repo, super cool!

Here's what a repo that uses it looks like:
- https://github.com/kyverno/kyverno/tree/main/charts/kyverno
- Adding the Helm repo is as easy as: `helm repo add kyverno https://kyverno.github.io/kyverno/`
- And it tracks the version history as shown in the Helm repo's index: https://kyverno.github.io/kyverno/index.yaml

**Comment by madkinsz** [comment]
Hey @SailingYYC -- I'm very familiar with both that action and helm chart publishing (https://github.com/PrefectHQ/server/pull/209). The complexity here is that we already have chart publishing in the `server` repository and as a team with high technical standards we'd likely want to consolidate the publishing so people don't have to add multiple Helm repositories. This is something we'd have to discuss internally in order to design a polished experience for our users. Most of the code for this already exists and you are welcome to host a personal copy of the agent Helm chart in the meantime.

**Comment by zhodowanec** [comment]
Adding related issue: https://github.com/PrefectHQ/prefect/issues/4525

**Comment by madkinsz** [comment]
This is available at `PrefectHQ/prefect-helm`.
