### ISSUE TITLE
Install infinite loop with aws "extra"

### ISSUE THREAD

**Issue by 1sttec** [PrefectHQ/prefect#4906]
### Discussed in https://github.com/PrefectHQ/prefect/discussions/4905

<div type='discussions-op-text'>

<sup>Originally posted by **1sttec** August 24, 2021</sup>
    python -m pip install prefect[all_extras]
  
or any combination of extras that includes 'aws' hangs on infinite loop with repeating msg:
  
>  "WARNING: dask-cloudprovider X.X.X does not provide the extra 'aws'"
  
- Windows Server 2012 R2
- Python 3.7.1
- Pip 21.2.4
  
Please advise.</div>

**Comment by madkinsz** [comment]
Hi, we pin `pip` to an older version in our CI `pip install "pip==20.2.4"` because the new resolver does not always terminate and tends to have issues with our extras. See https://github.com/pypa/pip/issues/9187

Also note the `aws` extra is different than the `dask_cloudprovider` extra which includes an install of _its_ aws extra. See https://github.com/PrefectHQ/prefect/blob/master/setup.py#L54

The `dask_cloudprovider[aws]` does seem to provided by that package as well still, perhaps it is attempting to install a very old version? https://cloudprovider.dask.org/en/latest/installation.html

**Comment by madkinsz** [comment]
See also https://github.com/PrefectHQ/prefect/issues/3144
