### ISSUE TITLE
Docs expose non-public API

### ISSUE THREAD

**Issue by dsaxton** [PrefectHQ/prefect#4994]
It would seem the docs are exposing an API that isn't meant to be public, e.g.: https://docs.prefect.io/api/latest/client/client.html#client-2. Here `Client` is documented as belonging to `prefect.client.client`, which is of course true, but it's also re-exported at `prefect.client`, presumably so that it would be imported this way by end users.

Is there a way around this, or is it just a necessary result of how the docs are built?

**Comment by kvnkho** [comment]
I think this is an artifact of how the API docs are built and can't be really changed. What we can do though is make the effort to ensure that the non-API docs have the simplified import if ever there are places with the longer import.

I don't really see any immediate action to take so I will close this issue for now, but do feel free to re-open if you feel otherwise.
