### ISSUE TITLE
Docs for flow of flows reference `StartFlowRun` instead of newer `create_flow_run` task

### ISSUE THREAD

**Issue by zangell44** [PrefectHQ/prefect#5092]
These docs should be updated https://docs.prefect.io/core/idioms/flow-to-flow.html

**Comment by madkinsz** [comment]
Leaving this issue open following #5095 so we can:
- Add actual flows to register instead of just saying to have "A", "B", etc. registered already
- Add `get_task_run_result` examples
- Add parameter passing

https://github.com/PrefectHQ/prefect/blob/master/src/prefect/tasks/prefect/flow_run.py#L5-L40 could be extended for this purpose
