### ISSUE TITLE
Modify the `ECSRun` or adjust the docs to match the current behavior with custom task definitions and roles

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#5110]
## Description
The description of ECSRun doesn't entirely match the current behavior or is at least confusing.

## Expected Behavior
- task_role_arn="arn:aws:iam::XXX:role/prefectTaskRole" works, but task_role_arn="prefectTaskRole" doesn't even though according to the docstring [here](https://docs.prefect.io/api/latest/run_configs.html#ecsrun) the name should suffice - QA this and adjust either the ECSRun code or documentation
- validate in what cases the defaults from the agents apply and when specific arguments must be passed explicitly, e.g. when using a custom ECR image, both full `task_role_arn` and `execution_role_ern` must be provided, regardless of what is configured on the agent
- validate (and adjust the docs if needed), what happens when providing both, a full task definition, and trying to override a task role from that definition on `task_role_arn` kwarg - does it use the one from the task_definition or the one provided in the`task_role_arn` kwarg?

**Comment by will-ockmore** [comment]
Thanks @anna-geller ; please see the [discussion thread](https://prefect-community.slack.com/archives/CL09KU1K7/p1635883735350600) on the community slack for background.

### `task_role_arn` and `execution_role_arn`

The description for task_role_arn is not correct:

> task_role_arn (str, optional): The name or full ARN for the IAM role to use for this task. If not provided, the default on the agent will be used (if configured). 

Only the full ARN will work here.

I haven't checked the behaviour of `execution_role_arn` but according to the [AWS documentation](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_TaskOverride.html) for the ECS `RunTask` overrides, it should function in the same way as the `task_role_arn` override (eg., it should require a full ARN). So the docs should be updated here as well.

### Custom Task Definitions and IAM Roles

The expected behaviour when defining a custom task definition would be for the execution role and task role provided in the definition to be used when running the task for a flow. The actual behaviour is:

1. If none of `task_definition`, `task_definition_path`,  `task_definition_arn`, `task_role_arn` or `execution_role_arn` are provided, both the task definition and the execution and task roles are taken from the task definition defined for the agent.
2. If any of `task_definition`, `task_definition_path` or `task_definition_arn` are provided, the new task definition is used, but the roles are _still overridden_ with those defined on the task definition for the agent.
3. Only when explicitly providing a role to `task_role_arn` can you define permissions on a per-flow basis.

This can be seen here: https://github.com/PrefectHQ/prefect/blob/e699fce534f77106e52dda1f0f0b23a3f8bcdf81/src/prefect/agent/ecs/agent.py#L454-L464

This behaviour is unintuitive, and would make more sense if it functioned in the same way as cpu / memory parameter handling https://github.com/PrefectHQ/prefect/blob/e699fce534f77106e52dda1f0f0b23a3f8bcdf81/src/prefect/agent/ecs/agent.py#L466-L475

If implemented, this should be behind a flag on the `ECSRun` config, to avoid breaking backwards compatibility.

**Comment by anna-geller** [comment]
All below observations are based on Prefect 0.15.7 using `ECSRun` run configuration with `S3` storage, and ECS agent deployed in-cluster as ECS service as described in [this post](https://towardsdatascience.com/how-to-cut-your-aws-ecs-costs-with-fargate-spot-and-prefect-1a1ba5d2e2df).

## 1. Referencing task role by name vs. by ARN

Referencing task role by IAM role name (as shown below) doesn't work, but it works when providing a full task role ARN → TODO: adjust the docs.

```python
RUN_CONFIG = ECSRun(
    labels=["prod"],
    task_role_arn="prefectTaskRole",
    run_task_kwargs=dict(cluster="prefectEcsCluster")
)
```

Referencing IAM role by name returns an error: `An error occurred (ClientException) when calling the RunTask operation: Role is not valid`

Referencing a full task role ARN works as expected:

```python
RUN_CONFIG = ECSRun(
    labels=["prod"],
    task_role_arn="arn:aws:iam::XXXX:role/prefectTaskRole",
    run_task_kwargs=dict(cluster="prefectEcsCluster")
)
```

## 2. Referencing a pre-registered task definition

Using this task definition: `prefect_flow_task_definition.json`

```python
{
  "family": "prefectFlow",
  "requiresCompatibilities": [
    "FARGATE"
  ],
  "networkMode": "awsvpc",
  "cpu": "512",
  "memory": "1024",
  "taskRoleArn": "arn:aws:iam::XXXX:role/prefectTaskRole",
  "executionRoleArn": "arn:aws:iam::XXXX:role/prefectECSAgentTaskExecutionRole",
  "containerDefinitions": [
    {
      "name": "flow",
      "image": "XXXX.dkr.ecr.us-east-1.amazonaws.com/community:latest",
      "essential": true,
      "environment": [
        {
          "name": "AWS_RETRY_MODE",
          "value": "adaptive"
        },
        {
          "name": "AWS_MAX_ATTEMPTS",
          "value": "10"
        }
      ],
      "logConfiguration": {
        "logDriver": "awslogs",
        "options": {
          "awslogs-group": "/ecs/prefectEcsAgent",
          "awslogs-region": "us-east-1",
          "awslogs-stream-prefix": "ecs",
          "awslogs-create-group": "true"
        }
      }
    }
  ]
}
```

and this command to register it:

```python
aws ecs register-task-definition --cli-input-json file://prefect_flow_task_definition.json
```

User can then reference only the `family:revision` rather than a full ARN:

```python
RUN_CONFIG = ECSRun(
    labels=["prod"],
    task_definition_arn="prefectFlow:1",
# same effect as when providing a full ARN: task_definition_arn="arn:aws:ecs:us-east-1:XXX:task-definition/prefectFlow:1",
    run_task_kwargs=dict(cluster="prefectEcsCluster"),
)
```

This works without providing any roles and without disclosing the AWS ACCOUNT ID in the ARN (@will-ockmore  this may be something for your use case?).

## 3. Referencing a task definition from a path

If we don't want to pre-register the task definition ourselves, we can pass only the path to the task definition (the same definition as above, but uploaded to S3):

```python
RUN_CONFIG = ECSRun(
    labels=["prod"],
    task_definition_path="s3://prefectdata/prefect_flow_task_definition.json",
    run_task_kwargs=dict(cluster="prefectEcsCluster"),
)
```

However, if we try to reference a local path, it doesn't work. The only way possible to find a local path to this task definition would be if this JSON file were baked into the agent's image and we would reference a path on a container (not even 100% sure if this would work). → TODO: adjust the docs that this should be S3 path, not a local one.

```python
RUN_CONFIG = ECSRun(
    labels=["prod"],
    task_definition_path="/Users/anna/ecs/prefect_flow_task_definition.json",
    run_task_kwargs=dict(cluster="prefectEcsCluster"),
)
```

```python
└── 13:26:09 | INFO    | Downloading flow from s3://prefect-datasets/flows/ecs_local_td_path.py
└── 13:26:10 | INFO    | Flow successfully downloaded. ETag: "494e1457559db520e80bd517b48eab98", LastModified: 2021-11-06T12:25:12+00:00, VersionId: None
└── 13:26:10 | INFO    | Entered state <Failed>: Failed to load and execute Flow's environment: FileNotFoundError(2, 'No such file or directory')
Flow run failed!
```

## 4. Providing a `task_definition_path` AND overriding a `task_role_arn` for the flow

The flow with the run configuration below fails, because the referenced task definition has a task role that doesn't have permissions to S3, preventing Prefect from downloading the flow file from S3.

```python
RUN_CONFIG = ECSRun(
    labels=["prod"],
    task_definition_path="s3://prefectdata/prefect_flow_task_definition_old_task_role.json",
    run_task_kwargs=dict(cluster="prefectEcsCluster"),
)
```

This results in:

```python
└── 20:28:53 | ERROR   | Error downloading Flow from S3: An error occurred (AccessDenied) when calling the GetObject operation: Access Denied
└── 20:28:53 | INFO    | Entered state <Failed>: Failed to load and execute Flow's environment: ClientError('An error occurred (AccessDenied) when calling the GetObject operation: Access Denied')
└── 20:28:53 | ERROR   | Failed to load and execute Flow's environment: ClientError('An error occurred (AccessDenied) when calling the GetObject operation: Access Denied')
```

When we add a `task_role_arn` keyword on top of custom task definition ARN, and this task role has access to S3, then it will work without errors, even though the task role from the original task definition did not have access to S3. This means that overriding `task_role_arn` works on a per-flow run level (*i.e. per ECS Run Task due to custom overrides*) even when using a custom task definition. IMO this is useful behavior that should be kept - e.g. if a user adds a new task to the flow that needs access to some additional AWS service such as DynamoDB, this allows overriding a new task role without having to modify the task definition on S3 or agent and helps maintain the least privilege principle. 

If users want to keep the task role from the original task definition, they have that option, too → if we don't override it, Prefect will take the role from our custom task definition rather than the one from the agent (@will-ockmore  I believe this was your concern).

```python
RUN_CONFIG = ECSRun(
    labels=["prod"],
    task_definition_path="s3://prefectdata/prefect_flow_task_definition_old_task_role.json",
    task_role_arn="arn:aws:iam::XXXX:role/prefectTaskRole", # this flow works well because the "bad" task role was overridden in this line
    run_task_kwargs=dict(cluster="prefectEcsCluster"),
) 
```

## 5. Not passing the `task_role_arn` at all when using `S3` storage

Providing this run configuration that doesn't explicitly specify `task_role_arn` doesn't work. 

```python
RUN_CONFIG = ECSRun(
    labels=["prod"],
    run_task_kwargs=dict(cluster="prefectEcsCluster"),
)
```

The same happens when providing only `execution_role_arn`:

```python
RUN_CONFIG = ECSRun(
    labels=["prod"],
    execution_role_arn="arn:aws:iam::XXXX:role/prefectECSAgentTaskExecutionRole",
    run_task_kwargs=dict(cluster="prefectEcsCluster"),
)
```

According to the current docstring, in this case, Prefect should take the default `task_role_arn` specified on the agent, but this doesn't happen. Instead, it fails with `Failed to load and execute Flow's environment: NoCredentialsError('Unable to locate credentials')`. 

TODO: if possible, change `ECSRun` code to take the `task_role_arn` and `execution_role_arn` from the agent if not specified explicitly, and if not possible, then adjust the docstring to ensure this gets passed explicitly.

Specifying only `task_role_arn` without `execution_role_arn` is fine, as long as we leverage the default Prefect image specified on the agent:

```python
RUN_CONFIG = ECSRun(
    labels=["prod"],
    task_role_arn="arn:aws:iam::XXXX:role/prefectTaskRole",
    run_task_kwargs=dict(cluster="prefectEcsCluster"),
)
```

When users want to provide a custom ECR image (or an image from any private Docker registry, e.g. a private Dockerhub account), then they need to explicitly specify both roles on the `ECSRun`:

- we need to set `execution_role_arn` because this is required to register a new task definition for a flow and to specify permissions to pull the image from ECR. The execution role is responsible for pulling the images → TODO: clarify this in the docs,
- we need to also explicitly specify the `task_role_arn`, because the flow gets downloaded from S3 storage and task role is where ECS expects those permissions  → TODO: clarify this in the docs,
- when using ECR, you only need an IAM role, but with a private external Docker registry, it requires storing the registry auth token as a secret in the Secrets Manager service and then granting access for this secret in the execution role.

```python
RUN_CONFIG = ECSRun(
    labels=["prod"],
    task_role_arn="arn:aws:iam::XXXX:role/prefectTaskRole",
    execution_role_arn="arn:aws:iam::XXXX:role/prefectECSAgentTaskExecutionRole",
    run_task_kwargs=dict(cluster="prefectEcsCluster"),
    image="XXXX.dkr.ecr.us-east-1.amazonaws.com/community:latest"
)
```

## 6. Not passing the `task_role_arn` at all when using `GitHub` storage

Providing this run configuration that doesn't explicitly specify `task_role_arn` will still work when our flow doesn't need access to AWS-specific resources such as S3 or ECR. When using a GitHub storage, the permissions are taken from a Secret, thus no IAM setup is needed. However, if we would need a custom ECR image, then an `execution_role_arn` would be required. 

```python
RUN_CONFIG = ECSRun(
    labels=["prod"],
    run_task_kwargs=dict(cluster="prefectEcsCluster"),
)
```

## 7. Relying on `run_task_kwargs`

Using:

```python
RUN_CONFIG = ECSRun(
    labels=["prod"],
    run_task_kwargs=dict(cluster="prefectEcsCluster", taskDefinition="prefectECSAgent:5"
# same for: taskDefinition="prefectECSAgent" i.e. without revision number
# also same when specifying a full ARN: taskDefinition="arn:aws:ecs:us-east-1:XXXX:task-definition/prefectECSAgent:5"
                         ),
)
```

returns: `run_task() got multiple values for keyword argument 'taskDefinition'`

It seems that in this case, Prefect receives the task definition twice: once the one from the agent is taken on the `task_definition` kwarg, and it receives the task definition kwarg again through the `run_task_kwargs`. Since no task definition is provided explicitly on the `task_definition` kwarg, Prefect is using the one from the agent. And because there are no other overrides, it registers a task definition for the flow based on the agent's task definition. Overriding task definition on `run_task_kwargs` makes therefore no sense. But using `run_task_kwargs` to override runtime task parameters such as the cluster, launch type (i.e. ECS capacity provider), cpu or memory, works as intended. TODO: make the `run_task_kwargs` docs clearer in terms of which values can be overridden this way.

## Conclusion

1. When a user provides a full `task_definition_path` or `task_definition_arn`, this is the only configuration where `task_role_arn` doesn't have to be set when using S3 storage because in that case the role is taken from the task definition the user-provided explicitly. In all other cases, a full task role ARN (not just the IAM role name) must be provided in order for Prefect to be authorized to download the flow file from `S3` storage. 
2. When using `GitHub` storage, no roles need to be set explicitly. 
3. All IAM roles must be provided with a full ARN, not just with the IAM role name.
4. When a custom ECR image is used, it can either be provided:
    1. in a custom task definition (either path or full ARN, as explained in section 1) with a container name "flow":
        
        ```python
        RUN_CONFIG = ECSRun(
            labels=["prod"],
            task_definition_path="s3://prefectdata/prefect_flow_task_definition.json",  # the same JSON file used previously in "Referencing a pre-registered task definition"
            run_task_kwargs=dict(cluster="prefectEcsCluster"),
        )
        ```
        
    2. or set explicitly with `execution_role_arn`:
        
        ```python
        RUN_CONFIG = ECSRun(
            labels=["prod"],
            task_role_arn="arn:aws:iam::XXXX:role/prefectTaskRole",
            execution_role_arn="arn:aws:iam::XXXX:role/prefectECSAgentTaskExecutionRole",
            run_task_kwargs=dict(cluster="prefectEcsCluster"),
            image="XXXX.dkr.ecr.us-east-1.amazonaws.com/community:latest"
        )
        ```
        
5. In no cases examined so far, the task or execution roles are taken from the agent. Perhaps this only happens when using a `default` ECS cluster? 
    1. The only exception to this is when a user explicitly provides the agent's `task_definition_arn` - then the task and execution roles are taken from the agent. But for most users, this will result in a failure because the agent's task definition normally doesn't have a container named "flow" in its definition (rather: agent or prefectEcsAgent). If the container in the agent's task definition would be named "flow" (under `containerDefinitions` → `name` in JSON spec), this would have worked though.
    
    ```python
    RUN_CONFIG = ECSRun(
        labels=["prod"],
        task_definition_arn="prefectECSAgent:5",
        # or full ARN: task_definition_arn="arn:aws:ecs:us-east-1:XXXX:task-definition/prefectECSAgent:5",
        run_task_kwargs=dict(cluster="prefectEcsCluster"),
    )
    ```
    
    ```python
    └── 14:33:30 | ERROR   | An error occurred (InvalidParameterException) when calling the RunTask operation: Override for container named flow is not a container in the TaskDefinition.
    └── 14:33:30 | INFO    | Entered state <Failed>: An error occurred (InvalidParameterException) when calling the RunTask operation: Override for container named flow is not a container in the TaskDefinition.
    Flow run failed!
    ```
    

The priority of arguments is as follows:

- if you provide a custom `task_definition` to your `ECSRun`, then all values including the task role and execution role will be taken from this task definition, not from the agent unless you want to override a specific role - in that case, additional kwargs are used to override values within the provided task definition,
- if you don’t provide a custom task definition, Prefect will create and register a new task definition (or a new revision of it) for you, based on the kwargs you provided to the `ECSRun` such as the `image`, `task_role_arn` and `execution_role_arn`
    - in this case, `task_role_arn` must be provided when using S3 storage, but it's optional when using one of `Git` storage classes
    - similarly, `execution_role_arn` is mandatory when using a custom image from a private container registry
- `run_task_kwargs` should only be used to override runtime task parameters such as the cluster, launch type, CPU or memory rather than task definition's specific arguments. Perhaps we can add in the docs some examples for that as well.

@will-ockmore regarding:

2 "new task definition is used, but the roles are *still overridden* with those provided to the agent." - I couldn't reproduce it. Both Prefect 0.15.6 and 0.15.7 did take the task role and execution role from the provided custom definition unless we would override it by providing a `task_role_arn` on top of the task definition. Can you share how did you start your agent, how does your task definition looks like, and what `ECSRun` configuration did you use in that case?

3 "Only when explicitly providing a role to `task_role_arn` can you define permissions on a per-flow basis." - that's correct when you override the one from the custom task definition, or when you don't provide any task definition and want to e.g. use S3 storage (as described in the long explanation section 5).

**Comment by anna-geller** [comment]
@will-ockmore here is a PR with documentation changes to make it clearer when custom roles should be passed, feel free to chime in if anything is still unclear or if you would like to add something: https://github.com/PrefectHQ/prefect/pull/5124

**Comment by will-ockmore** [comment]
@anna-geller that's a comprehensive investigation, thanks for taking the time to write it out. The suggestion you made here is the one I've gone with in the end.

With

> "new task definition is used, but the roles are still overridden with those provided to the agent."

two things may have been happening:

1. I was previously using the agent's option for default task role, I've since stopped using this option; however from your testing and the code, it would seem this can't have been the problem (although at the time it was the only thing I could think of)
2. I was also at the same time experiencing the issue with the `S3Upload` action, and may have confused myself as to the cause. Once I ran it manually it started working, but I didn't take the time to go back and test my assumptions

The PR looks good to me, and makes the docs much clearer :+1:

**Comment by madkinsz** [comment]
See https://docs.prefect.io/api/latest/run_configs.html#ecsrun for new documentation

**Comment by youcandanch** [comment]
Hi @anna-geller! I'm running into the behaviour @will-ockmore is describing, and I want to make sure I understand something:

> if you provide a custom task_definition to your ECSRun, then all values including the task role and execution role will be taken from this task definition, not from the agent unless you want to override a specific role - in that case, additional kwargs are used to override values within the provided task definition.

So hypothetically, say I start up a Prefect Agent with the following syntax: `prefect agent ecs start --task-role-arn arn:aws:iam::123456791011:role/prefect_task_role`. What I think you're saying is that this acts as a _default_ in the case that a task definition or explicit role aren't passed as part of the RunConfig. If that's the expected behaviour, then I think I see a problem. Granted, I'm really new to the Prefect source, so I want to walk it down to make sure. Here's my understanding of what happens:

When the agent is initialised with the `--task-role-arn` flag via the CLI, a task role ARN gets set on the instantiated ECSAgent object.
https://github.com/PrefectHQ/prefect/blob/e699fce534f77106e52dda1f0f0b23a3f8bcdf81/src/prefect/agent/ecs/agent.py#L172.

When a flow is deployed, and there's a `task_definition_arn` specifically passed to the ECSRun constructor, the task definition as set in the ECSRun is assigned to `taskdef_arn` here: https://github.com/PrefectHQ/prefect/blob/e699fce534f77106e52dda1f0f0b23a3f8bcdf81/src/prefect/agent/ecs/agent.py#L303-L315. 

At this point, I don't see `taskdef_arn` being used again until used as a parameter for the boto3 client's `run_task` function. 
https://github.com/PrefectHQ/prefect/blob/e699fce534f77106e52dda1f0f0b23a3f8bcdf81/src/prefect/agent/ecs/agent.py#L320

Before `run_task` is called, we call `self.get_run_task_kwargs`, and we run into this block:
https://github.com/PrefectHQ/prefect/blob/e699fce534f77106e52dda1f0f0b23a3f8bcdf81/src/prefect/agent/ecs/agent.py#L454-L458

If I'm reading this right, we check to see if the RunConfig itself has an explicit `task_role_arn`, and use it as an override if it does. That seems fine, but the next block checks to see if the instantiated ECSAgent has `task_role_arn` set, and uses that as an _override_ without checking if the task definition passed into RunConfig _has_ a task role set. I think this means instead of providing a _default_ on the agent, passing `--task-role-arn` actually means _any_ task being deployed by the agent ends up getting that task role. 

If that's the expected behaviour, I think it'd be good to make it clear in the docs that passing `task_definiton_arn` in RunConfig won't override the agent's default task role ARN, and a user has to pass the task role they're using on the definition into RunConfig explicitly. If it's _not_ expected behaviour, I think it could likely be fixed by loading the task definition via boto3, grabbing the task role ARN, and using that in `get_run_task_kwargs` as the default instead of the agent's task role ARN.

I hope this makes sense, let me know if there's anything I can elaborate on or if I made any errant assumptions!

**Comment by youcandanch** [comment]
(Side note, @madkinsz happy to open a new issue if that's easier, just wasn't 100% sure!)

**Comment by anna-geller** [comment]
> passing task_definiton_arn in RunConfig won't override the agent's default task role ARN, and a user has to pass the task role they're using on the definition into RunConfig explicitly

You can pass either `task_definition_path` or `task_definition_arn` on your run config - Prefect then won't take it from the agent, it will take your custom task definition. I encourage you to try this in some example flow. 

I think what may confuse you is this: you don't override both task definition and task role ARN at the same time. If you use a custom task definition, you define the task role (and everything else really except agent labels and ECS cluster) within your task definition.

Setting a custom task_role_arn on your run config should be used if you want to use the task definition of your agent but you only want to override the task_role_arn because e.g. your flow needs access to additional AWS services.

**Comment by youcandanch** [comment]
@anna-geller that's actually what we're doing, though. Here's an example, assuming our agent has been started with `prefect agent ecs start --task-role-arn arn:aws:iam::123456791011:role/default_task_role`, and our task definition specifies using `arn:aws:iam::123456791011:role/specific_task_role` for its task role.

Flow script:
```python
from prefect import Flow, task
from prefect.run_configs import ECSRun
from prefect.storage import S3 as S3FlowStorage

TASK_DEFINITION_ARN = `arn:aws:ecs:us-east-1:12345678910:task-definition/staging-test-prefect:1`
S3_BUCKET = 'test_s3_bucket'

@task
def try_to_use_sns():
    client = boto3.client('sns')
    topic = self._client.create_topic(Name='test-topic')

with Flow("Example Flow") as flow:
    try_to_use_sns()

flow.run_config = ECSRun(task_definition_arn=TASK_DEFINITION_ARN)
flow.storage = S3FlowStorage(bucket=S3_BUCKET )
flow.storage.build()
flow.register('test-project')
```

In this scenario, I'm only setting the task role on the task definition, and not explicitly overridding it in the run config. When I execute it via the Prefect UI, it looks like the run configuration is totally sound:

![image](https://user-images.githubusercontent.com/448732/150979227-91743104-2ced-494b-9775-d775305731ed.png)

But when the execution actually _happens_, we end up seeing the task role on the created Fargate Task come up with the agent's default. I think it really does come down to this -- I'm going to pull a few snippets out of the agent flow deployment code to put them side by side:

```python
taskdef_arn = run_config.task_definition_arn 
kwargs = {
    'overrides': {}
}
if run_config.task_role_arn: 
    overrides["taskRoleArn"] = run_config.task_role_arn 
elif self.task_role_arn: 
     overrides["taskRoleArn"] = self.task_role_arn 
self.ecs_client.run_task(taskDefinition=taskdef_arn, **kwargs)
```

So, again, this is my understanding, and I totally could be wrong -- the boto3 [run_task](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ecs.html#ECS.Client.run_task) function will use the task definiton's task role unless there's an override. In this case, however, I think there'll _always_ be an override, because `self.task_role_arn` is the agent's default, and the agent code never actually checks the passed in task definition to see if there's a task role associated with it. I think if we wanted to explicitly say that when providing a task definition ARN or path that has a task role, the task role always gets used, we'd have to do something like this:

```python
taskdef_arn = run_config.task_definition_arn 
describe_task_definiton_response = self.ecs_client.describe_task_definition(
    taskDefinition=taskdef_arn
)
task_definition = describe_task_definition_response['taskDefinition']
kwargs = {
    'overrides': {}
}
if run_config.task_role_arn: 
    overrides["taskRoleArn"] = run_config.task_role_arn 
elif self.task_role_arn and not task_definition['taskRoleArn']: 
     overrides["taskRoleArn"] = self.task_role_arn 
self.ecs_client.run_task(taskDefinition=taskdef_arn, **kwargs)
```

**Comment by anna-geller** [comment]
@youcandanch Excellent explanation, I understand the problem now. I will test this behavior and create a separate issue since this issue was about ECSRun and docs, and what you're describing looks like a bug on the ECS agent side.

**Comment by youcandanch** [comment]
Sounds good, and thanks for doing that! Wasn't sure whether or not it warranted a new issue. I'll prep a PR for it, since I think I've got a good handle on where it's coming from.

**Comment by anna-geller** [comment]
> Sounds good, and thanks for doing that! Wasn't sure whether or not it warranted a new issue. I'll prep a PR for it, since I think I've got a good handle on where it's coming from.

PR would be amazing. Feel free to tag me for review. Thanks a lot!
