### ISSUE TITLE
Validate whether EXTRA_PIP_PACKAGES can be used with all agents and document it

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#5195]
## Description
Based on [this Slack community thread](https://prefect-community.slack.com/archives/CL09KU1K7/p1638526403296900) the user was facing some issues when trying to install packages at flow runtime in an ECSRun. 

```python
from prefect.run_configs import ECSRun

flow.run_config = ECSRun(env={"EXTRA_PIP_PACKAGES": "scikit-learn pandas"}) 
```

## Expected Behavior
- test with which agents this pattern can be used and document it

**Comment by madkinsz** [comment]
This is not an agent feature, but rather a feature of the prefect docker image. If the user overrides the `ENTRYPOINT`, it will not work. If the user is using their own image, it also will not work.

**Comment by MrChadMWood** [comment]
Quick follow up on this,

What would be the correct way to make sure agents have the prefect-gitlab and prefect-aws dependency when also required for the prefect docker server?

I'm having an issue where I can correctly make the prefect-gitlab and prefect-aws storage blocks, because the server has the dependency. When I try to run a flow stored in GitLab though, it fails because the agent does not have the dependency.

**Comment by jawnsy** [comment]
@MrChadMWood My recommendation would be to create a custom image with all dependencies included as part of a build pipeline, so that the image is immutable and won't change on you unexpectedly.

I understand that it is convenient to install some dependencies during runtime, and we intend to support that use case, via: https://github.com/PrefectHQ/prefect-helm/issues/182 - you can do the same thing using the environment variable indicated here (the `EXTRA_PIP_PACKAGES`), as long as you're using the default entrypoint script.

The disadvantage of installing dependencies at runtime is that they can change unexpectedly (for instance, when new versions are released) and it can cause failures if there are network issues or similar. Using your own custom-build images means that you have more control over when things change, though there is also the maintenance cost, so there are tradeoffs involved.
