### ISSUE TITLE
Graceful Exit when Encountering SIGTERM Signal

### ISSUE THREAD

**Issue by kvnkho** [PrefectHQ/prefect#5198]
## Current behavior

When a Flow is hit by a SIGTERM, the process just dies without marking itself as failed. The heartbeats will then die and then the Flow will eventually be marked as failed. This takes some time though and having it be immediate would be helpful in restarting the work.

## Proposed behavior

The request is for some kind of SIGTERM handler that can mark the Flow and tasks as FAILED. This is a different concept than [this issue](https://github.com/PrefectHQ/prefect/issues/4988) about graceful shutdowns of compute resources if a Flow is cancelled. The solution may end up overlapping though.

## Example

A SIGTERM Handler example is [here](https://stackoverflow.com/questions/18499497/how-to-process-sigterm-signal-gracefully) and can be used to update the state before terminating the process.

**Comment by novotl** [comment]
Thank you for creating this issue. I want to provide a specific context for our use case.

We're self hosting Prefect server and we use the Kubernetes agent to run flows as Kubernetes jobs. We're using AWS Spot instances to run these jobs. These spot instances may terminate at any time, but they send a notice. We would like to use this 2 minute window before termination to send SIGTERM to the flow run. 

What happens currently when we send SIGTERM to the process
https://github.com/PrefectHQ/prefect/blob/afa7a553964787b725b657bd38ac4df650e8b864/src/prefect/agent/kubernetes/job_spec.yaml#L16
it exits, no longer doing any work, but the state of tasks in the eyes of server is left as `Running`. 

Even though the job has correct restart policy
https://github.com/PrefectHQ/prefect/blob/afa7a553964787b725b657bd38ac4df650e8b864/src/prefect/agent/kubernetes/job_spec.yaml#L50
this case doesn't count as error, it's a reschedule, Kubernetes will automatically create a new pod (almost immediately) on a different node. But this new pod doesn't continue the flow run from where it left of, it just logs the state of tasks and exits with
https://github.com/PrefectHQ/prefect/blob/9e4ea98e782df1a8123fedfb74648ebd412c5b21/src/prefect/engine/flow_runner.py#L700

In the end, the heartbeat fails and incomplete tasks are restarted by the Lazarus process. But this takes much longer to happen.

## Expected behaviour
When I send SIGTERM to the `prefect execute flow-run` I would expect it to call the server and transition all flow tasks that are in the Running state back to Pending (or even Failed so it counts as a retry).

**Comment by madkinsz** [comment]
#8127
