### ISSUE TITLE
ECS agent cannot use FARGATE_SPOT because launchType is always set

### ISSUE THREAD

**Issue by yin-aven** [PrefectHQ/prefect#5210]
https://github.com/PrefectHQ/prefect/blob/4a739a77d170fa990a076ab45d8ef6d9cc057551/src/prefect/agent/ecs/agent.py#L171

This prevents us from using capacityProvider to launch tasks on Fargate spot, for which launchType does not support.

[A task can use either a launch type or a capacity provider strategy. If a launchType is specified, the capacityProviderStrategy parameter must be omitted.](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RunTask.html#API_RunTask_RequestParameters)

If we use capacityProviderStrategy in run_task_kwargs like
`
        capacityProviderStrategy=[
            {
                'capacityProvider': 'FARGATE_SPOT',
                'weight': 1,
                'base': 0
            },
        ],
`

Even if we omit launch_type in ECSRun and run_task_kwargs, it'll still report 

An error occurred (InvalidParameterException) when calling the RunTask operation: You may choose a capacity provider or a launch type but not both.

and fail.

**Comment by kvnkho** [comment]
Related to #4356

**Comment by anna-geller** [comment]
I looked at it today and this indeed seems to be a problem. General information I have found:

- `launch_type` will always be displayed as "FARGATE" regardless of whether the capacity provider is FARGATE or FARGATE_SPOT
- there are 2 ways to configure ECS tasks to use FARGATE_SPOT:

1) Make use of the default capacity provider strategy defined when creating a specific ECS cluster. Examples:

```bash
# without specifying exact split between Fargate and Spot:
aws ecs create-cluster \
    --cluster-name $ECS_CLUSTER_NAME --capacity-providers FARGATE FARGATE_SPOT
```

```bash
# changing it afterwards:
aws ecs put-cluster-capacity-providers \
 --cluster $ECS_CLUSTER_NAME \
 --capacity-providers FARGATE FARGATE_SPOT \
--default-capacity-provider-strategy \
capacityProvider=FARGATE_SPOT,weight=3 \
capacityProvider=FARGATE,base=1,weight=2 \
```

```bash
# or setting it directly when creating a cluster:
aws ecs create-cluster --cluster-name $ECS_CLUSTER_NAME \
--capacity-providers FARGATE_SPOT FARGATE \
--default-capacity-provider-strategy \
capacityProvider=FARGATE_SPOT,weight=3 \
capacityProvider=FARGATE,base=1,weight=2 \
```

2) Set it when creating an ECS service or running an ECS task:

```bash
aws ecs create-service \
--cluster "my-cluster"
--service-name "my-service"
--desired-count 10
--capacity-provider-strategy capacityProvider=FARGATE_SPOT,weight=1
```

```bash
aws ecs run-task \
 --capacity-provider-strategy capacityProvider=FARGATE,weight=1
 capacityProvider=FARGATE_SPOT,weight=1 \
 --cluster $ECS_CLUSTER_NAME
```

Similarly to the above, we can set it on ECSRun:

```python
flow.run_config = ECSRun(
    labels=["prod"],
    task_definition_path="s3://bucket/flow_task_definition.yaml",
    run_task_kwargs=dict(cluster="prefectEcsCluster", capacityProviderStrategy=[{'capacityProvider': 'FARGATE_SPOT', 'weight': 1, 'base': 0}, ]),
)
```

But the result is always the same: Prefect agent always sets the `launchType` to FARGATE if launch type is not defined explicitly, which makes it impossible to use the capacity provider strategy atm.

I checked whether it is related to the platform version, but regardless of whether we run it on 1.3.0 or 1.4.0, the result is the same. Similarly, running the agent with capacity provider rather than launchType has only the effect that the agent itself runs on FARGATE_SPOT but the flows are still deployed with `launchType=”FARGATE”`.

Agent:
![image](https://user-images.githubusercontent.com/86264395/146553864-9285d0c3-c3ef-4f72-936e-b52c008ff69f.png)

Flow run:
![image](https://user-images.githubusercontent.com/86264395/146553832-9cdd1253-dae3-4f62-8ec9-abeb28a80b9c.png)

**Comment by yin-aven** [comment]
@anna-geller , thank you for looking into this.  As I mentioned, AWS document clearly states that we have to use capacityProviderStrategy in order to use FARGATE_SPOT and it can't be used together with launchType.

https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RunTask.html#API_RunTask_RequestParameters

`Note
Fargate Spot infrastructure is available for use but a capacity provider strategy must be used. For more information, see AWS Fargate capacity providers in the Amazon ECS User Guide for AWS Fargate .`

The simple fix would be not to default to `FARGATE` and ECSAgent to use None in launch_type.  Any timetable on the fix would be greatly appreciated since our ECS bill is ramping up rapidly.

**Comment by anna-geller** [comment]
Sorry to hear that. I have no timetable for this. If you would want to contribute a PR, we would take the time to review and QA this.

**Comment by wfclark5** [comment]
@anna-geller  Do you think this would work? https://github.com/PrefectHQ/prefect/pull/5411

**Comment by anna-geller** [comment]
> @anna-geller  Do you think this would work? https://github.com/PrefectHQ/prefect/pull/5411 
> 

Looks good at first glance, but I would need to QA with some flow to be sure. What you could do, would be adding some tests and QA this on a sample flow. Thanks for contributing!

**Comment by wfclark5** [comment]
> > @anna-geller  Do you think this would work? #5411
> 
> Looks good at first glance, but I would need to QA with some flow to be sure. What you could do, would be adding some tests and QA this on a sample flow. Thanks for contributing!

I added some tests and have QA'd it on a sample flow! Let me know if there is anything else!

**Comment by madkinsz** [comment]
This is fixed in Prefect 1 and 2
