### ISSUE TITLE
Consolidate data persistence documentation

### ISSUE THREAD

**Issue by aripollak** [PrefectHQ/prefect#5234]
## Current behavior
It seems that there are currently at least 3 pages about results:
https://docs.prefect.io/core/concepts/persistence.html
https://docs.prefect.io/core/concepts/results.html
https://docs.prefect.io/core/advanced_tutorials/using-results.html

There's a lot of overlapping information, but I'm not sure if one is more correct than the others.

## Proposed behavior
Ideally there'd be just one page about results and persistence, or a sequence of pages without duplicated information.

**Comment by kvnkho** [comment]
Thank you for the suggestion @aripollak . There are indeed multiple pages where the same thing is mentioned. To answer you quickly though,

1. Results is a subset of persistence. Results alone can be used for checkpointing, the mechanism to restart flow runs from the point of failure by loading in data from completed steps. This is confined to a single flow run.
2. Persistence is caching across flow runs, and then the results are loaded in
3. The third page indeed looks to contain a lot of redundant information.

We'll look into it!

**Comment by sm-Fifteen** [comment]
I very much agree. Information on checkpointing/caching/persistance/results is currently very spread out, and seems to contradict itself depending on what part you're reading.

> https://docs.prefect.io/orchestration/faq/dataflow.html#when-is-data-persisted
> 
> Ultimately, data will be persisted anytime a task's result's write method is called. Task result write methods are only called under the following circumstances:
> 
> * Task Retries: in this event, result methods are called on all upstream inputs to the retrying task
> * Task Queues: functionally equivalent to retries, occurs whenever a task hits a user-set concurrency limit, and result methods are called on all upstream inputs to the queued task
> * Task Caching: if a task is set to cache its own result, result methods are called on all upstream inputs to the cached task as well as on the task's output
> * Task Checkpointing: __any task requesting to be "checkpointed" will have its Result.write method called only on its own output__
> * Parameters: all parameters are JSON-serialized and sent directly to Prefect Cloud

That part seems to imply that checkpointing is merely one of the scenarios under which data is persisted, and broadly considered an "opt-in" thing that makes persistence always-on for a specific task.

> https://docs.prefect.io/core/concepts/persistence.html#persisting-output
> 
> Oftentimes it is useful to persist your task's data in an external location. You could always write this logic directly into the Task itself, but this can sometimes make testing difficult. Prefect offers a notion of task "checkpointing" that ensures that __every time a task is successfully run, its return value is written to persistent storage__ based on the configuration in a [Result](https://docs.prefect.io/core/concepts/results.html) object for the task. To configure your tasks for checkpointing, provide a Result matching the storage backend you want to the task's result kwarg and set checkpoint=True at task initialization:

This also indicates that checkpointing is opt-in and is meant to make persistance be always on for specific tasks.


> https://docs.prefect.io/core/advanced_tutorials/using-results.html
> 
> Why would you persist the output of your tasks? The most common situation is to enable retrying from failure of a task for users that use a state database, such as Prefect Core's server or Prefect Cloud. By persisting the output of a task somewhere besides in-memory, a state database that knows the persisted location of a task's output can restart from where it left off. In the same vein, using a persistent cache to prevent reruns of expensive or slow tasks outside of a single Python interpreter is only possible when the return value of tasks are persisted somewhere outside of memory. __Another common situation is to allow for inspection of intermediary data when debugging flows (including—maybe especially—production ones). By checkpointing data during different data transformation Tasks, runtime data bugs can be tracked down by analyzing the checkpoints sequentially.__

Combined with the other two, this paragraph really reinforces that *(always-on)* checkpointing is really meant more for data auditing/debugging, and that the default behavior is probably something closer to "persist-on-failure", where a failed retryable task merely persists its inputs so it can free up memory until it can be relaunched, or where the failed tasks of a failed flow can be relaunched or have their inputs inspected for cause of error.

...but then that's not what Prefect does.

> https://docs.prefect.io/core/advanced_tutorials/using-results.html#setting-up-to-handle-results
> 
> __Checkpointing must be enabled for the pipeline to write a result__. You must enable in two places: globally for the Prefect installation, and at the task level by providing a Result subclass to tasks either through its flow initialization or as a task-level override. [...]

So far so goo-- wait, does that mean data is never persisted at all unless checkponting is enabled??

> https://docs.prefect.io/core/advanced_tutorials/using-results.html#setting-up-to-handle-results
>
> For Core-only users, you must:
>
> * Opt-in to checkpointing globally by setting the prefect.config.flows.checkpointing to "True" via [your preferred Prefect configuration](https://docs.prefect.io/core/concepts/configuration)
> * Specify the result your tasks will use for at least one level of specificity (flow-level or task-level)
> 
> For Prefect Core server or Prefect Cloud users:
> 
> * Checkpointing will automatically be turned on; you can disable it by passing checkpoint=False to each task you want to turn it off for
> * A result subclass that matches the storage backend of your prefect.config.flows.storage setting will automatically be applied to all tasks, if available; notably this is not yet supported for Docker Storage
> * You can override the automatic result subclass at the global level, flow level, or task level

Ok, so checkpointing really is only opt-in for users who run their Prefect flows by hand, which I'm guessing amounts to pretty much just people who are debugging scripts locally. Not only that, but it needs to be opted-out of at the task level (and seemingly *only* at the task level???) and it's unclear from that page of the doc whether or not disabling always-on checkpointing will also turn off other forms of persistence.

Well, having set breakpoints in the LocalResult.write method to test for myself, it would appear that, yes, `checkpoint=False` does turn off all forms of checkpointing for a task. In fact, persistance seems to only be attempted in two places, [here](https://github.com/PrefectHQ/prefect/blob/e699fce534f77106e52dda1f0f0b23a3f8bcdf81/src/prefect/engine/task_runner.py#L1001-L1014) and [here](https://github.com/PrefectHQ/prefect/blob/e699fce534f77106e52dda1f0f0b23a3f8bcdf81/src/prefect/engine/task_runner.py#L913-L930), both of which are disabled if checkpointing is set to false in the configuration context or the task decorator, and the latter of which is intended to apply only to failed tasks, but skips non-looping tasks anyway. If Result.write() is called on the task's *inputs* in this manner at any point, I'm unable to find it.

To me, that makes most of what the documentation says on persistence *extremely misleading* at best, because most of it implies that it works differently than it actually does.

----

Most of the flows I'm running have to run on a 15 minutes schedule and the one I'm working on at the moment generates 70 megabytes of data per run across the whole flow if every single task is checkpointed. At 96 runs per day, that's just under 7 GB of data per day, which adds up very quickly and requires manual cleanup (though I'm considering writing a flow to handle that cleanup as well). That's for a single flow, and one that doesn't even generate *that much* data. In general, I really don't think most people want checkpointing to be always turned on, because even when storage is cheap, you don't have infinite amounts of it (you still need to pay for cloud storage, after all). Having an automatic "persist on failure" default, with the ability to checkpoint ("persist always") on critical tasks would seem to me like a much more sane use of storage, and wouldn't lose you the ability to resume a failed flow on a task that merely generates too much data to be persisted 100% of the time.

**Comment by sm-Fifteen** [comment]
Also, only somewhat related, but [target path templating](https://docs.prefect.io/core/concepts/persistence.html#output-caching-based-on-a-file-target) is only mentioned in passing and never really delved into much further, and it's easy to misuse because the resulting path acts like a cache key. When looking at the context documentation, it's easy to think something like this would work:

```py
PICKLE_TARGET_PATH="{date:%Y-%m-%d_%Hh%M}_{flow_run_name}/{task_name}.pickle"
```

...but `task_name` doesn't contain `map_index`, so mapped tasks may run with cached results from the same map. `nout` tasks don't mistakenly consider my_nout_task[0] to be a cached value for all of the other unpacked nout subtasks, but would probably misbehave if attempting to restore it from the persisted result if the flow needed to be retried. `task_full_name` does contain the map index, but not the `run_index`, so calling a generic utility task twice with different parameters will have it incorrectly reuse the "cached value" the second time. I'm not sure which of `task_slug` or `task_id` is the correct one to use for something like this.

The doc also doesn't mention that the task parameters are also available for templating, as they are unpacked alongside the task context when formatting the template.

**Comment by sm-Fifteen** [comment]
Also also, the Pandas serializer is currently undocumented, and given how a common use case for Perfect seems to be using it as an ETL, it's not exactly conveinient to have to go back and forth between [Prefect's code](https://github.com/PrefectHQ/prefect/blob/8a90f7258ba318ebcf4841971082ee9418d27b94/src/prefect/engine/serializers.py#L153), [Pandas' documentation](https://pandas.pydata.org/pandas-docs/version/1.1/reference/api/pandas.DataFrame.to_parquet.html) and [Arrow's documentation](https://arrow.apache.org/docs/python/pandas.html) to make sure nothing gets mangled along the way.

For example, Pandas' Parquet deserialization unpacks [int columns with nulls](https://pandas.pydata.org/pandas-docs/stable/user_guide/integer_na.html) as floats (converting nulls into NaNs), unless `use_nullable_dtypes` is set, in which case all columns will be deserialized wth Pandas' nullable dtypes. The former case might run you into issues where columns unpredictably change type. The latter case is going to work fine unless you try to perform arithmetic with `df.to_numpy()` (which may be faster than doing that with the dataframes directly), because Pandas' nullable types are considered to be extension object types by numpy. This scenario can unpredictably occur depending on how Prefect handled passing values between tasks (it only happens if the value was serialized and deserialized), which I think varies between local-core and server-core because of differences in checkpointing configurations(?), so that's the kind of caveat that should probably be mentionned in the doc.

As for why the Pandas serialized would be worth the hassle, I have a flow where one mapped task runs 9 times, each time downloading a CSV file (9 300 kiB) and immediately feeds it into pandas before returning the resulting dataframe. The next task takes the mapped results and concatenates them into one large dataframe.

* Without the Pandas serializer (using the default Pickle instead) the checkpointed results land between `13 600 kiB` and `15 200 kiB` for each of the CSV loading tasks and `130 500 kiB` for the result of the concatenation.
* With the Pandas serializer turned on, using pyArrow as the engine, that's between `650 kiB` and `730 kiB` per CSV loading task, and `5 100 kiB` for the concatenation task.

That's **a 95% size reduction** in my use case, having changed none of the code besides the constants being fed into `@prefect.task(target=PARQUET_TARGET_PATH, result=LocalResult(serializer=PARQUET_SERIALIZER))`, and that's the kind of massive gain that people using Pandas dataframes as the inputs and outputs of their tasks are going to be interested by, but as of right now you simply have to be aware of the PandasSerializer and its inner workings to be able to use it properly.

**Comment by tpdorsey** [comment]
@sm-Fifteen thank you for this terrifically detailed feedback! I'll put this on our roadmap for upcoming revisions.

**Comment by sm-Fifteen** [comment]
I notice that a lot of this has been adressed in Prefect 2.6 with #6908.

The new doc for persisting results is a lot more focused on that specific topic and its options, and points out that `persist_result` is three-valued and that the default of `None` only persists as needed (although there's no mention of what these conditions are), so that's good!

The Pandas Serializer is gone, which is unfortunate (I understand wanting to focus on the 90% of use cases), although there are instructions on how to implement custom serializers for this sort of thing. Having dataframe serialization used as an example for this feature could be a good way to cover this while pointing users to whatever external doc they might want to read up on as well.

**Comment by madkinsz** [comment]
Thanks for checking back in!

> although there's no mention of what these conditions are

The blurb [at the start of the persistence section](https://docs.prefect.io/concepts/results/#persisting-results) lists the features that enable results and under [the toggling section](https://docs.prefect.io/concepts/results/#toggling-persistence) there are some specific examples.

> The Pandas Serializer is gone, which is unfortunate 

Want to add it? Otherwise it's on my backlog :)

> Cache keys are also still only mentioned very briefly

Caching is discussed more here https://docs.prefect.io/concepts/tasks/#caching — Caching is implemented separately from results and functions a bit like an "idempotency key" for states. If you use cache keys without a persisted result you will not be able to retrieve the result of the cached state. For this reason, using cache keys enables persistence of that task result by default. If you opt out of persistence explicitly, your task will need to return `None` to be usable in a normal way.

**Comment by sm-Fifteen** [comment]
> > Cache keys are also still only mentioned very briefly
> 
> Caching is discussed more [in the task concept doc](https://docs.prefect.io/concepts/tasks/#caching). Caching is implemented separately from results and functions a bit like an "idempotency key" for states. If you use cache keys without a persisted result you will not be able to retrieve the result of the cached state. For this reason, using cache keys enables persistence of that task result by default. If you opt out of persistence explicitly, your task will need to return `None` to be usable in a normal way.

So having a manually set cache key forces you to either have persistence always on or to return nothing? You can't have `cache_key_fn=lambda: "sometimes", persist_result=None`?

> > although there's no mention of what these conditions are
> 
> The blurb [at the start of the persistence section](https://docs.prefect.io/concepts/results/#persisting-results) lists the features that enable results and under [the toggling section](https://docs.prefect.io/concepts/results/#toggling-persistence) there are some specific examples.

Ah, right, ok, the wording (distinction between storing and persisting) and hyperlink for "does not store except in special cases" was throwing me off. That does make sense, thank you.

> > The Pandas Serializer is gone, which is unfortunate
> 
> Want to add it? Otherwise it's on my backlog :)

Eh, why not! I can look into it and give it a shot. Since pandas uses PyArrow to convert back and forth between dataframes and formats like Parquet and ORC, I might as well look into using it directly to try and support other dataframe libraries like Polars and cuDF and whatnot while I'm at it.

**Comment by madkinsz** [comment]
> So having a manually set cache key forces you to either have persistence always on or to return nothing? You can't have cache_key_fn=lambda: "sometimes", persist_result=None?

If you do `cache_key_fn=lambda: "sometimes", persist_result=False` then have a function that returns a value, the result value will not be retrievable from the cached state returned by the API. You'll then encounter an exception.

> Eh, why not! I can look into it and give it a shot. Since pandas uses PyArrow to convert back and forth between dataframes and formats like Parquet and ORC, I might as well look into using it directly to try and support other dataframe libraries like Polars and cuDF and whatnot while I'm at it.

Sweet! The one in v1 works using some dynamic method grabbing because we cannot actually include pandas in the core library. I'm thinking of setting up something like that in the core library, but a bit cleaner and not specific to dataframes. @desertaxle is there a dataframe/pandas collection in progress? Might be a good place for a pandas-specific implementation.

**Comment by desertaxle** [comment]
There isn't a dataframe/pandas collection in progress, but I agree that a collection would be a good place for a pandas serializer.
