### ISSUE TITLE
Function parameters are not hinted at since the Flow comes back as Any type variable.

### ISSUE THREAD

**Issue by scoussens** [PrefectHQ/prefect#5354]
## Description
With modern development tooling, when you implement a function, you will see a list of variables the function expects.

![ApplicationFrameHost_e28wGWP8zO](https://user-images.githubusercontent.com/8010027/150600729-8f304dae-a947-419d-8284-ba12d8ab541c.png)

When you write a function as a Task using the Prefect @task decorator, it hides the parameters since the return type is 'FunctionTask'.

![image](https://user-images.githubusercontent.com/8010027/150600878-85c7439d-e3e5-40fb-ac3d-4a1dab7094e8.png)

## Expected Behavior
The IDE should be able to show the expected parameters, even if they have to be annotated in the @task decorator somehow. This way when building tasks (especially a large number of tasks), you can see what the task expects when you attempt to use it in your flow.

## Reproduction
Create a Task function (decorated with @task), then when using it in the Flow you will not see any hints as to what variables it expects, or if any at all.

## Environment
Linux ubuntu 20.04 docker container, using visual studio code, with python extension installed.

Optionally run `prefect diagnostics` from the command line and paste the information here. -->
{
  "config_overrides": {},
  "env_vars": [
    "PREFECT__CLOUD__USE_LOCAL_SECRETS",
    "PREFECT__CLOUD__API_KEY"
  ],
  "system_information": {
    "platform": "Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.28",
    "prefect_backend": "cloud",
    "prefect_version": "0.15.12",
    "python_version": "3.9.6"
  }
}

**Comment by madkinsz** [comment]
Hi! This is primarily a consequence of the novelty of typing in Python. The language has only [recently added support](https://www.python.org/dev/peps/pep-0612/) for maintaining type signatures on decorated functions like this. Prefect Orion supports this, but it only works with `pyright` (and consequently, VSCode) and it was a lot of work. It's actually not possible with `mypy` as they [haven't added support](https://github.com/python/mypy/issues/8645) for the `ParamSpec` type yet. We'd have to write a `mypy` extension, but I'd rather wait for real support to come upstream.

It is likely that our team will focus on supporting this cleanly in Orion rather than attempting to add compatibility here. I'd be willing to review a PR that backports the Orion implementation though.

**Comment by carderne** [comment]
Sorry to resuscitate, do you know if this is fixed yet in mypy/prefect?

Using Python `3.10.9`, mypy `0.991` and Prefect `2.7.3`.
Code below shows `res` having type `None`. 

```python
from prefect import flow, task

@task
def task_one() -> int:
    return 1

@flow
def main() -> None:
    res = task_one()
    reveal_type(res)
```
