### ISSUE TITLE
ECS Agent (as a service) should pull network configuration from the service before inheriting from the default VPC

### ISSUE THREAD

**Issue by abrookins** [PrefectHQ/prefect#5474]
## Current behavior

The current behavior of the ECS Agent is to determine network configuration in one of two ways:

1. Via the passed-in `--task-run-kwargs`
2. By inheriting from the default VPC

We **don't** try to retrieve network configuration from the AWS service.

## Proposed behavior

The ECS Agent should try to get network configuration in three ways:

1. Via the passed-in `--task-run-kwargs`
2. By inheriting from the service's network configuration
3. By inheriting from the default VPC

## Example

I don't have a good example, but I'm happy to work with someone more knowledgeable about AWS to produce one!

## Related Issues

- #5379

**Comment by jamie1911** [comment]
This is exactly the problem I am having.

We don't have a default VPC setup. I have the ECS service set with the correct network settings. The tasks starts up successfuly.. however the container keeps crashing because it can't find the default VPC (doesnt exist) and its claiming the network settings are not there.

I would be great to just grab the network settings of the service or have an option to skip trying to configure the networking automatically.
