### ISSUE TITLE
Mapped tasks trigger multiple times on GKE Autopilot

### ISSUE THREAD

**Issue by anyweez** [PrefectHQ/prefect#5485]
Hopefully I'm not conflating multiple things here, but I'm in quite a mess when I try to run one of my flows in a GKE Autopilot cluster.

## Description
Mapped tasks appear to (sometimes) trigger multiple times on GKE Autopilot. This puts flow runs into unstable states -- sometimes completing successfully, sometimes completing but reporting a failure, and sometimes the flow run itself does not complete due to failure.

In production, my tasks may run for multiple hours and I've observed 3-4 version of a child task kick off throughout the lifecycle of the original instance (including after the original instance has succeeded 🤯 ) despite no indication that previous attempts have failed.  I've [attached a log](https://github.com/PrefectHQ/prefect/files/8148045/prefect-multitrigger.txt) from a child task for the minimal example below. A few observations:

* In this instance, all `slow_run` children triggered more than once. In some cases this only appears to affect certain children, and *occasionally* I don't observe the issue (this is rare). This makes me think we're dealing with a race condition of some sort, potentially related to autoscaling in GKE.
* After being started three times, the first instance of `slow_run[0]` was actually killed by ZombieKiller and marked as a failed run for a few minutes. It then was changed to `Success` after the final instance of `slow_run[0]` completed (this one ran for 12 minutes, as shown in logs).
* Child tasks 0 and 2 of `report_results` both print out "Final value is None" which suggests the result of `slow_run` isn't passed down successfully.

## Expected Behavior
Mapped tasks should run through the expected [state transitions](https://docs.prefect.io/core/concepts/states.html#flow-state-transitions). Child tasks shouldn't re-trigger unless something happens to previous invocations, e.g. failures requiring retries.

I would expect the fact that I'm on GKE Autopilot (which includes autoscaling) to not affect the state transitions for child tasks.

## Reproduction

```python
from prefect import Flow

def share_state_transition(task, old_state, new_state):
    logger = prefect.context.get('logger')
    logger.info("\nState transition for {0}: {1} -> {2} (retrying={3})\n".format(
        task, 
        old_state, 
        new_state,
        new_state.is_retrying(),
    ))

    return new_state

@prefect.task
def get_list():
    return [1, 2, 3, 4, 5]

@prefect.task(state_handlers=[share_state_transition,],)
def slow_run(num):
    logger = prefect.context.get('logger')

    num_minutes = random.randint(4, 12)
    logger.info(
        'Running task num={} for {} minutes'.format(
            num,
            num_minutes,
        )
    )

    time.sleep(num_minutes * 60)

    return num * 2

@prefect.task(state_handlers=[share_state_transition,],)
def report_results(num):
    logger = prefect.context.get('logger')

    logger.info('Final value is {}'.format(num))

with Flow(
  # See below; using KubernetesRun (on GKE Autopilot) and DaskExecutor
) as flow:
    results = slow_run.map(
        get_list(),
    )

    report_results.map(results)
```

## Environment
I'm running in a [GKE Autopilot](https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-overview) cluster using `KubernetesRun` and `DaskExecutor` with adaptive scaling enabled. Excerpt of my flow config, happy to provide more but I don't think there's anything too controversial.

```
# ...within Flow()...
run_config=KubernetesRun(
    image='gcr.io/<our-image>',
    image_pull_policy='IfNotPresent',
),
executor=DaskExecutor(
    cluster_class=lambda: KubeCluster(
        make_pod_spec(
            image=prefect.context.image,
            cpu_request=2,
            memory_request='8G',
        ),
    ),
    adapt_kwargs={ 
        'minimum': 1, 
        'maximum': 12,
    },
),
```

Prefect diagnostics:
```json
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "macOS-12.2.1-arm64-arm-64bit",
    "prefect_backend": "cloud",
    "prefect_version": "1.0.0",
    "python_version": "3.9.7"
  }
}
```

**Comment by anyweez** [comment]
It appears that my flows are completing successfully if I disable adaptive scaling and assign a static number of workers. This makes me more confident that the underlying issue is in fact a resource/scaling-related race condition.

```
run_config=KubernetesRun(
    image='gcr.io/<our-image>',
    image_pull_policy='IfNotPresent',
),
executor=DaskExecutor(
    cluster_class=lambda: KubeCluster(
        make_pod_spec(
            image=prefect.context.image,
            cpu_request=2,
            memory_request='8G',
        ),
        n_workers=4,
    ),
),
```

**Comment by madkinsz** [comment]
Thanks for the thorough report. Just want to first make sure this isn't related to https://github.com/PrefectHQ/prefect/issues/3058 — this is an issue where autoscaling your Dask cluster on K8s is leading to reruns of your mapped tasks, correct?

Ensuring good behavior when a Dask work pod is shutdown while running tasks has proven challenging in the past. I am curious if adding `"cluster-autoscaler.kubernetes.io/safe-to-evict": "false"` to your Dask worker pods would help.

**Comment by anyweez** [comment]
This is very similar to #3058, but `"cluster-autoscaler.kubernetes.io/safe-to-evict": "false"` is explicitly not supported in GKE Autopilot. Otherwise the conditions described there are very similar to what I've observed here, including occasional `No heartbeat detected from the remote task` errors (these stop occurring with the workaround proposed above).

We've also tried [turning heartbeats off](https://docs.prefect.io/orchestration/concepts/flows.html#toggling-heartbeats) as suggested there, but that didn't create any noticeable improvements.

A few other things I've tried:
* [Turning off version locking](https://docs.prefect.io/orchestration/concepts/flows.html#flow-settings). No improvement - I also tried disabling Lazarus and heartbeats...my thought being that Prefect might not realize tasks are already running b/c they take a few minutes to scale up, and end up re-creating them. This didn't appear to help.
* I tried disabling retries `(@task(max_retries=0))` for our problematic tasks, thinking maybe Prefect was seeing a failure that it wasn't reporting and was automatically retrying. No change.

**Comment by madkinsz** [comment]
Does this only occur for mapped tasks? The more we can narrow it down the easier it will be to try to get a fix in.

It sounds like you've tried most of what I would suggest. Have you tried switching to the thread-based heartbeats? https://docs.prefect.io/orchestration/concepts/services.html#heartbeat-configuration

**Comment by BitTheByte** [comment]
Hi @madkinsz 

I've experienced the same problem before and still to this day, the problem is related to Dask's adaptive cluster for some reason prefect re-run the task even if it's completed before. my workaround is to create a new decorator with preset function targets to cache the result - https://gist.github.com/BitTheByte/cf7af4c0247ff6568d9298bc30270524 - this seems to partially solve the problem as it prevents long-running tasks from running again however as mentioned by @anyweez the problem is the unstable runs resulting from using the adaptive cluster.



Some of my failed attempts were
- Adding `"cluster-autoscaler.kubernetes.io/safe-to-evict": "false"` to k8s annotations for worker pods 
- Setting `"DASK_DISTRIBUTED__SCHEDULER__WORK_STEALING": "false"` EnvVar for worker pods
- Setting `"PREFECT__CLOUD__HEARTBEAT_MODE": "thread"`  EnvVar for worker pods
- Using `--no-nanny` to prevent Dask from restarting tasks

I'm hoping https://github.com/dask/dask-kubernetes/pull/392 could result in a more stable Dask's integration with k8s however this problem is totally related to prefect. probably a race condition issue

**Comment by BitTheByte** [comment]
Hi @madkinsz 

Have you been able to determine the root cause of this? Does it happen with Orion too?

**Comment by madkinsz** [comment]
I haven't had a chance to look into this further. Orion might have this issue, but we have stricter rules about state transitions which should prevent it.

**Comment by BitTheByte** [comment]
Hey @madkinsz 

I managed to force this behavior this happens when a worker pod killed in the middle of working hence this is more obvious in adaptive mode as this happens a lot

**Comment by BitTheByte** [comment]
After further research, this happens because after the killed worker is respawned it start executing every task from the beginning till this point it's not a race condition it's just a process coming from stateless state execution stateful discussions I think more restrictions need to be applied on API level rather than the codebase or implement a transparent - hidden from UI - caching function e.g.
```python
def cache_namespace():
    def creator(flow_id, flow_run_id, flow_name, flow_run_name, task_name, task_run_id, *args, **kwargs):
        return f"{flow_name}/{flow_run_name}.{flow_run_id}/{task_name}.{flow_id}.{task_run_id}.prefect_result"
    return creator
```

**Comment by BitTheByte** [comment]
@madkinsz would love to know if there are any updates on this 😃

**Comment by BitTheByte** [comment]
Hi @madkinsz 

I encounter this issue by daily basis and just discovered that my solution is invalid as it somehow sends "None" value or if it was successful the children takes have hard time executing properly and eventually everything breaks. I think this could be solved using state handler or a better logic at the state transition. As mentioned before the problem is reproducible by killing any of the dask workers. I know it's hard to debug and I'm willing to but the time and effort to fix this as its critical to our projects so could you please provide your opinion on this? Or at least what you think this cause of this?

**Comment by anna-geller** [comment]
I wonder whether [toggling version locking](https://docs.prefect.io/orchestration/concepts/flows.html#toggle-version-locking) could help to ensure your tasks get executed only once. Could you give it a try?

**Comment by BitTheByte** [comment]
Hello @anna-geller

Thanks for replying here, version locking is a paid feature and @anyweez confirmed that it did not help either

**Comment by anna-geller** [comment]
Yeah, I saw that a bit too late that's why I removed my comment :) but now that I think about it, @anyweez I think you should go the other way around - you should [toggle version locking](https://docs.prefect.io/orchestration/concepts/flows.html#toggle-version-locking) ON rather than OFF.

**Comment by anna-geller** [comment]
It can't hurt to sign up for a free tier of Prefect Cloud and give it a try. I can't test it on GKE Autopilot myself, but feel free to try turning version locking on and running the same flow on Cloud to see whether this helps. You can run 20,000 tasks every month for free; it should be enough to test it out before committing to anything.

**Comment by BitTheByte** [comment]
@anna-geller I really hoped that solves it. unfortunately, it didn't my caching function got invoked. indicating that the same task was relaunched again  

![image](https://user-images.githubusercontent.com/16452985/164250401-73bf60b2-d073-4ff6-88f3-7fab53e8efa4.png)

Keep in mind I'm having version locking enabled 

![image](https://user-images.githubusercontent.com/16452985/164250752-c351e001-ccc7-45e3-aeac-0664e8fe3fbb.png)

**Comment by madkinsz** [comment]
Hi again, I appreciate you saying that you'll do work debugging this. I do not have any suggestions of how to resolve this without spending significant time investigating it as well. I can continue to try to give you some guidance as best as I can, but the majority of my time right now is focused on addressing more common use-cases. As @anna-geller mentioned, if this is critical for you may benefit from contacting cs@prefect.io to get some dedicated resources outside of what we can provide in the open source project.

To clarify some of the language, flow runs on Kubernetes using Dask workers on Kubernetes should have the following objects:

- **Flow run job**: A Kubernetes Job to schedule a pod to execute the flow
- **Flow run pod**: A Kubernetes Pod for executing the flow
- **Flow runner**: Runs within the flow run pod, submits tasks to the Dask scheduler
- **Dask scheduler pod**: Runs the Dask scheduler
- **Dask worker pod**: A Kubernetes Pod for executing tasks sent to Dask
- **Task runner**: Runs as a task on the Dask worker pod to orchestrate a Prefect task

> After further research, this happens because after the killed worker is respawned it start executing every task from the beginning till this point

Are you saying that when a Dask worker pod is killed the replacement Dask worker pod re-executes all of the tasks it has ever received? Or all of the tasks in the flow? It re-executes tasks that have reported a success state _and_ returned a value to the flow runner?

> I managed to force this behavior this happens when a worker pod killed in the middle of working hence this is more obvious in adaptive mode as this happens a lot

To confirm, does this mean this behavior occurs if adaptive scaling is disabled and a worker is manually killed?

**Comment by BitTheByte** [comment]
@madkinsz 

> Are you saying that when a Dask worker pod is killed the replacement Dask worker pod re-executes all of the tasks it has ever received? Or all of the tasks in the flow? It re-executes tasks that have reported a success state and returned a value to the flow runner?

The new spawned worker pod starts executing tasks as if the flow is restarted and I think the problem is here as it changes the states of the runs 


> To confirm, does this mean this behavior occurs if adaptive scaling is disabled and a worker is manually killed?

This happens while using adaptive or not as prefect tries to reallocate failed tasks to other workers.  it shows more when adaptive is enabled and a new worker pod is added or an old worker is killed by any outside factor ( manually or due to network failure ) the spawned/respawned worker acts weird and changes the run state sometimes re-invoking some although it's clearly finished with success it's not GKE related it's reproducible on any k8s cluster. keep in mind you must have some finished tasks to see the effect (more visible when using [Targets](https://docs.prefect.io/core/idioms/targets.html))

**Comment by anna-geller** [comment]
If scaling out with `KubeCluster` doesn't work well on GKE Autopilot, I wonder whether it makes sense to try scaling up instead - you could try spinning up a flow run pod with more resources on `KubernetesRun` and use a `LocalDaskExecutor` within that single pod. It would vastly simplify the coordination between threads and processes and perhaps would solve the problem equally well? Definitely something worth trying

**Comment by BitTheByte** [comment]
@anna-geller distributed load balancing is a must for us that's why we choose prefect in the beginning. we are working with +100 machines and many many worker pods it's nearly impossible to achieve the same performance with a single node. that's said the scale of our projects isn't the problem here as it affects small workflows even if it just has two workers

**Comment by madkinsz** [comment]
Can you clarify a few points?

- Are you killing the flow run pod or a Dask task run worker pod?
- Can you provide more logs for the version locking exception?
- Do you see a flow version locking error or task version locking error?
- Can you provide a flow run id for a minimal run that reproduces the issue?

**Comment by BitTheByte** [comment]
@madkinsz 

> Are you killing the flow run pod or a Dask task run worker pod?

There are 3 types of pods 
1) **prefect-job**: creates `dask-scheduler` pod 
2) **dask-scheduler**: creates `dash-worker` pod
3) **dask-worker** : execute task runs

I'm killing the `dask-worker` pod 


> Can you provide more logs for the version locking exception?

I'm unable to force `Version Locking` to crash again. it seems like it doesn't care about this case

> Do you see a flow version locking error or task version locking error?

No


> Can you provide a flow run id for a minimal run that reproduces the issue?

Task Run: https://cloud.prefect.io/bitthebyte/flow-run/e8f9d1c7-8d03-4e28-93fd-98bff8231879?overview

Detailed video https://youtu.be/a5z5fNvqVnM

```python
from dask_kubernetes import KubeCluster, make_pod_spec
from prefect.run_configs import KubernetesRun
from prefect.engine.results import S3Result
from prefect.storage import Docker
from prefect import Flow, task
import prefect
import time


def cache_namespace(): 
    def creator(flow_id, flow_run_id, flow_name, flow_run_name, task_name, task_run_id, *args, **kwargs):
        return f"{flow_name}/{flow_run_name}.{flow_run_id}/{task_name}.{flow_id}.{task_run_id}.prefect_result"
    return creator


@task(name="my-task", target=cache_namespace()) # using target to be able to visually identify task re-run
def long_task(a):
    time.sleep(30)
    print(a)
    return a


with Flow(name="testing-workflow") as flow:
    long_task.map(a=range(100))


if __name__ == "__main__":
    flow.run_config = KubernetesRun()
    flow.storage = Docker(
        registry_url="<registry>",
        image_name=flow.name,
        image_tag="v1",
        extra_dockerfile_commands=[
            "RUN pip install dask_kubernetes"
        ]
    )
    flow.result = S3Result(bucket="prefect-data", boto3_kwargs={
        "aws_access_key_id": "<key>",
        "aws_secret_access_key": "<token>",
        "endpoint_url": "<minio_endpoint>",
    })
    flow.executor = prefect.executors.DaskExecutor(
        cluster_class=lambda: KubeCluster(
            pod_template=make_pod_spec(image=prefect.context.image),
        ),
        adapt_kwargs={"minimum": 2, "maximum": 10},
    )
    flow.register(project_name='<project>')
```

**Comment by BitTheByte** [comment]
Just wanted to get some light on the fact that **a worker doesn't have to be killed to trigger this behavior** the addition of a new worker triggers it too _sometimes_. it affects prefect as a whole and I'm really surprised to no one noticed it before

**Comment by BitTheByte** [comment]
As per my attempt to narrow it down, I suspected Lazarus process however even if "Lazarus" is disabled to same behavior applies 
![image](https://user-images.githubusercontent.com/16452985/164675723-64bb219b-813c-4f24-a31c-489646e2f11e.png)

**Comment by BitTheByte** [comment]
Sorry for making this thread too noisy I'm trying to be informative as possible, below is a clear log of mapped task with just 2 runs

```
22 April 2022,12:26:58 EET	prefect.CloudFlowRunner	INFO	Beginning Flow run for 'testing-workflow'
22 April 2022,12:27:08 EET	prefect.CloudTaskRunner	INFO	Task 'Constant[range]': Starting task run...
22 April 2022,12:27:09 EET	prefect.CloudTaskRunner	INFO	Task 'Constant[range]': Finished task run for task with final state: 'Success'
22 April 2022,12:27:10 EET	prefect.CloudTaskRunner	INFO	Task 'my-task': Starting task run...
22 April 2022,12:27:10 EET	prefect.my-task	INFO	State transition for my-task-1: <Pending: "Task run created"> -> <Mapped: "Ready to proceed with mapping.">
22 April 2022,12:27:11 EET	prefect.CloudTaskRunner	INFO	Task 'my-task': Finished task run for task with final state: 'Mapped'
22 April 2022,12:27:11 EET	prefect.CloudTaskRunner	INFO	Task 'my-task[1]': Starting task run...
22 April 2022,12:27:11 EET	prefect.CloudTaskRunner	INFO	Task 'my-task[0]': Starting task run...
22 April 2022,12:27:11 EET	prefect.my-task[0]	INFO	State transition for my-task-0: <Pending: "Task run created"> -> <Running: "Starting task run.">
22 April 2022,12:27:11 EET	prefect.my-task[1]	INFO	State transition for my-task-1: <Pending: "Task run created"> -> <Running: "Starting task run.">
22 April 2022,12:27:38 EET	prefect.CloudTaskRunner	INFO	Task 'my-task[0]': Starting task run...
22 April 2022,12:27:38 EET	prefect.my-task[0]	INFO	State transition for my-task-0: <Pending: "Task run created"> -> <Running: "Starting task run.">
22 April 2022,12:28:08 EET	prefect.my-task[0]	INFO	State transition for my-task-0: <Running: "Starting task run."> -> <Success: "Task run succeeded.">
22 April 2022,12:28:08 EET	prefect.CloudTaskRunner	INFO	Task 'my-task[0]': Finished task run for task with final state: 'Success'
22 April 2022,12:28:09 EET	prefect.CloudTaskRunner	INFO	Task 'my-task[1]': Starting task run...
22 April 2022,12:28:09 EET	prefect.my-task[1]	INFO	State transition for my-task-1: <Pending: "Task run created"> -> <Running: "Starting task run.">
              
            <--- WORKER IS KILLED HERE --->

22 April 2022,12:28:59 EET	prefect.CloudTaskRunner	INFO	Task 'Constant[range]': Starting task run...
22 April 2022,12:29:00 EET	prefect.CloudTaskRunner	INFO	Task 'Constant[range]': Finished task run for task with final state: 'Success'
22 April 2022,12:29:00 EET	prefect.CloudTaskRunner	INFO	Task 'my-task[1]': Starting task run...
22 April 2022,12:29:00 EET	prefect.my-task[1]	INFO	State transition for my-task-1: <Pending: "Task run created"> -> <Running: "Starting task run.">
22 April 2022,12:29:02 EET	prefect.CloudTaskRunner	INFO	Task 'my-task[0]': Starting task run...
22 April 2022,12:29:02 EET	prefect.my-task[0]	INFO	State transition for my-task-0: <Pending: "Task run created"> -> <Cached: "Result found at task target testing-workflow/rebel-scallop.9d058dda-3651-494f-8d24-a784c4d9e37b/my-task.e7f26cef-fdf6-4296-ae00-c418161cc1a9.5ef01dba-173d-47c0-ad39-a652f099684a.prefect_result">
22 April 2022,12:29:03 EET	prefect.CloudTaskRunner	INFO	Task 'my-task[0]': Finished task run for task with final state: 'Cached'
22 April 2022,12:30:02 EET	prefect.CloudFlowRunner	INFO	Flow run SUCCESS: all reference tasks succeeded
```

As you can see there are duplicate runs although these tasks finished before and to my surprise there is no direct state transition it's just two instances of the same flow running simultaneously 🤯 hence the broken states and weird runs after this happens

**Comment by anna-geller** [comment]
Don't worry about the noise; we won't complain about having more information for sure. Share any updates you have

**Comment by cicdw** [comment]
Hey everyone, I believe Prefect is doing the "right" thing here in the face of a noisy environment, but it's doing a poor job of displaying what's happening.  It's important to start by noting that with this setup Prefect doesn't control Dask's scheduler but rather layers on state handling features (retries, prevention of logic re-execution, etc.). With that, let me break down the different pieces:

- the only time your task logic is executing is when your task run is an a `Running` state within Prefect; this means that transitions such as `Pending` -> `Cached` do not represent a rerun of logic but rather a data load from a previous `Success` state; similarly, a transition of `Pending` -> `Success` does not represent a rerun (more on this later)
- if we focus our attention on a single flow run process, Prefect will _never_ re-execute completed upstream tasks
- Dask, on the other hand, does rerun things quite often -- when workers die, dask sometimes needs to recompute upstream data dependencies; other times, the Dask scheduler decides a rerun on a new worker is more efficient than shipping data around the cluster
- if you happen to be using Dask and wish to prevent your logic from executing twice, Prefect offers two options: 
    - the use of caching (so that a `Pending` -> `Running` transition is prevented and instead a `Pending` -> `Cached` transition occurs)
    - version locking: version locking prevents a task from transitioning `Pending` -> `Running` two times within a single flow run; instead, if a version lock is encountered, you'll see a `Pending` -> `Success` on the second attempted run.  The Prefect Client notices that there is a version mismatch and loads the most recent state (which in the examples above are `Success` states) 

There is a valid bug in the original report:

> After being started three times, the first instance of slow_run[0] was actually killed by ZombieKiller and marked as a failed run for a few minutes. It then was changed to Success after the final instance of slow_run[0] completed (this one ran for 12 minutes, as shown in logs).

that was caused by a race condition in the Prefect Cloud Zombie Killer that should now be resolved.

There are many improvements to the state bookkeeping that would make this experience more navigable, and we believe that the changes to state handling in 2.0 will address these.

**Comment by BitTheByte** [comment]
Hi @cicdw 

Prefect 2.0 doesn't have the same issue although **it's running on Dask too** (not applicable to use since it's very immature), Yes Dask may choose to rerun *"Failed"* tasks however those are clearly successfully so no a reason to resend again, version locking is not working on this case (see image) I had the same task transition multiple times on a single flow run and this doesn't explain the behavior of tasks after this happens as most of the runs will fail (due to weird errors) a simple fix is to use the same mechanism used in restarting flow runs to cache results rather than having us to implement something custom or maybe more restricted transition rules. I really want to debug this and get it fixed as soon as possible since prefect is heavily used in our infra but I really don't know where to start 


![image](https://user-images.githubusercontent.com/16452985/164882357-f30b36da-3e64-4293-b1c7-45b78b6b6bc2.png)

**Comment by BitTheByte** [comment]
I removed that caching and tried the same workflow but a was sending back pings when a task is finished and this task happened
 
![image](https://user-images.githubusercontent.com/16452985/164886051-fd9630dd-b31d-4ebc-87d4-56b11ac616fb.png)

I got two pings with to the same task. keep In mind **I have "Version Locking" enabled**

![image](https://user-images.githubusercontent.com/16452985/164886072-b5866287-20a7-4686-a9e8-655d8ec87449.png)
![image](https://user-images.githubusercontent.com/16452985/164886080-74fbd0c6-0059-418e-be64-d492bc8de48d.png)

**Comment by BitTheByte** [comment]
Here is a screenshot from our production environment, showing task moving from `Running -> Success -> Running` and I confirmed that it's actually running not a false positive  

![image](https://user-images.githubusercontent.com/16452985/164891360-9c5d6f57-0355-4166-9058-e599836685c6.png)

**Comment by BitTheByte** [comment]
I found a way to reproduce this effectively 
```python
from dask_kubernetes import KubeCluster, make_pod_spec
from prefect.run_configs import KubernetesRun
from prefect.engine.results import S3Result
from prefect.storage import Docker
from prefect import Flow, task
import prefect
import time

def share_state_transition(task, old_state, new_state):
    logger = prefect.context.get('logger')
    logger.info("State transition for {0}: {1} -> {2}".format(
        task,
        old_state,
        new_state,
    ))
    return new_state


@task(name="my-task", state_handlers = [share_state_transition])
def long_task(a):
    prefect.context.logger.info("HELLO FROM TASK-{}".format(a))
    time.sleep(30 * a)
    prefect.context.logger.info("GOODBYE FROM TASK-{}".format(a))
    return a

@task(name="hello-world", state_handlers = [share_state_transition])
def hello_world(a):
    prefect.context.logger.info("A" * 100)
    return a
    

with Flow(name="testing-workflow") as flow:
    hello = hello_world.map(range(10))
    long_task.map(a=prefect.flatten(hello))


if __name__ == "__main__":
    flow.run_config = KubernetesRun()
    flow.result = S3Result(bucket="prefect-data", boto3_kwargs={
        "aws_access_key_id": "<aws_access_key_id>",
        "aws_secret_access_key": "<aws_secret_access_key>,
        "endpoint_url": "<endpoint_url>",
    })
    flow.executor = prefect.executors.DaskExecutor(
        cluster_class=lambda: KubeCluster(
            pod_template=make_pod_spec(image="prefecthq/prefect:1.2.0-python3.9"),
        ),
        adapt_kwargs={"minimum": 1, "maximum": 1},
    )
    flow.run()
```

Killing the single worker dask have will result in in running task `hello-world` again and again. I hope that manages to make my point clear and confirm that prefect is re-running successful tasks

**Comment by BitTheByte** [comment]
I noticed that `FlowRunner` doesn't respect `Result` in this case however the same applies to `CloudFlowRunner`

**Comment by BitTheByte** [comment]
I know pinging the team is really annoying but I really need some feedback on this, again apologies for doing that
@madkinsz @cicdw @anna-geller

**Comment by madkinsz** [comment]
Please do not ping the team, we're all following this issue already and it will not lead to faster resolution. You are welcome to contribute a patch if this is pressing for you, otherwise we are investigating it as much as resources allow.

**Comment by BitTheByte** [comment]
Apologies for the ping, I was finally able to locate the issue here. What is happening is when a worker pod dies it loses the information about the tasks and futures it computed thus when a task is dependent on that information Dask tries to recompute the upstream with the same arguments and states thus Prefect is unable to detect this case it's a problem with resilience rather than a problem with prefect logic itself, I was able to partially fix it

**Comment by BitTheByte** [comment]
Apologies for the ping, I was finally able to locate the issue here. What is happening is when a worker pod dies it loses the information about the tasks and futures it computed thus when a task is dependent on that information Dask tries to recompute the upstream with the same arguments and states thus Prefect is unable to detect this case it's a problem with [resilience](https://distributed.dask.org/en/stable/resilience.html
) rather than a problem with prefect logic itself, I was able to partially fix it by calling `self.client.replicate(fut)` after submitting a task that ensures that at any given point at least two workers have the same copy of data however I stumbled across a problem with rebalancing since now the new worker will have nothing to do for a while. I'll keep you updated

**Comment by BitTheByte** [comment]
Apologies for the ping, I was finally able to locate the issue here. What is happening is when a worker pod dies it loses the information about the tasks and futures it computed thus when a task is dependent on that information Dask tries to recompute the upstream with the same arguments and states thus Prefect is unable to detect this case it's a problem with [resilience](https://distributed.dask.org/en/stable/resilience.html) rather than a problem with prefect logic itself

**Comment by BitTheByte** [comment]
For those who might encounter the same problem in the future. I was able to get very stable runs using adaptive mode using the following environment variables

```
"DASK_DISTRIBUTED__SCHEDULER__WORK_STEALING": "true",
"DASK_DISTRIBUTED__SCHEDULER__WORK_STEALING_INTERVAL": "120s",
"DASK_DISTRIBUTED__SCHEDULER__WORKER_TTL": "3600s",
"DASK_DISTRIBUTED__SCHEDULER__ALLOWED_FAILURES": "100",
"DASK_DISTRIBUTED__WORKER__PROFILE__INTERVAL": "10000ms",
"DASK_DISTRIBUTED__WORKER__PROFILE__CYCLE": "1000000ms",
"DASK_DISTRIBUTED__COMM__TIMEOUTS__CONNECT": "300s",
"DASK_DISTRIBUTED__COMM__SOCKET_BACKLOG": "16384",
"DASK_DISTRIBUTED__COMM__TIMEOUTS__TCP": "300s",
"DASK_DISTRIBUTED__COMM__RETRY__COUNT": "12"
```

**Comment by madkinsz** [comment]
Wow great! Thanks for sharing. cc @anna-geller / @kvnkho for elevating somewhere.

**Comment by anna-geller** [comment]
> why is it possible for Prefect to consider a task with "Running" as its final state?

this happens when there is an infrastructure crash e.g. when your container gets shut down or instance/pod gets terminated; in such case, the task is Running, Running, Running... and then due to the sudden infrastructure crash, the process doesn't have a chance to send update to the Prefect API and since Prefect cannot tell any new state updates, it keeps the latest state which was Running. It may seem weird to you at first, but imagine a situation when instead you had a long-running job and the heartbeat would be gone and Prefect would simply consider this as failed even though it would be still running. It's a tradeoff but due to the inability to determine the final state, Prefect keeps the latest state it can be sure was reported by the process - here it was the Running state

**Comment by klayhb** [comment]
@anna-geller so what will happen eventually? i.e. - is a task that's finished in a "Running" state considered successful? would it prevent the flow itself from finishing? from being marked as successful?
(eventually those tasks i mentioned did get marked as failed, i guess when the the something in the mechanism "gave up")

**Comment by anna-geller** [comment]
> @anna-geller so what will happen eventually? i.e. - is a task that's finished in a "Running" state considered successful? would it prevent the flow itself from finishing? from being marked as successful?
> (eventually those tasks i mentioned did get marked as failed, i guess when the the something in the mechanism "gave up")

No, this is the final task until you manually cancel it.

**Comment by klayhb** [comment]
@anna-geller  sorry, i don't understand the answer :(
what will happen to the **flow** if it has for example  3 tasks with a finished state of Running and 97 tasks that are successful -- all of which are mapped tasks of some task "X"?

will the flow be considered finished? successful? failed?
