### ISSUE TITLE
Permission error when following the prefect's tutorial and on the step of executing `leonardo-deployment`

### ISSUE THREAD

**Issue by kuatroka** [PrefectHQ/prefect#5824]
## Description
Permission error when following tutorial and creating `leonardo-deployment`. I set up local storage, created deployment, inspected it. All was fine,but when I ran `prefect deployment execute leonardo_dicapriflow/leonardo-deployment` I got an error

```
Loading flow from deployed location...
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\my_user\\AppData\\Local\\Temp\\flow-script-leonardo_dicapriflowqzt37f1v.py
```

## Reproduction / Example
I'm on in Windows 10
virtual environment, python=3.9.7
prefect 2.0 
profile connected to prefect cloud with API key

Thanks

**Comment by bunchesofdonald** [comment]
Hi @kuatroka! Thanks for submitting this issue. Things have changed a bit since this issue was created, so I walked through the deployment tutorial and while I ran into a different issue (#6638), I was able to build/apply/run the deployment. Could you try walking through the tutorial again and see if you're still having issues?
