### ISSUE TITLE
Frozen dataclass objects are not allowed as parameters to flows

### ISSUE THREAD

**Issue by riyabakhtiani** [PrefectHQ/prefect#6058]
## Description
The issue reported here https://github.com/PrefectHQ/prefect/issues/5663 is not fixed frozen data classes

## Reproduction / Example

from prefect import flow
from dataclasses import dataclass

@dataclass(frozen=True)
class MyDataClass:
    val1: bool = True
        
@flow(validate_parameters=False)
def my_flow(request: MyDataClass):
    print("Heres my flow", request.val1)
    
    
req = MyDataClass(True)

my_flow(req)

Pydantic throws type error:
TypeError: cannot inherit non-frozen dataclass from a frozen one

**Comment by bunchesofdonald** [comment]
@riyabakhtiani after looking into this it appears that this is a bug in Pydantic (https://github.com/pydantic/pydantic/issues/3469) where generating the schema from a frozen dataclass fails. Until that bug is fixed, I'd suggest using `pydantic.dataclasses.dataclass`, which would make your flow look something like:

```python
from prefect import flow
from pydantic.dataclasses import dataclass as pydantic_dataclass


@pydantic_dataclass(frozen=True)
class MyDataClass:
    val1: bool = True


@flow(validate_parameters=False)
def my_flow(request: MyDataClass):
    print("Heres my flow", request.val1)


req = MyDataClass(val1=True)

my_flow(req)
```

**Comment by madkinsz** [comment]
We no longer raise errors if parameters cannot be serialized.
