### ISSUE TITLE
Use a uniquely identifying `User-Agent` string for the `prefect` client

### ISSUE THREAD

**Issue by chrisguidry** [PrefectHQ/prefect#6122]
### Describe the proposed behavior

Send a `User-Agent` that identifies the `prefect` client version, like perhaps: `prefect; python 2.0.0+xyz`

### Describe the current behavior

Today, we sent API requests with `python-httpx 0.22.0`, but this could be any httpx client trying to access our APIs.

**Comment by jawnsy** [comment]
Love this idea! I'd propose that we restrict it to the Prefect library version in the User-Agent header, and that we use either separate headers or our existing telemetry system (sens-o-matic) to get more detailed user data (I think @dylanbhughes might be able to tell us how that works and how to send data there).

I think having both basic/very anonymous version info in this header, and more detailed telemetry (on an opt-in basis, since it's less anonymous) would make sense.

Some of the detailed telemetry I would be interested in includes:

* OS version (LSB release file info, kernel version; or Mac & Windows versions)
* Machine architecture (x86_64, AArch, etc) which can help us prioritize our binary builds and test infrastructure
* Details of running Python environment (conda, virtualenv, etc)
* Details about whether we're running inside a container (and if so, which runtime) or other virtualized environment

**Comment by dylanbhughes** [comment]
Yup I can help 👍
