### ISSUE TITLE
Allow agents to limit the number of concurrent flow runs

### ISSUE THREAD

**Issue by dkomisar** [PrefectHQ/prefect#6231]
### Prefect Version

1.x

### Describe the proposed behavior

Agents should have a way to limit the number of concurrent flow runs they submit for execution.

### Describe the current behavior

Currently the agents run them locally as fast as they can.

This can be done with the dask executor, but the agent still submit for execute as many flow runs as they can leading to running flow runs building up in dask.

### Example Use

We have a variable workload and we don't want to guess what agents will have what resources. There is no reason for an agent to submit a flow for execution until it has capacity. This allows that functionality (and it also allows removal of dask).

**Comment by madkinsz** [comment]
We've explored this in the past but do not have a clear path forward, see existing issue at https://github.com/PrefectHQ/server/issues/213 and drafted implementation at https://github.com/PrefectHQ/prefect/pull/4532

It's not likely that we will pursue this.

**Comment by Eronarn** [comment]
We're running an on-demand task with an expected latency of ~1 minute. This isn't even very high performance, but the (hardcoded!) polling latency of the Prefect agent on top of the startup latency of ECS tasks was too high. We switched to have the agent mount an ECS instance's Docker socket and launch flows as non-ECS Docker containers, to get the flow execution latency lower.

On Prefect 1.0, this works okay as long as we don't launch more flows than there are cores on that box... which is something we want to do frequently. The available concurrency controls simply do not support this.

I'm starting research on Prefect 2.0 and it's very disappointing to see that despite all the new "infrastructure" primitives added, that the scheduling and resource utilization stories are so underdeveloped.  _Don't kill the machine you are running on_ is table stakes for a well-behaved scheduler, and not having it prevents configuring Prefect in an elastically scalable way unless you're willing to incur scheduler-on-scheduler latency.

**Comment by madkinsz** [comment]
@Eronarn thanks for commenting with your thoughts! Note this issue is for v1 — there's work in progress for limiting concurrency per agent in v2 at #7361.

Regarding some of your comments:

> the (hardcoded!) polling latency of the Prefect agent

In v1, we fetch flow runs scheduled in the future including the polling interval to avoid this. In v2, you'll be happy to note this is configurable.

> the startup latency of ECS tasks was too high

In v2, we are working on addressing this by allowing startup to begin before the flow run is scheduled. See https://github.com/PrefectHQ/prefect/pull/7498 and https://github.com/PrefectHQ/prefect/pull/7585

In general though, Prefect is not focused on resource allocation — we instead aim to lean on services which are designed to scale elastically (Kubernetes, Google Cloud Run, AWS ECS, Azure ACI). Scheduling balanced resource allocation is a very hard problem and we'd rather focus on other elements of orchestration that are not addressed by other tools.

**Comment by acgourley** [comment]
I would really appreciating being able to start a LocalAgent which only attempted one job at a time. I wonder if that's the case for everyone else interested in this feature, and if true, if that could ease concerns about being complicated to implement.

**Comment by madkinsz** [comment]
We will not be implementing this in v1, but there are several patches that implement this in v1 and it's not hard to run your own agent with the extensions. This feature is available in v2.
