### ISSUE TITLE
Notifications/Create Notification page is missing option for "TimedOut" flow state

### ISSUE THREAD

**Issue by BennyJW** [PrefectHQ/prefect#6238]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

Under Notifications, Create Notification, there is a drop down for "Run States".  That dropdown seems to include all possible states but is missing "TimedOut".

### Reproduction

Go to Notifications, then Create Notification, and select the "Run States" dropdown.

### Error

This is not really an error, but a missing item in the "Run States" dropdown.

### Browers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Edge

### Prefect version

```

# Copy output of `prefect version` here if hosting your own UI

```

**Comment by madkinsz** [comment]
Hi! Thank you for reporting this issue. 

I believe this is because the UI displays is displaying state types for this selector. States have both "names" and "types". Types are used for deciding orchestration behavior while names are just labels. `TimedOut` is just a name, so it's not available in the state type filter. We've heard some feedback about this already and are likely to update user-facing filters to operate on names rather than types.

cc @billpalombi just discussed.
cc @zhen0 to confirm that the UI is displaying types here, the notification system is designed to filter on name rather than type, so we can definitely add support for this.

**Comment by zhen0** [comment]
Yes currently most ui state handling is done by state type (completed, running, scheduled, pending, failed, cancelled, crashed).  We have support for the named state "Late" because it is so useful so there is a precedent for adding other state names if this becomes a popular request.

**Comment by efranksrecroom** [comment]
Just to add fuel to this, if a flow ends in a TimedOut state/type, it does not trigger a notification for the states of Failed, Crashed or Late. This means that it just ends up in limbo which is VERY undesirable. It would be very much appreciated if this state/type can be added to the UI or the flow itself set to an actual state, such as failed, which triggers notifications (as a consumer, I don't care about semantics of type v state, this feels like a Prefect internal thing not something a consumer should care about, I just want to be able to trigger my notifications). Without this ability, have a timeout on a flow is a broken experience.

**Comment by EmilRex** [comment]
@zhen0 Bumping this up again... how much work is it to add a `TimedOut` state similar to the `Late` state? I also noticed that `TimedOut` is not available in Automations (which I assume uses the same mechanism as Notifications). Being able to trigger an action on `TimedOut` seems like a great feature to have.

**Comment by zhen0** [comment]
Thanks for bumping @EmilRex - we've made some small changes to state handling so this should be possible.
