### ISSUE TITLE
Add boolean, float, integer blocks

### ISSUE THREAD

**Issue by ahuang11** [PrefectHQ/prefect#6795]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

N/A

### Describe the proposed behavior

I think adding these allow portability of simple checks and settings.

cc @anna-geller since she suggested these blocks!

### Example Use
For example, for boolean block, user can activate debugging by changing it in the UI and rerunning their script.

```
from prefect.blocks.core import BooleanBlock

debug_mode = BooleanBlock.load("debug_mode")
if debug_mode.value:
    ...
```

### Additional context

Should the names be
`Boolean` or `Bool`
`Integer` or `Int`

Both `Float` and `Int` or just `Numeric`?

_No response_

**Comment by madkinsz** [comment]
I think these can all be accomplished by using the generic `JSON` block?

**Comment by ahuang11** [comment]
Yes, that seems to work
![image](https://user-images.githubusercontent.com/15331990/189730984-3130f9ad-2c88-40e0-ab07-f03788d935ab.png)

I don't think it's too intuitive for most users to use JSONBlock for float/int/bool though without specifying a dict.

**Comment by madkinsz** [comment]
We can add some examples to the docstring perhaps? That's just the JSON spec.

**Comment by anna-geller** [comment]
Fair point @madkinsz but then why do we have a String block? Following the same logic, String block shouldn't exist. I think Boolean block is especially useful as it gives users a nice toggle: imagine a single variable that user could leverage to determine whether something is true/false e.g. to build some conditional logic potentially across flows (just one silly example). It seems to give more benefits than harm to have more easy to use blocks based on a given use case, but definitely fair to say that you could do all that in theory with JSON

**Comment by madkinsz** [comment]
I'm not sure I see a strong motivation for the `String` block either to be honest. I think this basically comes down to a question of how specific we want the UI interface to be for editing these. I'm curious for @jlowin's thoughts.

**Comment by jlowin** [comment]
I had a great discussion with @billpalombi and @cicdw on a related topic and while I have been in favor of more granular typed blocks in the past (like these!), I currently believe we should actually not create these at this time (and remove the string block as well). The reason is that we have some work to do on guiding people to the best practices with blocks and encouraging them to use them as a KV replacement for generic (that is, divorced from a specific configuration or system) is likely to add to that confusion. I think we will be able to build better, first class features for those needs in the near future, so I’d rather not introduce them in a suboptimal way now, especially because the JSON block does satisfy the actual user need at this time.  If, however, we see overwhelming adoption of JSON blocks, we can revisit or accelerate the other efforts, but for now I think we should pursue clarity.

**Comment by madkinsz** [comment]
Feel free to open an issue to add examples for use of the JSON block for these types, it'd be a good candidate for a `good first issue` tag if explained well.
