### ISSUE TITLE
UI: Flow runs chart default 24hours gap

### ISSUE THREAD

**Issue by mikkelduif** [PrefectHQ/prefect#6815]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Chart is showing a full week. 
With some +1.000 runs per week, it's not even visible for the full week.
When I'm looking at flow runs I'm typically mostly concerned about what is going on right now, and not necessarily for the past week.

### Describe the proposed behavior

I propose to make the default setting to look 12 hours back and 12 hours forwards such that it is showing a 24hours gap.

**Comment by zhen0** [comment]
Thanks @mikkelduif - we have some work in mind for saving filters that might help you with this issue.

**Comment by mikkelduif** [comment]
Great to hear. I think 24 hours would still be the right choice though :)

**Comment by pleek91** [comment]
@mikkelduif I believe this is no longer an issue since you can now select "Past day" from the date input and you can also save that as a filter and set it as your default. Closing this issue but please let me know if this is still a problem. 
<img width="786" alt="image" src="https://github.com/PrefectHQ/prefect/assets/6200442/123a66b9-329e-47e6-98c8-d3bc11399ae6">
