### ISSUE TITLE
Add `prefect cloud logout` command

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#6966]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Add `prefect cloud logout` to log out of a workspace 

### Describe the proposed behavior

Likely by unsetting the `PREFECT_API_KEY` and `PREFECT_API_URL` back to default

**Comment by hallenmaia** [comment]
Is it necessary to keep any configuration in the profile after logout?

I ask this because the `prefect cloud login` command uses the `PREFECT_API_KEY` as a key to find an existing profile and update it:

https://github.com/PrefectHQ/prefect/blob/465f8e65cecbc20de04737d886b95166a37cd1b9/src/prefect/cli/cloud.py#L175-L178

And it also checks if the profile exists before saving the key to prevent an existing profile from being overwritten:

https://github.com/PrefectHQ/prefect/blob/465f8e65cecbc20de04737d886b95166a37cd1b9/src/prefect/cli/cloud.py#L217-L218

Therefore, setting `PREFECT_API_KEY` to the default value invalidates the entire profile.

If you don't need to maintain some configuration, the `prefect cloud logout` command could be an alias for `prefect profile delete`.

What do you think?

**Comment by madkinsz** [comment]
I'm not sure I love the behavior in the `prefect cloud login` command in the first place. I think the simplest way to implement this is:

- Check if the current profile has an API key set
- If not, error. Maybe display all the profiles that _are_ logged in.
- Otherwise, remove the API key and and API URL from the current profile

**Comment by hallenmaia** [comment]
@madkinsz I was following this path when I came across the errors caused in `prefect cloud login`.

https://github.com/hallenmaia/prefect/blob/32c7033965fe04ef7d4089eb4488569c60905d37/src/prefect/cli/cloud.py#L248-L263

After successfully executing the `prefect cloud logout` command, the `prefect cloud login` command starts to display the error: "Profile 'test' already exists".

I was taking the easy way out 😊. That's why I asked if it was necessary to keep the settings after `logout`.

To implement `logout` I will have to modify `login`.

**Comment by fzhcary** [comment]
this should be closed. i found it in latest version 2.8.4
