### ISSUE TITLE
Prefect UI http://127.0.0.1:4200 "GET / HTTP/1.1" 404 Not Found

### ISSUE THREAD

**Issue by Daemonyz** [PrefectHQ/prefect#6998]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

meet http://127.0.0.1:4200 404 not found

### Reproduction

Macos pip install -U prefect

### Error

http://127.0.0.1:4200 404 not found

### Browers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```

# Copy output of `prefect version` here if hosting your own UI

```
2.4.2+21.g1a43c7d71

### Additional context

2.4.2+21.g1a43c7d71

**Comment by madkinsz** [comment]
Hi! Note when we ask for `prefect version` it actually outputs more content e.g.

```
❯ prefect version             
Version:             2.4.2+27.g391dcf7f4
API version:         0.8.1
Python version:      3.8.3
Git commit:          391dcf7f
Built:               Tue, Sep 27, 2022 5:22 PM
OS/Arch:             darwin/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.31.1
```

It looks like you're running development code instead of an actual release (+21 on your version number shows you are 21 commits of the release tag). The UI is prebuilt for releases, but when developing you need to build it with `prefect dev build-ui`.

cc @zhen0 / @abrookins  we get questions like this a lot. A splash screen would be helpful.
