### ISSUE TITLE
Add the ability to toggle to json input for a list of strings

### ISSUE THREAD

**Issue by zhen0** [PrefectHQ/prefect#7021]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

If a user has a long list of strings, they have to enter them 1 by 1 in the UI.  This can be tedious/too much. 

### Describe the proposed behavior

We allow users to copy/paste a list of strings as json

### Example Use

See https://prefect-community.slack.com/archives/C0192RWGJQH/p1664459923886169

**Comment by richard-alexander** [comment]
Thanks for adding this issue Jenny! I subscribed to get updates on progress.

**Comment by madkinsz** [comment]
@richard-alexander I've also added parametrization of runs via the CLI in #6840 which may be helpful for people with similar requirements :)

**Comment by zhen0** [comment]
@brigidgliwa @billpalombi - after discussing with @pleek91 - we're concerned this could get messy - could we add to the list of things we should have a design/product input for.

**Comment by zhen0** [comment]
We could possibly tackle this in prefect design as allowing users to enter a comma delineated list of strings and ask if they want it as one value or many?

**Comment by tibuch** [comment]
Would this be similar to the functionality of prefect 1 cloud UI where users can toggle between dict and json mode to provide flow run parameters? If this is the case it would not only be strings but any list of parameters.
![image](https://user-images.githubusercontent.com/5450869/205875959-6d7d1a0a-3eda-428f-b794-5deadce5a119.png)


This would be a very useful feature for me in Orion UI. Because it reduces number of clicks drastically if I can just copy past flow-run parameters of a previous flow and only update the one parameter I want to change. Instead of having to type all parameters again.

**Comment by richard-alexander** [comment]
Yes @tibuch, some solution similar to the V1 input is what we're going for in order to reduce manual effort when starting a flow with many parameters, or a single list/dict parameter with MANY values.

**Comment by zhen0** [comment]
This is now possible in the UI. Marking as closed but let us know if there's anything I've missed.
