### ISSUE TITLE
DateTime block created via Python shows value None in Cloud and self-hosted UI rather than true value

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#7392]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

Created a block with Python code. Block does shows "None" for the value in the Cloud and self-hosted UI, even though the a DateTime value is retrievable.

### Reproduction

```python

from prefect.blocks.system import DateTime
from datetime import datetime


dt_block = DateTime(value=(str(datetime.today())))
dt_block.save("dt6", overwrite=True)

v = dt_block.load("dt6")
print(v)
```

terminal output:
```
DateTime(value=datetime.datetime(2022, 10, 31, 15, 10, 45, 381469))
````

### Error

<img width="414" alt="Screen Shot 2022-10-31 at 3 14 55 PM" src="https://user-images.githubusercontent.com/7703961/199091069-ca51c6f9-692c-4780-98f1-d0997bfabbfa.png">

### Browers

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```Text
Version:             2.6.5
API version:         0.8.3
Python version:      3.10.5
Git commit:          9fc2658f
Built:               Thu, Oct 27, 2022 2:24 PM
OS/Arch:             darwin/arm64
Profile:             jeffmshale
Server type:         cloud
```
```


### Additional context

_No response_

**Comment by zhen0** [comment]
UI handling should be fixed in https://github.com/PrefectHQ/orion-design/pull/788

The UI was throwing an error from the example provided because it expects DateTime to provide a timezone but actually that's not required.  This could create some confusion because an ISO 8601 string assumes local time when none is provided. So if a user has their timezone set in the UI to something different to their local machine, the same block will show different times.
