### ISSUE TITLE
Remove "Deployments" filter from Flows page

### ISSUE THREAD

**Issue by billpalombi** [PrefectHQ/prefect#7402]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

The Flows page includes a Deployments filter. This filter concatenates all of the deployment names from all flows, but does not de-duplicate them. If multiple flows have a deployment with the same name, that deployment name will be duplicated. Because deployments are independent, sub-flow concepts, this filter does not add any value over the flow search box. 

### Describe the proposed behavior

Lets remove this filter for now. Separately, we can consider how to best give users ways to organize their flows, possibly though tags or another grouping concept.

**Comment by pleek91** [comment]
@billpalombi the duplication issue is interesting but wouldn't that apply to the flows themselves as well? For example on the flow runs page we allow users to filter by deployment and/or flow. But if a user has a duplicate name for a flow or deployment they'll both show up in the dropdown because they are different as far as the system is concerned (they have different ids).

**Comment by madkinsz** [comment]
`flow-name/deployment-name` is our standard for identifying deployments so that makes sense to me!

**Comment by anna-geller** [comment]
I just wanted to open an issue for the same, but not to remove it but **only to de-duplicate** it. Both the flow name filter and deployment name filter make sense individually if they are deduplicated. Here are some use cases:

1. I have a parametrized flow named "scraper", but I created multiple scheduled deployments for this flow, each with different parameter values to scrape. As a user, I would love to be able to search for the flow name "scraper" and find all runs, both ad-hoc runs and those from all deployments related to the same flow. 
2. Imagine that I use a deployment name to distinguish between a "default" deployment in a local process and a deployment on a prod K8s cluster named "custom" or "k8s". It would be nice to be able to filter for "default" to only find default deployments and find all flow/deployment combinations related to "default" deployments

I kind of thought that this is one of the value props of decoupling flows from deployments, so curious if we can still keep both filters but only deduplicate them @billpalombi - perhaps a good solution here would be to keep both filters but only add the flow name in front of the deployment name?

Here is the ideal UX from a user perspective: 
![image](https://user-images.githubusercontent.com/86264395/200320169-7f4af8fe-776a-4da6-b393-025308a87990.png)

@billpalombi if you agree that we shouldn't remove this filter, let's adjust the issue title so that users don't panic that their beloved filter is getting removed :)

**Comment by billpalombi** [comment]
As I understand it, we are having two conversations:
1. Removing the "Deployments" filter from the "Flows" page, which I still support and is the focus of this ticket
2. Resolving duplication issues with the "Deployments" filter from the "Flow runs" page. No one ever suggested removing it. I support adding the flow name prefix to the deployment names on that page.

**Comment by anna-geller** [comment]
fully aligned, sorry for the confusion, didn't even realize this filter exists on the Flow page (I've never used that)

should I create a separate issue for deduplication on the flow run page?

**Comment by anna-geller** [comment]
Added here: https://github.com/PrefectHQ/prefect/issues/7459

**Comment by billpalombi** [comment]
Thank you @anna-geller!
