### ISSUE TITLE
Update to task input tab on the task run page

### ISSUE THREAD

**Issue by zhen0** [PrefectHQ/prefect#7547]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

Currently the task run page task input tab shows the correct keys but all values are empty.  There's a ticket to track api work for that here: https://github.com/PrefectHQ/prefect/issues/6627 Until that work is done, we should remove the values shown in the tab and only show the keys so that we're not giving the misleading suggestion that all task inputs are empty arrays. 

<img width="1293" alt="image" src="https://user-images.githubusercontent.com/40272060/202204368-c56d9506-1246-4e78-84f9-ea9755858e3c.png">

### Reproduction

Create a flow with tasks and run it - go to the task run page and look at the task inputs tab

### Error

<img width="1293" alt="image" src="https://user-images.githubusercontent.com/40272060/202204629-ac8d0e9c-5fdf-4e49-89be-19e7dd238eb6.png">

The [] section is misleading

### Browers

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

**Comment by madkinsz** [comment]
Note clarification at https://github.com/PrefectHQ/prefect/issues/6627#issuecomment-1372886667 — I do not believe this issue is following correct assumptions.

**Comment by jmesterh** [comment]
Just want to note as a new user -- this page _is_ misleading, I thought this was a bug or I had misconfigured Orion and my inputs were being lost. I'm testing an ETL and was hoping I could see what table the task was working on based on the inputs shown on this screen.

**Comment by aeisenbarth** [comment]
I came here because this issue describes what I am observing now, although it is marked as resolved and the solutions are merged.

I had to follow all merge requests links _and_ read between the lines to come to the conclusion that for now, only the keys are meaningful and the empty arrays are placeholders (?). This is absolutely not clear from the info modal. It mentions that it can include constants, parameters or other tasks, but no word about whether it means only the keys or whether we should also expect values. In that regard, https://github.com/PrefectHQ/prefect/pull/8295 does some clarification for other issues, but I don't feel it resolves this issue here.

**Comment by amgcc** [comment]
This is a really bad design, as a new user, I spent a bit of time scratching my head trying to make sense of what a "Task Input" could be and assuming I was using the tools incorrectly.  I see the issue is closed but this feature doesn't work as expected.
