### ISSUE TITLE
Add a `cache_key_fn` utility to support file-dependent task caching similar to targets in v1

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#7646]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Some users need guidance during migration from v1 targets. We could add a cache key function utility to make that easier for them

### Describe the proposed behavior

Similar to `from prefect.tasks import task_input_hash`, add a function for file-based caching

we could leverage file system blocks here as well

### Example Use

https://discourse.prefect.io/t/replicating-prefect-1-result-target-functionality-in-prefect-2/1959/2

**Comment by anna-geller** [comment]
from Michael: you can set the cache_key_fn to `Path("your-target").exists` - but it won't load the object as targets did

**Comment by madkinsz** [comment]
Note you'll need a wrapper since we'll pass context information to the given function and `exists` won't accept it :)

**Comment by haddon-korinek-ent** [comment]
> from Michael: you can set the cache_key_fn to `Path("your-target").exists` - but it won't load the object as targets did

Would this end up just doing a look up in the SQL database for "True"/"False" strings? We're looking to avoid the SQL database altogether since it doesn't allow for branching cache usage.

**Comment by madkinsz** [comment]
🤦 sorry you're totally right — that's not a valid cache key at all. 

Can you explain this more?

> We're looking to avoid the SQL database altogether since it doesn't allow for branching cache usage.

**Comment by haddon-korinek-ent** [comment]
> Can you explain this more?

Sure! We use the Prefect1 target caching as a way to share cache hits by turning the `Result` class into a `TieredResult` class which will check for targets at a `read_only_uri` before checking for targets at a `read_write_uri`.

ex.

Alice runs her flows and outputs results to `gs://home-alice`.

Bob has read only access to `gs://home-alice` but has read/write to `gs://home-bob`.

Bob can then check out Alice's code and use `gs://home-alice` as the `read_only_uri`. If Bob only modifies a small section of the flow, he can re-run the entire Flow and get cache hits from Alice's bucket for everything he didn't change.

**Comment by gabcoyne** [comment]
Example use:
We use a concept of tiered caches which can come from various uris. Typically, this is just in the form of having a "read_write_uri" and a "read_only_uri" pointed at different buckets. If live dev/prod flows are constantly ingesting and crunching vast amounts of data that isn't feasible to be re-ran by each individual person, the results from those live flows can write caches/results in a centralized place. Every person can then point their "read_only_uri" at a centralized bucket and point their "read_write_uri" at their own personal bucket.

Alice:
read_write_uri = gs://alice-bucket/foo-research-X/cache
read_only_uri = gs://shared-prod-bucket/foo-model/cache

Bob:
read_write_uri = gs://bob-bucket/foo-research-Y/cache
read_only_uri = gs://shared-prod-bucket/foo-model/cache


As long as you don't change your local code away from what was running in the live environment, you will get all cache hits. If you make any changes locally and re-run, you only end up running the affected tasks and those results get written to your personal bucket. If you re-run again with no further changes, you will get a mix of cache hits from the live environment and cache hits from our local environment.

This makes it so everyone can work on any part of the many flow-of-flows without worrying about stepping on each others toes. It relieves pressure from researchers by letting them have long-lived experiment branches that still can pull from a shared cache. People can also point their "read_write_uri" at a "research sharing" bucket and populate a set of results/caches for other researchers to consume from.

Another benefit is that if Prefect2 Cloud were to go down we need someway to keep our system alive. If all of our caches live in a SQL database in someone else's cloud, there's nothing we can do to recover currently as it isn't possible to rebuild all of our caches in a reasonable amount of time. With the file-based approach, all our caches are still reachable and we would be able to trigger our flows on a local prefect cluster and get cache hits.

We're basically looking for a Block based approach for Caching (like Result storage!) that combines ReadOnlyFileSystem and ReadWriteFileSystem Blocks.

**Comment by taylor-curran** [comment]
Example Implementation:
```
import asyncio
import functools
import hashlib
import json
import prefect.context
from prefect.flows import P, R, Flow
from prefect.tasks import Task

# This could be Redis, S3, GCS, local files, etc.
cache = {}


def get_target_hash(target):
    return hashlib.md5(
        json.dumps(target, sort_keys=True, ensure_ascii=False).encode("utf-8"),
        usedforsecurity=False,
    ).hexdigest()


def exists(target_hash):
    return target_hash in cache


def read(target_hash):
    return cache[target_hash]


def write(target_hash, res):
    cache[target_hash] = res


def targetcached(func):
    """
    This isn't ideal because it still requires sending a Task into a Running state, which eats into
    Task Concurrency limits and requires keeping track of cached tasks in the database.
    At a large scale (100k+Tasks), ideally we would have a way to completely avoid creating database
    entries for cache hits.
    """
    @functools.wraps(func)
    async def targetcached_wrapper(*args, **kwargs):
        context = prefect.context.get_run_context()
        target = {
            # this isn't fully accurate to pin hashes to tasks/flows, but works for this example
            "_context_version": context.flow.version if hasattr(context, "flow") else context.task.version,
            "_cache_args": args,
            "_cache_kwargs": kwargs
        }
        target_hash = get_target_hash(target)
        if exists(target_hash):
            print(f"cache hit for target_hash={target_hash}. target={target}")
            return read(target_hash)

        print(f"cache miss for target_hash={target_hash}. target={target}")
        res = await func(*args, **kwargs)

        write(target_hash, res)

        return res

    return targetcached_wrapper


def customflow(fn):
    return TargetCacheableFlow(fn=fn)


class TargetCacheableFlow(Flow[P, R]):
    def __init__(self, fn, *args, **kwargs):
        super().__init__(fn, *args, **kwargs)
        # After the super init is the only place you can successfully wrap underlying fn.
        self.fn = targetcached(self.fn)


def customtask(fn):
    return TargetCacheableTask(fn=fn)


class TargetCacheableTask(Task[P, R]):
    def __init__(self, fn, *args, **kwargs, ):
        super().__init__(fn, *args, **kwargs)
        # After the super init is the only place you can successfully wrap underlying fn.
        self.fn = targetcached(self.fn)


@customtask
async def task_1(input1):
    print("inside task 1")
    return f"output-{input1}"


@customflow
async def foo_flow(input_foo):
    print(f"inside foo flow {input_foo}")
    call1_res = await task_1(input_foo)
    # should be cached
    call2_res = await task_1(input_foo)
    return {
        "call1_res": call1_res,
        "call2_res": call2_res
    }


@customflow
async def parent_flow():
    flow_call1_res = await foo_flow("foo")
    # should be cached
    flow_call2_res = await foo_flow("foo")
    print("finished")


if __name__ == "__main__":
    asyncio.run(parent_flow())
```

**Comment by TimoVink** [comment]
Hi all! I came across this ticket while trying to design a great developer experience using `prefect` myself. We have a mechanically-similar need to what @gabcoyne is describing with regards to "tiered caches", though for a slightly different purpose. Sharing here in case it's valuable for you to see how the feature might be used:

Imagine we have a long-running flow in a remote Production environment that fails several hours (and dozens of tasks) into a run. How can I as a developer efficiently debug/fix this flow? If the bug is nontrivial then I probably want to reproduce the issue locally so that I can attach a debugger.

`prefect` has _excellent_ support for running flows locally against an ephemeral API/db, but since the flow failed hours into a run, it may be very painful for me to locally get a flow run in the same state as it got in remotely. _Wouldn't it be nice if_ I could write something like:

```python
# Flow code here. Omitted.

if __name__ == '__main__':
    run_using_remote_results(
        flow=my_flow,
        flow_run_name='magnificent-orca',
        remote_cache=my_production_storage_block,
        local_cache=local_machine_storage_block
    )   
```

Where the behaviour is:
1. The remote (in this case a readonly Production) cache is replicated to my local (i.e. readwrite) cache
2. A flow run is started against my local/ephemeral API pointing at my local cache
3. Flow will see many task results are already cached in my local cache, and essentially quickly skip ahead to the task that failed, allowing for a very easy/fast debugging experience. **No** data is written back to the Production storage -- this is all against my local ephemeral API/DB/cache.
4. I fix the bug, push my code, get my reviews, merge, and deploy to Production.
5. Click `Retry` on the original failed flow -- which will now succeed!

I realize this is a bit hand-wavy, and I don't expect `prefect` to provide me with this mythical `run_using_remote_results` function natively, but I believe this ticket could give me the building blocks needed to write it myself for my team. Something like: If I used `{flow_run_name}/{task_input_hash}` as the cache key and I could use file-dependent result caching that does not require any state in the prefect DB, then I could fill in the blanks around the cache synchronization myself (perhaps by writing a custom `FileSystem` implementation).

Starting to talk about things I don't fully understand here: But I believe the main issue preventing me from implementing this today is that the caching mechanism has state in the database, whereas I would need a way to indicate that I want cached results to be used merely using the presence of data in the right location in cache.

**Comment by limx0** [comment]
I'm also interesting in this type of workflow. 

Regarding your workflow @taylor-curran - ideally we wouldn't actually `read` the data from storage until it's required in Prefect. I'm imagining a flow `A -> B -> C` where A & B are cached, but C is not; We don't want to read A from the cache, its unnecessary. 

It would be great if there was a hook in prefect to allow returning a `Cached` state without reading data (via a cheaper call like `exists`), and the data was only loaded when its about to be passed to a task that's actually required to be run (similar to how the `Futures/State` interface works - data is only collected when its about to be used).

Would this be difficult to do?

@madkinsz may have some thoughts here also?

**Comment by AndreeaConstantin** [comment]
what are the updates for targets in prefect 2 ?
