### ISSUE TITLE
Allow reaction to flow cancellation

### ISSUE THREAD

**Issue by j-tr** [PrefectHQ/prefect#7766]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

When canceling an active flow run, the underlying infrastructure is killed by a sigterm signal, followed by a sigkill after a grace period (different implementation but same concept for different infra types), resulting in the termination of all tasks. In order to shut down gracefully, a flow would need to react to the sigterm signal and exit by itself.
As python signal handling can only be set up in the main thread, this cannot be set up from within a prefect flow. Consequently, the flow cannot react to sigterm and is eventually killed non-gracefully, potentially leading to number of unwanted side effects like corrupted files, ongoing external queries, etc.

### Describe the proposed behavior

Allow a flow or task to react to infrastructure termination within the grace period. 
Potential solution approaches:
- add functionality that allows registration of a sigterm handler via orion
- add flow parameter to specify a callback that is called on flow cancellation

### Example Use

When running tasks that call external services, these external services may continue running even if a flow is canceled. Reaction to flow cancellation would enable calling the external service and signaling termination.

**Comment by madkinsz** [comment]
Thanks for the issue!

@bunchesofdonald I believe this falls under the "engine handling of cancellation signals" goal.

I think to start, we'll handle this as if an error was raised in the flow itself. Separately, we can consider adding an option to flows to push additional contexts so code can be run on flow start/exit.

I'm also doing some separate work to run user code in the main thread instead of a worker.

**Comment by david-elliott-deliveroo** [comment]
➕ 1 to this issue - in Prefect 1.0 this was trivial with a flow state handler (when flow state moved to Cancelled, run some final python code) but is lacking from the 2.0 cancellation implementation, so would love to see some functionality to include this!

Side note - Cloud 2.0 Automations don't seem to be the fit for these use cases, as we need to be able to run some custom python code (typically cleanup code) upon flow cancellation, rather than just take a simpler action such as notifications or triggering another flow

**Comment by madkinsz** [comment]
This will be partially addressed by #7887

**Comment by serinamarie** [comment]
> ➕ 1 to this issue - in Prefect 1.0 this was trivial with a flow state handler (when flow state moved to Cancelled, run some final python code) but is lacking from the 2.0 cancellation implementation, so would love to see some functionality to include this!

@david-elliott-deliveroo  👋  An `on_cancelled` flow run state change hook went into last week's [release 2.10.11](
https://github.com/PrefectHQ/prefect/blob/main/RELEASE-NOTES.md#enhancements) along with [documentation](
https://docs.prefect.io/latest/concepts/states/#state-change-hooks) which may be useful to you and others.

**Comment by serinamarie** [comment]
@j-tr, please feel free to reopen if the above did not resolve your issue. Thanks!
