### ISSUE TITLE
links are broken in v1 documentation

### ISSUE THREAD

**Issue by lukeorland** [PrefectHQ/prefect#7801]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

e.g., each of the hyperlinks in paragraph under https://docs-v1.prefect.io/orchestration/faq/upgrade_environments.html#daskkubernetesenvironment
lead to a 404 page

### Reproduction

```python3
This target url is a 404 Not Found.
https://docs-v1.prefect.io/orchestration/faq/run_config.html#ecsrun
```

### Versions

```Text
0.15.13
```

**Comment by manic-miner** [comment]
The issue applies to multiple links on https://docs-v1.prefect.io/orchestration/faq/upgrade_environments.html
not just the paragraph linked by @lukeorland 

- These dead links point to wrong subdirectory:  /faq/ instead of /flow_config/
- Also some of the links point to run_config.html but the correct page is run_configs.html

Example: https://docs-v1.prefect.io/orchestration/faq/run_config.html#kubernetesrun
should be:
https://docs-v1.prefect.io/orchestration/flow_config/run_configs.html#kubernetesrun

**Comment by madkinsz** [comment]
I would welcome and review any contributions here! This is a great way to get familiar with making pull requests to an open source library.

**Comment by manic-miner** [comment]
I'm a bit confused how to do that because v1 docs are not included in this repository.

**Comment by madkinsz** [comment]
@manic-miner thanks for pointing that out! I know it's a bit confusing since we're managing multiple versions here. Prefect 1 lives in the [1.x branch](https://github.com/PrefectHQ/prefect/tree/1.x). To contribute, you need to branch off of that and set it as the base.

**Comment by Vision1224** [comment]
Is this issue still open?

**Comment by billpalombi** [comment]
No, this issue should be closed.
