### ISSUE TITLE
Respect user-configured logging format in prefect flow-run logs CLI

### ISSUE THREAD

**Issue by serinamarie** [PrefectHQ/prefect#8001]
Follow-up to https://github.com/PrefectHQ/prefect/pull/7982

### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently we have [hard-coded the logging format](https://github.com/PrefectHQ/prefect/blob/main/src/prefect/cli/flow_run.py#L168) when using `prefect flow-run logs` CLI.

### Describe the proposed behavior

It would be great to reuse the format from the logging config instead of hard-coding one.

**Comment by madkinsz** [comment]
Note this may not be feasible, but would be best practice if doable.

**Comment by ohadch** [comment]
As I only want to initiate a mutual thinking process, I will suggest a solution which I'm not sure is the best approach at all.

One way to do it is to accept an optional "pythonic" template from the user as follows:

```
prefect flow-run logs <uuid> -f "{log_timestamp} - {log_level} - Flow run '{flow_run_name}'"
```

This will result in something like:

```
2022-12-24 07:56:07.242 - INFO  - Flow run 'platinum-bat'
```

In order to do so, we could use the dict representations of the flow run and the log, and pass them to the template, like:

```
user_provided_template.format(log_level, **{
    **{f"log_{key}": value for  key, value in log.__dict__.items()},
    **{f"flow_run_{key}": value for  key, value in flow_run.__dict__.items()},
})
```

One unanswered question here is how to provide custom time formats (and whether that's important for the first phase).
Another one is that although the format is python style, I'm not sure it's intuitive enough.
