### ISSUE TITLE
search is buggy and stuttering

### ISSUE THREAD

**Issue by yaronlevi** [PrefectHQ/prefect#8143]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

Hi (-:
The bug is shown here:

https://discourse.prefect.io/t/search-box-is-buggy/2175

### Reproduction

Happens in the Cloud UI

### Error

Happens in the Cloud UI

### Browers

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

**Comment by madkinsz** [comment]
Hi @yaronlevi could you please attach the video here and include information on which browser was used?

**Comment by yaronlevi** [comment]
Sure,

![25ab7710621711230ee3ce02623fdcbf36aad5f7](https://user-images.githubusercontent.com/5398977/211907218-e027a089-9f6c-491a-b182-9d15f83eba31.gif)

used Chrome:

![CleanShot 2023-01-11 at 22 07 56@2x](https://user-images.githubusercontent.com/5398977/211907356-4d1ce135-6b32-43f8-a400-0d11cdce5812.jpg)

Also we have 91 Deployments which I think is the origin of the problem.

**Comment by zhen0** [comment]
Hi @yaronlevi thanks for the report. We saw a similar issue in QA and added an update which should now be released.  Can you let me know if you're still seeing this?  If you are, we'll dig in a bit further.

**Comment by yaronlevi** [comment]
@zhen0 yes, this is still happening.

**Comment by zhen0** [comment]
Thanks @yaronlevi - adding to our backlog to investigate.

**Comment by japerry911** [comment]
Just adding a bump: we started experiencing this today as well in chrome, with the same Chrome version as yaronlevi

Thank you for adding to backlog zhen0 !

**Comment by Ogaday** [comment]
I've been noticing the same thing in different search fields on Firefox [109.0.1 (64-bit)] for some weeks now. For instance, the search field on the flow-runs page (screengrabbed today):

![prefect-search-buggy](https://user-images.githubusercontent.com/6689770/215853776-cc2b8b12-ad3e-4e9f-b6e1-5aac6d339316.gif)

(Note I'm not entering any backspace characters. I tried typing `myflow I can't type anything`. and you can see the characters appearing and disappearing.)

I logged into prefect in a private browser, without extensions enabled and the bahviour was buggy, but also varied between different search fields:

- Flow runs search box: As in the gif above - very buggy with characters disappearing. Note we have over 10k flow runs.
- Flows: Same behaviour as flow runs. Impossible to type, as characters disappear immediately. Note we have 79 flows.
- Deployments: Different behaviour (perhaps due to the update?) - Most of the characters do show up after a 5 second delay. There is still an issue with some or all characters disappearing occasionally, but it's easier to type in that the flows* pages. Note we have 56 deployments.
- Queues & Blocks search bars: No issues. Note we have 25 blocks and 2 queues.

**Comment by yaronlevi** [comment]
Just making sure you know it's also happening in the Flows search screen:

![CleanShot 2023-02-06 at 09 25 14@2x](https://user-images.githubusercontent.com/5398977/216910184-4de349bd-e629-4852-874d-dfae3e36f74e.jpg)

Thanks!

**Comment by zhen0** [comment]
This should be addressed by https://github.com/PrefectHQ/prefect/pull/8277 (And in my local check of that it looks good.)

**Comment by japerry911** [comment]
Thank you @zhen0 !!!

**Comment by pleek91** [comment]
Closed by https://github.com/PrefectHQ/prefect/pull/8525
