### ISSUE TITLE
Table already exists error

### ISSUE THREAD

**Issue by Param-29** [PrefectHQ/prefect#8351]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I had installed prefect before, not sure why but when re-installed I saw this issue.

### Reproduction

```python3
Try installing prefect in a different virtual env, (multiple prefects in different different envs)
```

### Error

```python3
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table block_schema_reference already exists
[SQL: 
CREATE TABLE block_schema_reference (
        id CHAR(36) DEFAULT (
    (
        lower(hex(randomblob(4))) 
        || '-' 
        || lower(hex(randomblob(2))) 
        || '-4' 
        || substr(lower(hex(randomblob(2))),2) 
        || '-' 
        || substr('89ab',abs(random()) % 4 + 1, 1) 
        || substr(lower(hex(randomblob(2))),2) 
        || '-' 
        || lower(hex(randomblob(6)))
    )
    ) NOT NULL, 
        created DATETIME DEFAULT (strftime('%Y-%m-%d %H:%M:%f000', 'now')) NOT NULL, 
        updated DATETIME DEFAULT (strftime('%Y-%m-%d %H:%M:%f000', 'now')) NOT NULL, 
        name VARCHAR NOT NULL, 
        parent_block_schema_id CHAR(36) NOT NULL, 
        reference_block_schema_id CHAR(36) NOT NULL, 
        CONSTRAINT pk_block_schema_reference PRIMARY KEY (id), 
        CONSTRAINT fk_block_schema_reference__parent_block_schema_id__block_schema FOREIGN KEY(parent_block_schema_id) REFERENCES block_schema (id) ON DELETE cascade, 
        CONSTRAINT fk_block_schema_reference__reference_block_schema_id__block_schema FOREIGN KEY(reference_block_schema_id) REFERENCES block_schema (id) ON DELETE cascade
)
]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

### Versions

```Text
Version:             2.7.10
API version:         0.8.4
Python version:      3.10.9
Git commit:          f269d49b
Built:               Thu, Jan 26, 2023 3:51 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.40.1
```

### Additional context

I have been learning prefect through Data-Enginnering Zoomcamp 
* https://github.com/DataTalksClub/data-engineering-zoomcamp/
*Please drop a star, it would mean a lot* 

We found a simple fix in the community is to use
`rm /home/$USER/.prefect/orion.db` to clear the data-base and restart

Perhaps we could support more than one named servers? or a different way to solve this problem?

**Comment by serinamarie** [comment]
Hi @Param-29, thanks for the issue! It sounds like there was an incompatible migration due to installing a different version of Prefect, as mentioned in this Discourse post: [
When I try to start Orion, I get “sqlite3.OperationalError: table flow already exists” - how to troubleshoot this?](https://discourse.prefect.io/t/when-i-try-to-start-orion-i-get-sqlite3-operationalerror-table-flow-already-exists-how-to-troubleshoot-this/1933), which has more details on how you can manually upgrade/downgrade the database. We also have a free-tier on [Prefect Cloud](https://www.prefect.io/cloud/) that I would encourage you to check out!

Please also see this Discourse post on [Managing multiple environments (dev, staging, production)
](https://discourse.prefect.io/t/what-are-the-components-of-prefect-2-0-architecture/909) for more discussion and information around this.
