### ISSUE TITLE
Security hardening

### ISSUE THREAD

**Issue by xyxz-web** [PrefectHQ/prefect#8395]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I have the feeling that there isn't enough attention regarding security issues in prefect.
For example, spawned kubernetes pods have an Environment Variable containing the API-Key in plaintext.
This means anyone with access to the Kubernetes Metadata can get full access to the API and do pretty much anything they want with the corresponding prefect instance.
The correct way would be to create a secret containing the API key and assigning the secret.
This is really basic kubernetes security, and the fact that it wasn't implemented is what made me decide against using prefect in its current state.

### Reproduction

```python3
Setup a KubernetesJob and run it
```

### Versions

```Text
2.7.9
```

**Comment by jmg-duarte** [comment]
Don't Blocks do what you want?
https://docs.prefect.io/concepts/blocks/?h=secrets#secret-fields

**Comment by xyxz-web** [comment]
In this case no, because this is set by prefect itself.

**Comment by madkinsz** [comment]
Hi! Thanks for opening an issue, we take security very seriously at Prefect.

Prefect is designed for incremental adoption. Many of our users run single-tenant clusters where moving this API key into a secret is not necessary. For our users that are managing more complex clusters with higher security requirements, you _can_ use a secret:  see [this comment](https://github.com/PrefectHQ/prefect/issues/7185#issuecomment-1279392762) for the example. While it may seem like this is a basic thing to implement, it's actually quite difficult for us to create the secret for you because we allow every flow run to have fully customized infrastructure options. Each flow run manages its own infrastructure independently from the other runs and there is not a simple way for it to know if it should share an API key secret with other runs. The security implications of a flow run using the incorrect API key are quite concerning. We're doing some work to allow the agent to take more control over runs, which would make this change more feasible and we're tracking it in the meantime: see https://github.com/PrefectHQ/prefect/issues/7185 which was opened by a Prefect engineer.

As noted above, this issue is a duplicate so I'm going to close it in favor of the one with the examples.

**Comment by xyxz-web** [comment]
Hi @madkinsz ,


thanks for showing a way how to work around this.
However, if you take security seriously I do expect this kind of information to be part of the documentation, ideally as part of a security hardening section.
I neither have to time nor the will to search around all available prefect resources just in hope to be able to find all security relevant information.

Best regards
Niklaus
