### ISSUE TITLE
Expose interface for using saved blocks as flow run parameters

### ISSUE THREAD

**Issue by znicholasbrown** [PrefectHQ/prefect#8528]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Blocks are a flexible (and encouraged!) way to utilize shared information/connections/credentials between flows; right now we don't provide a way to use blocks as inputs.

### Reproduction
The following will build:

```python3
from prefect import flow
from prefect_bitbucket.credentials import BitBucketCredentials

@flow
def my_flow(
  bb_creds: BitBucketCredentials
):
  # do something with bb_creds

```

BUT there's no way to actually hydrate the block from a deployment. The way to handle this right now would be to pass a reference to the block instead:

```python
from prefect import flow
from prefect_bitbucket.credentials import BitBucketCredentials

@flow
def my_flow(
  bb_creds_ref: str
):
  bb_creds = BitBucketCredentials.load(bb_creds_ref)
```

### Versions

```Text
All versions ^2.0
```

**Comment by serinamarie** [comment]
Thanks for the issue! I interpreted your issue as one of a few things:
1. A block type such as `JSON` is permitted as a flow parameter but isn't usable to create a new block within a flow.
2. An existing block such as `my-json-block` cannot be loaded as a flow parameter.

However, since I didn't have an issue running such flows nor with building deployments and running them in either case, I don't think interpreted your issue correctly. Can you provide more detail about expected behavior?

Flows for reference:
1.
```python
from prefect import flow
from prefect.blocks.system import JSON

@flow()
def my_flow(
    my_json_data = JSON.load("my-json-block"),
):
    print(my_json_data)

if __name__ == "__main__":
    my_flow()
```

2. 
```python
from prefect import flow
from prefect.blocks.system import JSON

@flow()
async def my_flow(
):

    # create a new block using JSON block
    json_block = JSON(value={"the_answer": 42})
    await JSON.save(json_block, name="my-new-block")

if __name__ == "__main__":
    import asyncio
    asyncio.run(my_flow())
```

**Comment by madkinsz** [comment]
I don't think this is a bug; this looks like an enhancement request perhaps?
