### ISSUE TITLE
Add info from agent to logs as well as state message when a flow run is not picked up

### ISSUE THREAD

**Issue by kingsleyb** [PrefectHQ/prefect#8557]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

When a flow run fails to run it doesn't generate any flow logs, and therefore there are no flow logs to display on the screen. 

When looking to troubleshoot why the flow did not run there is useful information captured in the state message, which is shown in the details tab. This however, is not an obvious place to look and the flow run failure is not clear due to the lack of logs shown in the logs tab.  

### Reproduction

This was seen in a PACC exercise, when running a flow in a docker container. There was a failure somewhere between the agent and the infrastructure. The agent had logs but the flow failed to run in the docker container. 

### Error

Screenshots to follow

### Browers

- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

**Comment by kingsleyb** [comment]
![Screenshot from 2023-02-16 12-07-38](https://user-images.githubusercontent.com/11180775/219438073-2f49b0b4-031d-4f98-803c-d5e60f2f3cd1.png)

**Comment by taljaards** [comment]
I agree, this would be nice. Perhaps you can also show the state message(s) in between the logs, just formatted differently? Excuse this quick & dirty MS paint mockup:
![image](https://user-images.githubusercontent.com/6089256/219467034-d82c8c58-6840-41b9-9967-2311c2279b9c.png)

Some thoughts:
- Show each flow state in between the logs, as if it was a log entry, but perhaps formatted slightly different (I used the background from the timeline). (I said _each state_, because a flow's state can change/be changed.
- Show the final state message on the right (current behaviour), but when #8448 is merged in, make it clickable, taking you to the state message entry in the "logs view".

**Comment by zhen0** [comment]
@madkinsz - if it's low lift to add that I think that would be great.  It feels more logical to have it as part of the logs as that's where most users would look first for issues.  

If it's not simple, we could try some ui logic to show state messages in their own tab but the UX of that doesn't feel so good.

**Comment by zhen0** [comment]
Since we added the state message back to the UI, I'm re-labelling as medium priority @billpalombi - feel free to change if you think this should still be a high priority
