### ISSUE TITLE
Add tasks to context

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/prefect#889]
Following up from a conversation in #887 and related to #884, we might consider putting the entire `task` object into context, so it could be used by users in arbitrary ways. @cicdw raises a good point that some tasks may not have picklable attributes, but I think we could mitigate that by placing it in context "early" -- before any non-picklable attributes are instantiated. I'm assuming that's possible because the task itself is necessarily picklable in order to work with Dask.

**Comment by cicdw** [comment]
After further reflection on this, is there an actual use case here?  I'm not against it, but when I started to think about it, it felt unnecessary.  Inside a task created via `@task`, there aren't many "interesting" attributes that one would want at runtime (other than the `logger`).  Most other attributes are either bookkeeping or trigger / retry related.  Users can affect task behavior at runtime more explicitly via `RETRY` signals and other Prefect primitives.  Otherwise, if you want interesting attributes, use a Task class.  

Just curious - if there's a use I'm happy to implement this (I'll probably store the task under the key `"self"` to mimic class-based syntax).

**Comment by jlowin** [comment]
I've got a use case but it's admittedly weak -- if your task calls a function, and that function needs an attribute of your class, you'd have to pass the task down to the children functions because it isn't in context. In the absence of something stronger happy to table this.

**Comment by cicdw** [comment]
Per the discussion [in this PR](https://github.com/PrefectHQ/prefect/pull/1405) I'm going to close this issue.

If a user needs access to their Task instance for doing work, they can implement a custom `Task` subclass and reference `self`.
