### ISSUE TITLE
After deploying a flow, display a UI link to see it immediately

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/prefect#899]
UX improvement: after calling `flow.deploy()`, present a message to the user with a link to viewing the flow in the UI.

**Comment by dylanbhughes** [comment]
I was actually thinking about this while I was writing https://github.com/dylanbhughes/reddit-daily. It would be great to have a link to the UI in Cloud in the flow context maybe? For example, let's say I'm sending myself a slack message because one of my reference tasks failed, it would be great to include the link to the Cloud UI for the failed task run.

**Comment by cicdw** [comment]
@dylanbhughes is the URL completely determined by the Flow run ID?  If so, context already has `flow_run_id`.

**Comment by dylanbhughes** [comment]
@cicdw It might be nice to have a `flow_run_cloud_url` string in context, though. So people don't have to construct it manually

**Comment by bnaul** [comment]
Related to this: right now running from the CLI prints:
```
Flow Run ID: 036aec16-e184-4c83-afd4-6fa36447a249
```
Seems more useful to print a link directly to the run in the UI: https://cloud.prefect.io/replica/flow-run/036aec16-e184-4c83-afd4-6fa36447a249

Thoughts?

**Comment by joshmeek** [comment]
@bnaul Yeah that's exactly what we want! Theres a few CLI enhancements coming down the pipe and this will be included

**Comment by cicdw** [comment]
Yea that makes sense; the only thing that has me hesitant is that for all of this we'd need to make an additionally query for your tenant slug.  Obviously not a big deal, but it'd be nice to avoid making that.
