### ISSUE TITLE
`on_pending` flow run state change hook

### ISSUE THREAD

**Issue by billpalombi** [PrefectHQ/prefect#9347]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently, I cannot initiate arbitrary logic when a flow run enters a RUNNING state. 

### Describe the proposed behavior

With an `on_running` state change hook, I could define a function that was executed when the orchestration engine transitions the flow run that conatins the hook to a RUNNING state. 

### Example Use

```
def my_running_hook(flow: Flow, flow_run: FlowRun, state: State):
   print("I'm off and running!")
       ...

@flow(
  on_running=[my_running_hook]
)
def my_flow():
   ...
```

**Comment by madkinsz** [comment]
I do not understand the use-case for this hook. It's equivalent to having code called at the start of the flow run.

**Comment by billpalombi** [comment]
Yes, thats correct. I should not have marked this as high priority for that reason. The primary use case that I have in mind is one in which I want to think of some logic (e.g. sending a notification) as distinct from the flow itself.

**Comment by taylor-curran** [comment]
Specifically the request is for an “on_running” state handler, which **allows custom logic to be executed _before_ a flow/task even enters the running state (or being submitted to a task runner**).

A main use case in mind regards the ability to skip tasks or have tasks to enter into a skipped state (or equivalent). Caching was explored as a potential alternative to the skipped state but would not work since it requires an initial execution of the task.

**Comment by madkinsz** [comment]
> allows custom logic to be executed before a flow/task even enters the running state (or being submitted to a task runner).

This is not what `on_running` means in our current semantics. All state hooks are called _after_ the run enters the given state. We cannot do so beforehand because the server may _reject_ the state proposal. Submission to the task runner occurs after task run creation and would be more suitable as an `on_pending` hook.

**Comment by madkinsz** [comment]
Also notably we have explicitly stated that these state change hooks will not have the ability to mutate the state transitions i.e. you could not use this for skipping.

**Comment by taylor-curran** [comment]
Interesting on_pending thought. Is there an equivalence for tasks? Like on_submission to task runner?

**Comment by madkinsz** [comment]
Flows are placed in a `PENDING` state on creation _or_ on submission to flow run infrastructure (i.e. SCHEDULED -> PENDING). Tasks are placed on a `PENDING` state on creation.

**Comment by taylor-curran** [comment]
> If you want your task run to be skipped, why not just
> 
> ```python
> @task
> def my_task():
>     if cond:
>         return State(type=StateType.COMPLETED, name="Skipped")
>     ...
> ```

This would need to be checked before every task for their usecase.

**Comment by madkinsz** [comment]
@taylor-curran calling `my_utility()` at the start of every task doesn't seem like more work than `@task(on_running=my_utility)` — I presume people doing this level of customization would have custom wrappers for `@task` that can do arbitrary logic anyway.

**Comment by taylor-curran** [comment]
Acknowledged that a utility function is a perfectly valid solution. Thanks for mentioning. The main limitation to your proposed workaround is that in order to return a skipped state, the task run has to be brought into existence and get a state type of completed.

Creating a task run and also returning a completed state type is not representative of a task that is skipped. It is essentially executing a task in a skipped mode.

```
@task
def my_task():
    if cond:
        return State(type=StateType.COMPLETED, name="Skipped")
    else:
        # do the actual logic of the function.
        return State(type=StateType.COMPLETED, name="Completed")

@flow
def my_flow(skip):
# task a needs to be submitted in either case
    if task_a in skip:
        task_a.submit(cond=True)
    else:
        task_a.submit(cond=False)
```

**Comment by taylor-curran** [comment]
Would this be preferable to a skipped state? In which the task is not called based on if its in the skip list?
```python
@task
def my_task():
    print('my task')

@flow
def my_flow(skip: list):
    if 'task_a' in skip:
        pass
    else:
        task_a.submit()
        ```

**Comment by madkinsz** [comment]
@taylor-curran Yeah if they don't want the task run to be created then `on_pending` isn't going to help. Using a conditional branch in the flow is the intended pattern.

**Comment by billpalombi** [comment]
It sounds like, because our flow run hooks are run after the transition, not before, that this enhancement will not address the need and that users can better address this need with conditional code. Lets sync up internally.
