### ISSUE TITLE
Unable to Produce Dependency Arrows on Prefect UI (Self Hosted Version 2.10.3)

### ISSUE THREAD

**Issue by cleung1996** [PrefectHQ/prefect#9372]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

Hi there, 

I am tryign to test Prefect 2 to display the dependency arrows, and I want to see how they are generated and why my flows do not include them. I posted this on slack already and tried implementing the suggestions they did but with no success.  I was told you can either pass in an output of one task to the input of the next task in the flow OR you can use the `wait_for` command in the invocation of the task. I have tried both but stilll have no luck with the UI showing the dependency arrows. I am wondering if it is just my misunderstanding, OR if there is a bug somehow. Thanks a lot for your help!

### Reproduction

Code is written below: 
```
from prefect import flow, task

@task
def task_1(num):
    return num + 1

@task
def task_2(num):
    return num + 1

@task
def task_3(num):
    return num + 1

@flow()
def my_flow():
    x = task_1(1)
    # task 2 will wait for task_1 to complete
    y = task_2(x,wait_for=[x])
    print(task_3(y,wait_for=[y]))
    
if __name__ == "__main__":
   my_flow()
```

### Error

![image](https://user-images.githubusercontent.com/86694622/235218861-f38f2b0d-47b9-4758-9a0c-6e3818de2107.png)

### Browers

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Edge

### Prefect version

```Text
Prefect Version 2.10.3 (Self Hosted)
```

**Comment by madkinsz** [comment]
Hey @cleung1996 

We cannot track relationships when passing some types of data. Here, you are encountering a lack of tracking because you are passing small integers which are special-case singletons in Python

https://github.com/PrefectHQ/prefect/blob/64e20208d7a2c08fe81c1712aac60a57701de411/src/prefect/engine.py#L2063

**Comment by cleung1996** [comment]
Thanks @madkinsz, that's rly good to know. So basically you can only pass objects around to track relationship. 

Another follow up question: if we have subflows that are dependent on another flow and/or task and we want to show the dependency/relationship between the flow and the task, how do we do that? I know the `.submit` feature is only for tasks, but what about flows?

**Comment by madkinsz** [comment]
You can also pass integers around they just have to be big enough to have a unique address in memory. Otherwise, we can't distinguish between cases like:

```python
result = my_task_1()  # returns 1
my_task_2(result) 
my_task_2(1) # not related to `my_task_1` 
```

We'll track relationships with subflows in the same way as tasks. If you pass a future from a submitted task to it or a trackable object we should show the dependency.
