### ISSUE TITLE
Include "deployments" filter on flows page

### ISSUE THREAD

**Issue by billpalombi** [PrefectHQ/prefect#9517]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

The flows page includes all flows, regardless of whether or now they have a deployment.

### Describe the proposed behavior

As a user, I want to filter to only see flows that do not have deployments, or perhaps only flows that have deployments.

The filter name should be "deployments" with options:
- "All"
- "Deployed"
- "Un-deployed"

**Comment by discdiver** [comment]
Just came looking to create this issue if it didn't already exist. Glad to see it's in the hopper!

**Comment by brandonreid** [comment]
@billpalombi the flows page, in cloud at least, does currently have a column for "deployments". Does this mitigate the need for a filter?



![Image](https://github.com/PrefectHQ/prefect/assets/6776415/98bee1c9-99d3-45f2-9d5f-d79f8d4e2fc7)

**Comment by billpalombi** [comment]
This ticket was for the version of the flows page that @znicholasbrown and I were iterating on a couple of months ago.

@znicholasbrown, would it be feasible to add that page as a feature preview in staging so that we can revisit it?

**Comment by brandonreid** [comment]
It's cool! I can get that component to show up in Nebula. Will see what I can do here.

**Comment by brandonreid** [comment]
We'll need an API change to filters for this to be possible. I've documented the need in [this ticket](https://github.com/PrefectHQ/prefect/issues/10715).

When that is resolved, I've got a [draft PR started](https://github.com/PrefectHQ/prefect-ui-library/pull/1745/files?diff=unified&w=0), would just need to update it to use the new filter.

**Comment by brandonreid** [comment]
I've created an [issue](https://github.com/PrefectHQ/prefect-ui-library/issues/1763) for updating the flows page with a design that takes the best of both of our current implementations. Included in that is the ability to sort the table by deployments. This would allow you to sort in a way where flows that have deployments are on the top, which I believe would satisfy the goal of this ticket, so I'll close this one. If someone feels strongly that we need a filter, rather than sort, please comment on the new ticket!
