### ISSUE TITLE
Creating Sub-DAGs for modular pipelines

### ISSUE THREAD

**Issue by andersbogsnes** [PrefectHQ/prefect#980]
I am building an ETL pipeline for some machine learning models and I want the pipeline to be designed as modularly as possible, so our data scientists are able to easily add a new feature to the pipeline.

My main issue is that I want to be able to compose a DAG for each feature, which then get combined together into one flow. 

For example, I have the birthdates of some customers. I want to end up with the customers age and three binary columns; under_18, under_13 and under_3 (so I can sum them when aggregating to households later).

So I would normally model this feature as:

- one task to extract data from database,
- one task to calculate age from a birthdate
- three more tasks to create the new columns.

In for example scikit-learn pipelines, I would have a pipeline per feature that I then combine at the end.

For this one feature it works just fine, but I have an additional 20 or so features that all potentially involve multiple steps.

If I use a single flow to manage all 20 features, my flow definition would get very long and unwieldy.

By being able to define a sub-graph for each of my features, I could import just the sub-graph from a features module and my flow definition would be back to being elegant again 😄

**Comment by jlowin** [comment]
Hi @andersbogsnes -- thanks for the detail!

I want to be clear on what aspects of flow definitions you'd like to streamline.

Prefect actually allows you to define multiple flows and then combine them at a later time - so you could import feature flows (or even functions that return flows) from modules and then combine them in your main module. This may solve the portability problem - each feature flow becomes a single import or function call. Though it's supported, we haven't used this pattern too much yet, so I'd love to hear where it can be improved.

There's also the question of flow size / complexity. Airflow offers "SubDags" which basically take DAGs and turns them into single tasks, but this creates enormous execution complexity (and has consequently been proposed to be removed in the next major version of Airflow). In Prefect, the complexity is worse because of the data-passing requirements and state handling. We actually encourage flows made of many small tasks. We have a "tagging" concept that can be used to organize these tasks and select groups of them later, similar to TensorFlow. We can also use these tags to enhance visualization and UI elements, essentially getting the benefits of SubDags for organization without any of the drawbacks.

For example:


```python
from prefect import Flow, tags
with Flow("tagged flow") as flow:

    with tags("group 1"): 
        x = my_task()
        y = my_second_task(x)

    with tags("group 2"): 
        a = my_task()
        b = my_second_task(a)

flow.get_tasks(tags={"group 2"}) # returns a and b
```

One suggestion is to combine tagging with importing flow factory functions to get all the benefits of modularity without sacrificing any functionality.

I hope some of these suggestions address your concern, but if not we'd love to explore how to streamline this further!

**Comment by cicdw** [comment]
I am so sorry @andersbogsnes, I totally spaced that we _do_ have a `Flow.update` method for combining Flows!!  See the docs here: https://docs.prefect.io/api/unreleased/core/flow.html#prefect-core-flow-flow-update

Let us know if that fits your use case

**Comment by cicdw** [comment]
I'm going to close this as I believe `flow.update` solves the stated problem; but if not, we can always re-open in the future.
