### ISSUE TITLE
Cancellation not consistent between CLI and UI

### ISSUE THREAD

**Issue by taylor-curran** [PrefectHQ/prefect#9801]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

A] Cancellation for flow runs in process is no behaving properly: now if we cancel a flow run via the UI/API, the flow is moved to a ‘Cancelling’ state, but the process this flow run lives in continues to run until finishes. This seems to be at odd with the documentation of cancellation, which suggests:  “If the run does not terminate after a grace period (default of 30 seconds), the infrastructure will be killed, ensuring the flow run exits.” As shown in the log below, both flow and task run continues to finish if I specify the on_cancellation option, and in the UI you can see the task run actually completes even after I requested cancellation:
![image](https://github.com/PrefectHQ/prefect/assets/68969861/c2497fc7-4dda-4a31-8d11-99d2032e0304)
![image](https://github.com/PrefectHQ/prefect/assets/68969861/22f6537d-01fb-4fe1-b498-a101f5847bcf)

B] It seems like the on_cancellation function is not picked up if I perform cancellation via the UI:
Cancellation via CLI:
![image](https://github.com/PrefectHQ/prefect/assets/68969861/1d1a45e2-10bb-4d91-a77d-01940e482467)
Via UI:
![image](https://github.com/PrefectHQ/prefect/assets/68969861/6b5e9c4c-e360-41a9-8ce9-29f467bc1206)

C]When using K8s infrastructure during flow runs, cancelling the flow run from the UI will lead to the expected behavior of k8s pod ending, but the cancellation hook is never called.

### Reproduction

```python3
from prefect import flow
from time import sleep

def cancellation_hook(flow, flow_run, state):
    print("I am a cancellation hook")

@flow(on_cancellation=[cancellation_hook])
def my_flow():
    # user cancels flow run
    sleep(100)

if __name__ == '__main__':
    my_flow()
```

### Versions

```Text
Version:             2.10.11
API version:         0.8.4
Python version:      3.9.16
Git commit:          8c651ffc
Built:               Thu, May 25, 2023 2:59 PM
OS/Arch:             darwin/arm64
Profile:             tay-sandbox
Server type:         cloud
```

**Comment by serinamarie** [comment]
> A] Cancellation for flow runs in process is no behaving properly: now if we cancel a flow run via the UI/API, the flow is moved to a ‘Cancelling’ state, but the process this flow run lives in continues to run until finishes. This seems to be at odd with the documentation of cancellation, which suggests: “If the run does not terminate after a grace period (default of 30 seconds), the infrastructure will be killed, ensuring the flow run exits.” As shown in the log below, both flow and task run continues to finish if I specify the on_cancellation option, and in the UI you can see the task run actually completes even after I requested cancellation.

I am unable to replicate this issue. It's possible the 10 second task had a chance to finish before the agent looked for cancelled flow runs. 

Action item for the user: I was encourage the user to increase the task sleep time and see if the issue persists.

```python
from time import sleep
from prefect import flow, task

def cancellation_hook(flow, flow_run, state):
    print("I am a cancellation hook")

@task
def some_task():
    print("task sleep start")
    for i in range(100):
        sleep(1)
        print("task sleep:", i)
    print("task sleep end")

@flow(on_cancellation=[cancellation_hook], log_prints=True)
def my_flow():
    some_task.submit()
    # user cancels flow run
    print("flow sleep start")
    sleep(20)
    print("flow sleep end")

if __name__ == '__main__':
    from prefect.deployments import Deployment
    deployment = Deployment.build_from_flow(
        flow=my_flow,
        name="my-deployment-name",
        version=1,
        work_queue_name="default",
        work_pool_name="local-work",
    )
    deployment.apply()
```

> 
> B] It seems like the on_cancellation function is not picked up if I perform cancellation via the UI:

I agree that there appears to be an issue with cancellation from the UI and I was able to reproduce. This will need to be investigated.

> C]When using K8s infrastructure during flow runs, cancelling the flow run from the UI will lead to the expected behavior of k8s pod ending, but the cancellation hook is never called.

To me this seems to be a subissue/subset of issue B, no?

To reproduce I created a flow run from the deployment above with and without a cancellation hook and cancelled via CLI and UI. The results:
- Flow run with no cancellation hook, cancelled via CLI: Task was exited when flow run was cancelled, flow run ended in a `CANCELLED` state.
- Flow run with no cancellation hook, cancelled via UI: Task was exited when flow run was cancelled, flow run ended in a `CANCELLED` state.
- Flow run **with** cancellation hook, cancelled via CLI: Task was exited when flow run was cancelled, flow run ended in a `CANCELLED` state. Hook was not called
- Flow run **with** cancellation hook, cancelled via UI: Task was exited when flow run was cancelled, flow run ended in a `CANCELLED` state. Hook was not called

**Comment by PPPSDavid** [comment]
Hi @serinamarie , thank you for the quick update! I was able to try out your code above with Prefect running on my local server + agents, using Processes as infrastructure:

What I found is that cancellation **does not work**. Below is the full agent logs I get. Note that I canceled the flow run from the UI at around5 seconds after the task run started:
`18:38:42.159 | INFO    | Flow run 'heavenly-chinchilla' - Downloading flow code from storage at 'C:\\Users\\19665\\SynologyDrive\\Coding Projects\\hubmap2023'
18:38:42.422 | INFO    | Flow run 'heavenly-chinchilla' - flow sleep start
18:38:42.437 | INFO    | Flow run 'heavenly-chinchilla' - Created task run 'some_task-0' for task 'some_task'
18:38:42.438 | INFO    | Flow run 'heavenly-chinchilla' - Submitted task run 'some_task-0' for execution.
18:38:42.482 | INFO    | Task run 'some_task-0' - task sleep start
18:38:43.483 | INFO    | Task run 'some_task-0' - task sleep: 0
18:38:44.484 | INFO    | Task run 'some_task-0' - task sleep: 1
18:38:45.485 | INFO    | Task run 'some_task-0' - task sleep: 2
18:38:46.486 | INFO    | Task run 'some_task-0' - task sleep: 3
18:38:47.487 | INFO    | Task run 'some_task-0' - task sleep: 4
18:38:48.488 | INFO    | Task run 'some_task-0' - task sleep: 5
18:38:49.489 | INFO    | Task run 'some_task-0' - task sleep: 6
18:38:50.490 | INFO    | Task run 'some_task-0' - task sleep: 7
18:38:51.491 | INFO    | Task run 'some_task-0' - task sleep: 8
18:38:52.492 | INFO    | Task run 'some_task-0' - task sleep: 9
18:38:53.493 | INFO    | Task run 'some_task-0' - task sleep: 10
18:38:54.494 | INFO    | Task run 'some_task-0' - task sleep: 11
18:38:55.495 | INFO    | Task run 'some_task-0' - task sleep: 12
18:38:56.496 | INFO    | Task run 'some_task-0' - task sleep: 13
18:38:57.497 | INFO    | Task run 'some_task-0' - task sleep: 14
18:38:58.499 | INFO    | Task run 'some_task-0' - task sleep: 15
18:38:59.499 | INFO    | Task run 'some_task-0' - task sleep: 16
18:39:00.501 | INFO    | Task run 'some_task-0' - task sleep: 17
18:39:01.502 | INFO    | Task run 'some_task-0' - task sleep: 18
18:39:02.424 | INFO    | Flow run 'heavenly-chinchilla' - flow sleep end
18:39:02.503 | INFO    | Task run 'some_task-0' - task sleep: 19
18:39:03.505 | INFO    | Task run 'some_task-0' - task sleep: 20
18:39:04.506 | INFO    | Task run 'some_task-0' - task sleep: 21
18:39:05.508 | INFO    | Task run 'some_task-0' - task sleep: 22
18:39:06.509 | INFO    | Task run 'some_task-0' - task sleep: 23
18:39:07.510 | INFO    | Task run 'some_task-0' - task sleep: 24
18:39:08.512 | INFO    | Task run 'some_task-0' - task sleep: 25
18:39:09.513 | INFO    | Task run 'some_task-0' - task sleep: 26
18:39:10.514 | INFO    | Task run 'some_task-0' - task sleep: 27
18:39:11.515 | INFO    | Task run 'some_task-0' - task sleep: 28
18:39:12.516 | INFO    | Task run 'some_task-0' - task sleep: 29
18:39:13.517 | INFO    | Task run 'some_task-0' - task sleep: 30
18:39:14.518 | INFO    | Task run 'some_task-0' - task sleep: 31
18:39:15.519 | INFO    | Task run 'some_task-0' - task sleep: 32
18:39:16.521 | INFO    | Task run 'some_task-0' - task sleep: 33
18:39:17.521 | INFO    | Task run 'some_task-0' - task sleep: 34
18:39:18.522 | INFO    | Task run 'some_task-0' - task sleep: 35
18:39:19.523 | INFO    | Task run 'some_task-0' - task sleep: 36
18:39:20.525 | INFO    | Task run 'some_task-0' - task sleep: 37
18:39:21.526 | INFO    | Task run 'some_task-0' - task sleep: 38
18:39:22.527 | INFO    | Task run 'some_task-0' - task sleep: 39
18:39:23.528 | INFO    | Task run 'some_task-0' - task sleep: 40
18:39:24.530 | INFO    | Task run 'some_task-0' - task sleep: 41
18:39:25.531 | INFO    | Task run 'some_task-0' - task sleep: 42
18:39:26.532 | INFO    | Task run 'some_task-0' - task sleep: 43
18:39:27.533 | INFO    | Task run 'some_task-0' - task sleep: 44
18:39:28.534 | INFO    | Task run 'some_task-0' - task sleep: 45
18:39:29.535 | INFO    | Task run 'some_task-0' - task sleep: 46
18:39:30.536 | INFO    | Task run 'some_task-0' - task sleep: 47
18:39:31.537 | INFO    | Task run 'some_task-0' - task sleep: 48
18:39:32.538 | INFO    | Task run 'some_task-0' - task sleep: 49
18:39:33.539 | INFO    | Task run 'some_task-0' - task sleep: 50
18:39:34.540 | INFO    | Task run 'some_task-0' - task sleep: 51
18:39:35.542 | INFO    | Task run 'some_task-0' - task sleep: 52
18:39:36.543 | INFO    | Task run 'some_task-0' - task sleep: 53
18:39:37.544 | INFO    | Task run 'some_task-0' - task sleep: 54
18:39:38.545 | INFO    | Task run 'some_task-0' - task sleep: 55
18:39:39.546 | INFO    | Task run 'some_task-0' - task sleep: 56
18:39:40.548 | INFO    | Task run 'some_task-0' - task sleep: 57
18:39:41.549 | INFO    | Task run 'some_task-0' - task sleep: 58
18:39:42.550 | INFO    | Task run 'some_task-0' - task sleep: 59
18:39:43.551 | INFO    | Task run 'some_task-0' - task sleep: 60
18:39:44.552 | INFO    | Task run 'some_task-0' - task sleep: 61
18:39:45.553 | INFO    | Task run 'some_task-0' - task sleep: 62
18:39:46.554 | INFO    | Task run 'some_task-0' - task sleep: 63
18:39:47.556 | INFO    | Task run 'some_task-0' - task sleep: 64
18:39:48.556 | INFO    | Task run 'some_task-0' - task sleep: 65
18:39:49.557 | INFO    | Task run 'some_task-0' - task sleep: 66
18:39:50.558 | INFO    | Task run 'some_task-0' - task sleep: 67
18:39:51.559 | INFO    | Task run 'some_task-0' - task sleep: 68
18:39:52.561 | INFO    | Task run 'some_task-0' - task sleep: 69
18:39:53.561 | INFO    | Task run 'some_task-0' - task sleep: 70
18:39:54.562 | INFO    | Task run 'some_task-0' - task sleep: 71
18:39:55.563 | INFO    | Task run 'some_task-0' - task sleep: 72
18:39:56.564 | INFO    | Task run 'some_task-0' - task sleep: 73
18:39:57.565 | INFO    | Task run 'some_task-0' - task sleep: 74
18:39:58.567 | INFO    | Task run 'some_task-0' - task sleep: 75
18:39:59.567 | INFO    | Task run 'some_task-0' - task sleep: 76
18:40:00.569 | INFO    | Task run 'some_task-0' - task sleep: 77
18:40:01.570 | INFO    | Task run 'some_task-0' - task sleep: 78
18:40:02.571 | INFO    | Task run 'some_task-0' - task sleep: 79
18:40:03.572 | INFO    | Task run 'some_task-0' - task sleep: 80
18:40:04.574 | INFO    | Task run 'some_task-0' - task sleep: 81
18:40:05.575 | INFO    | Task run 'some_task-0' - task sleep: 82
18:40:06.576 | INFO    | Task run 'some_task-0' - task sleep: 83
18:40:07.577 | INFO    | Task run 'some_task-0' - task sleep: 84
18:40:08.578 | INFO    | Task run 'some_task-0' - task sleep: 85
18:40:09.580 | INFO    | Task run 'some_task-0' - task sleep: 86
18:40:10.581 | INFO    | Task run 'some_task-0' - task sleep: 87
18:40:11.582 | INFO    | Task run 'some_task-0' - task sleep: 88
18:40:12.583 | INFO    | Task run 'some_task-0' - task sleep: 89
18:40:13.584 | INFO    | Task run 'some_task-0' - task sleep: 90
18:40:14.585 | INFO    | Task run 'some_task-0' - task sleep: 91
18:40:15.586 | INFO    | Task run 'some_task-0' - task sleep: 92
18:40:16.588 | INFO    | Task run 'some_task-0' - task sleep: 93
18:40:17.589 | INFO    | Task run 'some_task-0' - task sleep: 94
18:40:18.591 | INFO    | Task run 'some_task-0' - task sleep: 95
18:40:19.592 | INFO    | Task run 'some_task-0' - task sleep: 96
18:40:20.593 | INFO    | Task run 'some_task-0' - task sleep: 97
18:40:21.594 | INFO    | Task run 'some_task-0' - task sleep: 98
18:40:22.595 | INFO    | Task run 'some_task-0' - task sleep: 99
18:40:22.596 | INFO    | Task run 'some_task-0' - task sleep end
18:40:22.615 | INFO    | Task run 'some_task-0' - Finished in state Completed()
18:40:22.632 | ERROR   | Flow run 'heavenly-chinchilla' - Finished in state Cancelling(type=CANCELLED)
18:40:23.039 | INFO    | prefect.infrastructure.process - Process 'heavenly-chinchilla' exited cleanly.`

And as shown in the UI, the weird result of task run finishing green but flow run canceled persisted:
![image](https://github.com/PrefectHQ/prefect/assets/39285150/eef13433-3d36-4b96-9898-cbee6c8158f7)

Cancellation via the CLI yields similar logs, just now the on_cancellation() hook is called

`18:43:58.704 | INFO    | Task run 'some_task-0' - Finished in state Completed()
18:43:58.719 | INFO    | Flow run 'sweet-chital' - Running hook 'cancellation_hook' in response to entering state 'Cancelling'
18:43:58.720 | INFO    | Flow run 'sweet-chital' - Hook 'cancellation_hook' finished running successfully
18:43:58.720 | INFO    | Flow run 'sweet-chital' - Received non-final state 'Cancelling' when proposing final state 'Completed' and will attempt to run again...
18:43:58.732 | ERROR   | Flow run 'sweet-chital' - Finished in state Cancelling()`

Agreed with your interpretation of B and C, just want to add that #C is particularly confusing because flow runs on K8s is actually killed and canceled (just the on_cancellation() hook is not called) with either the CLI or the UI, as opposed to the local process, in which flow run is never really canceled AND the on_cancellation() hook is not called

**Comment by madkinsz** [comment]
@PPPSDavid Could you please include DEBUG level agent logs with a full example of the command you start the agent with? It'd probably be good to _disable_ streaming flow run log output to the agent so we can just see what the agent is doing.

**Comment by serinamarie** [comment]
I was able to generate logs as well:

CLI:
```bash
13:10:12.512 | DEBUG   | prefect.agent - Checking for cancelled flow runs...
13:10:12.540 | INFO    | prefect.agent - Found 1 flow runs awaiting cancellation.
13:10:12.580 | INFO    | prefect.agent - Killing process 28788 for flow run 'f1d0d8c0-c263-4f34-b1e6-b568217d3222'...
13:10:12.581 | DEBUG   | prefect.task_runner.concurrent - Shutting down task runner...
13:10:12.582 | ERROR   | Task run 'some_task-0' - Crash detected! Execution was cancelled by the runtime environment.
13:10:12.582 | DEBUG   | Task run 'some_task-0' - Crash details:
Traceback (most recent call last):
  File "/Users/bean/code-oss/prefect/src/prefect/engine.py", line 1867, in report_task_run_crashes
    yield
  File "/Users/bean/code-oss/prefect/src/prefect/engine.py", line 1448, in begin_task_run
    state = await orchestrate_task_run(
  File "/Users/bean/code-oss/prefect/src/prefect/engine.py", line 1646, in orchestrate_task_run
    result = await call.aresult()
  File "/Users/bean/code-oss/prefect/src/prefect/_internal/concurrency/calls.py", line 181, in aresult
    return await asyncio.wrap_future(self.future)
asyncio.exceptions.CancelledError
13:10:12.601 | DEBUG   | prefect.engine - Reported crashed task run 'some_task-0' successfully!
13:10:12.602 | ERROR   | Flow run 'resourceful-shark' - Crash detected! Execution was aborted by a termination signal.
13:10:12.602 | DEBUG   | Flow run 'resourceful-shark' - Crash details:
Traceback (most recent call last):
  File "/Users/bean/code-oss/prefect/src/prefect/engine.py", line 1830, in report_flow_run_crashes
    yield
  File "/Users/bean/code-oss/prefect/src/prefect/engine.py", line 441, in begin_flow_run
    terminal_or_paused_state = await orchestrate_flow_run(
  File "/Users/bean/code-oss/prefect/src/prefect/engine.py", line 750, in orchestrate_flow_run
    result = await flow_call.aresult()
  File "/Users/bean/code-oss/prefect/src/prefect/_internal/concurrency/calls.py", line 181, in aresult
    return await asyncio.wrap_future(self.future)
  File "/Users/bean/code-oss/prefect/src/prefect/_internal/concurrency/calls.py", line 194, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "david.py", line 20, in my_flow
    sleep(100)
  File "/Users/bean/code-oss/prefect/src/prefect/engine.py", line 1793, in cancel_flow_run
    raise TerminationSignal(signal=signal.SIGTERM)
prefect.exceptions.TerminationSignal
⭐ 13:10:12.617 | DEBUG   | prefect.engine - Reported crashed flow run 'resourceful-shark' successfully!
⭐ 13:10:12.618 | INFO    | Flow run 'resourceful-shark' - Running hook 'cancellation_hook' in response to entering state 'Cancelling'
⭐ 13:10:12.618 | INFO    | Flow run 'resourceful-shark' - Hook 'cancellation_hook' finished running successfully
⭐ 13:10:12.626 | ERROR   | prefect.infrastructure.process - Process 'resourceful-shark' exited with status code: -15; This indicates that the process exited due to a SIGTERM signal. Typically, this is caused by manual cancellation.
```

UI: 
```bash
13:12:11.160 | DEBUG   | prefect.agent - Checking for cancelled flow runs...
13:12:11.198 | INFO    | prefect.agent - Found 1 flow runs awaiting cancellation.
13:12:11.236 | INFO    | prefect.agent - Killing process 28959 for flow run '0725046d-a563-4f29-9b9f-5335efa938c3'...
13:12:11.237 | DEBUG   | prefect.task_runner.concurrent - Shutting down task runner...
13:12:11.237 | ERROR   | Task run 'some_task-0' - Crash detected! Execution was cancelled by the runtime environment.
13:12:11.238 | DEBUG   | Task run 'some_task-0' - Crash details:
Traceback (most recent call last):
  File "/Users/bean/code-oss/prefect/src/prefect/engine.py", line 1867, in report_task_run_crashes
    yield
  File "/Users/bean/code-oss/prefect/src/prefect/engine.py", line 1448, in begin_task_run
    state = await orchestrate_task_run(
  File "/Users/bean/code-oss/prefect/src/prefect/engine.py", line 1646, in orchestrate_task_run
    result = await call.aresult()
  File "/Users/bean/code-oss/prefect/src/prefect/_internal/concurrency/calls.py", line 181, in aresult
    return await asyncio.wrap_future(self.future)
asyncio.exceptions.CancelledError
13:12:11.255 | DEBUG   | prefect.engine - Reported crashed task run 'some_task-0' successfully!
13:12:11.255 | ERROR   | Flow run 'belligerent-goat' - Crash detected! Execution was aborted by a termination signal.
13:12:11.256 | DEBUG   | Flow run 'belligerent-goat' - Crash details:
Traceback (most recent call last):
  File "/Users/bean/code-oss/prefect/src/prefect/engine.py", line 1830, in report_flow_run_crashes
    yield
  File "/Users/bean/code-oss/prefect/src/prefect/engine.py", line 441, in begin_flow_run
    terminal_or_paused_state = await orchestrate_flow_run(
  File "/Users/bean/code-oss/prefect/src/prefect/engine.py", line 750, in orchestrate_flow_run
    result = await flow_call.aresult()
  File "/Users/bean/code-oss/prefect/src/prefect/_internal/concurrency/calls.py", line 181, in aresult
    return await asyncio.wrap_future(self.future)
  File "/Users/bean/code-oss/prefect/src/prefect/_internal/concurrency/calls.py", line 194, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "david.py", line 20, in my_flow
    sleep(100)
  File "/Users/bean/code-oss/prefect/src/prefect/engine.py", line 1793, in cancel_flow_run
    raise TerminationSignal(signal=signal.SIGTERM)
prefect.exceptions.TerminationSignal
⭐ 13:12:11.269 | INFO    | prefect.engine - Engine execution of flow run '0725046d-a563-4f29-9b9f-5335efa938c3' aborted by orchestrator: Run is already in terminal state CANCELLED.
....
⭐ 13:22:23.509 | INFO    | prefect.infrastructure.process - Process 'stereotyped-corgi' exited cleanly.
⭐ 13:22:25.307 | INFO    | prefect.agent - Cancelled flow run '9e0bd9a2-4cd1-48d2-b873-478ba9bcab18'!
```

Looking into the discrepancy, but I think it's this line when cancelling from the UI that is causing the issue:
```bash
Engine execution of flow run '0725046d-a563-4f29-9b9f-5335efa938c3' aborted by orchestrator: Run is already in terminal state CANCELLED.
```

**Comment by madkinsz** [comment]
@serinamarie it looks like it might be doing something like:

- Run placed in CANCELLING by user
- Agent sends SIGTERM
- Agent reports run as CANCELLED
- Run attempts to proposed CRASHED state
- Orchestrator ABORTS run since it is CANCELLED already
- Process exits

Instead it should be:

- Run placed in CANCELLING by user
- Agent sends SIGTERM
- Agent waits for process to exit
- Run attempts to proposed CRASHED state
- Orchestrator rejects transition and returns CANCELLING
- Process exits
- Agent reports run as CANCELLED

We can also add an orchestration rule that REJECTS CANCELLED -> CRASHED instead of ABORT.

I'm not quite sure these stories are quite right though as I think that the agent already should be waiting for cancellation to complete before reporting?

**Comment by serinamarie** [comment]
I think there are 2 issues here:
1. I commented out the `_run_flow_hooks()` in `report_flow_run_crashes` and the issue was the same. I believe the real issue is in calling `propose_state()` there. When replacing this with `client.set_flow_run_state()`,  the errors appear to be handled similarly between UI and CLI, reaching the point of running hooks (unlike with `propose_state()` where we exit beforehand). 
2. Even still, cancellations from the UI with `client.set_flow_run_state(`) lead to an `OrchestrationResult` of `Crashed` so only `on_crashed` hooks would be called. I haven't yet determined why that is.

**Comment by serinamarie** [comment]
From the UI, I believe we bypass orchestration rules when we ping the `flow_run/{id}/set_state` endpoint, possibly attempting to set flow run state type to `Cancelled`, based on [the following UI code](https://github.com/PrefectHQ/prefect-ui-library/blob/fce11a5d8524446a0b65091a4e551727e4c571f5/src/services/WorkspaceFlowRunsApi.ts#L89-L92):

```typescript
  public setFlowRunState(id: string, body: StateUpdate): Promise<void> {
    const requestBody = mapper.map('StateUpdate', body, 'StateUpdateRequest')
    return this.post(`/${id}/set_state`, { state: requestBody.state, force: true })
  }
```

From this request we get the following response: 
```
{"state":{"id":"58013a1d-b358-430d-9612-c0280413b137","type":"CANCELLED","name":"Cancelling","timestamp":"2023-06-02T21:43:15.217862+00:00","message":null,"data":null,"state_details":{"flow_run_id":"28f62acd-29aa-4b1b-b775-08f5d61a8681","task_run_id":null,"child_flow_run_id":null,"scheduled_time":null,"cache_key":null,"cache_expiration":null,"untrackable_result":false,"pause_timeout":null,"pause_reschedule":false,"pause_key":null,"refresh_cache":null}},"status":"ACCEPT","details":{"type":"accept_details"}}
```
I think we might want a state type of `CANCELLING`?

Meanwhile, in cancellation via CLI we don't force the state and we propose a `Cancelling` state type.

https://github.com/PrefectHQ/prefect/blob/14616411c8b640df0dbf24bedb324723ce87389a/src/prefect/cli/flow_run.py#L124-L134

This makes me think maybe this is a UI change regarding the Cancel button.
