### ISSUE TITLE
Prefect UI not displaying double-backslashes in markdown artifact

### ISSUE THREAD

**Issue by PPPSDavid** [PrefectHQ/prefect#9816]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

When we want to create a markdown artifact with double backslash with code below, we were able to see the backslashes are escaped in the RAW data, but they are not showing up in the UI. 

create_markdown_artifact(markdown=“ABC:\n \\\\123”)

### Reproduction

Run the code above

### Error

The expected 2 backslashes before “123” is not shown in the UI, but the 2 **escaped**slashes are found in the raw data

### Browers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```Text
2.10.11
```

**Comment by znicholasbrown** [comment]
Hi @PPPSDavid - thanks for opening a ticket, this helped us find a bug! However, the bug doesn't entirely explain the issue here. 

With the behavior implemented correctly, your snippet would still fail to show double slashes and would instead show just 1. This is because backslashes `\` in markdown are treated as escape characters so you're telling the parser to use the literal `\` character instead of to display `\\`. To render backslashes in markdown, you need to escape them, which means you need to input `\\\\` to get `\\` output. This works in GitHub comments too 😄 

The bug this uncovered is that the markdown renderer wasn't accounting for escape characters at all, so any escaped block of text would end up as block-level html elements.

This behavior is fixed in https://github.com/PrefectHQ/prefect-design/pull/803, which will make its way through the stack on next release most likely - I'm going to close this issue as resolved.

**Comment by PPPSDavid** [comment]
Hi @znicholasbrown , sorry for the late update, but I was checking the UI recnetly and found the issue with backslashes seems to persist.

Our "raw data" markdown looks like:

"\n\n ABC Cat:\n\\\\123\\45"

and what we saw is:

ABC Cat:
123\45

Note that the two backslashes before "45" is escaped and recognized, but the first 4 backslashes are not resolved into "\\"

**Comment by znicholasbrown** [comment]
@PPPSDavid can you expand a little bit on where you're seeing this? When I try that same string in the parsing demo I get the following:

![image](https://github.com/PrefectHQ/prefect/assets/27291717/487e6b56-211d-42d6-a2d6-2e973e0cc9d4)

Are you using Prefect Cloud or Prefect Server? If Server, are you on the latest version? 

I'm going to close the other issue you opened as a duplicate - let's continue to discuss here and we can reopen this ticket as needed.

**Comment by PPPSDavid** [comment]
Thanks @znicholasbrown , 

- I am using Perfect Cloud
- I think the result in the parsing demo is what we want, but in the UI of Prefect Cloud we still cannot see the two back slashes in the front.

**Comment by znicholasbrown** [comment]
Great thanks for that @PPPSDavid; I'm going to re-open this issue while we investigate.

**Comment by PPPSDavid** [comment]
Thanks @znicholasbrown , I also updated the example above: our string does not have any spaces between \n and the 4 consequtive backslashes, maybe this is related to the weird behavior?

**Comment by PPPSDavid** [comment]
Hi @znicholasbrown , it seems like in one of the recent updates Prefect's markdown artifact display logic is changed. **We are still not seeing the expected result** but we are able to provide a more detailed reproducible example:

```

from prefect import flow
from prefect.artifacts import create_markdown_artifact

markdown = (f'[ABC DEF](https://www.google.com) \n'
    f'\n'
    f'Log Dir: \n'
    f'\\\\my_local_dir\\path\\file')

@flow
def artifact_flow():
    create_markdown_artifact(markdown)


if __name__ == '__main__':
    artifact_flow()
```


If we do `print(markdown)`, we can see the double back-slashes as expected before "my_dir":

```
[ABC DEF](https://www.google.com) 

Log Dir:
\\my_local_dir\path\file
```

However, from the UI of my local Prefect server running at v 2.10.20, we have:
![image](https://github.com/PrefectHQ/prefect/assets/39285150/460b017d-e2ad-4ecd-aa97-de49c5261803)


Please let me know if this example makes sense to you.

**Comment by serinamarie** [comment]
Hi, sorry I’m just seeing this now. I am OOO/AFK until August unfortunately but I can take a look when I return if the issue persists.

**Comment by znicholasbrown** [comment]
For posterity - since this behavior is expected (backslashes are being correctly used as escape characters), as a workaround I'd recommend wrapping any string whose contents containing backslashes that must be explicitly rendered in backticks. So instead of:

```
[ABC DEF](https://www.google.com) \n
\n
Log Dir: \n
\\\\my_local_dir\\path\\file
```
which renders as:


you'd pass:

![Screenshot 2024-03-18 at 11 03 23 AM](https://github.com/PrefectHQ/prefect/assets/27291717/59f2f360-e3ee-4fdc-b524-31a4dac14c7d)


```
[ABC DEF](https://www.google.com) \n
\n
Log Dir: \n
`\\\\my_local_dir\\path\\file`
```
which renders as:

![Screenshot 2024-03-18 at 11 03 31 AM](https://github.com/PrefectHQ/prefect/assets/27291717/6b24c05f-1fb4-4404-bb1b-5fdfc2470919)
