### ISSUE TITLE
Timestamps returned by graphql api strip trailing zeros from microseconds

### ISSUE THREAD

**Issue by gracepetryk** [PrefectHQ/prefect#9961]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

All timestamps returned by the graphql api trim trailing 0s from the microsecond section. For example, what should be `2023-06-15T23:00:34.123400+00:00` becomes `2023-06-15T23:00:34.1234+00:00`. This makes the timestamp unable to be parsed by python's  `datetime.datetime.fromisoformat` in versions prior to 3.11

### Reproduction

```python3
# Using the python client to get a consistent sub-second scheduled_start_time
import datetime
import prefect

api_key = "api_key"
tenant_id = "tenant_id"
version_group_id = "version_group_id"

prefect.Client(api_key=api_key, tenant_id=tenant_id).create_flow_run(
    run_name="test_timestamp_truncation",
    version_group_id=version_group_id,
    scheduled_start_time=datetime.datetime(
        2100, 1, 1, 0, 0, 0, 123400, tzinfo=datetime.datetime.utc
    )
)

# graphql query to get start time

query {
    flow_run ( where: { name: { _eq: "test_timestamp_truncation" }}) {
        scheduled_start_time
    }
}
```

### Versions

```Text
$ prefect version
1.3.0

$ prefect diagnostics
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Linux-5.15.49-linuxkit-pr-x86_64-with-glibc2.17",
    "prefect_backend": "cloud",
    "prefect_version": "1.3.0",
    "python_version": "3.9.16"
  }
}
```

**Comment by serinamarie** [comment]
Hi @gracepetryk, thanks for raising this issue! 

I'm unsure if we'll get a chance to work on this particular issue, but always welcome [contributors](https://docs-v1.prefect.io/core/development/overview.html) 🙂 to [Prefect 1](https://github.com/PrefectHQ/server/tree/master/src/prefect_server).

**Comment by Akshat162001** [comment]
import datetime
import prefect

api_key = "api_key"
tenant_id = "tenant_id"
version_group_id = "version_group_id"

scheduled_start_time = datetime.datetime(2100, 1, 1, 0, 0, 0, 123400, tzinfo=datetime.timezone.utc)
scheduled_start_time_truncated = scheduled_start_time.replace(microsecond=scheduled_start_time.microsecond // 1000 * 1000)

client = prefect.Client(api_key=api_key, tenant_id=tenant_id)
client.create_flow_run(
    run_name="test_timestamp_truncation",
    version_group_id=version_group_id,
    scheduled_start_time=scheduled_start_time_truncated
)

# graphql query to get start time

query = '''
query {
  flow_run (where: { name: { _eq: "test_timestamp_truncation" }}) {
    scheduled_start_time
  }
}
'''

result = client.graphql(query)
scheduled_start_time = result.data.flow_run[0].scheduled_start_time

# Parse the timestamp using a custom format
scheduled_start_time_parsed = datetime.datetime.strptime(scheduled_start_time, "%Y-%m-%dT%H:%M:%S.%f%z")
print(scheduled_start_time_parsed)
 this will fix the error of trialing zeroes sp if can assist me where to make changes since i am not able to find that location

**Comment by cicdw** [comment]
I'm closing this issue as stale, and because Prefect 1.x is no longer under active development.  Please upgrade to versions 2.x or 3.x.
